### ISSUE TITLE
DCR: Add new SequenceDialog class

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-sdk#5092]
## Issue
Waterfalls are defined as collection of functions. This works but *requires* a code behind functionality.

## Proposed change
We can get a simple effect of water falls but in a declarative way by creating a new class **SequenceDialog**.  A SequenceDialog is a ComponentDialog which has a collection of Dialogs.  The policy it uses for execution is to call each dialog in sequence until all of them are done.

If our prompts (and/or dialogs) have the **slot** property then you can define a sequence of dialogs or prompts that gather all of slots without requiring any code behind at all.  

Example pseudo code
```cs
public MyDialog : SequenceDialog
{
      this.AddDialog(new TextPrompt(slot: "FirstName", initialPrompt: "What is your first name?"));
      this.AddDialog(new TextPrompt(slot: "LastName", initialPrompt: "What is your last name?"));
      this.AddDialog(new IntegerPrompt(slot: "Age", initialPrompt: "What is your Age?", MinValue:0, MaxValue:100));
}
```

Example declarative
```xml
```cs
<SequenceDialog id='mainDialog'>
    <SequenceDialog.Dialogs>
             <TextPrompt slot="FirstName" initialPrompt="What is your first Name?"/>
             <TextPrompt slot="LastName" initialPrompt="What is your last Name?"/>
             <IntegerPrompt slot="Age" initialPrompt="What is your last Age?" MinValue="1" MaxValue="100"/>
     </SequenceDialog.Dialogs>
</SequenceDialog>
```

## Depends on DCRs
* #5088 - Should be serializable
* #5091 - Prompts should have slot property

## Component Impact 
This is a new class in the dialogs library.

## Customer Impact 
None, new functionality

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by Stevenic** [comment]
I don't think we can do this until we figure out how LG is going to work. My comment here is somewhat similar to my comment in #5091.

The issue with statically binding a prompts text to a `TextPrompt` class is that you then need to figure out how the prompt will access slot filling values when rendering LG templates.  I'm not saying that we can't figure out how to do that I'm just saying that I think we have to understand how LG templates will get rendered before we decide that the pseudo code you're showing is possible.  As I stated in #5091 there are already issues around trying to pass the slot name into `TextPrompt`.
