### ISSUE TITLE
DCR: Add new IntentDialog which allows declaritive recognizer and intent mappings

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-sdk#5093]
## Issue
Currently we have developers use Recognizers by invoking it directly.  Doing this impacts the ability to declaratively define dialogs.

## Proposed change
Create an **IntentDialog** which is derived from ComponentDialog.

It would add
* **Recognizer** property which can use an IRecognizer
* **IntentMappings** property which is a collection of IntentMapping objects

An IntentMapping would have properties:
* **IntentId** -- the intentid to match on
* **DialogId** -- the dialog  in the dialogs collection to invoke when intent fires

Example declarative
```xml
```cs
<IntentDialog id='mainDialog'>
    <IntentDialog.Recognizer>
              <LuisRecognizer AppId="123123123123123"/> 
      </IntentDialog>

    <IntentDialog.IntentMappings>
          <IntentMapping IntentId="greeting" DialogId="GreetUser"/>
          <IntentMapping IntentId="help" DialogId="helpUser"/>
          <IntentMapping IntentId="cancel" DialogId="CancelDialog"/>
     </IntentDialog.IntentMappings>

    <IntentDialog.Dialogs>
             <!-- … dialog definitions … -->
     </IntentDialog.Dialogs>
</IntentDialog>

```
It is important to note that V3 C# and node SDK both had a concept of an Intent based dialog, and this class is needed to have fuller migration story.

## Depends on DCRs
* #5088 Support serialization

## Component Impact 
This is a new class in the dialogs library.

## Customer Impact 
None, new functionality

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by Stevenic** [comment]
I have a prototype of this implemented in toybox over [here](https://github.com/Stevenic/botbuilder-toybox/blob/master/packages/botbuilder-toybox-controls/src/intentDialog.ts).  And here's what an example of using this new dialog looks like:

```JS
const recognizer = new LuisRecognizer('<my model>');
dialogs.add(new IntentDialog('main', recognizer)
    .addIntent('BookFlight', new BookFlightDialog())
    .addIntent('BookHotel', new BookHotelDialog())
    .addIntent('Help', new HelpDialog(), InteruptionMode.append)
    .addIntent('Cancel', new CancelDialog(), InteruptionMode.append)
    .addIntent('None', new FallbackDialog())
);
```

You just create a `LuisRecognizer` instance and pass it in to the constructor of your `IntentDialog`. From there you can use `addIntent()` to fluently define all of your intent to dialog mappings.  An optional `InterruptionMode` can be specified which lets you control how the dialog handles interruptions.  There are 3 modes:

- **none** - The intent will not be treated as an interruption so if a dialog is already active it won't be triggered. This is the default behavior.
- **replace** - If triggered, any current dialog will be cancelled before starting the new dialog.
- **append** - If triggered, the new dialog will be pushed onto the stack as a tagent such that the current dialog will reprompt once the interruption completes.

You can use the IntentDialog to build up your bots "main" dialog pretty quickly. For driver code you just need logic that starts the main dialog for a conversation if its not already running.
