### ISSUE TITLE
Add a button list style to the Choices for prompts

### ISSUE THREAD

**Issue by yochay** [microsoft/botframework-sdk#5121]
_From @rosskyl on October 24, 2018 18:36_

**Is your feature request related to a problem? Please describe.**
I am upgrading a v3 bot to v4 and am working on the prompts. I am currently using a ConfirmPrompt but would like to use buttons rather than just text.

**Describe the solution you'd like**
It would be great to have a button list style that would display the options as a card action inside a hero card attachment.

**Describe alternatives you've considered**
I have looked at creating a hero card and adding card actions to it and adding that to the prompt activity. However this displays the options "`(1) Yes or (2) No`" as text above the card still.

**Additional context**
This is what I am looking for:
![image](https://user-images.githubusercontent.com/9472151/47452613-4ce2e200-d790-11e8-8f14-e6c774e9b57e.png)
I do have some custom css styling to in the webchat.

[enhancement]

_Copied from original issue: Microsoft/botbuilder-dotnet#1057_

**Comment by yochay** [comment]
_From @sgellock on October 24, 2018 20:6_

Adaptive Cards should be able to address this issue for the customer

**Comment by yochay** [comment]
_From @nhadro on October 25, 2018 17:14_

I'm working with this developer on this and the primary channel we're using is Skype for Business which doesn't support many cards from what I've seen.

**Comment by yochay** [comment]
Moved from https://github.com/Microsoft/botbuilder-dotnet/issues/1062. 
DCR for all SDK languages.

**Comment by dividor** [comment]
Using adaptive cards is not a great option (and not supported on all channels), the SDK 3 list style was quick and efficient to implement. 

The SDK 4 choice prompt usability is questionable too, as many users are used to seeing such choice options inline in the chat rather than as - what looks like - suggested actions.

Is there any plan for SDK 4 to support these please?

**Comment by stevengum** [comment]
Inline and list formatting already [exists](https://github.com/Microsoft/botbuilder-js/blob/master/libraries/botbuilder-dialogs/src/prompts/prompt.ts#L17-L42):

```js
const { ChoicePrompt, ListStyle } = require('botbuilder-dialogs');

const choicePrompt = new ChoicePrompt('prompt');
// Change the ListStyle of the prompt to ListStyle.none.
choicePrompt.style = ListStyle.list; // or ListStyle.inline
```

**Comment by yapalex** [comment]
Has anyone found a better solution do to this? it works but its kinda of a pain.

**Comment by textminer** [comment]
I strongly believe on SDK 3 was easier and better on this than SDK 4. I'm using nodeJs with Teams channel, and I've tried:

this.dialogSet.dialogs.sourceCurrencyPrompt.style = ListStyle.heroCard; // or ListStyle.suggestedAction

and the BOT Emulator renders it whereas Teams does not. 

Also tried doing:
        var reply = MessageFactory.suggestedActions(['USD ($)', 'Euro (€)'], 'Choose destination currency');
        await stepContext.context.sendActivity(reply);

and also, the emulator renders it perfectly and again Teams does not even show anything. Very dissapointing.

**Comment by v-kydela** [comment]
@yochay - This was implemented in this pull request: https://github.com/Microsoft/botbuilder-dotnet/pull/1339

Should we close this issue?

**Comment by CoHealer** [comment]
Closing with fix merged https://github.com/Microsoft/botbuilder-dotnet/commit/170e3813302c74f9bf8e5ab3bcb197e2d54d4d1f

**Comment by textminer** [comment]
When is this being implemented for the NodeJs SDK? Thanks.

**Comment by sgellock** [comment]
customer wants the v3 solution carried forward to v4.

**Comment by v-kydela** [comment]
@textminer - The Node SDK has parity with .NET: https://github.com/microsoft/botbuilder-js/pull/773

**Comment by sgellock** [comment]
we believe this is resolved and possible with existing mechanisms
