### ISSUE TITLE
[DCR] Move all Swagger files to single repository and adjust generateClient.cmds

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-sdk#5135]
## Issue
We don't have a single source of truth regarding Swagger files, which can add some friction regenerating the schema and connector libraries.

## Proposed change
Per the Autorest team (Azure/autorest#93), Autorest is able to take a URL for the `-Input` argument.

## Component Impact 
The `swagger/` folders in each v4 SDK need to be updated, the Swagger files should be taken out, and the generateClient.cmd scripts should instead take the Swagger file from this repo (e.g. https://raw.githubusercontent.com/Microsoft/BotBuilder/master/swagger/ConnectorAPI.json), or the BotFramework-Services repo (e.g. https://raw.githubusercontent.com/Microsoft/BotFramework-Services/master/swagger/ConnectorAPI.json).

## Customer Impact 
N/A

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by sgellock** [comment]
Chris, can you us this to track a plan

**Comment by cleemullins** [comment]
We will be depricating the runtime use of AutoRest in the 4.5 timeframe in order to simplify our tooling chain. This issue will track.

**Comment by EricDahlvang** [comment]
Each repository should retain a copy of the swagger file that corresponds to the current state of that repo.  This will enable quickly determining what has changed, by comparing the repository's copy to the latest.

The source of truth is here now: https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-channel.json

**Comment by cleemullins** [comment]
I've reached out to @dandriscoll to see if we can get version numbers added to the swagger file. That will let up track "which is which" in a much more explicit way. Pushing this out another release until that's done.

**Comment by cleemullins** [comment]
Closing, as we no longer generate from swagger files.
