### ISSUE TITLE
As a developer, I would like to be able to override the methods in BotTelemetryClient

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#5194]
## Issue
I would like to be able to extend the OOTB client with additional business logic and obfuscate or augment the data being logged without having to write an IBotTelemetryClient from the scratch. For example, users will be able to opt-in/opt-out from logging and have different privacy preferences, I would like to override the TrackEvent method so I can manipulate the data based on the user that is using the bot.

## Proposed change
Make the methods in BotTelemetryClient virtual.

## Component Impact 
BotTelemetryClient

## Customer Impact 
Privacy

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

@daveta

**Comment by drub0y** [comment]
I just want to point out that this would be a breaking change for a shipped API and would violate semver rules unless you made a major version bump.

**Comment by daveta** [comment]
@scheyal : FYI, might want to triage what to do with this one..
