### ISSUE TITLE
Telemetry for Adaptive Dialog

### ISSUE THREAD

**Issue by daveta** [microsoft/botframework-sdk#5231]
This is a placeholder work item.  Once FlowDialog is further fleshed out, we need to define how telemetry is logged, and what is being logged.

Some of the basics:
- [ ] Log an event when a Adaptive dialog begins.
- [ ] Log an event when a Adaptive dialog completes.
- [ ] Log an event when a Adaptive dialgo is cancelled.
- [ ] Log an event when a Adaptive step starts and complete 
- [ ] Log an event when a Adaptive dialog Input (all types) starts, complete 
- [ ] Log an event when a Adaptive dialog recognizer starts, ends

Ideally, Telemetry could be defined at arbitrary points (ie a Command) in the flow to log telemetry, with the capability of logging contextual properties at the given point.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by yochay** [comment]
Telemetry for the new Adaptive dialog will be addressed in 4.5

**Comment by cleemullins** [comment]
No updates in nearly a year. Cllosing.

**Comment by yochay** [comment]
We need this.
Move to 4.7.

**Comment by daveta** [comment]
Here's a random stab.
https://github.com/daveta/analytics/blob/master/adaptive/README.md

**Comment by Ganesamurthy** [comment]
Hi @yochay,
It would be great, If you could please provide an update on this. Specifically in terms of Adaptive dialog and Luis telemetry with LUIS recognizer for preparing PBI reports mentioned in Virtual assistant template(https://microsoft.github.io/botframework-solutions/solution-accelerators/tutorials/view-analytics/1-intro/)
Related to https://github.com/microsoft/BotFramework-Composer/issues/1639

**Comment by scheyal** [comment]
This will more likely be an R9 deliverable. 
Re-assigning to @vishwacsena

**Comment by vishwacsena** [comment]
Tracked via https://github.com/microsoft/botbuilder-dotnet/issues/2406
