### ISSUE TITLE
ARM-based template for deploying App Insights Devops Dashboard

### ISSUE THREAD

**Issue by daveta** [microsoft/botframework-sdk#5233]
Include the following: unique sessions and users, average availability, failed requests, server exceptions and dependency failures, server response time.

**Comment by cleemullins** [comment]
Revisit this plan.

**Comment by cleemullins** [comment]
@scheyal Can you formulate a plan around this?

**Comment by scheyal** [comment]
According to @garypretty this is more challenging that initially thought. Per previous discussions, we decided to start with docs, and PowerBI guides/template. Docs will land in R7. Any further work should move to R8.

**Comment by scheyal** [comment]
We have a path, and we're targeting R8. 
@garypretty - please correct if we're not on path for R8. (basic dashboard)

**Comment by garypretty** [comment]
@scheyal we plan to validate the technical  approach next week. Getting this ready for an R8 release might be challenging given we need to also define what's on the dashboard.

This can be released as soon as we are ready though (I.e. We don't need to wait for R9) as in the first instance we will make this available via Github / docs.

**Comment by cleemullins** [comment]
@garypretty Can you provide an update for this? IT's marked as R8, and seems like we need to make a decision.

**Comment by garypretty** [comment]
@cleemullins Whilst this work is happening in the R8 window, it isn't intrinsically tied to it as the dashboard, when ready, will go out initially with docs and be passed to ABS for possible integration with the 'new bot' experience in Azure. We would like to get the template done before R8 wraps, but this has a dependency on us also getting the design of the initial MVP of the dashboard completed first.

With the above in mind - I will remove the R8 tag from this and replace with R9.  If we get it out in the R8 timeframe, great, but at least it isn't warping our numbers.

@emivers8 @scheyal and I will be regrouping on this week commencing 3/2.

**Comment by garypretty** [comment]
We now have successfully created an ARM template to deploy a dashboard.  The exact content of the template will need to be  amended once we land on the final makeup of our MVP dashboard, but the format of the template shouldn't change.

The current draft template 

is attached and needs four parameters to be deployed;

•	Path to the template file
•	Resource group (where your existing App Insights resource sits) name
•	App Insights resource name (where your bot is currently logging telemetry to)
•	Dashboard name

New-AzResourceGroupDeployment -TemplateFile .\dashboard-template.json -ResourceGroupName {ExistingAppInsightsResourceGroupName} -AppInsightsResourceName {ExistingAppInsightsResourceName} -DashboardName {DashboardName}

**Comment by garypretty** [comment]
Closing this as the work is being tracked in #5636
