### ISSUE TITLE
DCR: Add the ability to pass an initial value to a prompt

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5239]
## Issue
I'm working on a bot that will take entities received from LUIS and use them to potentially short circuit prompting the user within a waterfall.  The thing is these entities need to be validated and it would be great if we could easily use the validator built into the prompt to perform this validation. 

## Proposed change
We should add an `initialValue` option to the `PromptOptions` structure and then update prompts to first run the prompts validation routine against this value before prompting the user. If the value is valid the prompt will immediately return it as if the user had input it.  If it's invalid the prompt can go ahead and prompt the user for a valid value. We could also add a `invalidValuePrompt` to let the user tweak the message sent to the user.

This change should significantly clean up the way you skip steps for pre-populated values. You will no longer need to call `next()` to skip a step and can instead just always call the prompt and any pre-populated values that are valid will silently flow through to the next step. 

## Component Impact 
Just the `Prompt` base class and `PromptOptions` structures.

## Customer Impact 
This is additive so would be a non-breaking change for customers.  The docs will need to be updated though.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [x] Merged

[dcr]

**Comment by benbrown** [comment]
@Stevenic is this still applicable considering the input dialogs etc.

**Comment by Stevenic** [comment]
No
