### ISSUE TITLE
DCR: Add logic to AutoSaveStateMiddleware to save state before sending activities.

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5241]
## Issue
Currently, the `AutoSaveStateMiddleware` class only saves changes to the bots state at the end of the turn after all messages have been sent. This creates a small window where the user could reply before the bots state has been persisted.  

## Proposed change
We should update `AutoSaveStateMiddleware` to save any state changes **BEFORE** sending any activities.  The updated `onTurn()` method would look like this:

```JS
    public async onTurn(context: TurnContext, next: () => Promise<void>): Promise<void> {
        // ADD LOGIC TO SAVE STATE BEFORE SENDING ACTIVITIES
        context.onSendActivities(async (ctx, activities, next) => {
            await this.botStateSet.saveAllChanges(ctx, false);
            return await next();
        });

        // NORMAL PROCESSING FLOW
        await next();
        await this.botStateSet.saveAllChanges(context, false);
    }
```

While this does mean multiple calls to `saveAllChanges()`, the state objects are smart and will only make a storage call if something has changed so in most casses you will still only do a single storage call during a turn.

## Component Impact 
The AutoSaveStateMiddleware class.

## Customer Impact 
Most customers shouldn't notice any performance hit or behaviour change at all.  In certain casses this could introduce an additional storage call or two during a turn but it could be argue that in those scenarios the bot is even more at risk for getting into a bad state which this change would prevent.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
@Stevenic, closing this, it's been out there for too long.
