### ISSUE TITLE
DCR: consider adding new InputHintMiddleware class

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5257]
## Issue
When building a Cortana Skill its important that you correctly set the `inputHint` of outgoing activities. Unfortunately, this can be difficult because sometimes the dialog system will send an extra message that you weren't expecting (re-prompting for instance.)  We've seen time and time again that developers spend a lot of time just trying to get their input hints straight.

## Proposed change
We should consider adding a piece of middleware to the SDK that helps developers with this task by buffering up any outgoing activities and then  send them at the end of the turn after ensuring that all input hints are correctly set. Below is the TypeScript code for a piece of middleware that will do this and the C# version should look generally the same:

```TS
import { Middleware, TurnContext, InputHints, Activity, ActivityTypes } from 'botbuilder-core';

export class InputHintMiddleware implements Middleware {
    public async onTurn(context: TurnContext, next: () => Promise<void>): Promise<void> {
        // Buffer up outgoing messages without InputHints.IgnoringInput
        const buffer: Partial<Activity>[] = [];
        context.onSendActivities(async (ctx, activities, next) => {
            if (activities.length === 1 && 
                activities[0].type === ActivityTypes.Message &&
                activities[0].inputHint !== InputHints.IgnoringInput)
            {
                // Buffer up activity and return an empty ResourceResponse
                buffer.push(activities[0]);
                return [{}] as any;
            } else {
                // Let activities pass through
                return await next();
            }
        });

        // Continue processing activity
        await next();

        // Send any buffered messages
        if (buffer.length > 0) {
            // Adjust input hints
            for (let i = 0; i < buffer.length; i++) {
                if (i === (buffer.length - 1)) {
                    // Set to AcceptingInput if not already set to ExpectingInput
                    if (buffer[i].inputHint !== InputHints.ExpectingInput) {
                        buffer[i].inputHint = InputHints.AcceptingInput;
                    }
                } else {
                    // Force to IgnoringInput
                    buffer[i].inputHint = InputHints.IgnoringInput;
                }
            }

            // Send directly using adapter
            await context.adapter.sendActivities(context, buffer);
        }
    }
}
```

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
Cortana doesn't support skills anymore.
