### ISSUE TITLE
Request to offer a Conversation Flow Designer that simplifies common bot services with extensibility options

### ISSUE THREAD

**Issue by msolhab** [microsoft/botframework-sdk#5277]
A conversation flow service where pieces are defined and services are pointed to and outputs an intuitive, simple conversation flow utilizing those services would be very welcome to partners.

Users expect a higher level of abstraction, especially for commonly used conversational flows that connect to basic services such as LUIS, QnA Maker, Azure Search, with dialog choices and branches. Really need to offer an intuitive conversation designer that supports common flows while allowing for customization and extensibility.

**Comment by vovanb** [comment]
same reuest

**Comment by yochay** [comment]
We are actively working on a visual conversation design experience. We'll share updates by Build (early May 2019)

**Comment by bodyzatva** [comment]
any update?

**Comment by sgellock** [comment]
@yochay given the roadmap for this area, you should decided if this is addressed in the 4.6 release or if you want to keep it open past that.  moving to R7 as the Issue's resolution is not a 4.6 deliverable.

**Comment by yochay** [comment]
First part of the ask is part of 4.6. I'm not sure SDK will complete everything needed to provide and end-2-end solution for custom code in R7. With that said, we'll move this to R7 and keep updating as needed.

**Comment by vishwacsena** [comment]
[Bot Framework Composer](http://github.com/microsoft/botframework-composer) is now in public preview and offers a visual canvas that brings together Language Understanding, Dialog, Language generation and more. Please check it out and continue to share your feedback/ issues on that repo.
