### ISSUE TITLE
DCR: Bring back FileTranscriptStore 

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-sdk#5281]
## Issue
ITranscriptStore is the interface for interacting with a transcript store.  We had an implementation of ITranscriptStore which was folder/file based, but decided to remove it right before 4.0 to reduce surface area.  The problem is that we didn't remove it from the Javascript package.  

## Proposed change
* Add FileTranscriptStore back into .net assembly

## Component Impact 
Need to make sure docs get updated.

## Customer Impact 
None

## Tracking Status
**Dotnet SDK**
- [x] PR https://github.com/Microsoft/botbuilder-dotnet/pull/1355
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
Won't fix
