### ISSUE TITLE
[Feature Request] add an MRU cache to TextPrompt

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5283]
## Issue
Currently, the TextPrompt requires the user to have to type their answer in every time they answer a text prompt.  If you use a bot a lot and always have to type the same answer over and over again this can get annoying. If we add the concept of an MRU cache to TextPrompt we could use Suggested Actions to display the users previous responses to a given field.  The user can then simply click one of the displayed suggestions to answer the prompt. 
  
## Proposed change
This feature would depend on memory work I've been doing for 4.4 as the prompt would need to have direct access to UserState and/or ConversationState for persisting the MRU.

My idea is that we can add a `TextPrompt.mruProperty` which lets the developer specify where in memory they would like the cache stored. This would default to "user.promptMru" but the could change it to another memory location if they would like.  

We would also add a `TextPrompt.mruTag` which lets the developer specify the key to use for a given prompt within the bound cache.  If your bot had both `origCity` and `destCity` prompts, you could set the mruTag for both to "city" so that they share the same cached list of city names.

A `TextPrompt.mruSize` property would let the developer adjust the size of the cache for a given prompt.  This would probably default to something reasonable like 5.  

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
Closing this one, I think we can create a new one for adaptive if needed
