### ISSUE TITLE
Asp.Net MVC Integration

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5285]
# ASP MVC Integration
## Introducing an Event Based Programming Model
> The concepts here are common to the JavaScript and C# implementations, although the proposal here is to surface the functionality in slightly different platform specific ways.

With this DCR the bot application logic can be factored into a series of event handlers, as the following example illustrates:

```cs
    public class MyActivityHandler : ActivityHandler
    {
        protected override async Task OnMemberAddedAsync(
            ChannelAccount account,   
            ITurnContext<IConversationUpdateActivity> turnContext,
            CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync                (
                MessageFactory.Text($"Welcome {account.Name}"));
        }

        protected override async Task OnMessageAsync(
            ITurnContext<IMessageActivity> turnContext,
            CancellationToken cancellationToken)
        {
            await turnContext.SendActivityAsync(
                MessageFactory.Text($"Echo: {turnContext.Activity.Text}"));
        }
    }
```

The new SDK class here is **ActivityHandler**.

To the C# programmer these event handlers are plugged through inheritance and are _strongly typed_. Both the use of inheritance and the typing contribute to discoverability: with Intellisense the inheritance tells the developer what Activities can arrive and the typing tells her the shape of the particular Activity. In addition to removing boiler plate code from the application by putting it in the SDK.

To the JavaScript programmer the **ActivityHandler** exposes a set of Node JS style event handlers.

In C#, **ActivityHandler** is itself derived from **IBot**. As such users of the existing C# integration are free to incorporate this new class with minimal change to existing projects.

The C# programmer will be happy to see the stronger typing on the event handlers. By introducing a new interface **ITurnContext< T >** we are able to (for the first time) make effective use of the existing **IMessageActivity**, **IConversationUpdateActivity** etc.

### This section is specific to C#.

As previous samples have demonstrated [see C# Sample 30](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/30.asp-mvc-bot), it has always been possible to host bot logic in MVC Controllers. However, this has involved pulling in some custom serialization code, knowledge of headers and adapter invocation. In the previous sample code this code was hidden in a Controller base class. This DCR moves this code into the product but places it in a subclass of the **BotFrameworkAdapter** called **BotFrameworkAdapterEx**.

Needing to support two versions of ASP WebApi and Net Core means we end out with slightly different flavors of this class, though in essense they are the same. We put each in its own namespace, specific to the version of the .NET framework. The code goes into the corresponding, and preexitsing, integration packages.

In order to better support dependency injection this DCR also specifies a new interface called **IBotFrameworkAdapter**. This is defined as follows:

```cs
    public interface IBotFrameworkAdapter
    {
        Task ProcessAsync(
            HttpRequest request,
            HttpResponse response,
            IBot bot,
            CancellationToken cancellationToken = default(CancellationToken));
    }
```

The "Ex" versions of the BotFrameworkAdapter provide implementations of this interface. 

> It is worth noting that this actually brings the C# SDK more inline with the JavaScript SDK because the JavaScript SDK BotFrameworkAdapter has always taken the WebRequest and WebResponse as arguments to invoke the adapter.

Using this new adapter implementing a Controller is trivial, as the following example shows:

```cs
    [Route("mybot")]
    public class MyController : Controller
    {
        private IBotFrameworkAdapter _adapter;
        private IBot _bot;

        public BotController(
            IBotFrameworkAdapter adapter, IBot bot)
        {
            _adapter = adapter;
            _bot = bot;
        }

        [HttpPost]
        public async Task PostAsync()
        {
            await _adapter.ProcessAsync(Request, Response, _bot);
        }
    }
```
In this example both the *adapter* and the *bot* were dependency injected. The use of dependency injection is completely optional and simply a choice made by the developer of this particular project. For this particular example, the project's Startup.cs included the following:

```cs
    services.AddSingleton<IBotFrameworkAdapter>(
        sp => new BotFrameworkAdapterEx(
        new SimpleCredentialProvider()));

    services.AddTransient<IBot>(
        sp => new MyActivityHandler());
```

The application developer is of course free to write this Controller code themselves. However, generating this code is a natural step for the Visual Studio integration (via VSIX) we provide.

# Appendix I
---

_Summary of artifacts in C#_

**Microsoft.Bot.Builder**

- ITurnContext< T >
- ActivityHandler

**Microsoft.Bot.Builder.Integration.AspNet.Core**

- IBotFrameworkAdapter
- BotFrameworkAdapterEx

**Microsoft.Bot.Builder.Integration.AspNet.WebApi**

- IBotFrameworkAdapter
- BotFrameworkAdapterEx

_Summary of artifacts in JavaScript_

**Microsoft.Bot.Builder.Core**

- ActivityHandler

## Appendix II
---

Source code for C# AspNet.Core (for illustration only the final code will be a PR.)

### IBotFrameworkAdapter.cs
> Note there will be two flavors of this class one for Net Core and one for WebApi.

```cs
    public interface IBotFrameworkAdapter
    {
        Task ProcessAsync(HttpRequest request, HttpResponse response, IBot bot, CancellationToken cancellationToken = default(CancellationToken));
    }
```

### ITurnContext{T}.cs
> Note the assumption here is that T is IMessageActivity etc.

```cs
    public interface ITurnContext<T> : ITurnContext
    {
        new T Activity { get; }
    }
```

### ActivityHandler.cs
---

```cs
    public class ActivityHandler : IBot
    {
        public virtual Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            if (turnContext.Activity.Type == ActivityTypes.Message)
            {
                return OnMessageAsync(new DelegatingTurnContext<IMessageActivity>(turnContext), cancellationToken);
            }
            else if (turnContext.Activity.Type == ActivityTypes.ConversationUpdate)
            {
                return OnConversationUpdateAsync(new DelegatingTurnContext<IConversationUpdateActivity>(turnContext), cancellationToken);
            }
            else if (turnContext.Activity.Type == ActivityTypes.Event)
            {
                return OnEventActivityAsync(turnContext, cancellationToken);
            }
            else if (turnContext.Activity.Type == ActivityTypes.DeleteUserData)
            {
                return OnDeleteUserDataActivityAsync(turnContext, cancellationToken);
            }
            else if (turnContext.Activity.Type == ActivityTypes.ContactRelationUpdate)
            {
                return OnContactRelationUpdateActivityAsync(turnContext, cancellationToken);
            }
            else
            {
                return OnUnrecognizedActivityTypeAsync(turnContext, cancellationToken);
            }
        }

        protected virtual Task OnMessageAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        protected virtual Task OnConversationUpdateAsync(ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            if (turnContext.Activity.MembersAdded != null)
            {
                return OnMembersAddedAsync(turnContext.Activity.MembersAdded, turnContext, cancellationToken);
            }
            else if (turnContext.Activity.MembersRemoved != null)
            {
                return OnMembersRemovedAsync(turnContext.Activity.MembersAdded, turnContext, cancellationToken);
            }

            return Task.CompletedTask;
        }

        protected virtual async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            foreach (var member in membersAdded)
            {
                if (member.Id != turnContext.Activity.Recipient.Id)
                {
                    await OnMemberAddedAsync(member, turnContext, cancellationToken);
                }
            }
        }

        protected virtual async Task OnMembersRemovedAsync(IList<ChannelAccount> membersRemoved, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            foreach (var member in membersRemoved)
            {
                if (member.Id != turnContext.Activity.Recipient.Id)
                {
                    await OnMemberRemovedAsync(member, turnContext, cancellationToken);
                }
            }
        }

        protected virtual Task OnMemberAddedAsync(ChannelAccount account, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        protected virtual Task OnMemberRemovedAsync(ChannelAccount account, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        protected virtual Task OnEventActivityAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        protected virtual Task OnDeleteUserDataActivityAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        protected virtual Task OnContactRelationUpdateActivityAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            // TODO: some documentation as to when this Activity can be sent would be helpful
            return Task.CompletedTask;
        }

        protected virtual Task OnUnrecognizedActivityTypeAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        private class DelegatingTurnContext<T> : ITurnContext<T>
            where T : class
        {
            private ITurnContext _innerTurnContext;

            public DelegatingTurnContext(ITurnContext innerTurnContext)
            {
                _innerTurnContext = innerTurnContext;
            }

            T ITurnContext<T>.Activity => (T)(object)_innerTurnContext.Activity;

            public BotAdapter Adapter => _innerTurnContext.Adapter;

            public TurnContextStateCollection TurnState => _innerTurnContext.TurnState;

            public Activity Activity => _innerTurnContext.Activity;

            public bool Responded => _innerTurnContext.Responded;

            public Task DeleteActivityAsync(string activityId, CancellationToken cancellationToken = default(CancellationToken))
            {
                return _innerTurnContext.DeleteActivityAsync(activityId, cancellationToken);
            }

            public Task DeleteActivityAsync(ConversationReference conversationReference, CancellationToken cancellationToken = default(CancellationToken))
            {
                return _innerTurnContext.DeleteActivityAsync(conversationReference, cancellationToken);
            }

            public ITurnContext OnDeleteActivity(DeleteActivityHandler handler)
            {
                return _innerTurnContext.OnDeleteActivity(handler);
            }

            public ITurnContext OnSendActivities(SendActivitiesHandler handler)
            {
                return _innerTurnContext.OnSendActivities(handler);
            }

            public ITurnContext OnUpdateActivity(UpdateActivityHandler handler)
            {
                return _innerTurnContext.OnUpdateActivity(handler);
            }

            public Task<ResourceResponse[]> SendActivitiesAsync(IActivity[] activities, CancellationToken cancellationToken = default(CancellationToken))
            {
                return _innerTurnContext.SendActivitiesAsync(activities, cancellationToken);
            }

            public Task<ResourceResponse> SendActivityAsync(string textReplyToSend, string speak = null, string inputHint = "acceptingInput", CancellationToken cancellationToken = default(CancellationToken))
            {
                return _innerTurnContext.SendActivityAsync(textReplyToSend, speak, inputHint, cancellationToken);
            }

            public Task<ResourceResponse> SendActivityAsync(IActivity activity, CancellationToken cancellationToken = default(CancellationToken))
            {
                return _innerTurnContext.SendActivityAsync(activity, cancellationToken);
            }

            public Task<ResourceResponse> UpdateActivityAsync(IActivity activity, CancellationToken cancellationToken = default(CancellationToken))
            {
                return _innerTurnContext.UpdateActivityAsync(activity, cancellationToken);
            }
        }
    }
}
```

### BotFrameworkAdapterEx.cs
---

> Note there will be two flavors of this class one for Net Core and one for WebApi.

```cs
    public class BotFrameworkAdapterEx : BotFrameworkAdapter, IBotFrameworkAdapter
    {
        public BotFrameworkAdapterEx(
            ICredentialProvider credentialProvider)
            : base(credentialProvider)
        {
        }

        public async Task ProcessAsync(
            HttpRequest request,
            HttpResponse response,
            IBot bot,
            CancellationToken cancellationToken = default(CancellationToken))
        {
            // deserialize the incoming Activity
            var activity = HttpHelper.FromRequest(request);

            // grab the auth header from the inbound http request
            var authHeader = request.Headers["Authorization"];

            // process the inbound activity with the bot
            var invokeResponse = await ProcessActivityAsync(authHeader, activity, bot.OnTurnAsync, cancellationToken);

            // write the response, potentially serializing the InvokeResponse
            HttpHelper.ToResponse(response, invokeResponse);
        }
    }
```

**Comment by cleemullins** [comment]
The PR where this work is functional is here https://github.com/Microsoft/BotBuilder-Samples/pull/1176

**Comment by Stevenic** [comment]
My one nit is that I think it's dangerous to have `OnMemberAdded()` pass each individual member via a separate call.  You can theoretically get 50 members added in a single call which would cause your bot to flood the conversation with welcome messages.  I think we should stick closer to the protocol and call a single `OnConversationMembersAdded()` event for a given activity.  It's not that hard to loop over an array.  

If you want to filter out the fact that the bot was added to the conversation that's a different story. If the only member in the `membersAdded` array is the bot then I think you could safely ignore the activity which I believe is what you're striving for here.

**Comment by Stevenic** [comment]
@johnataylor you asked me to point out potential gotchas in the protocol so another one worth noting is that the address information for `ConversationUpdate` events is wrong and often needs to be patched before loading things like state.  The core issue is that you often get a ConversationUpdate that has either a missing or invalid `from` address.  That means that trying to load UserState will load the wrong users state and trying to send replies could result in replying to the wrong person.

It's safest to do this repair as a piece of middleware and you can find an example of the patch I do in my toybox repo as well as a detail explanation of the issue.  According to @dandriscoll the issue isn't really fixible. They sometimes just don't know who initiated the conversation update.

https://github.com/Stevenic/botbuilder-toybox/blob/master/packages/botbuilder-toybox-extensions/src/patchFromMiddleware.ts

**Comment by dandriscoll** [comment]
I wouldn't say it's not fixable ... it's that some messages don't originate from a user, so the `from` field can't meaningfully represent one.

**Comment by cleemullins** [comment]
@Stevenic Why would this need Middleware to fix? 

Seems like this could just as easily be fixed up as part of the actual Activty processing pipeline we've got here. If custom behavior is needed, it's easy enough to have a "public virtual FixUpFromAddress() type method that can be run.

**Comment by Stevenic** [comment]
@cleemullins you could do it as part of the processing pipeline but if you then add middleware that needs a valid `from` address it wouldn't have one.  Things like telemetry middleware for instance could log the wrong info.  Doing the patch as a piece of middleware just lets you do it first before anything else runs.

**Comment by sgellock** [comment]
this work is done as of 4.4
