### ISSUE TITLE
DCR: patch incoming ConversationUpdate activities

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5292]
## Issue
The `ConversationUpdate` activity sometimes has the wrong or missing "from" field. This can result in the following issues: 

- Changes made to UserState are lost because the changes are saved to a bogus users storage record.
- Direct conversations with the user added can't be started because of the bogus account info.

## Proposed change
I currently have a piece of middleware that patches the missing from field but its been proposed that we move this logic into the `BotFrameworkAdapter` so that developers don't need to know they should add this middleware.  The code I use to do the patch is listed below:

```TS
export class PatchFromMiddleware implements Middleware {

    public async onTurn(context: TurnContext, next: () => Promise<void>): Promise<void> {
        if (context.activity && context.activity.type === ActivityTypes.ConversationUpdate) {
            // Get list of members added or removed
            const members = context.activity.membersAdded ? context.activity.membersAdded : context.activity.membersRemoved;

            // Filter out "bot" for list of accounts
            const accounts = members && context.activity.recipient ? members.filter((m) => m.id !== (context.activity as any).recipient) : [];

            // Patch from field
            const cnt = accounts.length;
            if (cnt > 0 && (cnt === 1 || !context.activity.from)) {
                context.activity.from = accounts[0];
            }
        }
        await next();
    }
}
```

## Component Impact 
The `BotFrameworkAdapter`.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
I don't think this applies anymore
