### ISSUE TITLE
DCR: patch Message Text for submitted Adaptive Cards

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5293]
## Issue
When an AdaptiveCard is submitted via the `Submit.Action` button, the bot receives an `message` activity with an empty `text` field and a `value` field containing a JSON object with the submitted input field values. The issue is there's no built in way of knowing what button was clicked or what form is being submitted.  Developers currently need to add a hidden field to the `Submit.Action` which they can then use to route the received form data.

## Proposed change
We can provide a more general solution to this problem if we update the `BotFrameworkAdapter` class to detect an incoming AdaptiveCard form (missing text and JSON object in the value field) and then look for a special "message.text" field, in the values JSON object, which we then promote to being the `text` of the received activity. This will make the `Submit.Action` behave more like an `imBack` or `postBack` card action which can be easily routed within the bot.

## Component Impact 
Just the `BotFrameworkAdapter` class.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by v-kydela** [comment]
@Stevenic - This is a great DCR! I have a question and a comment if you don't mind.

1. It sounds like you are saying the `Activity.Text` would be populated with a "message.text" value retrieved from `Activity.Value`. I'm wondering how the "message.text" value would get there. Wouldn't it have to be put in the Adaptive Card just like the hidden field you mentioned that developers currently need to add?
2. If an adaptive submit action suddenly stopped producing textless messages, this would break bots that are currently checking if a message's text property is null when they respond to submit actions.

**Comment by Stevenic** [comment]
> 1. It sounds like you are saying the `Activity.Text` would be populated with a "message.text" value retrieved from `Activity.Value`. I'm wondering how the "message.text" value would get there. Wouldn't it have to be put in the Adaptive Card just like the hidden field you mentioned that developers currently need to add?
Yes... Developers would need to add a "message.text" hidden field to their adaptive cards so we would need docs and samples that show this in action.

> 2. If an adaptive submit action suddenly stopped producing textless messages, this would break bots that are currently checking if a message's text property is null when they respond to submit actions.
The developer would need to update all of their current adaptive cards to include the "message.text" for the behavior to change.  Given that it seems highly unlikely anyone currently has cards with a "message.text" field it seems like a pretty low risk change.

**Comment by v-kydela** [comment]
Ah, so when you say "Developers currently need to add a hidden field to the `Submit.Action`" you don't mean that's something that this DCR would change.

**Comment by darrenj** [comment]
This would address a key problem with Bots that leverage Adaptive Cards and remove manual workarounds required to get prompts for example to work.
