### ISSUE TITLE
FEATURE: add RegExpRecognizer

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5296]
## Issue
In v3 we had a `RegExpRecognizer` class that you could use to implement an intent based bot using regular expressions.  We briefly had that in v4 but pulled it because we wanted the LuisRecognizer to stabilize a bit. 

## Proposed change
Given that we can't easily change the shape of results returned from the luis recognizer I propose we first add a `Recognizer` interface which standardizes the shape of recognizer plugins:

```TS
interface Recognizer {
     recognize(context: TurnContext): Promise<RecognizerResult>;
}
```

Next I think we should add a `RegExpRecognizer` class back into the core SDK. I have a [JavaScript implementation here](https://github.com/Microsoft/botbuilder-js/blob/stevenic/4.4-planning/libraries/botbuilder-dialogs/src/planning/regExpRecognizer.ts) which I'd propose we just port to C#.

My current implementation supports the following features:

- Calculates a confidence score based of the number of characters in the utterance matched by the expression. 
- Devs can add multiple expressions for the same intent and the top scoring expression will be used.
- Has a `multiIntentMode` property which enables recognizing multiple intents within the same utterance. If this property is `false`, only the top scoring intent is returned. 
- Maps both named and numbered capture groups to entities that conform with the way LUIS returns entities.
- Entity values are returned as string arrays, like LUIS. When in "multi-intent" mode, the same entities returned by different expressions will only be appended to an array if they're unique in value. So if you have a "city" capture group in two different expressions and they both return a different city name you'll get an array containing both city names. If thy're the same then you'll just have the one common city name in the array.  
 
## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
Composer and adaptive have it, closing it
