### ISSUE TITLE
DCR: Add PromptQuestion helper method to make it easier to ask a quetion

### ISSUE THREAD

**Issue by AskYous** [microsoft/botframework-sdk#5299]
## Issue
Prompting the user is too complicated. It requires too many steps and is all over the place. I keep having to look back at the documentation or sample code every time I want to ask the user a question. I have to register some prompts, register a waterfall dialog step thing, check the `.activeDialog`, etc... I tried to see if there's a simple way to do this but I don't see one.

## Proposed change
Prompting the user for information should be 1 line of code:
`const name = await step.context.promptQuestion("What is your name?")`.  
It should be that simple.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by Stevenic** [comment]
This will be much simpler in 4.next

**Comment by Stevenic** [comment]
@AskYous giving a little more context... Your approach would only work if the users reply came back to the compute node that asked the question and we can't guarantee that. In fact, if you have a large production bot that's running across multiple compute nodes its very likely that the answer will be processed by a different machine.

Additionally, it could be minutes, hours, or even days before the user responds to a question and the bot could have been redeployed in between the question being asked and the user answering.  

While I agree that the current prompt system seems a little complicated its robust to all of these issues.  With that said, we've made significant progress in simplifying prompts with the new Adaptive Dialog work we're doing and we essentially have prompts reduced to a one liner.  The next preview of Adaptive Dialog should be released soon.

**Comment by AskYous** [comment]
Thanks for the update. I'm definitely excited for the one-liner prompts.
