### ISSUE TITLE
LINE - Update Docs for Cards and Actions

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5317]
Docs on the following topics need to be updated for Line:
1. Suggested Actions
2. Hero Cards
3. Adaptive Cards

According to @youyu16 we should set:
> max number of suggested actions should be 13 and max number of card action should be 4 depend on LINE document.

**Comment by EricDahlvang** [comment]
@cleemullins  I cannot find any docs that specify channel specific support for Suggested Actions, Hero Cards, or Adaptive Cards (well, there is this for AC: https://docs.microsoft.com/en-us/adaptive-cards/resources/partners ... but I don't think that is what you are referring to).  I asked @Kaiqb who said this is all we've got right now: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference

**Comment by youyu16** [comment]
@cleemullins to be honest, most of the card can support many buttons, only animation card have the 'max 4' limitation.

**Comment by EricDahlvang** [comment]
PR submitted https://github.com/MicrosoftDocs/bot-docs/pull/992

**Comment by Kaiqb** [comment]
This issue is tracked [here](https://github.com/microsoft/botframework-sdk/issues/5629)
