### ISSUE TITLE
4.5 DCR: break out dialog input & output binding as an interface

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5338]
## Issue
We currently have `Dialog.inputProperties` and `Dialog.outputProperty` members that the `DialogContext` uses to automatically data bind a dialogs options and output to memory. Given that not every dialog uses this feature, @tomlm  and I were thinking this should probably be an optional interface that dialogs implement as needed. 

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
@Stevenic , closing this for now, feel free to reopen if we need it.
