### ISSUE TITLE
4.5 DCR: Add EndConversation step

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5339]
## Issue
We don't currently have an `EndConversation` step in either the C# or JS code. The developer can send an `EndOfConversation` activity but what you really want to do is both send the activity and then clear the bots conversational memory.

## Proposed change
Add a new `EndConversation` step that does the following:

- Emits an "conversationEnded" event.
- If the event isn't handled the step will send an "EndOfConversation" activity.
- Sending of the "EndOfConversation" activity should trigger clearing of the bots conversation state and dialog stack.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
@Stevenic, closing this for now, feel free to reopen if we need it.
