### ISSUE TITLE
DCR: As a developer, I would like to see some documentation to understand how to use the DialogTestClient provided by the framework so I can write unit tests for my bot

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#5363]
The new Testing Framework needs to be documented so developers understand how to use it.

The documentation should include:
  - Inline documentation in code for key classes, methods and properties in the testing framework.
  - Redme.md files in CoreBot samples
  - Code comments in CoreBot samples
  - Getting started guide on how to write tests posted to docs.microsoft.com ( created for each supported language under https://aka.ms/cs-unit-test-docs)

## Tracking Status for documentation
**Dotnet documentation**
- [x] PR
- [x] Merged

**Javascript documentation**
- [x] PR
- [x] Merged

**Python documentation**
- [ ] PR
- [ ] Merged

## Tracking Status for samples readme
**Dotnet Readme**
- [x] PR
- [x] Merged

**Javascript Readme**
- [x] PR
- [x] Merged

**TypeScript Readme**
- [x] PR
- [x] Merged

**Python Readme**
- [ ] PR
- [ ] Merged

**Comment by Kaiqb** [comment]
Content is now staging here: https://review.docs.microsoft.com/en-us/azure/bot-service/test-bot?view=azure-bot-service-4.0&branch=pr-en-us-1588.

**Comment by gabog** [comment]
@Kaiqb, reopening this one to be able to track the changes that will be needed for Python in 4.6.

**Comment by Kaiqb** [comment]
@gabog - Python is not going to GA in 4.6. Removing the 4.6 tag.

**Comment by Kaiqb** [comment]
@gabog - are you planning to update this workitem for Python in R7?

**Comment by gabog** [comment]
+ @axelsrz, hi Axel, are you planning to write docs as part of Python R7 support for testing dialog?

**Comment by axelsrz** [comment]
If we have an equivalent doc for C# and JS, yes.

**Comment by Kaiqb** [comment]
@axelsrz - we do have C# and JS docs. You can see it [here](https://docs.microsoft.com/en-us/azure/bot-service/unit-test-bots?view=azure-bot-service-4.0&tabs=csharp). Do you plan to have additional namespaces to support the testing approach outlined in the topic?

**Comment by axelsrz** [comment]
This is already in master branch, the new library is botbuilder-testing https://github.com/microsoft/botbuilder-python/tree/master/libraries/botbuilder-testing

**Comment by Kaiqb** [comment]
Thanks! We'll pick this up in R8.

**Comment by JonathanFingold** [comment]
@axelsrz What are the dependencies for Python? The current topic has this for C# and JavaScript:
- C#: The CoreBot Tests sample used in this topic references the Microsoft.Bot.Builder.Testing package, XUnit, and Moq to create unit tests.
- JS: The CoreBot Tests sample used in this topic references the botbuilder-testing package, Mocha to create unit tests and Mocha Test Explorer to visualize test results in VS Code.

Also, I see a 13.core-bot.tests for C# and 13.core-bot for JS has a test subfolder. I don't see anything comparable for Python. Where can I pull code snippets from?
