### ISSUE TITLE
Email channel connection to Bot

### ISSUE THREAD

**Issue by wirstein** [microsoft/botframework-sdk#5372]
Hello there. I'm trying to connect the email channel to my bot TestGeneSupport .
All other channels working normally: skype, webchat... Have some troubles with slack, but it is not crytically.
After the attemption to connect the bot I see the message:
**Unable to validate the given credentials. ID: |bk9vr.XJVRb.877d5a30_**
I can offer my cridentials of microsoft office 365 account for testing:

I asked for the support team and Robert O. answered:
_I have just tried this from my side and I was able to reproduce the error using multiple browsers.So it looks like this an issue on Azure's side._

**Comment by EricDahlvang** [comment]
Hi @wirstein 

Please try running the Microsoft Exchange Web Services Connectivity Tests here: https://testconnectivity.microsoft.com/ 

Generally, when this error occurs it is due to Auto Discovery not being setup correctly for the exchange server.  The code the bot portal runs during email account verification is similar to this: https://github.com/EricDahlvang/ExchangeConnectivityTest/blob/master/ExchangeConnectivityTest/CredentialsTester.cs

**Comment by wirstein** [comment]
I reached the message "Connectivity Test Failed"

`<?xml version="1.0" encoding="utf-8"?>
<testresult status="Error" errorid="734044ef-11c2-4e30-9ee6-450d49e9d92c" contentUrl="" testdescription="Exchange Web Services synchronization, notification, availability, and Automatic Replies." resultdescription="Not all tests of Exchange Web Services tasks completed." additionaldetails="" elapsedMilliseconds="2991">
  <children>
    <testresult status="Error" errorid="734044ef-11c2-4e30-9ee6-450d49e9d92c" contentUrl="" testdescription="The Microsoft Connectivity Analyzer is attempting to test Autodiscover for regonline@testgen.ru." resultdescription="Testing Autodiscover failed." additionaldetails="" elapsedMilliseconds="2991">
      <children>
        <testresult status="Error" errorid="734044ef-11c2-4e30-9ee6-450d49e9d92c" contentUrl="" testdescription="Attempting each method of contacting the Autodiscover service." resultdescription="The Autodiscover service couldn't be contacted successfully by any method." additionaldetails="" elapsedMilliseconds="2991">
          <children>
            <testresult status="Error" errorid="734044ef-11c2-4e30-9ee6-450d49e9d92c" contentUrl="" testdescription="Attempting to test potential Autodiscover URL https://testgen.ru:443/Autodiscover/Autodiscover.xml" resultdescription="Testing of this potential Autodiscover URL failed." additionaldetails="" elapsedMilliseconds="2968">
              <children>
                <testresult status="Success" errorid="00000000-0000-0000-0000-000000000000" contentUrl="" testdescription="Attempting to resolve the host name testgen.ru in DNS." resultdescription="The host name resolved successfully." additionaldetails="IP addresses returned: 194.87.101.84" elapsedMilliseconds="16">
                  <children />
                </testresult>
                <testresult status="Success" errorid="00000000-0000-0000-0000-000000000000" contentUrl="" testdescription="Testing TCP port 443 on host testgen.ru to ensure it's listening and open." resultdescription="The port was opened successfully." additionaldetails="" elapsedMilliseconds="193">
                  <children />
                </testresult>
                <testresult status="Success" errorid="734044ef-11c2-4e30-9ee6-450d49e9d92c" contentUrl="" testdescription="Testing the SSL certificate to make sure it's valid." resultdescription="The certificate passed all validation requirements." additionaldetails="" elapsedMilliseconds="391">
                  <children>
                    <testresult status="Success" errorid="00000000-0000-0000-0000-000000000000" contentUrl="" testdescription="The Microsoft Connectivity Analyzer is attempting to obtain the SSL certificate from remote server testgen.ru on port 443." resultdescription="The Microsoft Connectivity Analyzer successfully obtained the remote SSL certificate." additionaldetails="Remote Certificate Subject: CN=testgen.ru, Issuer: CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US." elapsedMilliseconds="368">
                      <children />
                    </testresult>
                    <testresult status="Success" errorid="00000000-0000-0000-0000-000000000000" contentUrl="" testdescription="Validating the certificate name." resultdescription="The certificate name was validated successfully." additionaldetails="Host name testgen.ru was found in the Certificate Subject Common name." elapsedMilliseconds="0">
                      <children />
                    </testresult>
                    <testresult status="Success" errorid="00000000-0000-0000-0000-000000000000" contentUrl="" testdescription="Testing the certificate date to confirm the certificate is valid." resultdescription="Date validation passed. The certificate hasn't expired." additionaldetails="The certificate is valid. NotBefore = 4/8/2019 5:00:21 AM, NotAfter = 7/7/2019 5:00:21 AM" elapsedMilliseconds="0">
                      <children />
                    </testresult>
                  </children>
                </testresult>
                <testresult status="Success" errorid="00000000-0000-0000-0000-000000000000" contentUrl="" testdescription="Checking the IIS configuration for client certificate authentication." resultdescription="Client certificate authentication wasn't detected." additionaldetails="Accept/Require Client Certificates isn't configured." elapsedMilliseconds="1081">
                  <children />
                </testresult>
                <testresult status="Error" errorid="734044ef-11c2-4e30-9ee6-450d49e9d92c" contentUrl="" testdescription="Attempting to send an Autodiscover POST request to potential Autodiscover URLs." resultdescription="Autodiscover settings weren't obtained when the Autodiscover POST request was sent." additionaldetails="" elapsedMilliseconds="1286">
                  <children>
                    <testresult status="Error" errorid="12f4b21a-7e8d-4c95-b4a8-f4608e7d73b0" contentUrl="" testdescription="The Microsoft Connectivity Analyzer is attempting to retrieve an XML Autodiscover response from URL https://testgen.ru:443/Autodiscover/Autodiscover.xml for user regonline@testgen.ru." resultdescription="The Microsoft Connectivity Analyzer failed to obtain an Autodiscover XML response." additionaldetails="A Web exception occurred because an HTTP 404 - NotFound response was received from Unknown.&#xD;&#xA;HTTP Response Headers:&#xD;&#xA;Pragma: no-cache&#xD;&#xA;Content-Length: 21928&#xD;&#xA;Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0&#xD;&#xA;Content-Type: text/html; charset=UTF-8&#xD;&#xA;Date: Tue, 23 Apr 2019 17:11:20 GMT&#xD;&#xA;Expires: Thu, 19 Nov 1981 08:52:00 GMT&#xD;&#xA;Set-Cookie: PHPSESSID=jm5i08hcpobvg6gh8q4b0ktit3; expires=Tue, 30-Apr-2019 17:11:20 GMT; Max-Age=604800; path=/; HttpOnly&#xD;&#xA;Server: Microsoft-IIS/8.5&#xD;&#xA;X-Powered-By: PHP/5.6.31&#xD;&#xA;" elapsedMilliseconds="1285">
                      <children />
                    </testresult>
                  </children>
                </testresult>
              </children>
            </testresult>
            <testresult status="Error" errorid="734044ef-11c2-4e30-9ee6-450d49e9d92c" contentUrl="" testdescription="Attempting to test potential Autodiscover URL https://autodiscover.testgen.ru:443/Autodiscover/Autodiscover.xml" resultdescription="Testing of this potential Autodiscover URL failed." additionaldetails="" elapsedMilliseconds="10">
              <children>
                <testresult status="Error" errorid="84d3f5cd-1fb9-4163-b0cd-6b0e3581ec24" contentUrl="http://go.microsoft.com/?linkid=9843801" testdescription="Attempting to resolve the host name autodiscover.testgen.ru in DNS." resultdescription="The host name couldn't be resolved." additionaldetails="Host autodiscover.testgen.ru couldn't be resolved in DNS InfoDomainNonexistent." elapsedMilliseconds="10">
                  <children />
                </testresult>
              </children>
            </testresult>
            <testresult status="Error" errorid="734044ef-11c2-4e30-9ee6-450d49e9d92c" contentUrl="" testdescription="Attempting to contact the Autodiscover service using the HTTP redirect method." resultdescription="The attempt to contact Autodiscover using the HTTP Redirect method failed." additionaldetails="" elapsedMilliseconds="9">
              <children>
                <testresult status="Error" errorid="84d3f5cd-1fb9-4163-b0cd-6b0e3581ec24" contentUrl="http://go.microsoft.com/?linkid=9843801" testdescription="Attempting to resolve the host name autodiscover.testgen.ru in DNS." resultdescription="The host name couldn't be resolved." additionaldetails="Host autodiscover.testgen.ru couldn't be resolved in DNS InfoDomainNonexistent." elapsedMilliseconds="9">
                  <children />
                </testresult>
              </children>
            </testresult>
            <testresult status="Error" errorid="734044ef-11c2-4e30-9ee6-450d49e9d92c" contentUrl="" testdescription="Attempting to contact the Autodiscover service using the DNS SRV redirect method." resultdescription="The Microsoft Connectivity Analyzer failed to contact the Autodiscover service using the DNS SRV redirect method." additionaldetails="" elapsedMilliseconds="2">
              <children>
                <testresult status="Error" errorid="8249cc81-d0ce-43d2-b319-48ceadb1bfe7" contentUrl="http://go.microsoft.com/?linkid=9843849" testdescription="Attempting to locate SRV record _autodiscover._tcp.testgen.ru in DNS." resultdescription="The Autodiscover SRV record wasn't found in DNS." additionaldetails="" elapsedMilliseconds="1">
                  <children />
                </testresult>
              </children>
            </testresult>
            <testresult status="Warning" errorid="c0f75b77-072c-48d5-ab17-eebc99a4b3d9" contentUrl="http://go.microsoft.com/?linkid=9843786" testdescription="Checking if there is an autodiscover CNAME record in DNS for your domain 'testgen.ru' for Office 365." resultdescription="Failed to validate autodiscover CNAME record in DNS. If your mailbox isn't in Office 365, you can ignore this warning." additionaldetails="There is no Autodiscover CNAME record for your domain 'testgen.ru'." elapsedMilliseconds="1">
              <children />
            </testresult>
          </children>
        </testresult>
      </children>
    </testresult>
  </children>
</testresult>`

> Hi @wirstein
> 
> Please try running the Microsoft Exchange Web Services Connectivity Tests here: https://testconnectivity.microsoft.com/
> 
> Generally, when this error occurs it is due to Auto Discovery not being setup correctly for the exchange server. The code the bot portal runs during email account verification is similar to this: https://github.com/EricDahlvang/ExchangeConnectivityTest/blob/master/ExchangeConnectivityTest/CredentialsTester.cs

**Comment by EricDahlvang** [comment]
An administrator of the domain will need to configure auto-discovery. https://docs.microsoft.com/en-us/exchange/architecture/client-access/autodiscover?view=exchserver-2019

**Comment by wirstein** [comment]
> An administrator of the domain will need to configure auto-discovery. https://docs.microsoft.com/en-us/exchange/architecture/client-access/autodiscover?view=exchserver-2019

What if it is only office365 user which mail we wish to use? Where then should I setup the autodiscovery?

**Comment by dmvtech** [comment]
@wirstein Office365 _should_ have auto discovery configured already. That being said, outlook_03a37103e88e606a@outlook.com doesn't look to be a O365 account, but a free, outlook.com/MSA account. My assumption is that those _should_ have auto discovery set up as well, but I tried a test with my Hotmail address and it failed.

You can take a look [here](https://www.nucleustechnologies.com/blog/autodiscover-not-working-for-setting-up-office-365-account/), to see if anything there helps. Otherwise, I would recommend looking at other (O365/exchange/outlook.com) avenues for help determining why it is failing for that account.

**Comment by wirstein** [comment]
What type of license should I buy to use this option in office 365? I try to connect business account of my friend and it's worked, authorization was successfull. So now I realized that need to pay for special tariff, what exactly - it is the question.

**Comment by EricDahlvang** [comment]
The issue here is not with the Bot Framework Email channel, but with Auto Discovery not being configured for the account.  Please open a ticket with office 365 to determine what account type is required for auto discovery to be available on exchange email accounts.
