### ISSUE TITLE
Upgrade Text recognizer NuGet to 1.2 

### ISSUE THREAD

**Issue by cahann** [microsoft/botframework-sdk#5378]
## Issue
Discrepancy between LUIS Text recognizer version and Bot Builder SDK

## Proposed change
Upgrade text recognizer NuGet to 1.2 

## Tracking Status
**Dotnet SDK**
- [x] PR
- [x] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by johnataylor** [comment]
We have another issue tracking this #944

**Comment by cleemullins** [comment]
A quick update - we're currently working through a number of bugs in the 1.2 packages that are preventing us from taking them.

**Comment by EricDahlvang** [comment]
Upgrade to 1.2.6 with SuppressExtendedTypes in dotnet sdk has been merged https://github.com/microsoft/botbuilder-dotnet/pull/2448

**Comment by cleemullins** [comment]
Completed in https://github.com/microsoft/botbuilder-dotnet/pull/2448
