### ISSUE TITLE
DCR - Put "Obsolete" attributes on Autosave Middlware

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5381]
Per @yochay we should consider putting obsolete attributes on the Autosave Middlware in both JS and C#.

**Comment by cleemullins** [comment]
Note: @johnataylor has significant thoughts here, and we should get to agreement on this topic before deciding what to do.

**Comment by johnataylor** [comment]
I think we need to keep this. That's the path of least resistance for anyone using the framework.

In today's model the specific problem it solves is that it can run at the end of the middleware which would be useful if you were to manipulate state in middleware and only had a handle on the accessor. Its easy to imagine alternative models, however, this is the current model.
