### ISSUE TITLE
[Direct Line] Unable to get response in GET execution of Directline Api in microsoft bot framework

### ISSUE THREAD

**Issue by Rashree138** [microsoft/botframework-sdk#5382]
Hi All,

I am using DirectLine API to chat conversation today I found some issue with my bot as below:

1. - First two conversation I get the correct response from BOT.
2. - But in third message when I send my message to BOT i am not getting any response and no error as well.

**Example**:
==========
User 1st Input : Hi
Bot Response: Hello User

User 2nd Input : Hi
Bot Response: Hello User

User 3rd Input : Hi
Bot Response: No Response from Bot

3. - When I checked my BOT using Emulator then I get the correct response but not in DirectLine API.

My Query: 
Is there any issue going on with DirectLine?

I am using :
============
https://directline.botframework.com/v3/directline/conversations/{convID}/activities

**Comment by stevkan** [comment]
@Rashree138, can you provide details on your process? What client are you using and what steps are you taking that is leading to this result? Do you have code you can share, as well?

**Comment by stevkan** [comment]
@Rashree138, are you still needing assistance with this issue?

**Comment by stevkan** [comment]
Closing issue due to lack of response. Please reopen with new details posted if the issue reoccurs.
