### ISSUE TITLE
Bot Listening to every message in a teams channel

### ISSUE THREAD

**Issue by DamienDoumer** [microsoft/botframework-sdk#5387]
## Listening to every message sent even without @mention to bot in a teams channel

We are building a support bot which runs on Microsoft Teams Only.
Actually our bot only receives messages which contain a mention to it.
But the ideal scenario will be to listen to every message sent into the specific channel.
I went arround Microsoft Docs, and found out it was [not actually possible](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conv-channel#-mentions) to implement this later scenario
I also looked at [Bot-Builder Microsoft Teams SDK](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams), but this right now as I'm writing this is available only for SDK v3 which should be deprecated by now.
Is there a way to bypass the constraint of not being able to listen to every message in a Teams channel with V4 SDK ? 
Or Could this **Feature** be implemented in V4 ?

**Comment by dmvtech** [comment]
@DamienDoumer Unfortunately, there is no way to do this. As you have found, you must mention the bot every time you want it to respond.

You could put in a feature request/DCR into the Teams extension. You can find the v4 version (not yet release) [here](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet).

**Comment by mikhail-cabilao** [comment]
Any update on this? We are doing the same thing and might be this will be possible right now?

**Comment by dmvtech** [comment]
I don't believed anything has changed, even in the newer implementation of Teams integration in 4.6/4.7.

@clearab @Virtual-Josh Any thoughts? Would this be a DCR/enhancement that we would/could accept?

**Comment by Virtual-Josh** [comment]
This still isn't a supported scenario. I don't know if there's any intention to enable this scenario. @clearab would know better.

**Comment by clearab** [comment]
Currently, there is no plan to enable this for a bot directly. The functionality, when available, will come through the Graph API's and Graph permissions. If you'd like to learn more and/or reach out to the Teams team you can find how to contact them here: https://docs.microsoft.com/en-us/microsoftteams/platform/feedback

**Comment by nedimf** [comment]
Yeah, I second this.
