### ISSUE TITLE
Getting Skype Name in the activity object.

### ISSUE THREAD

**Issue by poojasd** [microsoft/botframework-sdk#5393]
Hi All,

I am trying to connect Bot Framework with Dialogflow. I need to get skype name in response to map with the database. Is there any way to get the skype name instead of obfuscated id which I am getting right now(" 29:1ZAV3agvZBm7Ujvx27Zkej7JGM........")

**Comment by v-kydela** [comment]
Hi @poojasd - I would like to help but I have a few questions.

1. Are you talking about Skype for Business or just Skype?
1. What SDK version are you using (v3 or v4)?
1. What language are you using (C# etc.)?
1. How are you getting that user ID?
1. In what way are you trying to connect the Bot Framework with Dialogflow?

**Comment by poojasd** [comment]
Hi  @v-kydela - Thanks for reaching out.
1. Skype
2. v4
3. Nodejs.
4. I am getting the user ID in the response from skype-dialogflow integration in originalDetectIntentRequest. I also tried using creating a bot by REST Framework and Nodejs SDK. But I am getting same user ID which is of the format (" 29:1ZAV3agvZBm7Ujvx27Zkej7JGM........"), which is consistent for a particular user.
5. I followed the instructions over here:
https://cloud.google.com/dialogflow-enterprise/docs/integrations/skype

**Comment by v-kydela** [comment]
@poojasd - Thank you for the information.

I'm understanding now that you haven't built a bot using the Bot Builder SDK. You've registered a bot in dev.botframework.com but you're setting its endpoint to a Dialogflow bot webhook like https://bots.dialogflow.com/skype/... Is that correct?

The Bot Framework's Skype connector does include the user name in the activities it sends to the endpoint. If Dialogflow discards the name when it interprets the activities, I don't think there's anything we can do about that. You'll have to raise an issue with the Dialogflow team.

If they don't fix it, you have two options for getting a user's name:

1. Have the bot ask for the name explicitly
1. Build the bot with the Bot Builder SDK instead of Dialogflow

**Comment by v-kydela** [comment]
@poojasd - Are you still working on this?

**Comment by poojasd** [comment]
@v-kydela Yes, I am still working on it.

**Comment by poojasd** [comment]
> @poojasd - Thank you for the information.
> 
> I'm understanding now that you haven't built a bot using the Bot Builder SDK. You've registered a bot in dev.botframework.com but you're setting its endpoint to a Dialogflow bot webhook like https://bots.dialogflow.com/skype/... Is that correct?
> 
> The Bot Framework's Skype connector does include the user name in the activities it sends to the endpoint. If Dialogflow discards the name when it interprets the activities, I don't think there's anything we can do about that. You'll have to raise an issue with the Dialogflow team.
> 
> If they don't fix it, you have two options for getting a user's name:
> 
>     1. Have the bot ask for the name explicitly
> 
>     2. Build the bot with the Bot Builder SDK instead of Dialogflow

I did try with Bot Builder SDK. However the response is same. I am getting Display Name, but not Skype Name.

**Comment by v-kydela** [comment]
@poojasd - Do you mean you're getting something like "Kyle Delaney" when you want something like "kyle-delaney"?

**Comment by poojasd** [comment]
@v-kydela  Yes, exactly. Can you help over here?

**Comment by v-kydela** [comment]
@poojasd - I believe the bot will only have access to the information contained in the activity, but I'm emailed the Skype team to verify. Can you explain what your bot would do with the user's Skype Name?

**Comment by poojasd** [comment]
@v-kydela I want to map it with the database and fetch information of information.

**Comment by v-kydela** [comment]
@poojasd - Ah well in that case, why not just use the display name and user ID? (" 29:1ZAV3agvZBm7Ujvx27Zkej7JGM........")

**Comment by poojasd** [comment]
@v-kydela my use case is that the Skype name of the format(kyle-delaney) is stored in the database already. I want to map this name and present custom menu to the bot user. The user ID provided in the skype response is generated after the interaction.

**Comment by v-kydela** [comment]
I received a response from the Skype team:

> There’s a privacy & security reasons why we don’t expose real Skype / Teams id of the user to bot. User id is pairwised before sending it to bot and it’s always the same. Bot should operate with the user id provided in the activity.

It looks like you won't be able to get the Skype name and will have to manage with the user ID in the activity. Do you need help designing a workaround?

**Comment by poojasd** [comment]
@v-kydela - Thanks for the update. I have designed the workaround as of now.

**Comment by v-kydela** [comment]
@poojasd - I'm glad to hear it
