### ISSUE TITLE
Adaptive Cards are Not Being Rendered Correctly in Direct-Line

### ISSUE THREAD

**Issue by Hoosayin** [microsoft/botframework-sdk#5399]
I'm using Direct-Line to host my bot on my Web App. But the Adaptive Cards are not rendering correctly as they supposed to render. The output is fine on the Bot Framework Emulator, but not in the Direct-Line.

Following is the output in Bot Framework Emulator that i was expecting in Direct-Line too.
![image](https://user-images.githubusercontent.com/47661256/58021213-c7f05900-7b23-11e9-866c-68f0300cf1d4.png)

And, here's how Direct-Line rendered the same card on my Web App. Note that the Text isn't bold and there's too much spacing between them.
![image](https://user-images.githubusercontent.com/47661256/58021323-02f28c80-7b24-11e9-8df2-db8cc68c2021.png)

What can be the solution for this? Or should I have to use WebChat instead?

**Comment by stevkan** [comment]
If you're not already using web chat, how are you connecting to your bot in your web app using direct line?

**Comment by Hoosayin** [comment]
> If you're not already using web chat, how are you connecting to your bot in your web app using direct line?

I'm using a plain HTML div, and embedding the bot using Direct-Line Token via JavaScript.
![image](https://user-images.githubusercontent.com/47661256/58042611-980d7980-7b54-11e9-82d0-289551779fb6.png)

**Comment by stevkan** [comment]
I'm not sure I'm following. Are you using the [BotFramework-WebChat](https://github.com/Microsoft/BotFramework-WebChat#bot-framework-web-chat) v3 'botchat' component or is this a completely custom built client? I see you have the Web Chat channel configured. Are you maybe using the embed code that channel makes available?

Just trying to get a complete picture so I know how best to help.

**Comment by cleemullins** [comment]
Need to XFer to the WebChat repo.

**Comment by stevkan** [comment]
@Hoosayin, are you still needing help on this issue?

**Comment by CoHealer** [comment]
Closing per lack of response. If you still require assistance, please comment.
