### ISSUE TITLE
[Question] BotAuthenticator ignoring incorrect specified passwords

### ISSUE THREAD

**Issue by Sfonxs** [microsoft/botframework-sdk#5402]
I am using the botframework sdk v3 to create  a MS Teams bot.

When using the BotAuthenticator (or BotAuthentication) to authenticate an incoming Activity this returns true in the ClaimsIdentity with AuthenticationType Federation.
This is as expected since the correct app id and pass are specified.

When specifying the correct app id but an incorrect app pass, the activities are still successfully identifies with AuthenticationType Federation.

My question is why? I would expect incorrect configured passwords to make the authentication fail, but why does this authentication still succeed?
When specifying an incorrect app ID, the authentication does fail as expected.

Kind regards,
Sven

**Comment by EricDahlvang** [comment]
Please share the code you are using.

If I'm understanding your question correctly, incoming activity authentication is accomplished by [validating the jwt token](https://github.com/microsoft/BotBuilder-V3/blob/master/CSharp/Library/Microsoft.Bot.Connector.Shared/JwtTokenExtractor.cs#L181).  A valid jwt token can only be retrieved with a valid appid and password, or from a secret.  Validation of the token does not require the password.

**Comment by Sfonxs** [comment]
For completeness, this was the code:
```
 public class MessagesController : ApiController
 {
     [HttpPost]
     public async Task<HttpResponseMessage> Post([FromBody] Activity activity)
     {
         string validAppId = "removed";
         string invalidAppPass = "invalid";
         var authenticator = new BotAuthenticator(validAppId, invalidAppPass);
         var request = HttpContext.Current.Items["MS_HttpRequestMessage"] as as HttpRequestMessage;
         var identity = await authenticator.AuthenticateAsync(request, new[] {activity}, CancellationToken.None);

         if (identity.Authenticated)
         {
             // OK
         }
         else
         {
             return new HttpResponseMessage(HttpStatusCode.Forbidden);
         }
     }
 }
```

But I didn't know that only the AppID was enough to validate a valid jwt token. After reading a bit more about JWT token this makes sense, thank you for the help.
