### ISSUE TITLE
DCR: Add State to the Semantic Action definition in Schema

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5403]
We've been asked to add the  'state' to the SemanticAction definition in Microsoft.Bot.Schema (SDK). The spec has this defined. 

This work needs to be done in:

- [x] C# [C# Issue 1944](https://github.com/microsoft/botbuilder-dotnet/issues/1944)
- [x] JS [JS Issue 943](https://github.com/microsoft/botbuilder-js/issues/943)
- [x] Python [Python Issue 189](https://github.com/microsoft/botbuilder-python/issues/189)

**Comment by gabog** [comment]
Hi @cleemullins, I am looking at https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md#semantic-action-type and can't find 'state' mentioned there, am I looking at the wrong place? 
If I got this wrong and state still needs to be added, do you know what type it should be?

**Comment by EricDahlvang** [comment]
@gabog SemanticActionStates is in the latest connector swagger file: https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-channel.json#L2145

Here is a PR to add it to dotnet: https://github.com/microsoft/botbuilder-dotnet/pull/2027

**Comment by gabog** [comment]
Ah, cool, I will transfer the dotnet PR to you so you can close it once your PR goes in.

**Comment by EricDahlvang** [comment]
Closing this ... all three language repos mentioned above are finished and merged.
