### ISSUE TITLE
DCR: Add new options memory shortcut

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-sdk#5407]
We need to support access to the dialog.options, and for adaptive dialogs this could be in 2 locations so it would be very useful to have a shortcut for it.

^xxxx => dialog.this.step.options.xxx || dialog.this.options.xxx

## Component Impact 
* dotnet and js libraries

## Customer Impact 
none

## Tracking Status
**Dotnet SDK** https://github.com/microsoft/botbuilder-dotnet/issues/1974
- [ ] PR 
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
I don't think we need this anymore, closing.
