### ISSUE TITLE
Adaptive Cards - Input.Date user value not returned

### ISSUE THREAD

**Issue by Jcragons** [microsoft/botframework-sdk#5411]
We are using the API via REST calls, mainly on Teams. All the adaptative card system is working fine, but as soon as we're using the input type date 'Input.Date' the value of the field (even if the user click inside) is never returned.

Here a trace of the construction of the card to see the difference between the two field :

```php
'type' => 'AdaptiveCard'
'$schema' => 'http://adaptivecards.io/schemas/adaptive-card.json'
'version' => '1.0'
'body' => array
(
	0 => array
	(
		'type' => 'Input.Date'
		'title' => ''
		'value' => '2019-06-03T22:00:00+0000'
		'id' => 'deadlineinput'
	)
	1 => array
	(
		'type' => 'Input.Text'
		'title' => ''
		'value' => '2019-06-03T22:00:00+0000'
		'id' => 'deadlineinputtxt'
	)
)
```

It's showing well on the client

![field](https://user-images.githubusercontent.com/1888995/58892362-5c46e800-86ee-11e9-8f95-cb3d6f4f5e38.png)       

And the trace in the result :             

```php
'action' => 'delaychoiceaction'
'actionData' => array
(
	'id' => 'XXXXXXXXX'
)
'checkbox-xxxxxx' => 'true'
'deadlineinputtxt' => '06/03/2019 22:00:00'
```

is there something wrong on the Input.Date on teams ?

**Comment by v-kydela** [comment]
@Jcragons - Let me see if I understand correctly. You have a Teams bot written in PHP using the Bot Framework REST API. Your bot sends the user an Adaptive Card with several input fields and submit actions, but your date input's value is not included in the data sent to the bot from a submit action. Is that correct?

**Comment by Jcragons** [comment]
Yes exactly that @v-kydela, all is working fine, but no input.date field send back in value array

**Comment by v-kydela** [comment]
@Jcragons - I can't reproduce your issue. I recreated your two input fields and both of their values get passed to the bot when a submit action is clicked.

![image](https://user-images.githubusercontent.com/41968495/58919491-28b29080-86e3-11e9-8498-e3869235be30.png)

Since the Adaptive Card you provided doesn't have any submit actions, I presume there's more to your card than you're showing here. In any case, it might help us synchronize our efforts if you construct your card with JSON-formatted text instead of PHP. Try the following JSON and see if you still get a problem:

```json
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "Input.Date",
      "value": "2019-06-03T22:00:00+0000",
      "id": "deadlineinput"
    },
    {
      "type": "Input.Text",
      "value": "2019-06-03T22:00:00+0000",
      "id": "deadlineinputtxt"
    }
  ],
  "actions": [
    {
      "type": "Action.Submit",
      "title": "Submit"
    }
  ]
}
```

**Comment by Jcragons** [comment]
Ok, i've just sent that card, It render the both fields, but if i click on submit, even if i change the field or not, the result of the date field is never returned. To be fully clear, here the card i've send into attachement data of the message to rest call :

```
  { 
	contentType: "application/vnd.microsoft.card.adaptive",
	content: {
		"$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
		"type": "AdaptiveCard",
		"version": "1.0",
		"body": [
		  {
			"type": "Input.Date",
			"value": "2019-06-03T22:00:00+0000",
			"id": "deadlineinput"
		  },
		  {
			"type": "Input.Text",
			"value": "2019-06-03T22:00:00+0000",
			"id": "deadlineinputtxt"
		  }
		],
		"actions": [
		  {
			"type": "Action.Submit",
			"title": "Submit"
		  }
		]
	}
  }

```
Here the full trace (sorry in php format) of what i've sent to the rest call :

```
(
    'type' => 'message'
    'from' => array
    (
        'id' => 'xxxxxxxx'
        'name' => 'Beesy-Local'
    )
    'attachments' => array
    (
        0 => array
        (
            'contentType' => 'application/vnd.microsoft.card.adaptive'
            'content' => array
            (
                '$schema' => 'http://adaptivecards.io/schemas/adaptive-card.json'
                'type' => 'AdaptiveCard'
                'version' => '1.0'
                'body' => array
                (
                    0 => array
                    (
                        'type' => 'Input.Date'
                        'value' => '2019-06-03T22:00:00+0000'
                        'id' => 'deadlineinput'
                    )
                    1 => array
                    (
                        'type' => 'Input.Text'
                        'value' => '2019-06-03T22:00:00+0000'
                        'id' => 'deadlineinputtxt'
                    )
                )
                'actions' => array
                (
                    0 => array
                    (
                        'type' => 'Action.Submit'
                        'title' => 'Submit'
                    )
                )
            )
        )
    )
    'conversation' => array
    (
        'conversationType' => 'personal'
        'tenantId' => 'xxxxxxxx'
        'id' => 'xxxxxxxx'
    )
    'recipient' => array
    (
        'id' => 'xxxxxxxx'
        'name' => 'Jean-Charles Ragons'
        'aadObjectId' => 'xxxxxxxx'
    )
    'replyToId' => 'xxxxxxxx'
    'locale' => 'fr-FR'
    'text' => 'A plus tard !'
    'textFormat' => 'xml'
)

```
In Teams, it show well the two fields : 

![screenok](https://user-images.githubusercontent.com/1888995/58947735-d035ce80-8788-11e9-8ac1-450ac712843f.png)

And here the (php) trace of the response after the click : 

```
(
    'type' => 'message'
    'timestamp' => '2019-06-05T09:49:48.099Z'
    'localTimestamp' => '2019-06-05T11:49:48.099+02:00'
    'id' => 'xxxxxxxx'
    'channelId' => 'msteams'
    'serviceUrl' => 'https://smba.trafficmanager.net/emea/'
    'from' => array
    (
        'id' => 'xxxxxxxx'
        'name' => 'Jean-Charles Ragons'
        'aadObjectId' => 'xxxxxxxx'
    )
    'conversation' => array
    (
        'conversationType' => 'personal'
        'tenantId' => 'xxxxxxxx'
        'id' => 'xxxxxxxx'
    )
    'recipient' => array
    (
        'id' => 'xxxxxxxx'
        'name' => 'Beesy-Local'
    )
    'entities' => array
    (
        0 => array
        (
            'locale' => 'fr-FR'
            'country' => 'FR'
            'platform' => 'Mac'
            'type' => 'clientInfo'
        )
    )
    'channelData' => array
    (
        'tenant' => array
        (
            'id' => 'xxxxxxxx'
        )
        'source' => array
        (
            'name' => 'message'
        )
    )
    'replyToId' => 'xxxxxxxx'
    'value' => array
    (
        'deadlineinputtxt' => '06/03/2019 22:00:00'
    )
    'locale' => 'fr-FR'
)

```
Could it be an issue due to the locale here (french one) ?

**Comment by v-kydela** [comment]
@Jcragons 

I suppose the locale could make a difference. We need to experiment further to find out where the problem is.

1. Try different locales to see if the problem persists
2. Try different channels to see if the problem persists
3. Try running a C# or Node.js bot to see if the problem persists
4. Try to identify the point at which the data is removed
a. Is the data present when the submit action sends a message from the channel to your bot? You can view the activities being sent in your App Insights logs. If you give me your Microsoft app ID then I can look up the messages in our database.
b. Is the data present when your bot receives the message? Your bot should receive an activity that goes through an adapter. You can try setting traces at different points and try to observe the activity when your app's endpoint first receives it.
c. Are your traces displaying the data accurately? You could try alternative logging methods, or try logging dummy data with the values you might expect the activity to contain and see if anything gets removed.

Also, what version of Teams are you using?

**Comment by v-kydela** [comment]
@Jcragons - Are you still working on this?

**Comment by Jcragons** [comment]
@v-kydela Sorry, yes i'm still on the integration, but due to that i've removed the use of Input.Date for now, but let me try quickly with another locale than french. On teams we are on webapp, electron osx client (1.2.00.8866), and ios 1.0.76, but i've already understand that for activecard support there is disparities between versions (like non support of selectAction on ios).

**Comment by Jcragons** [comment]
Ok, look like it's definitely a problem of locale, if i switch teams webapp or client to english locale, field is returned, here the trace 

in french locale

```
{
   "type":"message",
   "timestamp":"2019-06-12T08:25:53.06Z",
   "localTimestamp":"2019-06-12T10:25:53.06+02:00",
   "id":"xxxxxxxxx",
   "channelId":"msteams",
   "serviceUrl":"https://smba.trafficmanager.net/emea/",
   "from":{
      "id":"xxxxxxxxx",
      "name":"Jean-Charles Ragons",
      "aadObjectId":"xxxxxxxxx"
   },
   "conversation":{
      "conversationType":"personal",
      "tenantId":"5c63f6b3-e2fe-4485-8344-22ab78edcc06",
      "id":"xxxxxxxxx"
   },
   "recipient":{
      "id":"28:defc9901-2829-4149-bf2a-79938397e1cc",
      "name":"Beesy-Local"
   },
   "entities":[
      {
         "locale":"fr-FR",
         "country":"FR",
         "platform":"Mac",
         "type":"clientInfo"
      }
   ],
   "channelData":{
      "tenant":{
         "id":"5c63f6b3-e2fe-4485-8344-22ab78edcc06"
      },
      "source":{
         "name":"message"
      }
   },
   "replyToId":"xxxxxxxxx",
   "value":{
      "deadlineinputtxt":"06/03/2019 22:00:00"
   },
   "locale":"fr-FR"
}
```

in english locale

```
{
   "type":"message",
   "timestamp":"2019-06-12T08:27:32.532Z",
   "localTimestamp":"2019-06-12T10:27:32.532+02:00",
   "id":"xxxxxxxxx",
   "channelId":"msteams",
   "serviceUrl":"https://smba.trafficmanager.net/emea/",
   "from":{
      "id":"xxxxxxxxx",
      "name":"Jean-Charles Ragons",
      "aadObjectId":"xxxxxxxxx"
   },
   "conversation":{
      "conversationType":"personal",
      "tenantId":"5c63f6b3-e2fe-4485-8344-22ab78edcc06",
      "id":"xxxxxxxxx"
   },
   "recipient":{
      "id":"28:defc9901-2829-4149-bf2a-79938397e1cc",
      "name":"Beesy-Local"
   },
   "entities":[
      {
         "locale":"en-US",
         "country":"US",
         "platform":"Web",
         "type":"clientInfo"
      }
   ],
   "channelData":{
      "tenant":{
         "id":"5c63f6b3-e2fe-4485-8344-22ab78edcc06"
      },
      "source":{
         "name":"message"
      }
   },
   "replyToId":"xxxxxxxxx",
   "value":{
      "deadlineinput":"2019-06-03",
      "deadlineinputtxt":"06/03/2019 22:00:00"
   },
   "locale":"en-US"
}
```

**Comment by Jcragons** [comment]
i've tried with various date format in value for Input.Date, never succeed to return the value in french locale.

**Comment by v-kydela** [comment]
@Jcragons - Thank you for testing and figuring that out.

I've been able to reproduce this extensively. It seems like you've discovered a bug. Input.Date fields will use the configured locale only for displaying a card, and not for interpreting the card. Therefore it will show you the dates in French and then try to read those French dates using an English language parser. This will usually fail, and so the date input won't be included in the submit action's payload.

I will try to escalate this issue as much as I can, but until it's fixed you'll have to use a workaround. Three number inputs could work, but presumably you'll just want to use a text input.
