### ISSUE TITLE
SharePoint Online Connect to Azure Bot Framework with Visual Studio 2019

### ISSUE THREAD

**Issue by Ashwakum** [microsoft/botframework-sdk#5412]
Hi,

I have an issue with SharePoint Online authentication. When I try to get the item from my SharePoint online tenant. Then emulator is giving an error that is "**This the error The remote server returned an error: (400) Bad Request.**". And I don't any kind of desire output. Please help me

**Comment by dmvtech** [comment]
Hi @Ashwakum 

Can you give me the steps you are using to set this up? Is emulator the only 'channel' that is failing for you?

**Comment by dmvtech** [comment]
Closing due to no action. Please reopen if the issue persists and you still need assistance.
