### ISSUE TITLE
Cortana says " Bot service failed with status code: NotFound "

### ISSUE THREAD

**Issue by Pravandan** [microsoft/botframework-sdk#5414]
I am using node js v4 sdk of bot framework, my bot was.working fine from my local dev system, but suddenly Cortana starts showing this error - bot service failed with status code not found, this started happening after I pushed the changes of my source code to azure ( using azure cli for updating the bot). Please help

**Comment by mdrichardson** [comment]
Sounds like the deployment/update failed. 

Frequently, users zip from the parent folder of their code directory, so all of the files get deployed while inside of a folder. Meaning, if you have the file structure:

```
Bot Code
---bots/
---dialogs/
---.env
---index.js
---package.json
```

...don't zip `Bot Code/`, but zip up everything inside `Bot Code/`. This may not be your issue, but it's a frequent one.

**Can you go to `https://<yourBot>.scm.azurewebsites.net/dev/wwwroot/` and send a screenshot of the files? It should look exactly like your local code directory.**

**Comment by Pravandan** [comment]
I did the same as mentioned by you zipping everything inside the bot code, still the error is same
<img width="1440" alt="Screenshot 2019-06-07 at 7 06 55 AM" src="https://user-images.githubusercontent.com/16229748/59076284-ec557f00-88f2-11e9-84ec-4d30e9090436.png">

**Comment by mdrichardson** [comment]
Note: I'm working with @Pravandan via Teams. I'll post the solution/results/troubleshooting-steps here once we've figured things out.

**Comment by mdrichardson** [comment]
Closing as this was solved by a Cortana bug fix. Thanks @micromuncher
