### ISSUE TITLE
DCR: As a developer I would like to have a test client that would allow me to write unit tests for dialogs in isolation

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#5416]
## Issue
TestFlow doesn't provide an easy way of write and debug tests for dialogs. Debugging step by step is cumbersome and the stack traces for test failures are hard to track.

## Proposed change
Create a DialogTestClient that would allow developers to write unit tests for dialogs and use standard unit testing tools and frameworks.

The new testing client should be hosted in a separate package "Microsoft.Bot.Builder.Testing" that will host this class and the test framework for bots.

This package will be extended over time to include other testing classes and helpers. 

## Component Impact 
- Create new Microsoft.Bot.Builder.Testing to host the classes
- Create new Microsoft.Bot.Builder.Testing.Tests to unit test the new classes

## Implementation notes
- 3rd party frameworks to adopt for each platform are:
  - DotNet: [XUnit](https://xunit.net/) for unit tests, [Moq](https://github.com/moq/moq) for mocks, [FluentAssertions](https://fluentassertions.com/) for assertions (to be confirmed)
  - JS: TBD
  - Python: TBD
- Provide parity for SendActivity operations for test flow
- Use TestAdapter if possible but also provide the ability to pass a custom adapter and a custom callback if needed
- Provide the ability to pass a ChannelId to test different rendering conditions (right now TestAdapter passes ChannelId == "tests" which doesn't really allow the dev to test response rendering for different channels)

## Customer Impact 
NA: new feature

## Tracking Status
**Dotnet SDK** (Tracked by [2028](https://github.com/microsoft/botbuilder-dotnet/issues/2028))
- [x] PR
- [x] Merged

**Javascript SDK** (Tracked by [969](https://github.com/microsoft/botbuilder-js/issues/969))
- [x] PR
- [x] Merged

**Python SDK** (Tracked by [198](https://github.com/microsoft/botbuilder-python/issues/198))
- [x] PR
- [x] Merged

[dcr]

**Comment by sibbl** [comment]
I'm not 100% sure if this is the right spot to ask, but is the `DialogTestClient` here to stay and how will it improve? 

I personally prefer the syntax of `TestFlow` over the API of `DialogTestClient` for its compactness and readability. The current samples even show some problems, i.e. that you need complex and moreover untested code in your test package to have a usable syntax ([client sample with own data structure](https://github.com/microsoft/BotBuilder-Samples/blob/e9787529ba70f39d3b5001d2d55ff24f283cc520/generators/vsix-vs-win/BotBuilderVSIX-V4/UncompressedProjectTemplates/CoreBotWithTests/CoreBot.tests/Dialogs/TestData/BookingDialogTestsDataGenerator.cs) vs [testflow sample without any custom code](https://github.com/microsoft/botbuilder-dotnet/blob/a490f79d003aa1be296f54c95111fc7ff578d0bc/tests/Microsoft.Bot.Builder.Tests/MessageFactoryTests.cs#L462-L465)).

I especially like the ability to send multiple activities at once (i.e. a parsed transcript file) to `TestFlow` and let it run them. There's also no need to manually deal with `GetNextReply` (which I need to do when using the `DialogTestClient` - whereas `TestFlow` provides some in-built logic and asserts already).

Is it on the roadmap to make the client more usable for devs? Is feedback welcome here or should other issues be opened?
