### ISSUE TITLE
DCR: Update BotFrameworkAdapter to read environment variables/configuration for National Clouds

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-sdk#5417]
## Issue
Users need to perform manual changes to get template and samples code working in Azure US Gov (a National Cloud). These changes are minimal but obtrusive as we don't describe when a user would normally perform these changes (which is reliant on whether the user is using Public Azure or a [National Cloud](https://docs.microsoft.com/en-us/graph/deployments)).

This also adds friction in that the samples in [botbuilder-samples](https://github.com/microsoft/botbuilder-samples) aren't as easily deployable as deploying to Public Azure (no code changes required).

## Proposed change
Clean up BotFrameworkAdapter by having it check/default for BotOpenIdMetadata and ChannelService environment variables in the constructor/initializer in JS and Python.

These variables are configured in our deployment settings on Azure.

## Component Impact 
- [ ] **BotFrameworkAdapter** (JS, Python)
- [ ] **AuthenticationConstants** (JS, Python)
  - These are namespaced as Constants in `botframework-connector` and not exposed to the developer. In C# these constants are public.

## Tracking Status
**Dotnet SDK**
- [x] PR: .[netcore](https://github.com/microsoft/botbuilder-dotnet/pull/1926), needs update/fix
- [x] Merged

**Javascript SDK**
- [x] PR: microsoft/botbuilder-js#975
- [x] Merged

**Python SDK** https://github.com/microsoft/botbuilder-python/issues/232
- [x] PR
- [x] Merged

**Samples**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by cleemullins** [comment]
Pushing to 4.6 per the Python Issue. C# and JS are done.
