### ISSUE TITLE
DCR: as a bot framework developer I would like to refactor testbot so it is easier to write unit tests for it

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#5418]
## Issue

TestBot in the BotBuilder project is not very easy to test, we need to refactor it so it is easier to write unit tests for it and also try out our Testing Framework before applying it to samples.

## Proposed change
Refactor testbot as follows:
- Move dependent objects like LUIS and child dialogs to the dialog constructors to make it easier to inject mock object.
- Fine tune the conversation flows so they can be used to test different scenarios
  - Calling a child dialog
  - Test cancellation of flows
  - Pass objects from parent to child
  - Hook up a mock LUIS into MainDialog
- Introduce a FlightReservationService that can be mocked during the unit tests
- Refactor MainDialog so it can use LUIS or work without it

Here is a class diagram for how things are today:
![image](https://user-images.githubusercontent.com/12264946/59458481-84b69c80-8de8-11e9-97e5-ec1f24bec8bc.png)

And here is a diagram with the proposed changes:
![image](https://user-images.githubusercontent.com/12264946/59458293-2093d880-8de8-11e9-9191-935b224d4fed.png)

## Customer Impact 
NA: new feature

## Tracking Status
**Dotnet SDK** (Tacked in [2031](https://github.com/microsoft/botbuilder-dotnet/issues/2031))
- [x] PR
- [x] Merged

**Javascript SDK** (Tracked in [971](https://github.com/microsoft/botbuilder-js/issues/971))
- [x] PR
- [x] Merged

**Python SDK** (Tracked in [199](https://github.com/microsoft/botbuilder-python/issues/199))
- [ ] PR
- [ ] Merged

**Comment by cleemullins** [comment]
As this is an internal test bot, and not part of the "Packaged" product, I think this is fine.

**Comment by gabog** [comment]
Right @cleemullins, this is just for our internal use, some of these concepts will make it into CoreBot after the team reviews it. 
Most the work is already done in a branch I have, I am just formalizing the DCR so we can port the changes to the other platforms if needed and will link this item in the PRs.
