### ISSUE TITLE
Cortana does not waits for Submit Action of Adaptive Card.

### ISSUE THREAD

**Issue by Pravandan** [microsoft/botframework-sdk#5424]
I am trying to integrate Adaptive Cards in my bot, it works fine in Web Chat but cortana does not waits for the submit action of Adaptive Card even after I have explicitly placed a text prompt.

```javascript
await stepContext.context.sendActivity({speak : "Should I mark you as present in group ?",attachments : [cardToSendForAttendanceConfirmation]});
await stepContext.context.sendActivity("","Should I mark you as present in group ?");`
```
Rather it reloads and reruns the entire dialogue flow till this point.

Moreover cortana does not even executes the 2nd line of the above code, I think it just omits it ( Don't know the reason ). I need a solution for this also.

My Adaptive card is ->
```javascript
       {
            "type": "AdaptiveCard",
            "body": [
                {
                    "type": "TextBlock",
                    "spacing": "ExtraLarge",
                    "size": "Large",
                    "text": "Mark Attendance"
                },
                {
                    "type": "TextBlock",
                    "text": "Check-in Time : " + currTime
                },
                {
                    "type": "TextBlock",
                    "text": "Your location for attendance is - "
                },
                {
                    "type": "Image",
                    "url" : mapsUrl
                },
                {
                    "type": "TextBlock",
                    "spacing": "Large",
                    "text": "You have been marked as present."
                },
            ],
            "actions" : [
                {
                    "type": "Action.Submit",
                    "title": "Present",
                    "data" : "present"
                },
                {
                    "type": "Action.Submit",
                    "title": "Absent",
                    "data" : "absent"
                }
            ],
            
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.0"
        }
```
Please help.

Node JS Bot Builder Framework (v4)

**Comment by stevkan** [comment]
Please look over your 'attachment'. The organization appears incorrect according to the Bot Framework [schema](https://docs.microsoft.com/en-us/javascript/api/botbuilder-core/messagefactory?view=botbuilder-ts-latest#attachment-attachment--string--string--inputhints---string-).

The order of the attributes passed in for an attachment should be: _attachment_, _text_, _speak_, and _inputHint_. The only required attribute for an attachment is _attachment_ which must come first.

I'm also unsure why you are passing two sendActivity methods. Considering Cortana doesn't display a running dialog, the experience for the user will be a bit disjointed with first receiving an adaptive card asking them to mark if they will be present or not. Then, a message replacing it asking if they should be marked present.

Admittedly, I don't know if there are reasons for the design you present above, but combining the two into a single sendActivity works fine for Cortana.

Within the 'adaptive card' step, be sure to include `return { status: DialogTurnStatus.waiting };` at the end. This tells the bot to wait for user input before moving on.

In my testing in Test in Web Chat and in Cortana the bot stopped and waited for input on the card, then continued to the next step after I selected either 'present' or 'absent'.

```js
  async firstStep(stepContext) {
    const adaptiveCard = CardFactory.adaptiveCard(AdaptiveCard);

    await stepContext.context.sendActivity(
      {
        attachments: [adaptiveCard],
        text: 'Should I mark you as present in group?',
        speak: 'Should I mark you as present in group?'
      }
    );
    return { status: DialogTurnStatus.waiting };
  }

  async nextStep(stepContext) {
    await stepContext.context.sendActivity({
      text: 'Made it to the next step!'
    });
    return await stepContext.next();
  }
```

Hope of help!

**Comment by Pravandan** [comment]
Hi, it seems right but there is still a piece to figure out - DialogTurnStatus, as I am still not able to think that what it refers to since there is only stepContext in the entire picture.

I have sent you the code on teams.

**Comment by stevkan** [comment]
Because the adaptive card is sent via sendActivity() we must tell the step to stop and wait for user input. If we don't specify the DialogTurnStatus as 'waiting', then it will roll right on into the next step. The user, consequently, would not have an opportunity to respond.

I'm closing the issue as resolved. Please re-open if you continue to have a problem on this issue.
