### ISSUE TITLE
Verify Gov Auth Endpoints in SDKs, Emulator and relevant CLI tools.

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-sdk#5426]
## Issue
botframework.us is supposed to be _botframework.azure.us_

## Proposed change
Verify the correct Azure Gov endpoints across the Bot Framework tools and update endpoints where necessary.

@hristp, @Jeffders FYI

## Tracking Status
**Dotnet SDK**
- [x] PR https://github.com/microsoft/botbuilder-dotnet/pull/2227
- [x] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Tools**
- [x] PR
- [x] Merged

[dcr]

**Comment by cleemullins** [comment]
Please do a quick sync with @hristp to confirm this. @stevengum believes this should be 5/10 minutes to verify.

**Comment by hristp** [comment]
For legacy reasons, audiences, scopes and issuers were set to botframework.us on the service side (and it's very hard to change them now). So only **endpoints** need to be changed to botframework.azure.us.

**Comment by jwiley84** [comment]
After checking over the remaining repos (js, python and emulator), and a discussion with both @hristp and @stevengum, we're good to go. All the spots in the repos have been changed over to botframework.azure.us where they need to be.

There's no need for PRs, as the changes have been already made.
