### ISSUE TITLE
With latest Bot V4 and Asp.Net Core 2.2 getting bot auth error

### ISSUE THREAD

**Issue by AAATechGuy** [microsoft/botframework-sdk#5427]
## Issue
This is w.r.t. issue mentioned at https://github.com/MicrosoftDocs/bot-docs/issues/1159. When we upgrade "Microsoft.IdentityModel.Clients.ActiveDirectory" from 4.5 to 5.1, BotWebApp throws following error.

```
Method not found: 'Void Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(System.String, Boolean, Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache, System.Net.Http.HttpClient)'.

at Microsoft.Bot.Connector.Authentication.AdalAuthenticator..ctor(ClientCredential clientCredential, OAuthConfiguration configurationOAuth, HttpClient customHttpClient)
```

## Proposed change
Add an upper bound <5.0 to "Microsoft.IdentityModel.Clients.ActiveDirectory" if its not supported.

## Component Impact 
Runtime

## Customer Impact 
Breaking change is introduced which fails run time, after upgrade.

**Comment by sgellock** [comment]
@carlosscastro can you verify please?  thanks

**Comment by biste5** [comment]
@sgellock For me, with the latest release of Bot v4, this issue is gone, as it references ADAL 5.0.1 too

See: https://github.com/microsoft/botbuilder-dotnet/commit/3adc26cc2a7036f0c6e1bb2d7b5b197aad9ba7ca#diff-d243f9347aa630fd75b2dd3abef488cb

**Comment by cleemullins** [comment]
Resolving this as fixed, with the migration to ADAL.
