### ISSUE TITLE
Deploy bot with an existing appid / password

### ISSUE THREAD

**Issue by KevinBrooke** [microsoft/botframework-sdk#5429]
You can currently only deploy a bot by creating a Microsoft App ID and password. 
RBAC in the enterprise does not allow users who create bots also have access to AzureAD.
This means we cannot use any bot services.

Can you please add the ability to supply existing details for appid and password?

**Comment by jon-buckley** [comment]
+1

**Comment by mdrichardson** [comment]
You can create a "Web App Bot" with an existing appId/appPass via the [`az bot create`](https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#az-bot-create) command.

Example:

```bash
az bot create --kind webapp --resource-group "<existingRG>" --name "<anything>" --appid "<existingAppId>" --password "<existingPass>" --lang <Javascript|Csharp>
```

That being said, your issue sort of has two questions in it. Does this address it adequately, or are you also asking for different Azure permissions?

**Comment by EricDahlvang** [comment]
You can also provide a pre-existing appid and password while creating the bot in the portal:

![image](https://user-images.githubusercontent.com/11055362/59802783-90014080-929e-11e9-86e8-e8587428ccf3.png)

**Comment by KevinBrooke** [comment]
OK, this looks like more of a documentation / GUI issue. 
As you can see in the screenshot, everything is stating "create new", not "supply existing". 
I did a quick test using an existing AppID and it worked fine. 

The az cli documentation also does not state this clearly.
https://docs.microsoft.com/en-us/cli/azure/bot?view=azure-cli-latest#az-bot-create 

Thank you for your time.

**Comment by mdrichardson** [comment]
Agreed. I've created [an issue in the docs repo](https://github.com/MicrosoftDocs/bot-docs/issues/1223) to have a section for this. Glad you got it working!
