### ISSUE TITLE
Bing Spell Check language specific properties in LuisPredictionOptions

### ISSUE THREAD

**Issue by artemvalmus** [microsoft/botframework-sdk#5431]
## Issue
We have a bot speaking multiple languages and we need to enable Bing Spell Check. `LuisPredictionOptions` class has two properties: `SpellCheck `which says if the spell checking functionality is enabled and `BingSpellCheckSubscriptionKey` which connects the bot with the Azure Cognitive Services resource. 

But how do I specify a country code if I have multiple LUIS services (one for each language)?

## Proposed change
I would propose adding `SpellCheckCountryCode` and `SpellCheckMarket `properties to `LuisPredictionOptions`.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by chrimc62** [comment]
Today, the LUIS REST API does not expose anyway to change these settings even if added to the SDK.  This is something we can work on with the LUIS team.  We do have some spelling changes coming that should improve spelling quality.  Do you have a specific use cases that might have been solved by this functionality?

**Comment by sgellock** [comment]
@artemvalmus I'm going to close this issue as resolved.  Ping me in the next day or so before I do if you feel you want to keep it open to continue the dialog.
