### ISSUE TITLE
[DCR] Allow for Slack Block Kit API

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botframework-sdk#5434]
## Issue
Per: https://github.com/microsoft/botbuilder-js/issues/1014

Note: Based on testing, the issue isn't that the user is using a ChoicePrompt. It's that we don't map the API.

Slack has a new [Block Kit API](https://api.slack.com/block-kit). It accepts [formats](https://api.slack.com/reference/messaging/block-elements) like:

```js
{
  "type": string,
  "image_url": string,
  "alt_text": string
}
```

Currently, in [Slack we allow channel-specific](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-channeldata?view=azure-bot-service-4.0#create-a-full-fidelity-slack-message):

**Attachments**
```js
"channelData": {
   "text": "Now back in stock! :tada:",
   "attachments": [
        [...]
   ]
```

**Actions**
```js
"channelData": {
    "payload": {
        "actions": [
            [...]
        ],
```

## Proposed change

Allow for:

```js
"channelData": {
   "text": "Now back in stock! :tada:",
   "blocks": [
        [...]
   ]
```

## Component Impact 

Several on the Intercom Repo (not sure exactly what). I don't believe any updates will be necessary to public SDK as all the changes are in `channelData`. In my own testing, `blocks` goes through, but Slack doesn't know what to do with it, so I think it just needs to be mapped properly.

## Customer Impact 

Will allow Slack Customers to use new Block Kit API

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by peterswimm** [comment]
+1 on getting this resolved, this is a huge blocker for us as an organization.

**Comment by cleemullins** [comment]
This conversation has been started with @benbrown and others.

**Comment by mdrichardson** [comment]
Note: If your bot is in Node, you can use the [BotKit Slack Adapter](https://github.com/howdyai/botkit/tree/master/packages/botbuilder-adapter-slack), since [it supports the Block Kit API](https://github.com/microsoft/botframework-sdk/issues/5467).

**Comment by mdrichardson** [comment]
Disregard that issue reference ("[DCR/Bug] Cosmos PartitionKeys are semi-broken"). Accidental and no way to delete

**Comment by jpieres** [comment]
hi Ben! If this is something that is going to be implemented I would like to know if you can give us an idea of the timeframe? Thanks!

**Comment by martinlarosa** [comment]
> Note: If your bot is in Node, you can use the [BotKit Slack Adapter](https://github.com/howdyai/botkit/tree/master/packages/botbuilder-adapter-slack), since [it supports the Block Kit API](https://github.com/howdyai/botkit/tree/master/packages/botbuilder-adapter-slack#use-attachments-blocks-and-other-rich-message-features).

What about c# bots?

**Comment by cleemullins** [comment]
The support for C# / Slack Adapter is largely done and going through the [PR / Feedback process](https://github.com/microsoft/botbuilder-dotnet/pull/2051).

Current plan is to ship it as a "-preview" assembly in the 4.6 time frame, although it depends on the state of the overall PR.

**Comment by jmnsf** [comment]
@cleemullins are there plans to do this at the BotFramework level, i.e. using `channelData` as with most other functionality (and also as described in the issue)? We can already use the Slack API directly for this, but one would thing avoiding the platform goes against the point of having one in the first place.

There's also the REST API which has no support for this either.

**Comment by cleemullins** [comment]
@benbrown, of BotKit Fame, is our primary driver for Slack related features. Ben?

**Comment by benbrown** [comment]
@jmnsf Do you mean using it via the Azure Bot channel service?  There are no plans to add these features to the service.

However, as above, you can continue to use Bot Framework SDK by swapping out the built-in adapter for either the Javascript `botbuilder-adapter-slack` package, or the upcoming C# version.

**Comment by jmnsf** [comment]
@benbrown not sure honestly, I'll admit I'm somewhat overwhelmed with all the `X Bot Y` things that exist at this point. Specifically, what I mean is being able to call the [activities](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#send-to-conversation) endpoint with some Block Kit payload and having it delivered correctly to Slack.

**Comment by benbrown** [comment]
@jmnsf Based on my understanding of the roadmap right now, the activities endpoint will *not* be updated with support for Block Kit any time soon.

You may want to consider moving to the adapter linked above - it will give you access to all of the newer Slack features.

**Comment by gabog** [comment]
Hi @garypretty, is this addressed by the new adapter? Can we close it?

**Comment by benbrown** [comment]
You can use the adapter to send Block kit attachments, yes.

This is not a direct fix of the original issue, but does provide a workaround.

**Comment by gabog** [comment]
Thanks ben, closing it then.

**Comment by garypretty** [comment]
This is supported in the C# adapter (preview right now, but should be GA in 4.10) and should also work in the Python adapter too, as well as JS via Botkit.

I think this issue is probably related to the Slack ABS channel which won't work without changes, but I think it's probably enough for us to have the ability to fall back to the adapter so I think we can potentially close this. 

Agree?

**Comment by garypretty** [comment]
Ah, you already closed. We are aligned 👍
