### ISSUE TITLE
Create JS telemetry sample & corresponding doc content knowledge

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-sdk#5438]
To be used by doc writer to convert to a doc topic alongside dotnet

**Comment by kaushalgautam** [comment]
Any progress on this @scheyal / @munozemilio? Been waiting for this for a long time.

**Comment by cleemullins** [comment]
@scheyal - Can you please add significant detail in the form of requirements / scenarios to this issue? 

As it sits, it's hard to figure out how to defined success.

**Comment by gabog** [comment]
Closing it for now
