### ISSUE TITLE
Value cannot be null Parameter name: clientId is getting when trying to get user information in chatbot

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/botframework-sdk#5441]
Hello Team,
I am using MS Bot framework V4 and enabled the Teams channel in bot. For one case, I need to get user related information such as User ID, email ID etc (as you know in the context we will get only the user name). For getting user information i am using GetConversationMembersAsync method from Teams Connector. I followed the same method mentioned in MS blog for getting user details. But I am getting "Value cannot be null. Parameter Name : clientId" exception while running that method.
I have MSAppId and MSAppPassword maintained in appsettings.json file. Please help me to fix the issue.
PFB the code snippet used and the screenshot of the issue.
` 
ConnectorClient connector = new ConnectorClient(new Uri(dialogContext.Context.Activity.ServiceUrl));
var user_detail = await connector.Conversations.GetConversationMembersAsync(dialogContext.Context.Activity.Conversation.Id);
` 

![image](https://user-images.githubusercontent.com/17233137/60337688-60021d80-99c1-11e9-9965-7a87a0027391.png)

**Comment by Vigneshramkumar** [comment]
Hello Team,
The above exception got solved when i passed MS App ID and password with the connector client. Currently I am getting below error.

Method not found: 'Void Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(System.String, Boolean, Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache, System.Net.Http.HttpClient)'.

My intention is to get the user details like User ID, email, phone no etc for the person who is chatting to bot. As you know we only get User name in the context.
For getting required user details, whether i need to implement the OAuth functionality token generation in my bot or else we can get the details from above GetConversationMembersAsync method itself?

![image](https://user-images.githubusercontent.com/17233137/60362020-729a4800-99fd-11e9-830f-fc6598ffd3f8.png)

**Comment by jwiley84** [comment]
If you have the AppID and Password in your appsettings.json, check that they're being read properly. The only time "ClientID cannot be null" comes up is when they're not. See [here](https://stackoverflow.com/questions/55407725/argumentnullexception-in-createdirectconversation-createdirectconversationasync/56261762#56261762) and [here](https://stackoverflow.com/questions/56411065/value-cannot-be-null-clientid-on-getconversationmemberswithhttpmessagesasync-e)

**Comment by jwiley84** [comment]
Concerning your update: to get further details about a user such as the ones you're looking for, you'd have to implement OAuth functionality, for example, the Microsoft Graph API (https://docs.microsoft.com/en-us/graph/api/user-get?view=graph-rest-1.0&tabs=cs). 

There is a sample [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/24.bot-authentication-msgraph) on how to implement that.

**Comment by jwiley84** [comment]
Closing issue.
