### ISSUE TITLE
[DCR] Add Connector Tests to the Nightly Functional Tests, to Run Unmocked

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botframework-sdk#5442]
**Current status:** We're almost set up to hit Slack, but are blocked because we can't dynamically create a Web App Bot with a valid Slack channel. We're blocked by a change needed in the AZ CLI (I have a PR in) and some ARM/Swagger stuff that needs changing (@stevengum knows about it and @swagatmishra2007 will implement it, I believe)

---

A [PR in the JS Repo](https://github.com/microsoft/botbuilder-js/pull/908) recently re-enabled some old [Connector tests](https://github.com/microsoft/botbuilder-js/tree/master/libraries/botframework-connector/tests). There are environment variables that can be set to run the tests either mocked or live.

Per @cleemullins, the Nightly Functional Tests should run un-mocked.

For the Dotnet SDK Connector tests:

* Tests can also easily be run live by setting [`HttpRecorderMode`](https://github.com/microsoft/botbuilder-dotnet/blob/master/tests/Microsoft.Bot.Connector.Tests/BaseTest.cs#L21) to `HttpRecorderMode.None`
  * Note: `HttpRecorderMode.Record` also makes it live and re-records the tests for `Playback`
* 11 of 97 Connector tests currently fail when live.
  * All of those 11 tests that fail are ones that attempt to use invalid ids/activities/etc, so more edge-case tests.

- [X] [Fix C# Connector Tests](https://github.com/microsoft/botbuilder-dotnet/pull/2164)
- [ ] Add Connector Tests to Nightly Functional Tests - C#

**Comment by mdrichardson** [comment]
Tests fixed, although unmerged. Un-assigning myself as I don't believe I'll be involved in implementing this in the Nightly Functional Tests.

**Comment by cleemullins** [comment]
@mdrichardson I would love your opinion here. I'm also very happy to have you fix/implement the nightly functional suite.

**Comment by mdrichardson** [comment]
@cleemullins I'd be happy to, but could use a quick walkthrough from somebody. Who can I link up with on this?

**Comment by mdrichardson** [comment]
Note: This is currently stalled because the tests re-create a bot on every run and these tests need the Slack channel, which also needs to be re-created on every run. Currently, you can't add the Slack channel programmatically (it needs to go through Slack OAuth flow to actually register in the Web App). I have a fix for this. Working on issue and PR creation, now.

**Comment by cleemullins** [comment]
@mdrichardson  Let's sync on this. Can we ship this in R7?

**Comment by mdrichardson** [comment]
@cleemullins We can sync in person, but the short version is that for now, it's out of my hands so I can't give a straight answer. The tests rely on the Slack channel, which I think should stay because testing against a 3rd party channel seems like a good idea for this. In order to programatically add the Slack channel to the nightly test bot, which gets recreated on each run, there need to be some updates to AZ CLI. I've submitted a PR for those, but according to @stevengum, some additional things need to change on the ARM and Swagger side. Once all of that is in, I can actually test this and make sure it works. 

Let me know if you want me to pop down there today and we can talk about it.

**Comment by cleemullins** [comment]
I'm not sure what to do here. Can we sync in person tomorrow. Closing for now, as this seems not-actionable.

**Comment by mdrichardson** [comment]
@cleemullins Yeah, let's sync on this today. It's been more or less in limbo for awhile.
