### ISSUE TITLE
[DCR] make memory scopes extensible

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5444]
## Issue
@benbrown pointed out that when building an `AdaptiveDialog` based bot for a channel like MS Teams or Slack, the current memory scopes don't always cover your needs.  You may want to store something at the team or thread level which aren't exposed as scopes.

## Proposed change
We could solve this by making the available set of memory scopes extensible. This could be done using a map of scope names to storage keys. Something like this:

```JS
// Create bots DialogManager and bind to state storage
const bot = new DialogManager();
bot.storage = new MemoryStorage();
bot.rootDialog = new RootDialog();

// Add extended scopes
bot.addScope('team', '{channelData.tenant.id}/{channelData.team.id}');
bot.addScope('channel', '{channelData.tenant.id}/{channelData.team.id}');
```

The above example adds new `team` and `channel` scopes. The template follows the same basic syntax as LG but is assumed to be in the context of an incoming activity.

Here's the source for the example keys:

https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bot-conversations/bots-conversations#teams-channel-data

## Component Impact 
- The `DialogManager` class as it's responsible for reading & writing storage scopes.
- `DialogContext.state` needs a minor update to be aware of the additional scopes. 

## Customer Impact 
This only touches features which are currently in preview.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by Stevenic** [comment]
Oh I forgot to mention... This DCR comes along with an assumption that you'd only ever read & write to memory scopes through `DialogContext.state.getValue()` and `DialogContext.state.setValue()` which seems reasonable.  We could get rid of all the StateMap stuff as they're not really needed anyway.

Another assumption here is that the stock `user`, `conversation`, `dialog`, `turn`, and `configuration` scopes would continue to work as they do. We're just making it easy for developers to add additional scope.  We could have a discussion about making `user` an optional scope you have to define but `conversation` is needed for the bot to function and `dialog` & `turn` are computed scopes.

**Comment by benbrown** [comment]
This will be extremely useful in building bots for multi-user channels like Teams, Slack and others where data will need to be shared across multiple conversations within an organization!

**Comment by vishwacsena** [comment]
This is done.
