### ISSUE TITLE
Direct line Chanel concurrent user issue- bot not responding as expected

### ISSUE THREAD

**Issue by Jibin12345** [microsoft/botframework-sdk#5448]
When two users are accessing the chatbot concurrently , chatbot is responding to only one user.
Other user getting greeting message " How can I help you ?" .
Chanel=Direct Line
Bot Framework = V3
bot builder version =3

**Comment by jwiley84** [comment]
How are you implementing your directline?

**Comment by jwiley84** [comment]
Closing for lack of response.
