### ISSUE TITLE
[Skype] Chatbot not working on Skype, Skype URL's are not loading

### ISSUE THREAD

**Issue by naga245** [microsoft/botframework-sdk#5449]
Hi,
chatbot is not working as expected and some of the Skype URL's are not loading (getting 403 and 404 errors).
![Chatbot issue](https://user-images.githubusercontent.com/39310446/60701079-04331980-9f18-11e9-97e6-85f8639f48d1.png)

**Comment by naga245** [comment]
Any update on the issue?

**Comment by jwiley84** [comment]
@naga245 Are you still experiencing this?

**Comment by naga245** [comment]
@jwiley84 yes, still issue not resolved.

**Comment by CoHealer** [comment]
I've escalated the issue to the Skype team last week and checked in this morning. I'll respond with any updates tomorrow.

**Comment by CoHealer** [comment]
Still no response from the SWC team.

**Comment by CoHealer** [comment]
New update from the Skype Web Control Team. They have a fix checked in but are investigating a related issue. Current ETA to releasing the fix to production is currently mid next week.

**Comment by CoHealer** [comment]
The fix has not yet been deployed. I've asked the Skype Web Control team for new ETA. Will check back in with them early next week.

**Comment by naga245** [comment]
@CoHealer,

issue fixed after migrate from V1 API to V2 API.

**Comment by CoHealer** [comment]
Sounds good @naga245, thanks for letting us know
