### ISSUE TITLE
[DCR] Enable Cosmos DB Creation w/ PartitionKey

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botframework-sdk#5450]
## Issue

Currently, if a user wants to create a new Cosmos DB Container with a custom PartitionKey, they *must* do it through the Azure Portal UI. If they do it through the bot with `new CosmosDbStorage`:

* In Node, the bot runs, but the Container gets the default `_partitionKey` and not the custom one. I'm actually not sure why the bot still works after this.
* In C#, the Container is created with the default `_partitionKey`, but subsequent reads and deletes fail with: 

> Microsoft.Azure.Documents.DocumentClientException: 'Partition key provided either doesn't correspond to definition in the collection or doesn't match partition key field values specified in the document.

Note: [This DCR](https://github.com/microsoft/botframework-sdk/issues/5107) allows the use of partition keys in existing containers, just not while creating them.

## Proposed change

If the user specifies a custom PartitionKey for a Container that doesn't exist, the created Container should use the custom `PartitionKey`.

Additionally, if we're creating a container and a partitionKey is *not* specified, we should default to `id`. As-is, it uses `_partitionKey` and then none of the documents have a value, which I *believe* keeps everything on the same partition (haven't been able to verify). If we use `id`, it at least enables partitioning.

[More info on why to use `id` as the default](https://microsoft-my.sharepoint.com/:w:/p/v-micric/EeoGPJjp9KpJiuc43yn9J3gBvME6aN13VP4q-kqMK9riYw?e=herELH). **Edit: We should actually use `realId`; Cosmos won't let us use `id`**

## Component Impact 

`CosmosDbStorage`:

* Node: [`getOrCreateCollection`](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-azure/src/cosmosDbStorage.ts#L325) should add the partitionKey when container doesn't exist and is specified. If creating a container and no `partitionKey` is specified, it should default to `id`
* C#: [`InitializeAsync`](https://github.com/microsoft/botbuilder-js/blob/master/libraries/botbuilder-azure/src/cosmosDbStorage.ts#L325) should do the same

## Customer Impact 

Allows customers to scale their Cosmos DBs more easily.

## Notes

I haven't looked into how to do this with the older, DocumentDb packages. There are newer packages available:

* [`@azure/cosmos`](https://www.npmjs.com/package/@azure/cosmos)
* [`Microsoft.Azure.Cosmos`](https://www.nuget.org/packages/Microsoft.Azure.Cosmos/) - Currently in Public Preview, but [should be GA any day now](https://github.com/Azure/azure-cosmos-dotnet-v3/projects/2)
  * At one point, containers without a `partitionKey` weren't able to be used at all, breaking backwards compatibility, but I *believe* [this is fixed](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/5)

I toyed around with those packages some time ago and implemented this:

* [C#](https://github.com/mdrichardson/botbuilder-dotnet/blob/cosmosUpdate/libraries/Microsoft.Bot.Builder.Azure/CosmosDbStorage.cs)
* [Node](https://github.com/mdrichardson/botbuilder-js/blob/cosmosPull/libraries/botbuilder-azure/src/cosmosDbStorage.ts)

Note, however, that those are from February and likely need significant updates to be useful.

There's kind of a [DCR to update the packages](https://github.com/Microsoft/botbuilder-js/issues/328), but currently labeled `WontFix`, I believe due to the breaking changes with older containers/collections without a partitionKey.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by sumitshrm4** [comment]
When it could be fixed, we need it as soon as possible ?

**Comment by sumitshrm4** [comment]
@cleemullins @mdrichardson  Yes, generally this a low priority issue, but in our case we don't create any db tables manually, we have so many different instance running (and pending for deployment in some ), so team just run the applications and it creates the tables/collections automatically. However, we can delete and manually create it, I agree ! But our applications is live and around 10k users at a time in peak hours, if we run into a situation to restart the app and create conversationData table again, on the first see support team would not be able to notice that they need to create the table again manually, so for large enterprises like us, it is a big issue. I appreciate your quick response here !

**Comment by sumitshrm4** [comment]
@mdrichardson @cleemullins And In our case, we need partition key to be realId as you mentioned. Because we have lots of traffic, so a fixed partition ( 10 GB ) could be filled in a week.

**Comment by sumitshrm4** [comment]
@mdrichardson @cleemullins 
Also, is it possible to have set TTL (time to live) with Partition key ?

**Comment by sumitshrm4** [comment]
@mdrichardson As you suggested, I have added parttionKey in CosmosDbStorageOptions and in DocumentCollectionRequestOptions for read/write and delete. However, it is still have problem while wither reading or writing. My version is Microsoft.Azure.DocumentDB.Core is 2.4.0   here it the sample - 

`IStorage dataStore = new CosmosDbStorage(new CosmosDbStorageOptions
            {
                AuthKey = "somekey"
                CollectionId = "somekey",
                CosmosDBEndpoint = "somekey",
                DatabaseId = "somekey",
                DocumentCollectionRequestOptions = new RequestOptions
                {
                    PartitionKey = new PartitionKey("somekey")                    
                }
                PartitionKey = "somekey"
            });`

**Comment by mdrichardson** [comment]
@sumitshrm4 With the current BotFramework SDK, you can't set your `PartitionKey` to just anything. Please follow the ["Temporary Workaround" heading here](https://github.com/microsoft/botframework-sdk/issues/5467#issue-469385575)
