### ISSUE TITLE
LUIS SDK v3 Endpoint Support 

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5451]
Issues that need to be resolved:
1. The CogSrvs SDK introduced breaking changes recently in a minor version bump.
2. This actively prevents us from upgrading. 
3. ... which prevents us from implementing the LUIS v3 APIs

We need to get a plan in place for 4.6 to resolve. Sync w/ Mina to resolve CogSrvs SDK version issues.

**Comment by sgellock** [comment]
this work is tracked in the individual language repositories
