### ISSUE TITLE
[Adaptive] [DCR] Drop steps tied to adaptive dialog

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-sdk#5458]
Based on several rounds of feedback, we should drop "steps" tied directly to an adaptive dialog and move to a strictly [event + constraints] -> action (steps) model. This change will: 
- help minimize and streamline concept count 
- ensure all actions are always tied back to an event (and a constraint where applicable) 
- instill clarity at both root dialog, child dispatcher as well as child dialog level on where actions (steps) should be associated with. 

- [ ] C#
- [ ] JS

**Comment by benbrown** [comment]
Would this mean that all event+constraints ALWAYS fire a leaf dialog?

and/or

Would this mean that the actions within the event handler would behave like the top level actions do now -- be interruptible by each other, use recognizer

And/or what is the implication for how the "Default" behavior of any given leaf dialog would work?

**Comment by gabog** [comment]
@vishwacsena, I think this is old, closing it.
