### ISSUE TITLE
Remove mention of chat bot name in MS teams

### ISSUE THREAD

**Issue by kannanambadi** [microsoft/botframework-sdk#5465]
I have a developed a chat bot using v4 and C#. first it was deployed to web, now we added bot into MS teams. In teams, chat bot is not responding with accurate answers from QnA service, however the same question gets answered with correct one in Web. We've found the reason, that the chat bot name (@ChatBot) gets appended in front of the question, that in turn changes the question structure. 

I tried the methods RemoveMentionText(turnContext.Activity.Id); and RemoveRecipientMention, but no luck so far. 

Is there a way i can remove the chat bot name from the question before calling the QnA or Luis service. ? Please help

**Comment by CoHealer** [comment]
@mdrichardson, please investigate

**Comment by mdrichardson** [comment]
`RemoveMentionText` is currently [only compatible with Skype](https://github.com/microsoft/botbuilder-dotnet/blob/35c747e8d127884f38c5a683ce697b0d7f64004b/libraries/Microsoft.Bot.Schema/ActivityExtensions.cs#L49).

I'll work on a PR to get this working for Teams as well.

In the meantime, you can use the [Botframework Teams Extension](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet). It can also [strip out Teams mentions](https://github.com/OfficeDev/BotBuilder-MicrosoftTeams-dotnet)
