### ISSUE TITLE
[Adaptive] Add a property on input to short circuit consultation bubbling on interruption

### ISSUE THREAD

**Issue by vishwacsena** [microsoft/botframework-sdk#5470]
## **Issue**
Current consultation bubbling logic does not provide for cases where user needs to stop bubbling when a specific constraint is met. We have a blanket, boolean allow interruption setting. 

However it is evident that when you use Language Understanding powered by a non-deterministic system such as LUIS, you would need the ability to short-circuit consultation bubbling when a specific constraint is met (e.g. LUIS recognizer came back with a specific intent and/ or LUIS recognizer came back with a specific entity value etc.)

## **Proposed change:**
- To all input dialogs, add a new property `DoNotInterrupt` that accepts a `an expression` as value. 
- This propoerty can only be set if `AllowInterruption` is set to true.
- The value (constraint specified as an expression) provided for `DoNotInterrup` property is evaluated **_only_** after the recognizer tied to that dialog runs for the given turn of the conversation. This is required so the expressions are always evaluated on fresh recognition results for the given turn of the conversation. 
- Upon evaluating the `DoNotInterrupt` property, if the value expression evaluates to
    - TRUE: then consultation bubbling stops and the input continues its evaluation based on properties configured on that input.
    - FALSE: then continue consultation bubbling and issue a reprompt on the input if no other rules fired on the consultation bubble.

## **Impact:**
Without this change users will have to explicitly add Rules to explicitly short circuit consultation bubbling and provide an opportunity for the leaf input dialo's recognizer to be run. With this change, users do not have to resort to handling the `RecognizedIntent` event to short-circuit consultation bubbling.

**Before this change**
```C#
var rootDialog = new AdaptiveDialog("root") {
    Rules = new List<IDialog>() {
        new EventRule() {
            Events = List<IDialog>() {
                AdaptiveEvents.BeginDialog
            },
            Steps = new List<IDialog>() {
                new NumberInput() {
                    Property = "user.profile.age",
                    Prompt = new ActivityTemplate("What is your age?"),
                    AllowInterruption = true
                },
                new SendActivity("I have your age as {user.profile.age}")
            }
        },
        new IntentRule() {
            Intent = "StopBubbling",
            Steps = new List<IDialog>() {
                // handle this intent via a rule to stop consultation bubbling.
            }
        }
    }
};
```

**After this change**
```C#
var rootDialog = new AdaptiveDialog("root") {
    Rules = new List<IDialog>() {
        new EventRule() {
            Events = List<IDialog>() {
                AdaptiveEvents.BeginDialog
            },
            Steps = new List<IDialog>() {
                new NumberInput() {
                    Property = "user.profile.age",
                    Prompt = new ActivityTemplate("What is your age?"),
                    AllowInterruption = true,
                    // New property to short circuit consultation bubbling.
                    // Having the value as an expression enables things like "#StopBubbling" 
                    // or "@number" or "#StopBubbling && @number" etc. 
                    DoNotInterrupt = "#StopBubbling"        
                },
                new SendActivity("I have your age as {user.profile.age}")
            }
        }
    }
};
```

## Implementation
- [ ] C#
- [ ] JS

**Comment by benbrown** [comment]
So if I have a local recognizer in my dialog, I would train the None intent and use DoNotInterrupt = #None to allow my input to capture the value?

**Comment by benbrown** [comment]
I am wondering what type of real life values you'd imagine being used in DoNotInterrupt.

**Comment by yochay** [comment]
Few comments:

- This property can only be set if AllowInterruption is set to true. --> for code SDK, this means this property will only take effect if AllowInterruption is set to true. For Composer, we can add inline validation on the checkbox. 
- @vishwacsena , we should also add the case for customer explicitly adding an Intent Rule (Evnet) that handles the same Intent that can be defined in the DoNotInterrupt. I am not sure how this can be easily done when DoNotInterrupt is an expression. Maybe we need to allow specifically to identify an intent?

**Comment by vishwacsena** [comment]
@benbrown 
```
So if I have a local recognizer in my dialog, I would train the None intent and use DoNotInterrupt = #None to allow my input to capture the value?
```
> If you are using a LUIS recognizer in your dialog and you are expecting to use with consultation, you would train the model with utterances that capture entities you are looking for and set doNotInterrupt to that intent so consultation bubbling does not continue if your dialog recognizes the intent aka user is answering your prompt.  

```
I am wondering what type of real life values you'd imagine being used in DoNotInterrupt.

If my parent dialog has lots of intents and I am not using a local recognizer, how do I protect against interruption?
```
> If you have intents that you would like to handle within the scope of a dialog, then add rules that handle those intents in that dialog and consultation ends because you handled incoming user input. Without this property, you will need to explicitly add a rule to handle the intent but we would be unable to in that case differentiate between a Rule you have added to short-circuit consultation .vs. a rule you added to handle the utterance as an interruption locally within your dialog. 

```
If my parent dialog has lots of intents and I am not using a local recognizer, how do I protect against interruption?
```
>  Two options - 1) set allowinterruption = false or 2) add a local recognizer with specific utterances you do not wish to bubble up to the parent. 

@yochay 
```
@vishwacsena , we should also add the case for customer explicitly adding an Intent Rule (Evnet) that handles the same Intent that can be defined in the DoNotInterrupt. I am not sure how this can be easily done when DoNotInterrupt is an expression. Maybe we need to allow specifically to identify an intent?
```
> I thought about this and the current rule handling behavior seemed right in that if you have a constraint that will short consultation, that will trump any rule that you add that might otherwise trigger without the constraint.

**Comment by yochay** [comment]
@vishwacsena 
> I thought about this and the current rule handling behavior seemed right in that if you have a constraint that will short consultation, that will trump any rule that you add that might otherwise trigger without the constraint.

What happen if I define both DontAllow with a given intent (#GetTypeOfOder)  and set a rule for the same GetTypeOfOder intent? Which will win?

**Comment by vishwacsena** [comment]
@yochay 

>What happen if I define both DontAllow with a given intent (#GetTypeOfOder) and set a rule for the same GetTypeOfOder intent? Which will win?

The rule will not be executed - the property will win. This is identical to rules not triggering when `AllowInterruption` property on an input is set to `false`

**Comment by benbrown** [comment]
Is the following correct?

If I use a LUIS recognizer, then in a child dialog use a choice/switch to create a branching flow, that means:

1) I will add all choices in my choice prompt definition
2) I will then also add them all of those choices again in the switch
3) Then add them a third time in an intent that exists purely to block interruptions
4) Then go back and add that intent name to the choice prompt
5) then CROSS MY FINGERS that luis will reliably recognize the choices and 
6) possibly continue to have to train and retrain luis so that it will see my free text input as free text

**Comment by benbrown** [comment]
Here is another scenario:

My root dialog has 10 intents defined, 9 of them are "commands" that fire child dialogs.  Then, I have "quit" defined, which is super simple - it just calls cancel all dialogs and ends.

Now, in my 9 child dialogs, I have LOTS AND LOTS of inputs.  Like, 20 in each dialog.  All of them are using plain text prompts.  I'm asking things like "What is your favorite gummy bear flavor" and "Tell me 5 things you like to do on the weekends"  -- things that would be REALLY HARD to train luis to reliably recognize.   And I want my user to be able to quit out of any one of those prompts back to the root, so I've got "allow interrupts" enabled.

What do I have to do to get that to work? How do I get those raw text values accepted by the prompt and NOT hijacked by the root dialog? This should be easy. This is the expected behavior and should _just work_ without lots of extra options or conditions required.   I am concerned that the proposed solution is going to require a lot of additional developer work.

**Comment by vishwacsena** [comment]
@benbrown 
```
Is the following correct?

If I use a LUIS recognizer, then in a child dialog use a choice/switch to create a branching flow, that means:

1. I will add all choices in my choice prompt definition
2. I will then also add them all of those choices again in the switch
3. Then add them a third time in an intent that exists purely to block interruptions
4. Then go back and add that intent name to the choice prompt in this new difficult to understand option
5. then CROSS MY FINGERS that luis will reliably recognize the choices and
6. possibly continue to have to train and retrain luis so that it will see my free text input as free text
this is a lot of work!
for every single input?
a LOT of work.
```

First off, I do not see how everything except for step #4 you outlined above relates to the specific DCR. I have a separate spec that outlines things we are doing to minimize the overall amount of work from a LOT to a LOT LESSER in more detail. I’ll DM that to you again and let’s continue to discuss additional things we can do there offline. 

#1, #2 and #3 can also be better through a shared data model definition that can be used across LU, LG and dialog and I’ll working on a separate proposal for that and will share it once I have a draft ready.

**Comment by vishwacsena** [comment]
@benbrown 
```
Here is another scenario:

My root dialog has 10 intents defined, 9 of them are "commands" that fire child dialogs. Then, I have "quit" defined, which is super simple - it just calls cancel all dialogs and ends.

Now, in my 9 child dialogs, I have LOTS AND LOTS of inputs. Like, 20 in each dialog. All of them are using plain text prompts. I'm asking things like "What is your favorite gummy bear flavor" and "Tell me 5 things you like to do on the weekends" -- things that would be REALLY HARD to train luis to reliably recognize. And I want my user to be able to quit out of any one of those prompts back to the root, so I've got "allow interrupts" enabled.

Once this solution is in place, what do I have to do to get that to work? How do I get those raw text values accepted by the prompt and NOT hijacked by the root dialog? This should be easy. This is the expected behavior and should just work without lots of extra options or conditions required. I am concerned that the proposed solution is going to require a lot of additional developer work.
```
If your conversation design calls for you to use text input in your child dialogs then you would not use LUIS recognizer in your child dialogs especially when you are only looking to have quit work in each child. The solution would be to use a simple regex recognizer on each of the child dialogs that **only** fire when the user says things related to quit that have an exact match. For everything else, based on the current consultation logic, your text input will continue to process user input as you would expect. Using LUIS recognizer for just the ‘quit’ intent determination is possible although you’d then have to start playing with confidence score since ‘vishwac’ might come back as possibly the ‘quit’ intent if that’s the only intent in your model albeit with a low confidence score.

**Comment by boydc2014** [comment]
To be honest, this feels odds to me, 

From a design perspective, 
* we are again adding a new property that's is not tight to this input, but to the system, because this config works in a very specific time in the bubbling process
* if this only work when allowInterruption = true, why just allowInterruption = expression. 

From the actual behavior,
I think my question is similar to @benbrown's 
1. how this would work if i have >2 layer lu, because this seems only designed to evaluate the first layer dialog's lu result?

**Comment by vishwacsena** [comment]
Closing the DCR since we are taking a surgical fix.
