### ISSUE TITLE
[Adaptive] Use EmitEvent to coordinate the original InputDialog and the interrupters

### ISSUE THREAD

**Issue by boydc2014** [microsoft/botframework-sdk#5471]
## Issue
Today, we have a fixed logic here to judge whether an inputDialog should re-prompt or re-process the activity after consulation. 

The logic is stepsCount > 0, reprompt, because something happes, we consider this has been taken, we reprompt, otherwise we procee again in InputDialog. 

What we want is sometimes, even interrupts reacted, but still want the original InputDialog to process instead of reprompt. 

## Context
There is already a proposal for that in https://github.com/microsoft/botframework-sdk/issues/5470, which adds a new property. This issue at it's core is a coordinating issue, but we are trying to make it into one particular InputDialog. The downside of this, 
* This property is hard to explain, because essentially it's a configuration to the whole process rather than this inputDialog
* It relies solely on this Dialog's direct parent's LU result, have siginicant limitation, which means don't allow any other dialog in the pipeline to have a chance.
* It only works together with allowInterruption (Which itself is already hard to explain)
* It relies on an expression, again, adding learning curve     

More importantly, as the conversation experience gets more and more advanced, i believe the direction is there would be more and more coordination between different dialogs, we should generic solution to handle this.

## Proposal
Instead, my proposal is reusing the event system, which is by designed to corrdination things like this,
 > Everything remains the same, if steps > 0, we reprompt, unless we see such an Event "ProcessAgain". 

So anyone in the bubbling (consultation) pipeline can have a step EmitEvent("ProcessAgain"), and even can  swallow and emit again, whatever. The point is it's a generic solution allow any participants to join in the discussion. 

It's also concept simple to explain,  it tells the followers, 
 > hey, i reacted, but i think you should also take a look

that's it. 

## More advanced
Let me also list an more advanced scenario, that the interrupter want neither re-prompt or re-take, the interrupter want bypass this. So interrupter can send an event "InputGet" 
Assume
```
Bot: age?   // NumberInput wait for number
User: i don't want give age ? // interuption happend
Bot: ok, i assume you are 30 // interupter set age=30, and emit "InputGet:age"
Bot: ok, what's your name? // NumberInput react to InputGet, neither re-prompt or re-take, just bypass
```
This is another proof that, a generic event solution can work, but a customized field won't, it would be "insane" to add another property for this behavior. 

## Example
```C#
var rootDialog = new AdaptiveDialog(nameof(AdaptiveDialog))
{
    Generator = new TemplateEngineLanguageGenerator(),
    Recognizer = new RegexRecognizer() {
        Intents = new Dictionary<string, string>() {
            { "None", "(?i)test" },
            { "Greeting", "(?i)hi" },
            { "Start", "(?i)start" }
        }
    },
    Rules = new List<IRule> ()
    {
        new IntentRule() {
            Intent = "Start",
            Steps = new List<IDialog>() {
                new TextInput() {
                    Prompt = new ActivityTemplate("What is your name?"),
                    Property = "turn.userName",
                    AllowInterruptions = true
                },
                new SendActivity("I have {turn.userName} as your name")
            }
        },
        new IntentRule() {
            Intent = "None",
            Steps = new List<IDialog>() {
                new SendActivity("In none, hey,  i don't know what you talking, wait a moment")
                // Send a signal that this text needs to take care again
                new EmitEvent("ProcessAgain")
            }
        },
        new IntentRule() {
            Intent = "Greeting",
            Steps = new List<IDialog>() {
                new SendActivity("Hi, I'm the test bot!")
            }
        }
    }
};
```

## Conclusion and Furture thinking
A simple EmitEvent and InputDialog react to that, is simple\good enough, techincally much much simper than encoding confusing properties into specific dialog. 

If we think about our direction of dialog model, we want one unified dialog model, which i expect "InputDIalog should be implemented as ApativeDialog", if we think from that standpoint, we should solve the problem in a generic way, rather than go one step further of specializing InputDialog.

**Comment by vishwacsena** [comment]
This was resolved via this PR - https://github.com/microsoft/botbuilder-dotnet/pull/2337
