### ISSUE TITLE
Adaptive card is not rendering in skype latest version

### ISSUE THREAD

**Issue by roshnig** [microsoft/botframework-sdk#5479]
In skype bot we are using adaptive cards but it is not rendering properly in skype latest version. It is displaying as an icon (please see attachment). One of my team member has older version for skype, for her same card is displaying properly.

latest version where it is not working : 8.50.0.38
It is coming like this in latest version -
![Capture](https://user-images.githubusercontent.com/19589981/61859405-f988f600-aebf-11e9-8c57-464ae6024946.PNG)

older version where it is working :  8.30.0.50
Here card is displaying properly -
![Capture1](https://user-images.githubusercontent.com/19589981/61859842-d1e65d80-aec0-11e9-8823-c13b85535f77.PNG)

Please let me know, how can I fix this issue.

**Comment by v-kydela** [comment]
@roshnig - Skype does not officially support Adaptive Cards, so any instance of Adaptive Cards seeming to work is incidental. The appearance of your card suggests that an alternative should work, like a receipt card. Would you provide the JSON for your card to help me provide a good solution?

**Comment by roshnig** [comment]
Thanks for your response. Actually we are already using other types of card and these are working perfectly fine in skype bot. We wanted to explore adaptive cards so tried multiple json samples given in microsoft website -
https://adaptivecards.io/designer/
None of these samples are working for me but for my colleague all samples are working.

**Comment by v-kydela** [comment]
@roshnig - I'm glad you have a working alternative to Adaptive Cards. Skype does not support Adaptive Cards, so I strongly recommend against trying to use Adaptive Cards in Skype. You can see a list of platforms that officially support Adaptive Cards here: https://docs.microsoft.com/en-us/adaptive-cards/resources/partners
