### ISSUE TITLE
Integration of Skype and BMC Remedy - Can I use Skype bot for calling to Mobile   phone when a new ticket appears in BMC Remedy Ticketing tool?

### ISSUE THREAD

**Issue by needyourhelp508** [microsoft/botframework-sdk#5490]
Hello,

Greetings folks!!

Can anyone throw some light if you have done some automation for monitoring the tickets with the above approach or come across such scenario?

We would like to implement in our environment as well that can help saving the efforts of manual monitoring by Analyst or Support engineer?

I believe this may be achieved by Skype bot integration with Remedy tool, however, not sure if there is any tool (with some specific technology) to be developed for integration of same.

Any inputs/comments/suggestion in this regard are highly appreciated. Many thanks in advance!!

**Comment by CoHealer** [comment]
@EricDahlvang , can you assist?

**Comment by EricDahlvang** [comment]
I don't think Skype bots can make outgoing calls.  There might be a way to accomplish this using a normal Skype user and the apis, but I'm not sure.
