### ISSUE TITLE
DCR: detect dialog changes when a bot is deployed

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5495]
## Issue
When a lot of structural changes are made to a bot dialog system and it's re-deployed, it's possible for users that are having an existing conversation with the bot to get into a stuck state. We should add logic to detect this and automatically cleanup the conversations dialog stack.

## Proposed change
My proposal is that for every container (AdaptiveDialog) we generate an ordered list of the child dialog IDs added to the container. We can then hash all of these IDs into a code that we can persist with the containers dialog state.  When a new Activity comes in we can compare the dialogs current hash against the persisted hash. If they're different the containers structure has changed and we should raise a `dialogChanged` event that the bot can catch to notify the user of the change and cleanup their state.  Should the bot not handle the event then we should at least raise an error so the bots state gets cleaned up.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by benbrown** [comment]
Another possibility is would be to use the `updatedAt` attribute in the dialog files -- currently `$designer.updatedAt` which would catch _any_ changes in the dialog.  This is automatically set whenever a change to the dialog file is made.

**Comment by benbrown** [comment]
I think this is a really big deal in terms of the maturation of the SDK in production environments!
