### ISSUE TITLE
Add UserVoice to our milestone planning process

### ISSUE THREAD

**Issue by sgellock** [microsoft/botframework-sdk#5501]
Once our community engineer starts, I'd like to use UserVoice or something similar to help us engage the community around milestone feature work

**Comment by cleemullins** [comment]
@garypretty, When you can, let's get a list of mechanisms by which we should engage the community with feature work.

**Comment by cleemullins** [comment]
@garypretty How do we resolve this issue in the 4.6 cycle?

**Comment by garypretty** [comment]
Closing this and moving to internal planning with PM team.
