### ISSUE TITLE
Instructions for Enabling AppInsights for Bots

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5504]
When supporting a bot, the CSS team often has incomplete information. 

We need a Doc / Link that does the following:
1. How to enable App Insights in your Bot?
2. How to determine if App Insights is enabled for your bot?

As it sits now, older bots that have updated to the latest SDK's won't have appInsights. Bots that start from a sample won't have this enabled either. 

We should consider having this be a "Starting Point" for the CSS team, as "Enable App Insights, duplicate the problem, and send us the resulting trace". 

This is especially true for all the gateway timeout issues, that look like they're from DirectLine but are generally root-causes to be user-code running slowly.

**Comment by cleemullins** [comment]
Note: Need Node and C# examples. Python for Extra Credit.

**Comment by munozemilio** [comment]
@garypretty FYI

**Comment by garypretty** [comment]
@munozemilio I will take this one under docs - we already have a page, but there is a PR to add the latest node instructions.

I also just added this PR under samples https://github.com/microsoft/BotBuilder-Samples/pull/2509 to add the link to the page to our samples comments for the catch all error handler.

**Comment by garypretty** [comment]
Given we now have this documentation live http://aka.ms/bottelemetry and we have a PR open to add the link to samples error handlers, I am going to close this issue out.
