### ISSUE TITLE
Authentication - OAuth (Oauth card) login card works

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botframework-sdk#5524]
- [ ] C#
- [ ] Javascript

**Comment by EricDahlvang** [comment]
OAuthCard does NOT work.  In fact, the OAuthPrompt uses a SignIn card when on Teams: https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/OAuthPrompt.cs#L421  (this is currently an open question to the Teams team)

https://github.com/microsoft/BotBuilder-Samples/tree/teams-samples/experimental/teams/csharp-dotnetcore/Scenarios/46.teams-auth-Expanded

**Comment by iMicknl** [comment]
@EricDahlvang this is different behaviour compared to the Javascript SDK. `channelSupportsOAuthCard` does list `msteams`. https://github.com/microsoft/botbuilder-js/blob/6e41343a1bc57a26461947c9462117a636aa718a/libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts#L318

**Comment by EricDahlvang** [comment]
Hi @iMicknl

channelSupportsOAuthCard is returning false for teams:

https://github.com/microsoft/botbuilder-js/blob/6e41343a1bc57a26461947c9462117a636aa718a/libraries/botbuilder-dialogs/src/prompts/oauthPrompt.ts#L322

I've been waiting to talk with @Jeffders who  i think originally enabled OAuthPrompt on teams by adding the SignInCard. I have not been able to get OAuthCard to work.

**Comment by Virtual-Josh** [comment]
Note: Need to confirm with Andrew that this work is out of scope and we can close this ticket out.

**Comment by EricDahlvang** [comment]
Closing this, as @Jeffders has confirmed Teams does not support OAuthCard.
