### ISSUE TITLE
Authentication - OAuth (sign in card) login works

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botframework-sdk#5525]
- [x] C#
- [x] Javascript

**Comment by EricDahlvang** [comment]
Sign in card works as expected. (OAuthPrompt uses Sign in Card)

https://github.com/microsoft/BotBuilder-Samples/tree/teams-samples/experimental/teams/csharp-dotnetcore/Scenarios/46.teams-auth-Expanded

**Comment by EricDahlvang** [comment]
JS sample using OAuthPrompt (which uses Sign In Card internally, when on Teams):

https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/46.teams-auth
