### ISSUE TITLE
Error: POST to 'https://facebook.botframework.com/v3/conversations/283300000-2584000000/activities/isdfsdfDUde7fZyH6iW_xn7BbA' failed: [503] Service Unavailableat Request._callback

### ISSUE THREAD

**Issue by DevSharkOne** [microsoft/botframework-sdk#5576]
## Issue

Try to request https://facebook.botframework.com/v3/conversations
fire the error:
Error: POST to 'https://facebook.botframework.com/v3/conversations/283300000-2584000000/activities/isdfsdfDUde7fZyH6iW_xn7BbA' failed: [503] Service Unavailableat Request._callback

Please help!

**Comment by mdrichardson** [comment]
@DevSharkOne 	

How are you making the request? Something like Postman?

Can you provide:

* AppId
* ConversationId (is the one above legit, or obfuscated?)

A 503 means the Activity never gets to the Bot controller but instead the request is rejected by the host platform (nothing in the Bot Builder SDK returns 503 errors).

So it looks like an issue with the hosting platform running the bot. On Azure App Services, a 503 can be caused when a machine reboots, for example. 

* How are you hosting your bot? 
* What additional hosting platform telemetry do you have available (Windows logs, IIS logs, etc.)?

**Comment by DevSharkOne** [comment]
@mdrichardson 
The request was made from the bot, the error was found in the logfile.
The AppId and ConversationId was change in the title it is not the real data

The bot is hosted in an Azure App Service and exposed through bot channel registration.

The issue began on 1st september and yesterday at night was resolved without any action from us, so what you are commenting about that it may be associated to azure app service make sense.
Right now the issue can not be reproduced because the service is working fine.
If something happens again i will contact the github repo.

Thank you for your help.

**Comment by mdrichardson** [comment]
I see. If you'd like, I can look into it a bit more. Could've been a service outage. If so, please provide the `appId` and I will track it down.

**Comment by DevSharkOne** [comment]
@mdrichardson 
Is there any secure way to share you the AppId?

**Comment by mdrichardson** [comment]
@DevSharkOne 	

Sure. Send to vDASHmicricATmicrosoftDOTcom (replace all-caps with appropriate character)

**Comment by DevSharkOne** [comment]
@mdrichardson 
I have sent the app id to your inbox.
Thank you very much for follow up.

**Comment by mdrichardson** [comment]
@DevSharkOne 	

It appears that the Botframework's Facebook channel server you connect to experienced high CPU on a few of its instances at the same times that I was able to see your 400- and 500-level errors.

Over the last month, that particular server has had > 99.99% availability. I think you were just unfortunate to catch the 0.01%. I wouldn't expect this to be a recurring issue.

**Comment by DevSharkOne** [comment]
@mdrichardson 
I really appreciate your effort to research the reason that was behind the botframework behavior.
Thank you very much.

**Comment by mdrichardson** [comment]
No problem. Happy to help!
