### ISSUE TITLE
Customize telemetry

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-sdk#5577]
#### Is your feature request related to a problem? Please describe. 

In TelemetryLoggerMiddleware, attachments are not logged.

In IBotTelemetryClient.TrackException, related activity is not logged.

#### What is the solution you are looking for?

Extend TelemetryLoggerMiddleware: when attachments are jsons for adaptive card, save id if exists.

Create properties like ones in TelemetryLoggerMiddleware to IBotTelemetryClient.TrackException, so exception could be logged together with related activity.

#### What alternatives have you considered?

Apply these updates in sdk.

**Comment by garypretty** [comment]
This has now been implemented as of 4.9.

C# PR https://github.com/microsoft/botbuilder-dotnet/pull/3737
JS PR https://github.com/microsoft/botbuilder-js/issues/2030 

Python PR remains outstanding https://github.com/microsoft/botbuilder-python/issues/940
