### ISSUE TITLE
Provide some exception flag in Telemetry

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-sdk#5578]
#### Is your feature request related to a problem? Please describe. 

Even if IBotTelemetryClient.TrackException could associate exception with related activity, sometimes the exception is caught within the bot so OnTurnError is not called and one may still want to flag it as an exception for further analysis.

Related #5577 

#### What is the solution you are looking for?

Add a new ActivityTypes. Or could user use any custom type they like?

#### What alternatives have you considered?

Guide user to track a custom exception together with related reply.

#### Is there any other context you can provide?

I have thought this might be transferred to https://github.com/microsoft/botbuilder-dotnet not here. Yet it happened, so I continue here.

**Comment by garypretty** [comment]
@xieofxie you already have access to the IBotTelemetryClient in a dialog, so you can manually call TrackException if / when you catch an exception - does this not cover your scenario?  If not, can you provide some further detail as I am not quite sure what you are asking for.  Thanks.
