### ISSUE TITLE
QnAMakerOptions interface is missing properties

### ISSUE THREAD

**Issue by Tush-r** [microsoft/botframework-sdk#5580]
## Issue
`QnAMakerOptions` interface is missing certain properties like, `RankerType` and `isTest`.

These properties/ parameters are mentioned here:
* https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/concepts/best-practices#searching-for-answers
* https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/how-to/metadata-generateanswer-usage#match-questions-only-by-text

## Other links

QnAMaker rest api: https://docs.microsoft.com/en-us/rest/api/cognitiveservices/qnamakerruntime/runtime/generateanswer#request-body

JavaScript docs: https://docs.microsoft.com/en-us/javascript/api/botbuilder-ai/qnamakeroptions?view=botbuilder-ts-latest

.NET docs: https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.ai.qna.qnamakeroptions?view=botbuilder-dotnet-stable

**Comment by cleemullins** [comment]
@trojenguri, could you take a look at this question from @Tush-r and let them know why this is and if we've got any plans to address?

**Comment by trojenguri** [comment]
For Bot SDK, we thought of allowing only to Production endpoint. So, we didn't gave "isTest" flag.
And "RankerType" is the new field that we added. We will add this support later.

**Comment by tsuwandy** [comment]
@trojenguri, when will the new properties be available for use?  Please update, thanks!

**Comment by trojenguri** [comment]
ETA would be by end of Oct. In next release of SDK.

**Comment by Tush-r** [comment]
> @trojenguri, when will the new properties be available for use? Could you provide an ETA for customer? Please update, thanks!

The properties can still be used in TypeScript by type casting the `QnAMakerOptions` object as `any`.
In C# it may be possible by extending the `QnAMakerOptions` class.

Thanks for your support.
