### ISSUE TITLE
Implement Skill Validation Prototypes

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#5582]
This task involves creating working prototypes that validate that the skills functionality works as expected.

These prototypes can be published to the Experimental folder in the Samples repo once they are completed.

Key prototypes

### Simple Echo bot

Scenario https://github.com/microsoft/botframework-sdk/projects/13#card-26118546

Implement a SimpleRootBot that invokes a remote skill. The SimpleRootBot should be based on the BF Echo Bot template and directly instantiate the SkillConnector to invoke a remote skill directly without having to have a MainDialog.

- [x] DotNet [PR](https://github.com/microsoft/BotBuilder-Samples/pull/2032)
- [x] JavaScript [PR](https://github.com/microsoft/BotBuilder-Samples/pull/2070)
- [x] Python [PR](https://github.com/microsoft/BotBuilder-Samples/pull/2092)

### Dialog to Dialog
This example should showcase and validate the following scenarios:

1. A sample SkillDialog that can be used on the parent bot to have a skill participate in a waterfall
2. Sending input parameters to a skill
3. Handling return parameters from a skill
4. Handling skill cancellation from parent
5. Invoking a skill using an event that passes the startup intent
6. Invoking a skill by just passing a message (with or without parameters) so the skill can do its own LU and entity parsing on the original request
7. Single and mult turn interactions with a skill
8. Handle skill cancellation in case of parent catastrophic failure (in OnError)

- [x] DotNet (Released as part of Experimental sample in R7 [PR](https://github.com/microsoft/BotBuilder-Samples/pull/2032), , formal sample will be done in R8)
- [x] JavaScript (To be done in R8 once DotNet is ready)
- [x] Python (To be done in R8 once DotNet is ready)

### OAuth dialog support in a skill
This prototype should validate that a skill can render an OAuth dialog and that the underlying infrastructure works

- [x] DotNet (Released as part of Experimental sample in R7, formal sample will be done in R8)
- [ ] JavaScript (Tested in dev, formal sample will be done in R8)
- [ ] Python (To be done in R8 once DotNet is ready)

### Proactive messages
This prototype should that a skill can initiate a proactive message on the parent bot

- [ ] DotNet (To be done in R8)
- [ ] JavaScript (To be done in R8)
- [ ] Python (To be done in R8)

**Comment by cleemullins** [comment]
Currently blocked on PR #1461

**Comment by johnataylor** [comment]
Assuming this work is part of the end to end testing for skills.
