### ISSUE TITLE
Broken link in Bot Framework -- Activity file

### ISSUE THREAD

**Issue by zxyanliu** [microsoft/botframework-sdk#5585]
## Issue
*In [Bot Framework -- Activity](https://github.com/Microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md) file* , the [Bot Framework Protocol](https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-protocol/botframework-protocol.md) link is broken.  

![image](https://user-images.githubusercontent.com/32497439/64447210-afcf2600-d08f-11e9-96cc-bd8b4e0dc9f7.png)

## Proposed change
*Please fix the link*

**Comment by cleemullins** [comment]
I can't find that Markdown file. I've assigned this to @Kaiqb who runs our documentation team.

**Comment by zxyanliu** [comment]
Hi @cleemullins 

Thanks for your reply. 

That Markdown file is here: 
[botframework-sdk/specs/botframework-activity/botframework-activity.md](https://github.com/microsoft/botframework-sdk)

We think the [Bot Framework Protocol](https://github.com/microsoft/botframework-sdk/tree/master/specs/botframework-protocol) link points to 
https://github.com/microsoft/botframework-sdk/tree/master/specs/botframework-protocol

I work for documentation team. If the link is correct and I have access, I can fix it. 

Thanks. 

Yan

**Comment by Kaiqb** [comment]
@Cleemullins - this content is in the repo that Dan's team manages.

**Comment by dandriscoll** [comment]
@Kaiqb this spec is not complete/finished, can you remove it from the docs here?
