### ISSUE TITLE
Refactor Microsoft.Bot.Builder.Skills library

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-sdk#5586]
#### Is your feature request related to a problem? Please describe. 

This item is to track a series of work to refactor the current Microsoft.Bot.Builder.Skills library to better match the design principals of the BotBuilder SDK

- [x] Apply SDK Roslyn Analyzers and rulesets
- [x] Apply SDK editorconfig to the solution
- [x] Move VA specific code and classes that will be out of scope for the SDK into a separate package
- [x] Pass in slots from dialogOptions for skilldialog
- [x] create skillconnector and fold forwarding operation in SkillDialog to SkillConnector
- [x] use callerId to isolate state access
- [x] remove incorrect callerId usage
- [x] use botframeworkstreamingextention adapter instead of SkillWebSocketBotAdapter
- [x] create another component on top of the current Skill component so that we could put core components in there and non-core ones in the new library

**Comment by gabog** [comment]
This issue has been superseded by others. Closing it
