### ISSUE TITLE
Remove dependency on MultiProviderAuthDialog from SkillDialog

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-sdk#5591]
#### What happens?

We need to remove the dependency on MultiProviderAuthDialog so that developers can pass in whatever AuthDialog implementation they want to use for Auth operations

**Comment by gabog** [comment]
Hi @lzc850612 , should we keep this task? Transfer it back to solutions? or close it given the direction we are taking?

Thanks

**Comment by gabog** [comment]
This one is not needed based on the latest implementation, closing it
