### ISSUE TITLE
Implement mechanism to share OAuth tokens between parent bot and the skill

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#5599]
TODO: need to flesh out the requirements for this. VA has a mechanism in place to handle this but we need to review it and see if we want to refactor it.

**Comment by dandriscoll** [comment]
We have an architectural discussion happening about roles and responsibilities in this part of the system. @darrenj is involved

**Comment by gabog** [comment]
This one is not longer required based on the latest implementation, closing it.
