### ISSUE TITLE
Implementation of Message Extension Search Commands

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botframework-sdk#5606]
This is a ticket to track the implementation and addition of a Message Extension Search Commands project to the overarching solution

**Comment by stevengum** [comment]
closing via [botbuilder-dotnet/master#4d4b4d1aaae0faaf18ecab0e5130ecacc058d4f3](https://github.com/microsoft/botbuilder-dotnet/commit/4d4b4d1aaae0faaf18ecab0e5130ecacc058d4f3)
