### ISSUE TITLE
Implementation of Message Extension Configuration

### ISSUE THREAD

**Issue by Virtual-Josh** [microsoft/botframework-sdk#5607]
This is a ticket to track the implementation and addition of a Message Extension Configuration project to the overarching solution

**Comment by cleemullins** [comment]
Done in JS. Needs to be done in C#.

**Comment by Virtual-Josh** [comment]
Tracked in the dotnet repo. Tracked here:

https://github.com/microsoft/botbuilder-dotnet/issues/2606
