### ISSUE TITLE
Simplify working with Teams messaging extensions

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-sdk#5620]
## Issue
Working with Teams messaging extensions can be quite complex, requiring the developer to create complex nested structures and use specific "magic strings". It is essentially impossible currently to build one from scratch w/o either very deep knowledge of the space, or by starting from a sample (the code is very undiscoverable on its own).

Certain outgoing (from bot to channel) classes/interfaces have magic strings instead of enums (e.g. `MessagingExtensionResult`)

```cs
        /// <summary>
        /// Initializes a new instance of the MessagingExtensionResult class.
        /// </summary>
        /// <param name="attachmentLayout">Hint for how to deal with multiple
        /// attachments. Possible values include: 'list', 'grid'</param>
        /// <param name="type">The type of the result. Possible values include:
        /// 'result', 'auth', 'config', 'message', 'botMessagePreview'</param>
        /// <param name="attachments">(Only when type is result)
        /// Attachments</param>
        /// <param name="text">(Only when type is message) Text</param>
        /// <param name="activityPreview">(Only when type is botMessagePreview)
        /// Message activity to preview</param>
        public MessagingExtensionResult(string attachmentLayout = default(string), string type = default(string), IList<MessagingExtensionAttachment> attachments = default(IList<MessagingExtensionAttachment>), MessagingExtensionSuggestedAction suggestedActions = default(MessagingExtensionSuggestedAction), string text = default(string), Activity activityPreview = default(Activity))
```

## Proposed change
Add response factory to simplify creating nested response structures including their magic strings. We should probably start with a sample and get feedback from the community before moving to the core SDK.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by johnataylor** [comment]
We could consider adding:

    public static class TeamsAttachmentLayout
    {
      public const string List = "list";
      public const string Grid = "grid";
    };

and

    public static class TeamsMessagingExtensionResultType
    {
      public const string Result= "result";
      public const string Auth= "auth";
      public const string Config= "config";
      public const string Message= "message";
      public const string BotMessagePreview= "botMessagePreview";
    };

and the equivalent for the other languages.

**Comment by johnataylor** [comment]
We should also introduce a response factory pattern. The factory would create the appropriate nested structure with the appropriate "type" fields set. It is the multiply nested structure that we found to be excessively complex. This might eliminate some of the need for these constant. It would be best to see this work as part of that exercise.

Moving this issue to R9 and making the title more generic.

**Comment by johnataylor** [comment]
We could introduce the response factory pattern in the samples before we move it into the product.

**Comment by johnataylor** [comment]
We are not tracking this for R9 at this point. Perhaps we could explore the idea further in samples. Or potentially samples/experimental.

**Comment by cleemullins** [comment]
@clearab to make a case for taking this in R11.

**Comment by clearab** [comment]
Closing - this work will eventually be part of composer.
