### ISSUE TITLE
BotBuilder Teams: ME Scenarios should be renamed (minor enhancement)

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-sdk#5621]
## Issue
Messaging Extension Scenarios in [tests/Teams](https://github.com/microsoft/botbuilder-dotnet/tree/master/tests/Teams) should be organized:

- MessagingExtension-Action
- MessagingExtension-ActionNoTask
- MessagingExtension-LinkUnfurling
- MessagingExtension-Search

They're currently organized like this:
![image](https://user-images.githubusercontent.com/14935595/65169184-e34c7180-d9fa-11e9-85ab-871e872af3bf.png)

___

Other Comments:
This is only for [microsoft/botbuilder-dotnet](https://github.com/microsoft/botbuilder-dotnet), since it is the only repo with the scenarios in the master branch.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by cleemullins** [comment]
Not a deliverable.
