### ISSUE TITLE
DCR: Simplified proactive messaging support

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5622]
## Issue
While we provide several proactive messaging examples, today, it's largely left as an exercise for the developer to architect how they'd like to architect proactive support for their bot.  New features like Composer and Skills are adding pressure for the SDK to provide a more turnkey solution to proactive messaging.  Below is a proposal for supporting a relatively simple callback based proactive story that should work for both Composer and Skills. 

## Proposed change
The basic idea is to support the creation of secure callback urls which a Skill or Service can perform an HTTP POST to and raise an event within the context of a given conversation.  For example, a bot hosted at `https://alarmbot.com` can generate a callback url along the lines of ` https://alarmbot.com/notify?token=ENCRYPTED_PAYLOAD` that when posted to raise an `alarmTriggered` event within the context of the conversation that set the alarm.

The `ENCRYPTED_PAYLOAD` would contain the following JSON structure encrypted with the bots AppSecret:

``` JSON
{
     "event": "alarmTriggered",
     "value": {
          "alarmName": "doctors appointment"
     },
     "ref": { conversation-ref },
     "expires": "<optional time the callback expires>"
} 
```

When a service performs posts the above token to `https://alarmbot.com/notify`, the token will be decrypted using the bots AppSecret and then mapped into an activity that looks like this:

``` JSON
{
     "type": "event",
     "name": "alarmTriggered",
     "value": {
          "alarmName":  "doctors appointment"
     },

     /** conversation reference fields **/

}
```

This event activity will be dispatched to the bot as if it was received from channel.

There are a number of ways we could build this into the SDK but I'd propose adding two new methods to the `BotFrameworkAdapter`:

### CreateCallbackEventToken()
This method would create an encrypted token that can be sent to any service and would take the following arguments:

- **conversationRef**: The conversation reference to raise an event for.
- **eventName**: The name of the event to raise.
- **value**: (Optional) value to include with the event.
- **expires**: (Optional) timestamp of when the token should expire.

### ProcessCallbackEventAsync()
This method decrypts an event token and dispatches it to the bot for processing. It would take the following arguments:

- **token**: The encrypted token for the event being raised.
- **value**: (Optional) value that was sent by the service raising the event. This should be a dictionary and will be merged with any value embedded in the token.
- **callback**: The `BotHandlerCallback` for the bots logic to call.
- **cancellationToken**: (Optional) cancellation token. 

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by stevengum** [comment]
@stevenic, is this still necessary?
