### ISSUE TITLE
MessageFactory should be channel aware when rendering responses 

### ISSUE THREAD

**Issue by yochay** [microsoft/botframework-sdk#5623]
## Issue
Scenario: As a developer, I want to send large number of card, displayed in a carousel. I expect the BF to be able to handle channel specific limits and handle any logic needed to send multiple activities to a given channel. For example, Teams has a max number of cards per message of 10 - see https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#card-collections. If I send 20 cards, i expect BF to send two reply, 10 cards each.

## Proposed change
Update MessageFactory to be channel aware and return list of messages 

Looks something like the following:

```
      // Create and send a message.
      List<Activity> messages = MessageFactory.Text(ObjectNameWithManyCards, optional ChannelEnum);
      await context.SendActivity(message);
```

## Component Impact 
Microsoft.Bot.Builder

## Customer Impact 
Address specific customer asks.
This is an additive ask 

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by pavolum** [comment]
We are evaluating this for our next upcoming release, thanks for the request!

**Comment by lauren-mills** [comment]
Removing customer labels since @yochay was on the team at the time of creation.
