### ISSUE TITLE
SSL 500 Error: wrong version number on Self Hostet System with Reverse Proxy

### ISSUE THREAD

**Issue by lucsoft** [microsoft/botframework-sdk#5626]
## Issue
Im using the echo template for NodeJS

My Server is a virtual machine thats on Ubuntu 18 with Node v11.15.0
My local machine thats running Windows 10 with Node v11.15.0

V3 works on my local machine and on the server 

the ssl is working fine and i dont have any problems

Im using a reverse proxy  it forwards the port from 9100 to 443
```
(node:19842) UnhandledPromiseRejectionWarning: Error: Error: write EPROTO 140513096628096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at BotFrameworkAdapter.processActivity (/home/lucsoft/homesys/node_modules/botbuilder/src/botFrameworkAdapter.ts:615:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

(node:19842) UnhandledPromiseRejectionWarning: Error: Error: write EPROTO 140513096628096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at BotFrameworkAdapter.processActivity (/home/lucsoft/homesys/node_modules/botbuilder/src/botFrameworkAdapter.ts:615:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by CoHealer** [comment]
Is there a reason you're using v3 and not v4? v4 is recommended v3 is sun setting some time next year.

**Comment by CoHealer** [comment]
@lucsoft, I've assigned this to @stevkan to assist you shortly.

**Comment by stevkan** [comment]
@lucsoft, I've started trying to recreate your setup to test against. Can you give greater detail or provide code on how you have your reverse proxy setup?

**Comment by stevkan** [comment]
@lucsoft, there needs to be activity in order for the issue to remain open. Are you able to provide info on how you are setting up your reverse proxy?

**Comment by stevkan** [comment]
Closing this issue. Please feel free to re-open if the issue persists and you need continued help.
