### ISSUE TITLE
TranscriptLoggerMiddleware bug investigation

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-sdk#5628]
## Describe the bug
The current JS implementation of handling invoke activities in Teams doesn't create an id for the activity that is sent from the bot. 

This breaks the `FileTranscriptStore` used in the `TranscriptLoggerMiddleware`. (`FileTranscriptStore` uses `activity.id` as the temporary file name before it receives the activity from the service) 

While this bug is already fixed, we need to determine how to test the new Teams code with the already existing code in our libraries.

Potential touch points:
- State management
- Transcripts
- Invoke Handling followed by a Dialog

[bug]

**Comment by cleemullins** [comment]
Middleware bug in the Transcript Logger.

**Comment by cleemullins** [comment]
@jwiley84 Please sync with @stevengum regarding the investigation that needs to happen here.

**Comment by johnataylor** [comment]
It seems OK that Invokes are different in the transcript. Specifically Invokes are just regular HTTP POSTs plumbed into the framework. The outbound activity is just a mockup in the framework world. On the wire it is just an HTTP POST response payload. The id is intrinsically the request id.

So what we need to know is that the transcript code doesn't crash or behavior horribly when we send Invoke activities.

**Comment by stevengum** [comment]
@jwiley84 FYI Issue https://github.com/microsoft/botbuilder-js/issues/1122 and PR https://github.com/microsoft/botbuilder-js/pull/1138 please see if this meets your liking...

**Comment by CoHealer** [comment]
@stevengum & @jwiley84 please sync on this to close out

**Comment by stevengum** [comment]
@CoHealer I'll sync with @jwiley84 today
