### ISSUE TITLE
Missing Doc - What cards are supported on each channel?

### ISSUE THREAD

**Issue by yochay** [microsoft/botframework-sdk#5629]
## Version
All

## Describe the bug
We have a great doc for activity support across channels - https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0 

We do not have a doc describing which cards are supported on which channel. Either append current doc or create a new one. 

[bug]

**Comment by Kaiqb** [comment]
@yochay - we are going to start the investigation in R7, and will wrap up the work in R8.

**Comment by mdrichardson** [comment]
@Kaiqb This is what I have so far. Having trouble adding Kik and GroupMe to my bot for testing.

# Channel Support by Card Type

| Channel | Adaptive Card | Animation Card | Audio Card | Hero Card | Receipt Card | Signin Card | Thumbnail Card | Video Card |
|:-------:|:-------------:|:--------------:|:----------:|:---------:|:------------:|:-----------:|:--------------:|:----------:|
|Cortana|✔|❌|❌|❌|✔|✔|✔|❌|
|Email|🔶|🌐|🌐|✔|✔|✔|✔|🌐|
|Facebook|❌|✔|❌|✔|✔|✔|✔|❌|
|GroupMe|||||||||
|Kik|||||||||
|Line|❌|✔|❌|🌐|✔|✔|✔|✔|
|Microsoft Teams|✔|❌|❌|✔|✔|✔|✔|❌|
|Skype|❌|✔|✔|✔|✔|✔|✔|✔|
|Slack|🔶|✔|🌐|🔶🌐|✔|✔|🌐|🌐|
|Telegram|❌|✔|🌐|✔|✔|✔|✔|✔|
|Twilio|🔶|✔|❌|✔|✔|🌐|✔|❌|
|Web Chat|✔|✔|✔|✔|✔|✔|✔|✔|

*Note: The Direct Line channel technically supports all cards, but it's up to the client to implement them*

* ✔: Full Support
* ❌: No Support
* 🔶: Card is Converted to Image
* 🌐: Card is Converted to Link Unfurl or Text With Links

**Comment by Kaiqb** [comment]
Looks great!

**Comment by youyu16** [comment]
@mdrichardson LINE channel does support herocard, audiocard and also can convert adaptercard to image. do you meet any issue?
![image](https://user-images.githubusercontent.com/17819112/70123126-f7744680-16ac-11ea-922e-19292a084ac0.png)
![image](https://user-images.githubusercontent.com/17819112/70123163-0824bc80-16ad-11ea-8126-2195e2f9a00e.png)
![image](https://user-images.githubusercontent.com/17819112/70123188-12df5180-16ad-11ea-984a-2abb87b39bad.png)

**Comment by mdrichardson** [comment]
@youyu16 I get an error when sending a fairly simple adaptive card with input (below) in both the mobile and desktop apps. I'll mark it as partially supported.

I only don't mark the audio card as fully supported because it won't play in-app, so it works more like a link.

Good call on the Hero card, however. My mistake.

---

```json
{
    "type": "AdaptiveCard",
    "body": [
        {
            "type": "TextBlock",
            "text": "Text Input - id: textInput"
        },
        {
            "type": "Input.Text",
            "placeholder": "Enter some text",
            "id": "textInput"
        },
        {
            "type": "TextBlock",
            "text": "Number Input - id: numberInput"
        },
        {
            "type": "Input.Number",
            "placeholder": "Enter a number",
            "id": "numberInput"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Submit"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}
```

**Comment by Kaiqb** [comment]
Merged the changes into master branch. Live site should have the update in an hour.

**Comment by youyu16** [comment]
@mdrichardson For LINE submit action is partially supported. it is because if card converted to an image, input can't be use, exception throw because get null data when convert submit action to the real channel message.
give it a default data should fix the issue. 
```
"actions": [
    {
      "type": "Action.Submit",
      "title": "Submit",
      "data": {
        "text": “submited text”
      }
    }
  ],
```

**Comment by asp1egui** [comment]
Is the video card still supported on Skype ? the video card works well on webchat but not on Skype. It gives me the service unavailable
