### ISSUE TITLE
retryprompt does not work

### ISSUE THREAD

**Issue by imdat1guy** [microsoft/botframework-sdk#5631]
## Version
v4

## Describe the bug
Bot does not send the retryprompt passed as an option for a promptAsync calls. All my prompts do not reprompt if response is not valid. One example is this attachment prompt:

private async Task<DialogTurnResult> AttachmentsStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            bool attach = (bool)stepContext.Result;

            if (attach)
            {
                return await stepContext.PromptAsync(nameof(AttachmentPrompt), new PromptOptions {Prompt = MessageFactory.Text("Please select all the files you would like to upload"), RetryPrompt = MessageFactory.Text("Sorry I need an attachment") }, cancellationToken);
            }
            else
            {
                return await stepContext.ContinueDialogAsync(cancellationToken);
            }
        }

if an attachment is not sent the RetryPrompt is not sent. The bot does not respond with anything.

**Comment by imdat1guy** [comment]
I found out that sending a typing activity is causing this to happen. Is there a fix for this or do I need to remove the typing activity?

This is the code for sending the typing activity: (This happens in the OnTurnAsync())

Activity a = new Activity { Type = ActivityTypes.Typing };
await turnContext.SendActivityAsync(a);

**Comment by jwiley84** [comment]
Hi @imdat1guy! I see you've also opened this issue [here](https://github.com/microsoft/botbuilder-dotnet/issues/2625). I'm going to close this issue so that we can better track it over there.
