### ISSUE TITLE
DCR: Builtin dialogs

### ISSUE THREAD

**Issue by v-kydela** [microsoft/botframework-sdk#5632]
## Issue
Prompt dialogs are seldom modified before they're added to dialog sets and used. It feels unnecessary to have to construct prompts and add them to dialog sets when there's nothing special about them. You can construct one choice prompt for example and use that one prompt's dialog ID to add it to the stack 5 times in 5 different waterfall steps to ask 5 different questions, because the actual choice prompt object that's added to the dialog stack needn't be different for those different questions. You can see an example of this awkward pattern in [this document](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-dialog-manage-conversation-flow?view=azure-bot-service-4.0&tabs=csharp#create-the-main-dialog):

```c#
AddDialog(new TextPrompt(nameof(TextPrompt)));
AddDialog(new NumberPrompt<int>(nameof(NumberPrompt<int>), AgePromptValidatorAsync));
AddDialog(new ChoicePrompt(nameof(ChoicePrompt)));
AddDialog(new ConfirmPrompt(nameof(ConfirmPrompt)));
```

In v3 you could use the static `PromptDialog` class to call a prompt dialog at the moment you want to use it without worrying about adding it to the dialog set first.

## Proposed change
We could reserve a special dialog ID for each type of prompt, and using that ID to begin a dialog would automatically construct the default prompt of that type. Here are some examples of how the special dialog ID could be referenced:

1. If the special ID is the same as the name of the prompt class, developers could use the same pattern they often use now with the `nameof` keyword (in C#): `dc.PromptAsync(nameof(TextPrompt)...` or `dc.promptAsync('ConfirmPrompt'...` etc.
2. We could make the special ID a constant of each prompt class like `dc.PromptAsync(TextPrompt.Id...` or `dc.promptAsync(ConfirmPrompt.Default...` etc.
3. We could make a new static class to contain all the special ID constants like `dc.PromptAsync(PromptDialog.Text...` or `dc.promptAsync(DefaultPrompt.Confirm...` etc.

If the dialog context's `findDialog` method fails to find the dialog in the dialog set and the ID matches the ID for a builtin dialog then the builtin dialog would be used. This would work whether beginning the dialog or continuing the dialog when a builtin dialog's ID is found on the dialog stack.

## Component Impact 
Only the dialogs library would need to be updated.

## Customer Impact 
Since any dialogs the developer explicitly defines would effectively "overwrite" the builtin dialogs if they have the same ID, this change would not break any existing bots.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by gabog** [comment]
Hi @tomlm, is this applicable now that adaptive is out? Or should we just close it?
