### ISSUE TITLE
Deprecate current CosmodDB classes and patterns

### ISSUE THREAD

**Issue by yochay** [microsoft/botframework-sdk#5634]
## Issue
documentdb v1.x client sdk deprecation and the new partition implementation in the SDK. 

Bot Builder js V4 issue:
https://github.com/microsoft/botbuilder-js/issues/1162

~Bot Builder js V3 issue:
https://github.com/microsoft/BotBuilder-V3/issues/164~

## Proposed change
in 4.6, we're introducing an new way to use CosmosDB and provide specific partition implementation based on keys (@garypretty  can you link to the PR/ items?). To prevent breaking changes, the new partition is an addition to the SDK. 

We need to deprecate the older pattern and use the new partition provider. 

## Component Impact 
CosmodDB state provider across all SDKs
Requires updates for:
- Generators
- Samples
- Docs

## Customer Impact 
Once deprecated, all customers should update to new partition provider. 

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by garypretty** [comment]
@yochay C# PR is merged -> https://github.com/microsoft/botbuilder-dotnet/pull/2613

We need to think about migration, as customers cannot just switch out the providers,  The new provider creates a container with a partition key whereas, in most cases, the existing one does not - therefore the new one will not retrieve data correctly if my understanding is right.

**Comment by EricDahlvang** [comment]
note: Striked through the Bot Builder V3 line  after discussion with @christopheranderson 

Determined that we do not need to take any action for the BBV3 sdk.  Since the CosmosDb support for v1 is ending AFTER the BBV3 support date, this is not something we need to address in the V3 Bot Builder sdk. (The current bits should continue to function for the foreseeable future and customers requesting 'support' will be asked to upgrade to Bot Builder V4.)

**Comment by cleemullins** [comment]
@EricDahlvang  Can you dig into this and figure out what we should do?

**Comment by EricDahlvang** [comment]
@cleemullins If anything, i suppose we could mark CosmosDbStorage as deprecated with a pointer to CosmosDbPartitionedStorage.  But, I think we can just close this issue.

With the addition of the `compatibilityMode` flag, containers created with `CosmosDbStorage` can be used with `CosmosDbPartitionedStorage` (see links below)

For the V3 sdk, we will just be recommending users upgrade to the V4 sdk.

links:
https://github.com/microsoft/botbuilder-js/commit/3635d0aae346e145aeb32ac8f444d3ce6769809d#diff-b08bda4b65d150bd034415c409afac2bR262

https://github.com/microsoft/botbuilder-dotnet/blob/dd34f0a8067750bce06b9f4f79abdc3d82210968/libraries/Microsoft.Bot.Builder.Azure/CosmosDbPartitionedStorage.cs#L289

**Comment by cleemullins** [comment]
I like adding the depreciated / obsolete flag. Could you add that, and let our doc writers know so they can update the docs?
