### ISSUE TITLE
Create telemetry dashboard

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-sdk#5636]
## Feature: Create a reusable telemetry dashboard

Context:
We have a collection of queries (inspired from Dave's repo) that can compromise a re-usable Azure dashboard to ship with the SDK's samples for instance or be made available in the docs as well as in VA.
The foundation of queries can be found here:
* [Queries](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/4b9dbc78-8b15-4d4b-b478-bdce776aca4f/resourceGroups/bfva/providers/microsoft.insights/components/bfva-appinsights/logs)
* [Sample Dashboard](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/dashboard/arm/subscriptions/a76dac98-f63e-4d59-bc59-9a163be24d7e/resourcegroups/dashboards/providers/microsoft.portal/dashboards/7bfbfd4c-ebe9-49de-aa5f-6ac8ca135383)

Work required:
1. Cleanup and generalize dashboard so that it can be re-used easily by any customer (dev resource)
2. Develop accompanying documentation including (pm/docs)
  * Install/deploy information
  * Interpretation analysis

**Comment by garypretty** [comment]
@scheyal I am happy to help with the developer resource required here. I have been working on other telemetry enhancements recently and worked with the dashboard from solutions when I was external. Ill assign to myself so I can track, but happy for others to jump in too.

**Comment by garypretty** [comment]
@scheyal The links above are not working for me, are they still live for you?

**Comment by garypretty** [comment]
Issue #5233 is tracking the creation of the ARM template and MVP dashboard.

**Comment by garypretty** [comment]
MVP dashboard content agreed with @emivers8. Outstanding actions to release;
- @emivers8 looking to provide updates for text descriptions on the dashboard
- @garypretty to update ARM template

**Comment by gabog** [comment]
@garypretty, can this be closed? or you are still working on it?

**Comment by garypretty** [comment]
@gabog Still working on it - should be closed within the next few weeks. Just finalising.

**Comment by garypretty** [comment]
Closing this.  Separate analytics stream currently in planning which will encompass this work.
