### ISSUE TITLE
Bot Framework Deploy issue

### ISSUE THREAD

**Issue by puyu2010** [microsoft/botframework-sdk#5638]
I have created a AppId for my local bot. And deploy it to Azure. But after my test, I found some issue below. When I test my local bot on Bot Framework Emulator, it works well. But when I fill in AppId and password in appsettings, it cannot work will information below. 

![图片](https://user-images.githubusercontent.com/13258796/66409293-f9aa8380-ea22-11e9-84ac-95daa885899b.png)
![图片](https://user-images.githubusercontent.com/13258796/66409474-370f1100-ea23-11e9-8b2b-7e67bd878aed.png)

And when I test it in Web Chat, it appear error as below:

There was an error sending this message to your bot: HTTP status code InternalServerError

Can anyone please help me to solve this issue, and tell me why does this issue happen ? Great Thanks for your help.

**Comment by dmvtech** [comment]
How did you create the Bot and AppID? Does the app ID match the application here:
https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade ?

With the Emulator, you should be able to:

1. Have MicrosoftAppId and MicrosoftAppPassword be blank in appsettings, and not supply them when the emulator connects, or
2. Supply MicrosoftAppId and MicrosoftAppPassword n appsettings, and then supply them when emulator connects.

Is that the behavior you are seeing with emulator? 

With your deployed bot, is it hosted in azure as an App Service? Or do you just have a bot registration pointing to the bot endpoint elsewhere?

**Comment by puyu2010** [comment]
Greate Thanks for your help. My answer is as below: 

1. I create Appid and password by cmd in Azure as below, which I learned from spec. And I can see it from link you provide. 
az ad app create --display-name "displayName" --password "AtLeastSixteenCharacters_0" --available-to-other-tenants

Then create bot with command below:
az deployment create --name "<name-of-deployment>" --template-file "template-with-new-rg.json" --location "location-name" --parameters appId="<msa-app-guid>" appSecret="<msa-app-password>" botId="<id-or-name-of-bot>" botSku=F0 newAppServicePlanName="<name-of-app-service-plan>" newWebAppName="<name-of-web-app>" groupName="<new-group-name>" groupLocation="<location>" newAppServicePlanLocation="<location>"

2. For Emulator, when I set AppId and AppPassword with empty, my bot can work as my expected. But when I supply it in appsettings, it will not work and told me "Cannot post activity. Unauthorized.", which is same with the screenshot in my question. 

After I deployed my bot, I can see 3 resources in my Azure, which is as below. And I can see App Service, Bot Registration Channel and Resource Group in it. 
![图片](https://user-images.githubusercontent.com/13258796/66485232-0ab6cb80-eadb-11e9-9162-f545a7f9b549.png)

**Comment by dmvtech** [comment]
Just to confirm, did you also run the commands:

`az bot prepare-deploy`
and then zip up your project, and then:
`az webapp deployment source config-zip`

If you are using the appsettings to have the appid/password, you will have to re-zip and re-run `az web app deployment`

Alternately, you can add/ensure you have two Application Settings (`MicrosoftAppId `and `MicrosoftAppPassword`) set in your App Service's Configuration:

![image](https://user-images.githubusercontent.com/43397658/66509180-5cce0180-ea87-11e9-9935-812c5370c986.png)

**Comment by dmvtech** [comment]
You can also try opening your log stream for the app service and see what you see during the attempt to connect. See here for more info:
https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs

**Comment by puyu2010** [comment]
Great for your help. For your first reply, I deploy my bot in Visual Studio, not cmd. You can see as below.
![图片](https://user-images.githubusercontent.com/13258796/66585365-42944080-ebb9-11e9-8520-8fe3f63ca6bf.png)

And for add log stream, I think maybe some bug I found in it. In screenshot, we can see it is because Invalid client secret. But I think I don't forget it. But anyway, I reset it in AppId Manage, and update in my code, and deploy it again. But when I run my bot in Web Chat, same bug still occur. Can you help me to check why does this happen. Thank you.
![图片](https://user-images.githubusercontent.com/13258796/66585323-36a87e80-ebb9-11e9-9081-e89f1132eb9d.png)
![图片](https://user-images.githubusercontent.com/13258796/66585623-c0f0e280-ebb9-11e9-8cc9-58cbc7b79c42.png)

**Comment by dmvtech** [comment]
Ok, thank you.

So after creating a new client secret, you copied that value to the appsettings.json, then republished and it is _still_ failing?

**_If_** that is the case, can you try adding it as a Application Setting in the App Service's configuration? (again, you will need both MicrosoftAppId and MicrosoftAppPassword)

**Comment by puyu2010** [comment]
Great Thanks for your help. As default, deploy slot setting is not selected. After I set it, my bot work as my expected. Thank you very much.

**Comment by puyu2010** [comment]
![image](https://user-images.githubusercontent.com/13258796/66663354-278b0480-ec7d-11e9-8d9a-4d30e5edd850.png)
