### ISSUE TITLE
No effective tools available to debug simple Bot Framework Errors in an Enterprise Environment

### ISSUE THREAD

**Issue by archmangler** [microsoft/botframework-sdk#5640]
Hi, I've deployed a chatbot to azure via ARM templates and am trying to communicate with it via the web chat window in the portal.

In the channels interface I see the following error:

“There was an error sending this message to your bot: HTTP status code InternalServerError”

Looking for logs or diagnostics in the portal turns up nothing.

The ngrok tool is recommended for debugging but it's pretty useless as it cannot be used in any kind of secure corporate environment.

Please recommend an effective method of debugging azure bot service in this scenarion ?

**Comment by EricDahlvang** [comment]
Hello @archmangler

Application insights might be helpful: https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net

This doc has some other tips for tracking down 500 errors: 

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-troubleshoot-500-errors

**Comment by CoHealer** [comment]
Closing as resolved
