### ISSUE TITLE
[AZ CLI] Slack Channel Creation Needs to Take in Signing Secret

### ISSUE THREAD

**Issue by mdrichardson** [microsoft/botframework-sdk#5647]
## Issue
When using the AZ CLI to add the Slack Channel to a Web App in Azure, the channel doesn't really add itself. It requires going through the Slack OAuth flow before actually registering and validating in Azure.

See line 86 in [SlackChannel/SettingsController](https://dev.azure.com/FuseLabs/_git/Intercom?path=%2FChannels%2FSlackChannel%2FSlackChannel%2FControllers%2FSettingsController.cs&version=GBmaster) in the Intercom repo (internal only)

This is currently blocking [connector nightly functional tests](https://github.com/microsoft/botframework-sdk/issues/5442#issuecomment-543316221)

## Proposed change

Allow `az bot slack create ... --signing-secret *******`

If present, send it and `registerBeforeOauthFlow: true`

**Note: The Signing Secret comes from the Slack App settings**

## Discussion

Should this be a required parameter? In my own testing, there isn't a link or anything that pops up in Azure Portal to go through the OAuth flow and the Slack channel is sort of...frozen. I think we should either:

1. Make it a required parameter, or
2. When not included, open a link for the user to start the OAuth flow (it's returned in the HTTP request when successful) -- or at least make the link **very** apparent

## Component Impact 

* https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/botservice/channel_operations.py#L135
* https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/botservice/azure-mgmt-botservice/azure/mgmt/botservice/models/slack_channel_properties.py#L47
* https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/botservice/azure-mgmt-botservice/azure/mgmt/botservice/models/slack_channel_properties_py3.py#L47

## Specific Changes to slack_channel_properties_py(3)

I believe those files need to end up with these changes:

```diff
_validation = {
    'client_id': {'required': True},
    'client_secret': {'required': True},
    'verification_token': {'required': True},
    'redirect_action': {'readonly': True},
    'last_submission_id': {'readonly': True},
    'register_before_oauth_flow': {'required': True},
    'is_validated': {'readonly': True},
    'is_enabled': {'required': True},
+   'signing_secret': {'readonly': True}
}

_attribute_map = {
    'client_id': {'key': 'clientId', 'type': 'str'},
    'client_secret': {'key': 'clientSecret', 'type': 'str'},
    'verification_token': {'key': 'verificationToken', 'type': 'str'},
    'landing_page_url': {'key': 'landingPageUrl', 'type': 'str'},
    'redirect_action': {'key': 'redirectAction', 'type': 'str'},
    'last_submission_id': {'key': 'lastSubmissionId', 'type': 'str'},
    'register_before_oauth_flow': {'key': 'registerBeforeOAuthFlow', 'type': 'bool'},
    'is_validated': {'key': 'isValidated', 'type': 'bool'},
    'is_enabled': {'key': 'isEnabled', 'type': 'bool'},
+   'signing_secret': {'key': 'signingSecret', 'type': 'str'}
}

def __init__(self, **kwargs):
    super(SlackChannelProperties, self).__init__(**kwargs)
    self.client_id = kwargs.get('client_id', None)
    self.client_secret = kwargs.get('client_secret', None)
    self.verification_token = kwargs.get('verification_token', None)
    self.landing_page_url = kwargs.get('landing_page_url', None)
    self.redirect_action = None
    self.last_submission_id = None
-   self.register_before_oauth_flow = None
+   self.register_before_oauth_flow = kwargs.get('register_before_oauth_flow', False)
    self.is_validated = None
-   self.is_enabled = kwargs.get('is_enabled', None)
+   self.is_enabled = kwargs.get('is_enabled', None),
+   self.signing_secret = kwargs.get('signing_secret', None)
```

## Customer Impact 

No backwards-compat issues. Would allow customers to actually add the Slack Channel, programmatically.

## Tracking Status

- [ ] Decision made on whether param is required or not

**Tools**
- [X] [PR](https://github.com/Azure/azure-cli/pull/10930/)
- [ ] Merged

**Swagger Files** (referencing the last two links above)
- [ ] PR
- [ ] Merged

[dcr]

**Comment by mdrichardson** [comment]
@swagatmishra2007 [PR is in for the AZ CLI portion of this](https://github.com/Azure/azure-cli/pull/10930/). I think we just need the swagger/ARM stuff on your end. Let me know if I can do anything further to help.

**Comment by stevengum** [comment]
@mdrichardson, once the Resource Provider support is in, can you add unit tests to your PR? If you need help let me know!

**Comment by mdrichardson** [comment]
Closes since [parent PR](https://github.com/microsoft/botframework-sdk/issues/5442#issuecomment-543316221) is closed.
