### ISSUE TITLE
Bot: There was an error sending this message to your bot: HTTP status code GatewayTimeout

### ISSUE THREAD

**Issue by Amokstakov** [microsoft/botframework-sdk#5663]
I am attempting to integrate SDK4.0 Bot Framework into Web Chat Channel.

Everything seems to be running smoothly- dot was deployed onto Azure from local environment and is testing properly.

Issue is when integrating it into the actual website via web chat channel. 
Following this source:
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-webchat?view=azure-bot-service-4.0

but receiving the following errors:
<img width="660" alt="Capture" src="https://user-images.githubusercontent.com/53410236/67961796-913e6480-fbd2-11e9-95bb-8bbdaaec9090.PNG">
Any help would be very helpful.

Thank you,
-

**Comment by Amokstakov** [comment]
Any help? ~{bump}

**Comment by mdrichardson** [comment]
I can help with this, but need some additional information:

1. Does "Test in Web Chat" work from `Azure Portal > Your Resource Group > Your Web App Bot/Bot Channels Registration > Test in Web Chat`?
2. What is your `MicrosoftAppId`?
3. Can you share the full HTML that you're using to implement WebChat (minus your secret)?

**Comment by CoHealer** [comment]
@Amokstakov do you still require assistance or should we consider the issue resolved?

**Comment by Amokstakov** [comment]
Hi Sorry - 
1) It works through Test yes
2) My app Id exists and I have it
3) the Iframe I am using:
<iframe src='https://webchat.botframework.com/embed/SECRET INFO'  style={{minWidth: '400px', width: '100%', minHeight: '500px'}}></iframe>

So as an update I have actually put it in the Website

however my NEW ISSUE UPDATE:
I can see the chatbot, and I can interact with it. However, it doesn't show the Welcome Message.
It only starts working when I send a message initially like "Hey".

When I see it embedded in the website, it is just chatbox. And It doesn't start until a message is prompted by the user, but I do have a onMembersAdded handler in my code, and in the Testing Site on Azure it shows up when I go on the Testing channel. 

Any help?

**Comment by mdrichardson** [comment]
We've got a few issues to handle here:

1. If you would like me to troubleshoot things on the backend, I'll need to know your appId.
2. The iframe version of WebChat isn't updated to the latest version of WebChat for most people and can often cause issues. [See here for more info](https://github.com/microsoft/BotFramework-WebChat/blob/5bf82c32f6da5773e33e9de701775f3c19902bea/packages/embed/README.md#what-version-of-web-chat-am-i-using-on-my-site).
3. Not all channels send a `conversationUpdate` (which triggers welcome messages), including WebChat. However, [one of the samples shows you how to force the welcome message to be sent](https://github.com/microsoft/BotFramework-WebChat/tree/b0c803e5722bd8859b5891c6165d55aa8405ed96/samples/15.d.backchannel-send-welcome-event)

**Comment by Amokstakov** [comment]
> We've got a few issues to handle here:
> 
> 1. If you would like me to troubleshoot things on the backend, I'll need to know your appId.
> 2. The `iframe` version of WebChat isn't updated to the latest version of WebChat for most people and can often cause issues. [See here for more info](https://github.com/microsoft/BotFramework-WebChat/blob/5bf82c32f6da5773e33e9de701775f3c19902bea/packages/embed/README.md#what-version-of-web-chat-am-i-using-on-my-site).
> 3. Not all channels send a `conversationUpdate` (which triggers welcome messages), including WebChat. However, [one of the samples shows you how to force the welcome message to be sent](https://github.com/microsoft/BotFramework-WebChat/tree/b0c803e5722bd8859b5891c6165d55aa8405ed96/samples/15.d.backchannel-send-welcome-event)

Hi!
Thanks for the help.

1)206ea021-b5f1-4cef-a275-29a6dfc61706
2) This was good to know - thank you
3) I have seen example ChatBots created where once it is integrated into the website, whenever someone opens it - it begins dialog/welcome message.

Here is an example:
https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/12.customization-minimizable-web-chat

^ in the above example, I attempted to git clone it and look at the code, to see if i can just replace it with my personal iframe but I could not see that tag anywhere in the script

**Comment by mdrichardson** [comment]
@Amokstakov Regarding your point #3...they likely did what I included in my point #3. Regarding that example, you don't copy/paste your iframe code over the sample's (which doesn't exist). [Its README tells you where to put your Secret](https://github.com/microsoft/BotFramework-WebChat/blob/master/samples/12.customization-minimizable-web-chat/README.md#L86). I don't recommend starting with that sample, though, as it's fairly complex. [Sample 1](https://github.com/microsoft/BotFramework-WebChat/tree/master/samples/01.a.getting-started-full-bundle) is pretty easy. You can just replace (in `index.html`):

```diff
- const { token } = await res.json();
+ const token = '<yourWebChatSecret>';
```

However, as the README states:

> It is never recommended to put the Direct Line secret in the browser or client app. To learn more about secrets and tokens for Direct Line, visit [this tutorial on authentication](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication).

**Comment by Amokstakov** [comment]
@mdrichardson 
This did not fix my issue - I am not sure why it is closed

**Comment by mdrichardson** [comment]
@Amokstakov What is your issue, now? By implementing everything I suggested, it will fix all of your issues.

**Comment by Amokstakov** [comment]
@mdrichardson 

my issue is that when I integrate my chatbot into my web chat (website) via Iframe or Direct Secrety, the ChatBot does not work until a user sends a message in the chatbot.

In the Azure Portal, when inside the Test Channel the ChatBot automatically sends the expected welcome message when it realizes a user is there, not needing the user to send an initial message.

But even now, when I did what you suggested via Sample 1, and I go to my Local Host where it is running, it is just a blank screen. I expect it to send the welcome message, as it does in my Test Channel on Azure.

It only starts working when I send an initial message

**Comment by Amokstakov** [comment]
<img width="955" alt="screen_shot" src="https://user-images.githubusercontent.com/53410236/68327803-09f26480-009c-11ea-8d0e-9f8e5f36bf0f.PNG">

Please see attached images. The one above is what I see in any instance of when the ChatBot is integrated,

and the second image below is how it reacts after i send a message. The first two "Welcome.." is expected to be prompted right when the user triggers the Chat.

<img width="958" alt="screen_shot_2" src="https://user-images.githubusercontent.com/53410236/68327904-3a3a0300-009c-11ea-9260-fd7668a12c61.PNG">

**Comment by mdrichardson** [comment]
You may have just missed [this comment](https://github.com/microsoft/botframework-sdk/issues/5663#issuecomment-550096199), then:

> Not all channels send a conversationUpdate (which triggers welcome messages), including WebChat. However, [one of the samples shows you how to force the welcome message to be sent](https://github.com/microsoft/BotFramework-WebChat/tree/b0c803e5722bd8859b5891c6165d55aa8405ed96/samples/15.d.backchannel-send-welcome-event)

**Comment by Amokstakov** [comment]
Hi,

I just implemented that same sample and switched the code and still same issue:

see attached. The only difference is now I see a "Channel-Data" on the bottom.

<img width="955" alt="screen_shot_3" src="https://user-images.githubusercontent.com/53410236/68328290-feec0400-009c-11ea-867e-b7b7d290018e.PNG">

**Comment by mdrichardson** [comment]
Please copy/paste your index.html (remove your secret, first)

**Comment by Amokstakov** [comment]
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Web Chat: Inject data on post activity</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    
    <script src="https://cdn.botframework.com/botframework-webchat/latest/webchat.js"></script>

    
    <script src="https://unpkg.com/simple-update-in/dist/simple-update-in.production.min.js"></script>
    <style>
      html,
      body {
        height: 100%;
      }
      body {
        margin: 0;
      }

      #webchat {
        height: 100%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="webchat" role="main"></div>
    <script>
      (async function() {
        // In this demo, we are using Direct Line token from MockBot.
        // Your client code must provide either a secret or a token to talk to your bot.
        // Tokens are more secure. To learn about the differences between secrets and tokens
        // and to understand the risks associated with using secrets, visit https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-authentication?view=azure-bot-service-4.0

        const res = await fetch('https://webchat-mockbot.azurewebsites.net/directline/token', { method: 'POST' });
        const token  = 'SECRET';

        // We are adding a new middleware to customize the behavior of DIRECT_LINE/POST_ACTIVITY.
        const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
          if (action.type === 'DIRECT_LINE/POST_ACTIVITY') {
            // The channelData submitted here is very similar to HTTP cookies and vulnerable to forgery attack.
            // Make sure you use signature to protect it and verify the signature on the bot side.

            // To minimize unexpected behaviors, we recommend to treat the "action" object as if it is immutable.
            // We use simple-update-in package to update "action" with partial deep cloning.
            action = window.simpleUpdateIn(
              action,
              ['payload', 'activity', 'channelData', 'email'],
              () => 'johndoe@example.com'
            );
          }

          return next(action);
        });

        window.WebChat.renderWebChat(
          {
            directLine: window.WebChat.createDirectLine({ token }),
            // We will use a custom version of Redux store, which we added middleware to handle backchannel messages.
            store
          },
          document.getElementById('webchat')
        );

        store.dispatch({
          type: 'WEB_CHAT/SET_SEND_BOX',
          payload: { text: 'channel-data' }
        });

        document.querySelector('#webchat > *').focus();
      })().catch(err => console.error(err));
    </script>
  </body>
</html>

**Comment by Amokstakov** [comment]
BTW,

Here is a sample of what is happening in my Test channel.
These messages happen automatically 
<img width="434" alt="screen_shot_4" src="https://user-images.githubusercontent.com/53410236/68329507-5ee3aa00-009f-11ea-922e-f460975301f2.PNG">

**Comment by mdrichardson** [comment]
I think you may have gotten your samples mixed up for the welcome message. You should be using [this](https://github.com/microsoft/BotFramework-WebChat/tree/b0c803e5722bd8859b5891c6165d55aa8405ed96/samples/15.d.backchannel-send-welcome-event#completed-code):

```js
const store = window.WebChat.createStore({}, ({ dispatch }) => next => action => {
    if (action.type === 'DIRECT_LINE/CONNECT_FULFILLED') {
      // When we receive DIRECT_LINE/CONNECT_FULFILLED action, we will send an event activity using WEB_CHAT/SEND_EVENT
      dispatch({
        type: 'WEB_CHAT/SEND_EVENT',
        payload: {
          name: 'webchat/join',
          value: { language: window.navigator.language }
        }
      });
    }

[...]

window.WebChat.renderWebChat({
    directLine: window.WebChat.createDirectLine({ token }),
    store
    }, document.getElementById('webchat'));
    document.querySelector('#webchat > *').focus();
})().catch(err => console.error(err));
```

**Comment by Amokstakov** [comment]
@mdrichardson 
Thank you for the incredible help and work. Worth all appraisal for this.
resolved and fixed.

Best!

**Comment by mdrichardson** [comment]
😁 Glad you got it working! And I understand your confusion:

1. "Test in Web Chat" and Emulator don't always operate like the `iframe` (this will be fixed as the updated iframe code starts rolling out to everybody)
2. There are *a lot* of Web Chat samples

**Comment by JeSami** [comment]
Hi,

I am facing similar issue. I have created a bot using Python and tested successfully locally but after deploying to azure I am not getting any response from bot in Web Chat.

BDW - i went through the discussion on this thread but i still did not get where exactly to modify the code.

Appreciate for any help on this.

**Comment by mdrichardson** [comment]
@JeSami I've only ever see this happen if somebody didn't follow [the deployment docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp) *exactly*. I recommend re-deploying, starting from the top. Common hangups are:

1. Not using a password that meets the requirements: 16 characters long, contain at least 1 upper or lower case alphabetical character, and contain at least 1 special character.
2. Missing the last step and not actually deploying.
3. Zipping up their files incorrectly. The file tree should look like this:

```
/code.zip
--app.py
--requirements.txt
--...
```

and not like this:

```
/code.zip
--/myBot
----app.py
----requirements.txt
----...
```

If you still can't get this to work, please open a new issue with what you've tried.

**Comment by JeSami** [comment]
@mdrichardson thank you so much for your great help. Previously my folder structure was incorrect for zipping. Now this is resolved. I can happily chat with my first web chatbot :)

**Comment by prafuldhone** [comment]
Hi Team,

I am publishing the Bot from Composer. It is getting published properly from Composer. But I am not able to run it on Web APP Bot on Azure Portal:
Mostly I am getting this error:
There was an error sending this message to your bot: HTTP status code GatewayTimeout

Sometimes I do get this error:
There was an error sending this message to your bot: HTTP status code InternalServerError

Please note, I have added appropriate AppID and Password by getting it from APP Service from Azure. 
Second thing, it is properly running on Composer. 

Can someone quickly help me here?

**Comment by z1net** [comment]
@prafuldhone i have this problem too, did u fix it?
