### ISSUE TITLE
[Azure CLI] Take us out of preview

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-sdk#5667]
The code base is mature and ready. If we are still not confident about certain commands or command groups of the Azure CLI, they should **individually** be marked as preview.

`az bot` is here to stay, so it's time to move out of "preview".

**Comment by cleemullins** [comment]
PR is out, per @stevengum.

**Comment by stevengum** [comment]
Closed via Azure/azure-cli#11318.
