### ISSUE TITLE
ChatBot embedded on Website does not prompt Welcome Message

### ISSUE THREAD

**Issue by Amokstakov** [microsoft/botframework-sdk#5668]
Hi all,

quick question regarding ChatBot. 
I have it embedded into my website via Iframe.
I have developed it with onMembersAdded handler, which works accordingly on Emulator and Test Channel.

However, it does not seem to work when it is embedded. That Chatbot never sends a welcome message, only waits until user sends an initial message then it responds, instead of clicking within the chat window and beginning with a welcome message.

Any Help?

**Comment by mdrichardson** [comment]
Closing, since we covered this [here](https://github.com/microsoft/botframework-sdk/issues/5663#issuecomment-550096199)
