### ISSUE TITLE
AZ CLI: Remove --version flag from az bot create

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-sdk#5669]
## Information:
* Tools Libraries: Azure CLI

## Issue Description:
Remove `--version` from az bot create (users are only able to create v4 bots with the latest CLI so the flag doesn't add value)

The flag was originally left for future proofing for v5, but since there is no timeline for that, it's not necessary.

**Comment by stevengum** [comment]
This will go out in R7.

**Comment by cleemullins** [comment]
IN PR, tests are passing (per @stevengum )

**Comment by stevengum** [comment]
Closed via Azure/azure-cli#11318.
