### ISSUE TITLE
Directline API is failing with 403 and Site disabled message

### ISSUE THREAD

**Issue by Sakshams** [microsoft/botframework-sdk#5672]
API calls to :
https://directline.botframework.com/v3/directline/conversations   and 
https://directline.botframework.com/v3/directline/tokens/generate have suddenly started failing.

It was all working fine till yesterday and have started failing now.

**Comment by Sakshams** [comment]
There was no change in Secret Key from our end. Is there a status page for Directline API Health.

**Comment by sgellock** [comment]
@Sakshams there was a partial Azure outage on Friday which caused service disruption.  This was resolved later in the afternoon, Seattle time.  service availability has been restored.
