### ISSUE TITLE
Embed Bot repeats question after every answer

### ISSUE THREAD

**Issue by Nitin2392** [microsoft/botframework-sdk#5674]
We have an enterprise bot framework codebase set up in .NET and hosted on Azure. There are multiple embed chatbots conversing with the above deployed instance. 

There was an issue recently reported from one our users that questions were being repeated after the answers like so: 

![image](https://user-images.githubusercontent.com/3441046/68618219-dbf39280-0496-11ea-8a9e-624944ebe85c.png)

The above embed bots obtain the DirectLine token in exchange for a secret. The architecture for that API was similar to what is mentioned in this document - https://blog.botframework.com/2018/09/25/enhanced-direct-line-authentication-features/

I tried setting up another independent bot that referenced the same endpoint and I found out that the issue was happening with the way we setup the `user` object in the body of the POST request to the directline token generate endpoint - `POST https://directline.botframework.com/v3/directline/tokens/generate`

What we had initially was like so : 

```js
user: { 
  id: $"dl_{GUID.NewGUID()}"
}
```

I tried changing it to 

```js
user: { 
  id: "someRandomName@enterprise.com"
}
```

..and the issue stopped presenting itself. 

I looked through the DirectLine documentation to see if any changes have been made to the API but it doesn't look like there are any. I would appreciate it if someone is able to provide some clarity on why this issue is suddenly happening and how the fix I added seems to work?

**Comment by v-kydela** [comment]
Hi @Nitin2392 - When you said "embed chatbot," do you mean a Direct Line client UI that's embedded in your website?

The issue appears to be that your client polls the Direct Line activities endpoint and interprets an old message sent by the user as a new message sent by the bot. It will be hard to diagnose the problem more specifically without seeing your client code, but would you go ahead and try calling the [Get Activities](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-api-reference?view=azure-bot-service-4.0#get-activities) API for an affected conversation so you can see if the user's question actually exists as a duplicated activity? If it is duplicated then it could be a problem with the bot, and if it's not duplicated then it's probably a problem with the client.

**Comment by v-kydela** [comment]
@Nitin2392 - Are you still working on this?

**Comment by Nitin2392** [comment]
Hey @v-kydela. I apologize for not following up on this. I was pulled into a few other important things. 

To answer your question -> yes, the "embed chatbot" is a Direct Line Client UI that's embedded in one of our websites. 

I tried calling the Get Activities API with one of the conversationId but I keep getting an error response (though I am using a conversationId that was generated via the di - 

```
{
  "error": {
    "code": "BadArgument",
    "message": "Unknown conversation"
  }
}
```

**Comment by Nitin2392** [comment]
Also, it seems like the issue is happening when I generate the DirectLineToken. It works perfectly fine when I generate the token - POST @ `https://directline.botframework.com/v3/directline/tokens/generate` with the body have a `user: { id: }` marked to a legit enterprise ID while the repeating of question happens when I mark it with a GUID for instance. 

I don't sense a code smell here because 1) This code has been in place for over a year now without any major changes and works perfectly fine in an another environment we have. 
2) The bot works perfectly fine when I generate the token with a valid enterprise ID but throws this issue up when I generate the token with a different userId

**Comment by v-kydela** [comment]
@Nitin2392 - That's very strange. I do notice something odd about the way you're providing the user ID:

``` js
user: { 
  id: $"dl_{GUID.NewGUID()}"
}
```

You're using C# string interpolation in a JavaScript object. This will surely throw an error, since JavaScript won't know how to interpret that dollar sign. Can you explain what you're doing here?

**Comment by v-kydela** [comment]
@Nitin2392 - Are you still working on this?

Possibly related: https://stackoverflow.com/questions/59060524/bot-duplicates-user-messages-when-i-use-directline-channel

**Comment by Nitin2392** [comment]
@v-kydela The code snippet I shared was from a C# source, not JavaScript so the interpolation works fine.

**Comment by v-kydela** [comment]
@Nitin2392 - This is not valid C#:

```
user: { 
  id: $"dl_{GUID.NewGUID()}"
}
```

Perhaps it will make sense if I see the code around it. Can you please provide some more context?

**Comment by Nitin2392** [comment]
@v-kydela  My bad. I didn't mean to indicate the exact code. I was referring more to the pseudocode. 

Here's a quick snippet of how I create the DirectLineToken. It's a WebAPI 

```
if (authorizationFromHeader!=null && authorizationFromHeader.Equals(HelperService.GetDirectLineAuthHeader()))
                {
                    var secret = HelperService.GetDirectLineSecret();
                    DirectLineToken returnDirectLineTokenObject = new DirectLineToken();

                    HttpClient client = new HttpClient();

                    HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, HelperService.GetDirectLineTokenEndpoint());

                    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", secret);

                    request.Content = new StringContent(JsonConvert.SerializeObject(
                            new {
                                User = new
                                {
                                    Id = string.IsNullOrEmpty(userId)
                                        ? "userUnknown"
                                        : userId
                                }
                            }), Encoding.UTF8, "application/json");

                    var response = await client.SendAsync(request);

                    if (response.IsSuccessStatusCode)
                    {
                        var body = await response.Content.ReadAsStringAsync();
                        returnDirectLineTokenObject = JsonConvert.DeserializeObject<DirectLineToken>(body);
                    }

                    return returnDirectLineTokenObject;
                }
```

**Comment by Nitin2392** [comment]
Here, `userId` is passed as a queryParam to the API call. If I set it to some random id, the token generated causes the question to repeat after the answer. If we, however, send a valid enterprise id (say - `v-kydela@microsoft.com`), it works perfectly

**Comment by v-kydela** [comment]
@Nitin2392 - I've looked into the Direct Line source code and I've discovered that there is a case when a user ID will behave differently when not prefixed by `dl_`, but the difference is that the API call will throw a 400 error. This only happens when Direct Line recognizes your site as secure, but can you check anyway to see if the `tokens/generate` endpoint is returning an error code? You haven't posted much code, so perhaps your code is handling errors in such a way that it uses a fallback that fixes your problem.

Also, you still need to provide that Get Activities check. If you can't call Get Activities then how is your client doing it? And if your client isn't calling the Get Activities API then how is it having a conversation with a bot?

**Comment by Nitin2392** [comment]
In my case though, I am not sending a `dl_` userId and yet receive a token that behaves properly. And no, there is no additional error handling we are doing. We just use the DL Token returned to start a conversation with the bot. 

I'll try the `GetActivities` API again and update this thread.

**Comment by Nitin2392** [comment]
@v-kydela @anusharavindrar  - I am closing this issue for now. I'm planning to inspect the entire conversation flow and identify potential hotspots which might lead to the issue since you've mentioned that the `userId` value shouldn't matter. 

I'll update this thread if something comes up. Thank you for your assistance. Appreciate the help.
