### ISSUE TITLE
Scenario: Opinion Polling

### ISSUE THREAD

**Issue by AdamSobieski** [microsoft/botframework-sdk#5675]
## Introduction
I would like to describe an important scenario for the Microsoft Bot Framework SDK: virtual opinion pollsters. I would also like to share these ideas with the bot developer community.

While implementing virtual opinion pollsters may be possible with the current version of the Microsoft Bot Framework SDK, I would like to request features for and support for the scenario.

## Virtual Opinion Pollsters
A virtual opinion pollster is a dialogue system or bot which conducts opinion polling interviews and collects resultant data. Virtual opinion pollsters can utilize numerous communication channels to connect with arbitrarily large numbers of individual respondents.

Additionally, intelligent virtual assistants (e.g. Alexa, Cortana, Google Assistant, and Siri) are extensible. Software developers can extend their capabilities by creating skills. Intelligent virtual assistants can be virtual opinion pollsters.

## Dialogue-based Opinion Polling
Opinion polls can be envisioned which vary based upon participants’ responses. In these regards, dialogues with virtual opinion pollsters can be natural, aesthetic and coherent.

Beyond lists of questions, opinion polls could be authored as trees or graphs of questions.

## The Computer-aided Authoring and Evaluation of Opinion Polls
Software systems can process questionnaires, dialogues and interview transcripts to detect questionnaire construction issues, question sequence issues, question wording issues, and other issues.

Personnel could make use of such software to ensure that dialogues are designed and unfold in accordance with the best practices of questionnaire construction and survey methodology.

## Scheduling Opinion Polls
Opinion polls can be described as opening and closing at certain times and as being open for certain durations. Software systems can schedule opinion poll participation with arbitrarily large numbers of respondents. Interoperability with calendaring software is envisioned.

With each individual respondent able to easily schedule and reschedule the times of their opinion poll interviews with virtual opinion pollsters, a greater overall participation can be expected.

## Conclusion
Opinion polls can be conducted by virtual opinion pollsters. Dialogue-based opinion polling can be conducted across a variety of communication channels. Opinion polls can be scheduled with arbitrarily large numbers of individual respondents.

By providing these new and emerging technologies to opinion polling and journalistic organizations, enfranchisement and participation can be broadened with respect to the democratic processes of cities, states and nations.

**Comment by EricDahlvang** [comment]
Hi @AdamSobieski 

This is a great idea!  Bots are definitely well suited for opinion polls.  Polly is a great example: https://www.polly.ai/microsoft-teams  It is built on the Microsoft Bot Framework.  The Samples repository also provides a rudimentary example of how to create a poll in a Messaging Extension: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/53.teams-messaging-extensions-action-preview

Other than samples and examples such as this, what specifically do you envision would be useful for the sdk to provide towards enabling developers to write opinion polls in bots?

**Comment by AdamSobieski** [comment]
Thank you for sharing the example and sample. It appears that software built on the Microsoft Bot Framework SDK, such as [Polly](https://www.polly.ai/), are ready to scale to provide surveys for cities, states and nations.

For purposes of discussion, some brainstorming:

## Authoring Surveys

Beyond designing sequences of questions, one can envision flowcharts or other visual diagrams of questions. Individual routes through these diagrams could vary based upon users’ responses. There could be a variety of types of decision points or junctions to consider; such diagrams could be, from a developer perspective, extensible.

Visual authoring processes could be of use for both forms-based as well as natural-language-based surveys. Hopefully, such visual authoring tools would be able to generate multi-channel or omni-channel surveys.

See also: [Bot Framework Composer](https://github.com/microsoft/BotFramework-Composer/blob/stable/README.md).

## Evaluating Surveys

For large-scale surveys, we might want some means of analyzing and evaluating survey diagrams, or their serializations, for: spelling and grammar, questionnaire construction issues, question sequence issues, question wording issues, and other issues.

Survey evaluation components could provide informational, warning and error messages with respect to portions of diagrams. These messages could be collected together into an on-screen region of a visual survey authoring tool.

See also: [Bot Framework Composer](https://github.com/microsoft/BotFramework-Composer/blob/stable/README.md).

## Scheduling Surveys

Scheduling and rescheduling surveys appears to have been considered by [Polly](https://www.polly.ai/). This topic also appears to be covered by a [calendar bot skill](https://microsoft.github.io/botframework-solutions/skills/samples/calendar/).

## Adaptive Surveys

“Adaptive Dialogs enable developers to build conversations that can be dynamically changed as the conversation progresses. Traditionally developers have mapped out the entire flow of a conversation up front, which limits the flexibility of the conversation. Adaptive dialogs allow them to be more flexible, to respond to changes in context and insert new steps or entire sub-dialogs into the conversation as it progresses.”

These exciting concepts could be applicable to dialogue-based surveys. This would, however, add some complexity to the a priori evaluation of surveys for: spelling and grammar, questionnaire construction issues, question sequence issues, question wording issues, and other issues.

## Visualizing Survey Data

Visualizing and navigating resultant data could become a bit more complex with response-dependent routes through surveys. Perhaps visual diagrams could be reused for some data visualization and navigation views.

**Comment by EricDahlvang** [comment]
These are all great ideas!  

If you develop a library, please consider contributing to the Bot Builder Community repository:
https://github.com/BotBuilderCommunity/
