### ISSUE TITLE
Software Interoperation and Automation

### ISSUE THREAD

**Issue by AdamSobieski** [microsoft/botframework-sdk#5678]
## Controlling Software Applications

There are a number of interesting scenarios to consider with respect to a general-purpose interoperation between dialogue systems and other software applications and services.

**Scenario 1:** We can consider interoperation between dialogue systems and [CAD](https://en.wikipedia.org/wiki/Computer-aided_design)/[CAE](https://en.wikipedia.org/wiki/Computer-aided_engineering) software. As users interact with dialogue systems, the dialogue systems could interoperate with CAD/CAE software to assist users by performing tasks.

**Scenario 2:** We can consider interoperation between dialogue systems and Web browsers. We can consider that dialogue systems could open Web browsers to addresses, scroll to specific content, and highlight specific content. Web browsers are also digital textbook reader software. We can also consider that dialogue systems could open digital textbooks to specific content and highlight specific content.

* What are the best practices with respect to developing software applications and services towards interoperation with dialogue systems and intelligent virtual assistants? Might software applications such as CAD/CAE software and Web browsers utilize and implement the same suite of COM interfaces?

* What are the best practices with respect to developing dialogue systems towards interoperation with other software applications and services?

## Receiving Events and Notifications from Software Applications

Considering general-purpose interoperation and automation, dialogue systems should be able to receive asynchronous events and notifications from the software applications and services which they are connected to.

* What are the best practices of designing dialogue systems so that they can receive and process asynchronous events and notifications from the software applications and services which they are connected to?

## Brainstorming

Perhaps we might consider an `application` scripting object from the dialogue system development and diagramming perspective. The matter could, then, be phrased as interacting with an `application` scripting object (representing an interface to a software application or service) which might implement something like an `INotifyPropertyChanged` interface with respect to its object graph.

Perhaps designing or developing interactions between dialogue systems and software applications and services could make use of new diagramming elements.

Perhaps general-purpose interoperation and automation could expand upon adaptive dialogue concepts. Connected-to software applications and services could provide diagrammatic content for dialogue systems. This would be useful in the CAD/CAE scenario. One can envision using natural language to initiate actions on selected objects or regions. After so doing, multiple parameters may need to be specified. As a popup window appears in the CAD/CAE application for entering scalars, the CAD/CAE application could provide diagrammatic content to the connected-to dialogue system for entering the values using natural language.

**Comment by benbrown** [comment]
Hey Adam -- These are interesting ideas! You should see what you can achieve with the current SDK and let us know!  The web chat component in particular would allow you to send and receive events between the bot and external pieces of software (at least on the web)

You might consider contributing anything you build to the community repo which houses a collection of plugins and extensions from third party devs!

https://github.com/BotBuilderCommunity/

**Comment by AdamSobieski** [comment]
Thank you. I'm looking at the source code of the current version of the SDK presently. I think that I can prototype the aforementioned concepts utilizing sockets for platform-independent inter-process communication between dialogue systems and other software applications.

That prototype would include two software applications. The first would be a dialogue system or bot which would be able to function as a natural-language user interface for the second software application. That second software application might include some colored shapes to be moved around and stacked atop one another as well as a popup window with a form on it for entering data. That second software application would send diagrammatic content to the dialogue system for users to be able to interact with the popup window using natural language.

That prototype would include a means of transmitting diagrammatic content between the applications, a means of serializing and deserializing diagrams or conversation flows (e.g. JSON). The diagram model would be extended from the SDK's (e.g. `Microsoft.Bot.Builder.Dialogs.Adaptive`) to include action(s) for interacting with connected-to software applications.
