### ISSUE TITLE
Registration of new bots for skype

### ISSUE THREAD

**Issue by zharikovartem** [microsoft/botframework-sdk#5679]
I need to create a Skype bot, but registration of new bots was terminated.

In this regard, I have several questions:

Will an alternative technology for automatically sending messages to classic skype (No skype for business) be provided?

will registration of new bots be renewed, if so how soon?

is it possible to register a bot as an exception? Since it is extremely important for the further development of our software product.

**Comment by mdrichardson** [comment]
I apologize, but Skype is being deprecated. Please [follow the docs to migrate to Teams](https://docs.microsoft.com/en-us/microsoftteams/upgrade-and-coexistence-of-skypeforbusiness-and-teams). Note that it isn't just being deprecated on the Bot Framework, but is being deprecated for [all of Microsoft](https://docs.microsoft.com/en-us/microsoftteams/upgrade-start-here#when-should-my-organization-upgrade-to-teams). If you are developing software for Skype, you'll need to migrate that to Teams, too as it will no longer work on July 31, 2021.

**Comment by zharikovartem** [comment]
The fact is that in my country 99% of the business of correspondence occurs through classic Skype. Change is extremely difficult. 100 contacts is enough for almost all needs.

**Comment by mdrichardson** [comment]
@zharikovartem I'm sorry. It's not up to me or even the Bot Framework. This is a Microsoft decision.

**Comment by zharikovartem** [comment]
Can you tell me how you can contact Microsoft to resolve this issue?

**Comment by mdrichardson** [comment]
@zharikovartem There is *no* resolution. Skype services are being deprecated. The only thing that can be done about it is to migrate to Teams.

**Comment by zharikovartem** [comment]
Teams do not give the opportunity to generalize to Skype classic

**Comment by mdrichardson** [comment]
@zharikovartem Correct, which is why your users will also need to migrate to Teams.

**Comment by zharikovartem** [comment]
We are talking about large wholesale companies whose communication is completely built on Skype. If they will switch it is likely to telegram.

**Comment by mdrichardson** [comment]
Unfortunately, nothing can be done about continuing support for Skype or Skype for Business. The [upgrade documentation](https://docs.microsoft.com/en-us/microsoftteams/upgrade-plan-journey) does a really good job about walking you through the process of migrating. Most bots developed for Skype should also work in Teams without many changes. In fact, bots are *mostly* channel-agnostic and cross-compatible.

Here's some documentation for [using your bot with Telegram](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-telegram?view=azure-bot-service-4.0) and [using your bot with Teams](https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0).

**Comment by EricDahlvang** [comment]
Some have created bots using ucwa 

https://github.com/kenakamu/UCWABot

This is not an officialy supported option, but might help to unblock.

**Comment by zharikovartem** [comment]
Is it possible in UCWABot to create a bot for classic Skype? Without receiving access tokens on the azure portal.
