### ISSUE TITLE
ChatBot Calendar Card not showing up on mobile - Scaling issue

### ISSUE THREAD

**Issue by Amokstakov** [microsoft/botframework-sdk#5680]
Hi all,

I have an issue regarding my ChatBot. I am using WebServices, and everything has been deployed. I am using the ChatBot and everything is working correctly on my staging site, and on the test, however when we use the functionality of the chatbot on mobile, during the Calendar waterfall stage - the calendar does not show up.

See attached images.

Any help would be seriously appreciated. I almost finished this entire project!

<img width="322" alt="Calendar_Issue" src="https://user-images.githubusercontent.com/53410236/69652950-7085f500-1040-11ea-82f7-6ba63cffb25d.PNG">

**Comment by benbrown** [comment]
Hi @Amokstakov  - When you say "on mobile", can you provide us the OS and browser you are using to load the bot?

**Comment by benbrown** [comment]
Can you also send the Adaptive card JSON and the web chat version you are using? Thanks.

**Comment by Amokstakov** [comment]
Hi!

@benbrown 

Sorry for my delayed answer.

Mobile: on mobile telephone
OS: Iphone
Browser: Chrome and Safari

JSON:

    "type": "AdaptiveCard",
    "actions": [{
        "type": "Action.Submit",
        "id": "submit",
        "title": "Submit"
    }],
    "body": [
        {
            "type":"TextBlock",
            "weight":"bolder",
            "text":"Please pick a date for your mortgage appointment. \n\nMortgage appointments take approximately two hours."
        },
        {
            "type": "Input.Date",
            "id": "date",
            "title": "New Input.Toggle"
        }
    ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0"
}

**Comment by Amokstakov** [comment]
@benbrown any updates?

**Comment by Amokstakov** [comment]
bump

**Comment by benbrown** [comment]
Hi @Amokstakov, thanks for sending this info.

We'll investigate this and get back to you ASAP.

**Comment by cwhitten** [comment]
@Amokstakov can you give us some additional details for diagnosis?

1. How are you hosting the WebChat control?
2. Are you using the embed from the Azure Portal or self-hosting the React component? If the latter, what version of WebChat are you using?
3. In your mobile environment, which platform and browser are you using? Is is issue appearing on all mobile platforms?

**Comment by Amokstakov** [comment]
@cwhitten 
Thank you for your reply.

1) I don't understand - hosting? It is running through the Azure Portal. 

2) We are using the code from this former issue to embed the ChatBot:
https://github.com/microsoft/botframework-sdk/issues/5663
@mdrichardson  reply is what we went with, his last one.

3) this is appearing on all forms of mobile devices, such as Iphone/Android. Using and tested on chrome and safari.

**Comment by Amokstakov** [comment]
@benbrown any updates?
Sorry for push - this is for a launch and is being pushed from third party.

**Comment by tdurnford** [comment]
@Amokstakov I'm not able to reproduce this issue. The Adaptive Card you added above appears to work fine with the latest version of Web Chat using Safari and Chrome on an iPhone. What version of Web Chat are you using and do you have any additional customizations that might be changing the behavior?

**Web Chat v4.6.0 - Safari**
![Untitled](https://user-images.githubusercontent.com/17039790/70070419-6fa51400-15a8-11ea-89d9-5a1384b3ef1d.png)

**Comment by Amokstakov** [comment]
@tdurnford 

Thank you for your reply.
How do I check the particular version? I believe it is SDK 4.0 ?

Is there any other information in terms of hosting that I can supply to you to help with the diagnoses?

**Comment by tdurnford** [comment]
Adding your Web Chat code would be helpful.
