### ISSUE TITLE
Azure AD Auth make the bot fail

### ISSUE THREAD

**Issue by Skaaapi** [microsoft/botframework-sdk#5681]
Hi,

I tried to add **Authentification App Service** on my bot **App Service** :
![image](https://user-images.githubusercontent.com/42973489/69792847-aa353800-11c7-11ea-971e-a123c8bb872e.png)

I'm used to do those auths for many other apps but bots.

What is the issue :
  - If I disable the App Service Authentication, the bot is working fine.
  - If I enable the App Service Authentication, the bot will throw a 502 Bad Gateway, with a 401 :

![image](https://user-images.githubusercontent.com/42973489/69793086-1617a080-11c8-11ea-9d47-b4db18fcfe5c.png)

Does someone have an idea ?

Thanks a lot in advance :).

Guillaume.

**Comment by jwiley84** [comment]
HI @Skaaapi!

Sorry for the delayed response. 
While that particular setting seems like it would be the place to input OAuth flow for a bot (as it would for another app), it actually sets your azure bot service behind an inaccessible auth service. This is why you're getting a 'Failed to send (401)' error. If you are intending to set up OAuth for the users of your bot, please follow this tutorial:

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp

**Comment by CoHealer** [comment]
Closing, no response in 10 days
