### ISSUE TITLE
The README.md has not been updated

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5688]
## Issue
The README.md has not been updated (says the current version is 4.5, and that 4.6 is in preview)

## Proposed change
Update to reflect the current version. Might make sense to wait until 4.7 at this point.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by clearab** [comment]
Bump - the README is now two versions out of date.

**Comment by cleemullins** [comment]
Inspected all the readme files in the repos. Everything is up-to-date and current. Closing.
