### ISSUE TITLE
Bot Analytics Not Working - 403 Error

### ISSUE THREAD

**Issue by Amokstakov** [microsoft/botframework-sdk#5689]
I have a WebChat Bot configured to a Website. 
Everything is connected properly and tested through Test Channel etc.

However through the Azure Portal, when I click the Analytics tab - I get:
Retention - Error 403  - [Object object]
Users - Error 403  - [Object object]
Activity - Error 403  - [Object object]

Am i doing something wrong or have the wrong configuration?
Please let me know!

**Comment by dmvtech** [comment]
Hi @Amokstakov, nothing jumps to mind off the top of my head. 

May I ask how you created the bot? Did you create it from the portal (`Web App Bot `or `Bot Channels Registration`) or did you create and provision it from your development machine and use `az` cli to create/deploy? What language does the bot run in (is it Node, TypeScript, C#, etc).

**Comment by dmvtech** [comment]
hi @Amokstakov Just checking in. Still having issues/needing help? If so, can you help me by sharing more information?

**Comment by dmvtech** [comment]
Let us know if you still need assistance on this.

**Comment by dmvtech** [comment]
I did some more poking around. This is because the `instrumetation key`, `api app ID` or `api key` are incorrect/mismatched. Let me know if you need help finding which one maps to where.

![image](https://user-images.githubusercontent.com/43397658/71598980-d3662280-2afd-11ea-9095-11ff455e8870.png)
