### ISSUE TITLE
Automated Planning, Dialogue Systems and Natural Language Generation

### ISSUE THREAD

**Issue by AdamSobieski** [microsoft/botframework-sdk#5690]
## Introduction

I am excited to be developing with the Microsoft Bot Framework and am hoping to share some ideas and feature requests. Perhaps these ideas and feature requests could be of use for future versions of the Microsoft Bot Framework.

## Automated Planning, Dialogue Systems and Natural Language Generation

Automated planning can be of use for dialogue systems and natural language generation.

Some researchers have found off-the-shelf automated planning software to to be [slow for non-trivial natural language generation planning domains](https://www.semanticscholar.org/paper/Experiences-with-planning-for-natural-language-Koller-Petrick/00a6da2dac3aad9e4fc9b9744a415e2a14c028e2). Harnessing graphics card hardware and cloud-based, distributed automated planning techniques can accelerate performance.

## Automated Planning and Conversation Flow Diagrams

Generated plans can be more than sequences of actions; plans can, for instance, contain control flow, conditional branching and loops. Advanced topics in automated planning and related techniques include [workflow synthesis](http://www.phoster.com/parallel-and-distributed-computer-aided-and-automated-reasoning-planning-and-scheduling/workflow-synthesis/) and [program synthesis](http://www.phoster.com/parallel-and-distributed-computer-aided-and-automated-reasoning-planning-and-scheduling/program-synthesis/). It is possible to generate conversation flow diagrams via the techniques of automated planning, workflow synthesis, and program synthesis. These ideas are discussed [here](https://arxiv.org/abs/1902.00771).

## Cloud-based, Distributed Automated Planning

Contemporary research and development topics include cloud-based, distributed automated planning and scheduling. Publications on these topics are available [here](http://www.phoster.com/parallel-and-distributed-computer-aided-and-automated-reasoning-planning-and-scheduling/cloud-computing/). There are, presently, only a handful of publications on these topics.

## Automated Planning as a Cognitive Service

I requested automated planning and scheduling become a new Microsoft Cognitive Service (https://cognitive.uservoice.com/forums/356325-general-feedback/suggestions/32249440-automated-planning-and-scheduling-as-cognitive-ser). I am excited about these ideas and hope to increase interest in these ideas. We can envision cloud-based services with which to generate both conversation flow diagrams and natural language and these are but a few of the scenarios possible with cloud-based, distributed automated planning and scheduling as a service.

## Conclusion

Thank you. I hope that these ideas and feature requests can be of use for future versions of the Microsoft Bot Framework.

**Comment by sgellock** [comment]
@AdamSobieski thank you for the feedback.  There is work happening in this area and we've been looking at how it could help.  there has been active developer in this area, though we are not yet ready to product-ize it.  I've added the issue to our backlog for tracking.  feel free to engage further if you like, we appreciate it.

**Comment by sgellock** [comment]
@AdamSobieski we're evolving our dialog stack to address the planning aspect you've raised.  We have, in public preview, Adaptive Dialogs that were designed to address some of the planning issues you've raised.  I would encourage you to look at this work and provide feedback as you feel fit.
