### ISSUE TITLE
Identifying the conversation entry point of the bot 

### ISSUE THREAD

**Issue by vidyakdil** [microsoft/botframework-sdk#5698]
I've a bot using the **MS bot framework& hosted in Facebook** which is also embedded in a website in form of a messenger chat plug in. As a part of getting analytics I **need to know the conversation entry point of the bot**(as we have multiple user entry points for Facebook) - i.e, **whether bot is chatting from 
(a) desktop facebook messenger 
(b) facebook web 
(c) messenger app in mobile phones 
(d) messenger chat plugin embedded in a web site.** 

Is there any way to identify the conversation entry point to the bot?

**Comment by a-b-r-o-w-n** [comment]
@vidyakdil Thanks for opening an issue. For questions like this, you will get a better and quicker response on stackoverflow.

cc @stevkan
