### ISSUE TITLE
BotFramework Handoff to Cisco UCCX

### ISSUE THREAD

**Issue by Amokstakov** [microsoft/botframework-sdk#5701]
Hi,

Quick question regarding a future project.
Is it possible to have an option with the dialog of the ChatBot to hand off the existing state of the conversation to an actual human - connected via Cisco UCCX?

**Comment by vishwacsena** [comment]
@arturl can you comment?

**Comment by arturl** [comment]
Hi @Amokstakov, we're in the process of designing a solution for the next release of the SDK. So far, we have an experimental prototype available [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library). The eventual solution in the product may differ, but that's where our current thinking is.

The goal of the work is to standardize the developer experience for bot developers and define extensibility points for solution integrators for enabling connectivity with Cisco UCCX and other agent hub platforms. Happy to learn more about your scenarios and get feedback on the proposal.

**Comment by Amokstakov** [comment]
@arturl 
Thank you for your reply!

Are you able to speak on specific information regarding Cisco UCCX with the sample that you linked?
As to where the connection needs to be built within the sample or what needs to be modified to build the potential solution?

**Comment by arturl** [comment]
Please stay tuned, we're going to update the handoff library and publish more supporting docs soon.

**Comment by arturl** [comment]
Hi @Amokstakov, we will not support specific engagement hubs out of the box. Instead, we're defining the protocol that bot developers and system integrators can use to support specific applications. Please see the updated readme [here](https://github.com/microsoft/BotBuilder-Samples/blob/master/experimental/handoff-library/README.md).

**Comment by muzeeali** [comment]
@Amokstakov  were you able to solve this issue? Actually I also want to do the same thing if you can help me out.
