### ISSUE TITLE
How to add Telemetry Insights to bot using Javascript/Node.Js

### ISSUE THREAD

**Issue by Amokstakov** [microsoft/botframework-sdk#5706]
Hi all,

This is stemming from one previous issue I posted regarding how to get Chat Logs from a ChatBot conversation (as in where does the conversation end, when does a client leave from the convo, what is the human user sending to the bot, etc..)

I know now that I require Telemetry insights for the bot, but following this link:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry?view=azure-bot-service-4.0#visualizing-your-telemetry-data-in-application-insights

it is all done in C#.
The bot I have developed using Bot Framework is using node.js. Is there any instructions/samples on how to add these insights via node.js?

Please let me know! This will be helpful

**Comment by scheyal** [comment]
Hi @Amokstakov,
We are aware of this gap, and have a work item to update the documentation for JS. We will update this issue once we have more details. 
Thank you for the report.

**Comment by Virtual-Josh** [comment]
The PR to address this is in progress. @garypretty please confirm.

**Comment by garypretty** [comment]
Thanks @Virtual-Josh.  

@Amokstakov The PR to add the JS sample for telemetry was merged today.  The JS sample can be found at https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/21.corebot-app-insights.  This sample is based on the core bot sample, which means you should be able to see just the changes required to wire up telemetry.  Take a look and if you are hitting any issues then just let me know.  The docs for JS telemetry will be updated in the near future, but the sample should be enough for you to get going in the mean time.

**Comment by garypretty** [comment]
@Amokstakov Closing this issue now that the sample is available - please re-open another issue or reach out if you are struggling to implement telemetry in node.  Doc updates to follow in the near future, but hopefully the sample solves your problem.
