### ISSUE TITLE
Issue: Manifest Name not reflect by Bot Recipient

### ISSUE THREAD

**Issue by dcaterinicchio** [microsoft/botframework-sdk#5711]
Hello, there seems to be an issue when utilizing the Bot framework from a Personal Teams Chat.  The Activity object that is returned with the message is not displaying the name field under the Recipient object as the name given in the Team Apps Manifest file.

**Comment by Virtual-Josh** [comment]
Forward along to Andrew

**Comment by clearab** [comment]
Hi - My apologies, but I'm not sure what exactly you're referring to. Would you mind sharing an example of the JSON, and highlight the deviation?

**Comment by dcaterinicchio** [comment]
`"name": {
    "short": "ChatBot",
    "full": "Development ChatBot"
  },`

This is the section inside the manifest.json for the Teams App, where you set the short and full name.  The Activity Object that gets passed to the bot however does not reflect this in the Recipient Name.

**Comment by clearab** [comment]
The recipient name in the Activity object should map to the name in the bot channels registration, not the Teams app manifest. Typically it is recommended that you use the same name in both places.

**Comment by dcaterinicchio** [comment]
Gotcha, I must have misunderstood this.  Thank you!
