### ISSUE TITLE
BotState wont be saved or serialized

### ISSUE THREAD

**Issue by isoindisystems** [microsoft/botframework-sdk#5713]
Hello!
I´m using bot framework v4.7.1 and built a facebook messenger bot.
The problem is, that suddenly my bot is not persisting the userprofile states anymore.

After I modified the data I save it as follows:

```
public override async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
        {
            await base.OnTurnAsync(turnContext, cancellationToken).ConfigureAwait(false);

            await conversationState.SaveChangesAsync(turnContext, true, cancellationToken).ConfigureAwait(false);
            await userState.SaveChangesAsync(turnContext, true, cancellationToken).ConfigureAwait(false);
        }
```

Well, after that the file that is being generated on my Azure Blob Storage is truely a null storage:
```
{ 
"$type":"System.Collections.Concurrent.ConcurrentDictionary`2[[System.String, System.Private.CoreLib],[System.Object, System.Private.CoreLib]], System.Collections.Concurrent",
"UserProfile":{ 
"$type":"Microsoft.BotBuilderSamples.Models.UserProfile, Facebook-Events-Bot",
"MessageFlowType":0,
"OtherQuestionMessage":null,
"InsuranceCompanyName":null,
"YearOfSignContract":null,
"IsActiveOrCanceled":null,
"FavourOfPhoneTime":null,
"PhoneNumber":null,
"CurrentStep":null,
"CustomerServiceBotPerson":null,
"ExpertNameBotPerson":null,
"WasOptin":false,
"FacebookProfile":null
}
}
```

The bot is saving nothing, and I can't explain it, no exceptions, no errors or strange events in ApplicationInsights.

**Comment by dmvtech** [comment]
@isoindisystems This was working up until some point? No changes recently? So, it's still writing to the Blob Storage, but the values are null. Is there anyway to check the values before getting saved to state (i.e. are you able to debug via ngrok or log/track this stuff via application insights)? Does this **_only_** happen for the Facebook?

**Comment by CoHealer** [comment]
@isoindisystems, do you still require assistance?

**Comment by dmvtech** [comment]
I am closing this as no movement is happening. Please reopen if you still need assistance.
