### ISSUE TITLE
Skill Dialog

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5723]
## Overview
The SkillDialog provide the ability to integrate a Skill in a parent bot dialog stack (e.g. a skill can be invoked as part of a waterfall in the parent bot).  

### Requirements
1. The dialog should work with Composer
2. Needs to bind to memory to be used with adaptive
3. The dialog should take input parameters and send them to the skill
4. The dialog should handle return values returned by the skill to the parent
5. The dialog should handle EndOfConversation received from the skill
6. The dialog should send EndOFConversation to the skill if it is canceled
7. The dialog should be able to initiate an interaction with the skill for 
	a. Message Activities
	b. Event Activities
8. A bot developer should be able to inherit from the SDK SkillDialog and add additional functionality (e.g.: handle interruptions and cancellations)
9. It should not be a singleton. 

### Design considerations
* Apply Options pattern to constructor parameter to simplify initialization through DI (Check compat adaptive) 
* Handling Skill ConversationIDs
  * Multiple conversations with the same skill at the same time. 
* Forgetful dialog vs not forgetful.
* Do we implement DialogArgs? 
* What is the story for reving the manifest and how does that impact the properties in the skillDialog. What is the relationship between the runtime and the manifest? 
* Do we pass the target skill at construction time to SkillDialog? Or in DialogArgs during BeingDialogAsync? 
* Do we pass parent ID in constructor or let the SkillDialog pull it from config?

## Tracking Status
**Dotnet SDK** (Tracked in [3311](https://github.com/microsoft/botbuilder-dotnet/issues/3311))
- [x] PR
- [x] Merged

**Javascript SDK** (Tracked in [1635](https://github.com/microsoft/botbuilder-js/issues/1635))
- [x] PR
- [x] Merged

**Python SDK** (Tracked in [665](https://github.com/microsoft/botbuilder-python/issues/665))
- [x] PR
- [x] Merged

**Comment by JonathanFingold** [comment]
@clearab @gabog , to support Teams bots/skills, does requirement 7 need to include invoke activities?

**Comment by gabog** [comment]
Not sure yet, the invoke is just request/response, a developer can use SkillClient to do this, a dialog doesn't help much (because is really single turn request/response) but I still trying to decide if we support it in SkillDialog or not
