### ISSUE TITLE
Add POCO classes for skills manifest parsing

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5724]
## Overview
Provide POCOs to read and create manifests 
I should be able to read a manifest and validate it. 
I should be able to create a manifest and save it. 
It should support different manifest versions. 

## Tracking Status
**Dotnet SDK** (Tracked in [3312](https://github.com/microsoft/botbuilder-dotnet/issues/3312))
- [ ] PR
- [ ] Merged

**Javascript SDK** (Tracked in [1638](https://github.com/microsoft/botbuilder-js/issues/1638))
- [ ] PR
- [ ] Merged

**Python SDK** (Tracked in [668](https://github.com/microsoft/botbuilder-python/issues/668))
- [ ] PR
- [ ] Merged

**Comment by cleemullins** [comment]
This needs a spec before we write the code. @clearab Could you author the requirements / spec for this so we can implement?

**Comment by gabog** [comment]
We don't think we need this, closing
