### ISSUE TITLE
I can develop skills in Emulator without an app password

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5726]
## Scenario
As a developer, I need to be able to test by skill as a skill (not a stand alone bot) from the emulator without registering an app Id/password).

## Background
Several sections of the bot framework code need to know if the activity being process is in a consumer bot or a skill bot. The code uses the claims extracted from the auth header to determine this and that requires that the consumer and the skill have an AppId and Password configured. 

This causes friction for developers that are not quite ready to register the consumer or the skill as a bot. 

Here are the places where we use [SkillValidation.IsSkillClaim()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Connector/Authentication/SkillValidation.cs#L85) in the framework code and samples: 
  - [AllowedSkillsClaimsValidator sample](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/81.skills-skilldialog/DialogRootBot/Authentication/AllowedSkillsClaimsValidator.cs#L34) uses it to determine if the request is coming from a skill and validate the appId against the allowed apps list.
  - [OAuthInput.SendOAuthCardAsync()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Input/OAuthInput.cs#L381) uses to determine the cardActionType to use in the promp.
  - [DialogExtensions.SendEoCToParent()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs#L103) helper uses it to determine if it should send EoC to the caller when the dialog stack is empty. 
  - [DialogExtensions.IsFromParentToSkill()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs#L122) helper uses it to determine if the message is sent from a parent that is talking to a channel or to another skill. 
  - [DialogManager.OnTurnAsync()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs#L206) uses it to determine if the bot is running as a skill or as a parent bot.
  - [DialogManager.IsFromParentToSkill()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs#L255) helper uses it to determine if the message is sent from a parent that is talking to a channel or to another skill. 
  - [DialogManager.ShouldSendEndOfConversationToParent()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs#L286) helper uses it to determine if it should send EoC to the parent or not. 
  - [BotFrameworkAdapter.ContinueConversationAsync()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L366) uses it to determine if it should add the activity service Url to the AppCredentials.TrustServiceUrl list.
  - [BotFrameworkAdapter.ProcessActivityAsync()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L448) uses it to extract the OAuthScope and place it in turn state for later use. 
  - [BotFrameworkAdapter.GenerateCallerIdAsync()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L1522) uses it to generate the callerId property. 
  - [BotFrameworkAdapter.CreateConnectorClientAsync()](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/BotFrameworkAdapter.cs#L1577) uses it to get the OAuthScope and that will be used to generate the connector client. 
  - The [botframwork-skills repo](https://github.com/microsoft/botframework-skills/search?l=C%23&q=IsSkill) uses it in several places:
  - The [botframwork-skills repo](https://github.com/microsoft/botframework-skills/) also an extension method for [ITurnContext](https://github.com/microsoft/botframework-skills/blob/main/skills/csharp/shared/SkillServiceLibrary/Utilities/ITurnContextEx.cs#L10) that wraps the logic around inspecting claims to determine if something is a skill or not
    - In [MainDialog](https://github.com/microsoft/botframework-skills/blob/main/skills/csharp/experimental/eventskill/Dialogs/MainDialog.cs#L173) to determine if the need to end the dialog stack or begin a new dialog on a cancelation. 
    - In [DefaultAdapter](https://github.com/microsoft/botframework-skills/blob/main/skills/csharp/experimental/eventskill/Adapters/DefaultAdapter.cs#L99) to determine if the bot needs to send an EoC if there's a catastrophic error on the skill.  

Constraints
- The scenario only applies when the channelId is Emulator, all other channels will require AppId and password.
- All the bots involved should be running locally (parent and consumers), if any of them has or require and App/Id and password, all the bots will require it too (e.g.: I can't have a consumer running locally without appId and password that calls a skill that has an appId and password configured. 

## Solution

We introduced a new RoleType = "skill" that is set on the Recipient of the activity when an activity is sent from the consumer bot to a child bot through `BotframeworkHttpClient`. 

We also updated the auth logic in the framework to create a special claim for anonymous skill calls (see `SkillValidation.CreateAnonymousSkillClaim()` for details on the claim) that is set when there is no AuthHeader and the channel is Emulator.

## Component Impact 

- Emulator
- Composer
- BF SDK

## Tracking Status

**Dotnet SDK** [4752](https://github.com/microsoft/botbuilder-dotnet/issues/4752)
- [x] PR
- [x] Merged

**Javascript SDK** [2860](https://github.com/microsoft/botbuilder-js/issues/2860)
- [x] PR
- [x] Merged

**Python SDK** [1396](https://github.com/microsoft/botbuilder-python/issues/1396)
- [x] PR
- [x] Merged

**Java SDK** [809](https://github.com/microsoft/botbuilder-java/issues/809)
- [ ] PR
- [ ] Merged

**Comment by stevengum** [comment]
This has implications for generating the callerId (see https://github.com/microsoft/botbuilder-dotnet/pull/3753)

**Comment by clearab** [comment]
Yeah, we'll probably need to have an new IRI for the Emulator

**Comment by gabog** [comment]
dotnet, JS and Python are done, Java will be done in a future release

**Comment by tracyboehrer** [comment]
Java merged today
