### ISSUE TITLE
Skills Auth fails on Government cloud

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5730]
Consuming and calling skills registered in the azure gov cloud fails when authenticating the request. 

Steps to repro.
1. Configure the SimpleBotToBot sample to use and Azure Gov AppID and Password (both projects).
2. Attempt to invoke the echo skill and the call will fail with the following exception:
System.AggregateException: Failed to acquire token for client credentials. (AADSTS700016: Application with identifier '4b55cdcc-1659-4414-ad86-16c7f52109c2' was not found in the directory 'botframework.com'.

FYI: @lauren-mills 

## Tracking Status
**Dotnet SDK** (Tracked in [3233](https://github.com/microsoft/botbuilder-dotnet/issues/3233))
- [x] [PR](https://github.com/microsoft/botbuilder-dotnet/pull/3353)
- [x] Merged

**Javascript SDK** (Tracked in [1647](https://github.com/microsoft/botbuilder-js/issues/1647))
- [x] PR
- [x] Merged

**Python SDK** (Tracked in [675](https://github.com/microsoft/botbuilder-python/issues/675))
- [x] PR
- [x] Merged

**Comment by cleemullins** [comment]
Java isn't relevant to the PR at this time, as we don't have Skills in Java quite yet...
