### ISSUE TITLE
Skills can handle request/response from custom adapters. AKA the affinity problem.

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5735]
Step 1: create a proposal (John T), reevaluate after proposal and costing
Step 2.0: Review with OBI
Step 2.5: review proposal with big rocks
Step 3: implement

## Tracking Status
**Dotnet SDK** (Tracked in [issue](https://github.com/microsoft/botbuilder-dotnet/issues/3430))
- [x] PR
- [x] Merged

**Javascript SDK** (Tracked in [issue](https://github.com/microsoft/botbuilder-js/issues/1780))
- [x] PR
- [x] Merged

**Python SDK** (Tracked in [issue](https://github.com/microsoft/botbuilder-python/issues/781))
- [x] PR
- [x] Merged

**Comment by johnataylor** [comment]
we have trackings issues in javascript, c# and python.

https://github.com/microsoft/botbuilder-js/issues/1780
https://github.com/microsoft/botbuilder-dotnet/issues/3430
https://github.com/microsoft/botbuilder-python/issues/781

**Comment by johnataylor** [comment]
@clearab sorry did I close this prematurely - I thought once we had the tracking issues we were good - oops.

OK status is we have the C# in yesterday and I'll test and push Steve's PR tomorrow. Maybe we'll get Python done too.
