### ISSUE TITLE
[Skill] Introduce a way to localize skill names

### ISSUE THREAD

**Issue by lzc850612** [microsoft/botframework-sdk#5736]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**

Currently in VA implementation, there's a SkillSwitch feature, where if a user is in a skill dialog (EmailSkill) and the user suddenly says 'I want to check my calendar' we detect that the user is trying to switch to a different skill and prompt the user with 'do you want to switch to the calendar skill?'. We need to be able to localize the 'calendar skill' as the skill's display name. This is not currently supported. We could come up with a solution in VA but I think this should be better handled from the Skill core library or a pattern that's recommended by the SDK.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by gabog** [comment]
Hi @lzc850612, I am closing this one, we can reopen or create a new one once @carlosscastro finishes defining the scope for the localization efforts.
