### ISSUE TITLE
Bot greeting

### ISSUE THREAD

**Issue by 2501-Liz** [microsoft/botframework-sdk#5737]
Hi, I created a bot, when I test it in Web Chat, it gives an automatically greeting, but I want to skip or edit the initial greeting.

![image](https://user-images.githubusercontent.com/60667243/73774302-9d3d4380-4738-11ea-83ca-e778295c8293.png)

That's the picture with the initial greeting, I want to change that.

**Comment by mdrichardson** [comment]
@2501-Liz You'll need to edit the bot code.

1. [Download the bot code](https://docs.microsoft.com/en-us/azure/bot-service/abs-quickstart?view=azure-bot-service-4.0#download-code)
2. Edit the bot code in VS Code or Visual Studio:
    * It looks like you used an Echo Bot. So, you'll need to go into `<yourBot>/Bots/EchoBot.cs` and remove [`OnMembersAddedAsync()`](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/csharp_dotnetcore/02.echo-bot/Bots/EchoBot.cs#L20). This will completely remove the welcome message.
    * You can also edit it to say something else, if you'd prefer
3. Test it locally using [Emulator](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-debug-emulator?view=azure-bot-service-4.0&tabs=csharp)
4. [Deploy the bot back to Azure](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp)

I highly, highly recommend reading through the docs that I linked to. They should get you squared away.

**Comment by daveta** [comment]
Thanks, please follow up on Stackoverflow
