### ISSUE TITLE
Teams not rendering base64 encoded svg images.

### ISSUE THREAD

**Issue by baki32** [microsoft/botframework-sdk#5741]
Hi,
we were using just webchat for our bot but now extending to MS Teams. For some cards we are using base64 encoded svg images. When I tried adding our base64 image to Designer on adaptivecards.io and selected teams channel image was rendered correctly

![image](https://user-images.githubusercontent.com/22841494/73853146-b0cbd580-4830-11ea-9f6b-1611c83b41e7.png)

however when it get's deployed to actual teams client we get undefined images:
![image](https://user-images.githubusercontent.com/22841494/73853578-6860e780-4831-11ea-841a-828beca5dc8b.png)

Full base64 image used in designer for reference:
data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iaXNvLTg4NTktMSI/Pg0KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDE2LjAuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPg0KPCFET0NUWVBFIHN2ZyBQVUJMSUMgIi0vL1czQy8vRFREIFNWRyAxLjEvL0VOIiAiaHR0cDovL3d3dy53My5vcmcvR3JhcGhpY3MvU1ZHLzEuMS9EVEQvc3ZnMTEuZHRkIj4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iQ2FwYV8xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCINCgkgd2lkdGg9IjE1cHgiIGhlaWdodD0iMTVweCIgdmlld0JveD0iMCAwIDk3LjE2IDk3LjE2IiBzdHlsZT0iZmlsbDojNzYxMDkyIiB4bWw6c3BhY2U9InByZXNlcnZlIg0KCT4NCjxnPg0KCTxnPg0KCQk8cGF0aCBkPSJNNDguNTgsMEMyMS43OTMsMCwwLDIxLjc5MywwLDQ4LjU4czIxLjc5Myw0OC41OCw0OC41OCw0OC41OHM0OC41OC0yMS43OTMsNDguNTgtNDguNThTNzUuMzY3LDAsNDguNTgsMHogTTQ4LjU4LDg2LjgyMw0KCQkJYy0yMS4wODcsMC0zOC4yNDQtMTcuMTU1LTM4LjI0NC0zOC4yNDNTMjcuNDkzLDEwLjMzNyw0OC41OCwxMC4zMzdTODYuODI0LDI3LjQ5Miw4Ni44MjQsNDguNThTNjkuNjY3LDg2LjgyMyw0OC41OCw4Ni44MjN6Ii8+DQoJCTxwYXRoIGQ9Ik03My44OTgsNDcuMDhINTIuMDY2VjIwLjgzYzAtMi4yMDktMS43OTEtNC00LTRjLTIuMjA5LDAtNCwxLjc5MS00LDR2MzAuMjVjMCwyLjIwOSwxLjc5MSw0LDQsNGgyNS44MzINCgkJCWMyLjIwOSwwLDQtMS43OTEsNC00Uzc2LjEwNyw0Ny4wOCw3My44OTgsNDcuMDh6Ii8+DQoJPC9nPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPGc+DQo8L2c+DQo8Zz4NCjwvZz4NCjxnPg0KPC9nPg0KPC9zdmc+DQo=

**Comment by baki32** [comment]
Base64 JPEGs do work fine but we would like to stick to SVGs

**Comment by clearab** [comment]
Hi - SVGs are not supported in Teams. Please see this for reference: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#common-properties-for-all-cards.

**Comment by dmvtech** [comment]
@baki32 As this has been determined to be something that will not work or supported, I am closing this.
