### ISSUE TITLE
[Interruptions] do not work when a child dialog is interrupted -  4.7.2  C# 

### ISSUE THREAD

**Issue by marcasmar94** [microsoft/botframework-sdk#5744]
**Using V 4.7.2**

I have the following scenario: 

- MainDialog 
- HelpDialog (ComponentDialog - Waterfall)
- Dialog A   (ComponentDialog - Waterfall)
- Dialog B   (ComponentDialog - Waterfall)
- Dialog C   (ComponentDialog - Waterfall)

In my **MainDialog** i have an implementation of **OnInterruptDialogAsync** that checks if the user says "**Help**", we will start a **HelpDialog**

In my **OnInterruptDialogAsync** I'm doing the following:

- I have a list of Dialog names that include user **Prompts**
- I check if the **ActiveDialog** is in that list
  - I return  **InterruptionAction**.**Waiting**
- If the ActiveDialog is not in that list --> meaning there is no prompt
  - I return **InterruptionAction**.**Resume**

<br>

THE BELOW **WORKS** FINE

- **Dialog A** is running 
- **Dialog A** is **prompting** the user a question
- The user types "**Help**" and triggers the Interruption
- **HelpDialog** runs and shows the user a menu then finishes 
- RepromptDialogAsync() is triggered and the prompt that the user did not answer to is re-asked again 
   
THE BELOW **DOES NOT WORK**

- **Dialog B** is running
- On the last step of **Dialog B** 
  - we end the dialog --> await EndDialogAsync()
  - We begin **Dialog C** --> return await sc.BeginDialogAsync("Dialog C"); 
- **Dialog C** is running now and **prompting** the user a question
- The user types "**Help**" and triggers the Interruption
- **HelpDialog** runs and shows the user a menu then finishes 
- It is expected that the prompt of **Dialog C** to be **Reprompted** **BUT**:
  - **ERROR** : DialogSet.RepromptDialogAsync(): Can't find A dialog with an id of '**Dialog C**'
    

Has anyone faced this issue before ? 

Thank you, <br>
Marc

**Comment by dinudany** [comment]
I am also facing the same issue, not able to digress from child dialog.
