### ISSUE TITLE
Design Suggestion: Forward compatibility for declarative Json migration

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-sdk#5747]
Consider how we can design for a smooth (or light tough) migration to V.Next for declarative models. For example, bake versioning awareness, with corresponding features for reduced rendering or support of multiple schemas. 

Primarily ensure to avoid difficult migration paths from current to future versions.

(given the potential structure/schema sensitivity of composer->Json->Adaptive loader, it'd be good to consider this path from V0).

**Comment by vishwacsena** [comment]
No new engineering work here. We just need to formalize and document the versioning and upgrade proposal/ doc.
