### ISSUE TITLE
Emulator  un-responsive while trying to run locally the echo bot from sample

### ISSUE THREAD

**Issue by ARArun** [microsoft/botframework-sdk#5756]
![Capture](https://user-images.githubusercontent.com/26450729/75033563-36a67c80-54d1-11ea-9f69-78c9101b89d1.PNG)
'listening on http://[::]:52885'
why does the emulator try this. when all I am trying is available locally.

**Comment by dmvtech** [comment]
hi @ARArun The emulator emulates the direct line service. The bot is running on one port and the emulated service is running on another (52885 in this case).

Are you specifying appid/password for the bot in your test? Whatever you are doing in your appsettings.json/.env you need to supply in the emulator dialog (blank or values)

**Comment by ARArun** [comment]
@dmvtech Thanks for the reply. 
shouldn't the 52885 port also be in localhost .
I am trying to run it via python. So i guess I have a config.py which looks something like this
`
class DefaultConfig:
    

    PORT = 3978
    APP_ID = os.environ.get("MicrosoftAppId", "")
    APP_PASSWORD = os.environ.get("MicrosoftAppPassword", "")
`
While running the emulator I am not inputting any values for AppId or Password.
What changes should I make.
Thanks again

**Comment by dmvtech** [comment]
That should be all you need. I'll look more on my end and let you know.

**Comment by dmvtech** [comment]
Hi @ARArun Can you confirm you are using [this](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/02.echo-bot) echobot sample? Or are you using one of these?:

- https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/python_quart/02.echo-bot
- https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/python_tornado/02.echo-bot

**Comment by ARArun** [comment]
@dmvtech The issue got resolved. I was running the program from first link.  Thanks for you time. When I removed the proxy settings from my environment variables(HTTP_PROXY and HTTPS_PROXY). It started working fine.

Thanks again for you time
