### ISSUE TITLE
[testing] Add SSO scenarios to sign off tests

### ISSUE THREAD

**Issue by christopheranderson** [microsoft/botframework-sdk#5757]
## Problem

Need to ensure we don't regress functionality of SSO scenarios between releases. These can be tricky to catch because of the numerous systems that need integrating, thus we don't have check in or nightly tests. Given that nightly runs for these are likely an R10 thing, sign off tests are a good stop gap.

## Scenarios

1. Host + SSO
2. WebChat + SSO

(Skills is out of scope for R8)

**Comment by cleemullins** [comment]
Status Update: @carlosscastro and @swagatmishra2007 are meeting today (Feb 25) to identify scenarios. I've also reached out to Karthik (from PVA) to identify any core scenarios he envisions. 

@jwiley84 is booked to then setup and start executing these tests.
