### ISSUE TITLE
Conversation Management for Intents in MS Bot framework

### ISSUE THREAD

**Issue by Vigneshramkumar** [microsoft/botframework-sdk#5763]
I am using C# MS Bot Framework V4.0 and using LUIS for intent identification. As you aware we are having Dialog classes for managing conversations for a particular intent by using Waterflow dialog etc.. For each and every intent we need to create a dialog class and manage the conversation flow using the same. Or else we can have a standard JSON template and can have a generic Dialog class for handling all conversations based on the flow in that JSON for that identified intent.
But are we having any UI/UX tool for configuring/managing or training the conversation flow of each and every intent like the parent and sub intent concepts present in Dialogflow?
Is that possible in LUIS, because i can see only intent and entity identification in LUIS?
Is there any other way we can achieve that conversation management instead of coding?

**Comment by christopheranderson** [comment]
Hey @Vigneshramkumar - we are working on such a tool based on Adaptive Dialogs. Checkout https://github.com/microsoft/BotFramework-Composer - this still requires some code, but allows for visual designing of your experience.

You should also consider Power Virtual Agents, built on the Bot Framework SDK, which is a SaaS that we recently GA'd. It's simpler and completely no-code compared to using the SDK directly. You can also add bits of code via Skills if needed.

**Comment by Vigneshramkumar** [comment]
@christopheranderson : Thanks for your valuable response. Is there any expected release date for Bot Framework - Composer, currently its in preview version?

**Comment by chrimc62** [comment]
It is in public preview and we are targeting Build 2020 for GA on the C# runtime and the composer.
