### ISSUE TITLE
Sending Messages to User Directly From Azure

### ISSUE THREAD

**Issue by SubramanyamKirikera** [microsoft/botframework-sdk#5764]
Hi Team,

We have a requirement like - We will be consuming messages from queue and based on the message type processing happens . Here after processing we want to send message directly to the User in Teams. 
1. How can i send a direct message to user from code ?  
2. What information i require for that ? 

Here first user is not interacting with bot . So we wont be having conversation id/Service Url. 
(In general we can send mail using his mail id. But for sending message to a member in Teams. I don't know how to do that)

Could any body please help with reference?

Thank you
Subbu

**Comment by dmvtech** [comment]
> Here after processing we want to send message directly to the User in Teams.

To confirm, you want to be able to send messages to users (1:1 conversation between bot and user) and that user won't have any previous interaction with the bot. You are not wanting to message a  whole team or a team's channel. Correct?

**Comment by dmvtech** [comment]
@SubramanyamKirikera Can you please let me know if you still need assistance. Is my summary above correct in what you are looking to do?

**Comment by dmvtech** [comment]
Closing as no respose. @SubramanyamKirikera; let us know, or reopen this, if you are still having issues.
