### ISSUE TITLE
Feature Request: Dialogue System Trends Data

### ISSUE THREAD

**Issue by AdamSobieski** [microsoft/botframework-sdk#5777]
I would like to share an idea with the bot developer community: dialogue system trends. Just as there are Web search engine trends, so too might it be useful to have features which support aggregating dialogue system trends data from large numbers of user interactions.

Dialogue systems could aggregate users' questions, including in dialogue contexts, together and present the questions, with real-time trends data, to bot developer teams, to knowledgebase curators, and to editors of third-party Q&A and fact-checking resources, via such resources' APIs.

In particular for scenarios where dialogue systems can postpone answering questions – awaiting knowledgebase curation or fact-checking services – notifying users as answers arrive and change – teams might desire dashboards indicating which questions, potentially in dialogue contexts, that users await answers to.

**See also:**
* https://docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-analytics
* https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-telemetry-qnamaker

**Comment by chrimc62** [comment]
We are shipping some of this in a week as part of our R8 release and @garypretty can supply more details.

**Comment by AdamSobieski** [comment]
@chrimc62, @garypretty, Thank you. Looking forward to learning more about the R8 release.

**Comment by cleemullins** [comment]
With the work we shipped around Analytics in R8, I believe we can close this out.
