### ISSUE TITLE
Sending gif from bot not working on Teams

### ISSUE THREAD

**Issue by FedericoMartinelli** [microsoft/botframework-sdk#5778]
I want to send gifs to the user from the Bot and apparently those are rendered correctly both on Bot Emulator and on the Web Chat but not in Teams. In Teams gifs are rendered as images.

I'm using Bot service 4.0 and I'm developing in C#.

That's how I create the reply containing a gif:

```
Attachment attachment = new Attachment 
{ 
    Name = "happy gif",
    ContentType = "image/*", 
    ContentUrl ="https://media.giphy.com/media/examplegif/giphy.gif", 
};

var reply = context.Activity.CreateReply();

reply.Attachments = new List<Attachment>() { attachment };
```
I tried with ContentType = image/gif, image/\*, video/mp4, video/\* but those doesn't work.

Can you please help me with that? Thank you very much!

**Comment by clearab** [comment]
Unfortunately, .gif formatted is not supported by the Teams channel currently. Please see: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet#picture-messages.
