### ISSUE TITLE
Feature Request: Question Answering with Dynamic Data

### ISSUE THREAD

**Issue by AdamSobieski** [microsoft/botframework-sdk#5781]
## Introduction
I would like to separate a feature request topic from an earlier multi-topic issue (https://github.com/microsoft/botframework-sdk/issues/5776).

Microsoft Bot Framework SDK features requested are those supporting the development of dialogue systems such that resultant systems could:

1. postpone answering users’ questions when information is unavailable and subsequently notify users, via a number of channels, as requested information becomes available.

2. notify users, via a number of channels, as previously requested and provided information changes.

## Prioritizing Knowledgebase Curation Tasks with Trends Data
Access to dialogue system trends data (https://github.com/microsoft/botframework-sdk/issues/5777) could facilitate the prioritization of knowledgebase curation tasks by dialogue system teams and by third-party service teams. Data pertaining to pending questions and to alerts to which users are subscribed could be of use for the prioritization of knowledgebase curation tasks.

**Comment by CezaryMarcjan** [comment]
Thank you Adam for the suggestion. We are considering adding a similar functionality. Once we know more details including the timeline we'll send an update.

**Comment by cleemullins** [comment]
@AdamSobieski  I don't think this is a feature we're evaluating in the short term.
