### ISSUE TITLE
Skill consumers should not be able to send Activities to skills without a recipient

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5785]
Options for fixing this:
- Go through the SDK to add all the necessary null checks.
- Add the missing recipient in the HttpAdapter

## Tracking Status

**Dotnet SDK** (Tracked in [issue](https://github.com/microsoft/botbuilder-dotnet/issues/3684))
- [ ] PR
- [ ] Merged

**Javascript SDK** (Tracked in [issue](https://github.com/microsoft/botbuilder-js/issues/1997))
- [ ] PR
- [ ] Merged

**Python SDK** (Tracked in [issue](https://github.com/microsoft/botbuilder-python/issues/922))
- [ ] PR
- [ ] Merged

**Comment by stevengum** [comment]
For this scenario, are we ensuring a Recipient exists, or are we setting the outgoing Recipient to have it's `Id` be the Skill's AppId?

**Comment by stevengum** [comment]
Internal discussions and initial investigations point towards requiring that the Recipient value exist, not that it be populated.

In other words, SDK has numerous places that require `Activity.Recipient`, but not necessarily `Activity.Recipient.Id`. 

Populating an empty `ChannelAccount` for `Activity.Recipient` _should_ prevent the SDK from throwing easily avoidable exceptions.

The spec ([public](https://github.com/microsoft/botframework-sdk/blob/582ddb5a01768d9cd8ac2c4c7556a585780f56f7/specs/botframework-activity/botframework-activity.md#recipient), [bf-obi](https://github.com/microsoft/botframework-obi/blob/master/protocols/botframework-activity/botframework-activity.md#recipient)) doesn't specify that bots should reject activities without a recipient, so the receiving bot shouldn't return a 400 HTTP status code.

Channels (_and parent-bot child-bots are not in the specs_) are only required to include a recipient when the activity is sent to **a single recipient**.

**Comment by stevengum** [comment]
Closing as this has been completed.
