### ISSUE TITLE
Update DialogManager to work with Skills

### ISSUE THREAD

**Issue by cwhitten** [microsoft/botframework-sdk#5792]
In order to enable a Composer-generated bot as a Skill, the DialogManager needs to be updated to support sending an EndOfConversation to signal a Skill exiting. Without this, a Skill created from Composer will be unable to end itself.

<img width="970" alt="Screen Shot 2020-03-25 at 9 07 06 PM" src="https://user-images.githubusercontent.com/1156704/77609203-9b903080-6edc-11ea-8867-aa7eaee0fce9.png">

## Tracking Status
**Dotnet SDK** (Tracked in [3657](https://github.com/microsoft/botbuilder-dotnet/issues/3657))
- [x] PR
- [x] Merged

**Javascript SDK** (R10, Tracked in [1970](https://github.com/microsoft/botbuilder-js/issues/1970))
- [x] PR
- [x] Merged

cc @luhan2017 @boydc2014

**Comment by vishwacsena** [comment]
The only other caveat here is to not send EoC if the bot already sent this.

**Comment by vishwacsena** [comment]
@gabog per @Stevenic dialogmanager also needs to support `OnResumeDialogAsync`.

**Comment by gabog** [comment]
dotnet and JS have been updated, closing
