### ISSUE TITLE
Update Skill Manifest 2.1.preview-0 to work with Composer editing experience 

### ISSUE THREAD

**Issue by tdurnford** [microsoft/botframework-sdk#5794]
## Issue
We're currently adding a skill manifest editor to Composer, and in order to make the schema work with the AdaptiveForm editor, we had to make several small changes to the schema. 

## Proposed change
Here are the changes to each property in the schema we would like to see changed

- Tags
  - Define the items' type as string
  - ```diff
    "tags": {
      "type": "array",
      "uniqueItems": true,
    - "description": "An array of strings with tags for the skill"
    + "description": "An array of strings with tags for the skill",
    + "items": {
    +   "type": "string"
    + }
    },
    ```
- Dispatch Models
  - Languages/Intent
    - Remove `oneOf` attribute since there is only one item in the array
    - ```diff
      "languages": {
        "type": "object",
        "description": "List of languages supported by the skill",
        "minProperties": 1,
        "additionalProperties": {
      -   "oneOf": [
      -     {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "description": "List of language models supported by the skill",
              "items": {
                  "$ref": "#/definitions/languageModel"
              }                               
      -     } 
      -   ]
        }
      }
      ```
- Activities/Activities sent 
  - Changed `anyOf` in `additionalProperties` to `oneOf`
  - ```diff
    "activities": {
      "type": "object",
      "description": "Definition for the activities accepted by the skill",
      "additionalProperties": {
    -   "anyOf": [
    +   "oneOf": [

                {
                    "$ref": "#/definitions/eventActivity"
                },
                {
                    "$ref": "#/definitions/invokeActivity"
                },
                {
                    "$ref": "#/definitions/messageActivity"
                }
            ]
        }
    },
    ```
- Event/Invoke/Message Activities
  - Changed type from an enum with one option to use a const value
  - Added titles for drop-down selection
  - ```diff
    "eventActivity": {
    + "title": "Event Activity",
      "type": "object",
      "description": "An activity with Type=Event where the Name property indicates the task that the skill will execute",
      "required": [
          "type",
          "name"
      ],
      "properties": {
          "type": {
              "type": "string",
              "description": "The activity type",
    -         "enum": [
    -           "event"
    -         ]
    +         "const": "event"
          },
        ...
      }
    }
    ```
## Component Impact 
Skills Manifest

## Customer Impact 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/17039790/78304943-09e87a80-74fd-11ea-9774-9fb60a4499ab.png)

**Comment by gabog** [comment]
These changes are being worked on [this branch](https://github.com/microsoft/botframework-sdk/tree/gabog/SkillManifest21Updates). 

We may take additional changes as part of this, we are reviewing the changes with the composer team on 4/20/2020.
