### ISSUE TITLE
Auto-generate skills manifest from declaratively defined adaptive dialogs

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5795]
Build a library that can auto-generate a skills manifest for declaratively defined adaptive dialogs.

## Tracking Status

**Dotnet SDK** (Tracked in [issue](https://github.com/microsoft/botbuilder-dotnet/issues/3561))
- [ ] PR
- [ ] Merged

**Javascript SDK** (Tracked in []())
- [ ] PR
- [ ] Merged

**Comment by gabog** [comment]
Composer adds support for this, we won't be doing this at the SDK level
