### ISSUE TITLE
OAuthPrompt + Skills automated Testing 

### ISSUE THREAD

**Issue by carlosscastro** [microsoft/botframework-sdk#5796]
Expand the current Skills test matrix with skills + OauthPrompt testing using a custom identity provider to control auth flow.

**Comment by cleemullins** [comment]
ETA "Tomorrow" per @carlosscastro

**Comment by carlosscastro** [comment]
Closing as the tests are done. There are some failures, but they come from the bot / host / skills rathr than from the test itself.
