### ISSUE TITLE
Bot send welcome message twice when user first add bot

### ISSUE THREAD

**Issue by oliver1191** [microsoft/botframework-sdk#5798]
## Bot Info
<ul>
    <li>Framework: .Net Core 2.2</li>
     <li>SDK Version: botbuilder 4.5.1</li>
     <li>Active Channels: Microsoft Teams</li>
     <li>Deployment Environment: Azure Bot Service,not occur in local development with Emulator</li>
</ul>

## Issue Description
*When user add bot to teams first,bot will send welcome message to user once a few months ago.*

*However bot send twice welcome message recently not only my custom bot but also some bot in Teams store(I just test about 4 bots which will send welcome message).*

*This issue does not  happen in Emulator.*

## Code example
<pre>
        public async Task OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken = default(CancellationToken))
        {            
            switch (turnContext.Activity.Type)
            {
                //ConversationUpdate occur twice
                case ActivityTypes.ConversationUpdate:
                    await OnConversationUpdateActivityAsync(turnContext, cancellationToken);
                    break;                
                default:
                    await next(cancellationToken).ConfigureAwait(false);
                    break;
            }
        }
        protected async Task OnConversationUpdateActivityAsync(ITurnContext turnContext, CancellationToken cancellationToken)
        {       
            //ConversationUpdate occur twice and get the same MembersAdded    
            if (turnContext.Activity.MembersAdded != null)
            {
                if (turnContext.Activity.MembersAdded.Any(m => m.Id != turnContext.Activity.Recipient?.Id))
                {
                    //send message
                }
            }
        }
</pre>

## Expected Behavior
*Get welcome message once when user first add bot to teams*

## Actual Results
*bot send welcome message twice*

**Comment by jwiley84** [comment]
It looks like your MembersAdded is firing twice because you have it tucked into `OnConversationUpdateActivityAcync`. You should move it to `OnMembersAddedAsync' instead. Specifically for Teams, this would like the following:

```
protected override async Task OnTeamsMembersAddedAsync(IList<TeamsChannelAccount> membersAdded, TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
        {
            foreach (var teamMember in membersAdded)
            {
                await turnContext.SendActivityAsync(MessageFactory.Text($"<YOUR MESSAGE HERE>."), cancellationToken);
            }
        }
```
This might require you to update your botbuilder packages. The current release is 4.8.0.

**Comment by jwiley84** [comment]
A good sample of a Teams conversation bot with a welcome message is this: https://github.com/microsoft/BotBuilder-Samples/tree/608515d7a2fb296ec942cdfc0391fa7abb1d906d/samples/csharp_dotnetcore/57.teams-conversation-bot

**Comment by oliver1191** [comment]
> It looks like your MembersAdded is firing twice because you have it tucked into `OnConversationUpdateActivityAcync`. You should move it to `OnMembersAddedAsync` instead. Specifically for Teams, this would like the following:
> 
> ```
> protected override async Task OnTeamsMembersAddedAsync(IList<TeamsChannelAccount> membersAdded, TeamInfo teamInfo, ITurnContext<IConversationUpdateActivity> turnContext, CancellationToken cancellationToken)
>         {
>             foreach (var teamMember in membersAdded)
>             {
>                 await turnContext.SendActivityAsync(MessageFactory.Text($"<YOUR MESSAGE HERE>."), cancellationToken);
>             }
>         }
> ```
> 
> This might require you to update your botbuilder packages. The current release is 4.8.0.

Thanks for your reply! I try the methods mentioned above,but it does not work.
1.Because my company has no idea to update botbuilder packages recently,so I have to use version 4.5.1.
2. OnMembersAddedAsync function also occur twice.The 'membersAdded' property in the log file is the same,for example<pre>OnMembersAddedAsync members json string:[{"id":"29:'sensitive information',"name":null,"aadObjectId":'sensitive information',"role":null},{"id":"28:'sensitive information',"name":null,"aadObjectId":null,"role":null}]</pre>
So I can not get the difference from the property.
3.Here is my example code.
`protected override async Task OnMembersAddedAsync(IList<ChannelAccount> membersAdded, ITurnContext&ltIConversationUpdateActivity> turnContext, CancellationToken cancellationToken)`
<pre>
{
    logger.Info("OnMembersAddedAsync members json string:{0}", JsonConvert.SerializeObject(membersAdded));`
    if (membersAdded != null && membersAdded.Any(m => m.Id != turnContext.Activity.Recipient?.Id))
    {
          //send  welcome message
     }
}</pre>
Thank for your any idea to let me know!

**Comment by vunhutien** [comment]
I also got this issue, i use this example: https://github.com/microsoft/BotBuilder-Samples/tree/608515d7a2fb296ec942cdfc0391fa7abb1d906d/samples/csharp_dotnetcore/57.teams-conversation-bot

**Comment by jwiley84** [comment]
@vunhutien Did you get the double welcome after making no changes to the sample? Or did you make any code changes?

**Comment by jwiley84** [comment]
@oliver1191 

Circling back around to the package: Teams wasn't supported in Bot Framework until 4.6.0. Packages older then that are going to have unexpected behaviours. Please update to AT LEAST 4.6.0.

Additionally, use `OnTeamsMembersAddedAsync` instead of `OnMembersAddedAynsc`, as the first method is specifically built to handle the fact that it's going to fire twice, once for the bot and once for the user.
