### ISSUE TITLE
Tab unfurling for Teams

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5805]
## SPEC UPDATED - DESIGN CHANGED
Teams altered the way this will work. See updated spec below.

## Issue
Teams is requesting SDK support for a new "tab unfurling" feature. Essentially, this feature allows a bot developer to provide the URL's and information needed to pin a website as a tab - either through an Adaptive Card or with a specifically formatted deep-link URL.

## Requirements:

As a developer:

1. I can create a deeplink to the URL/tab stageview. I can include this in link in an adaptive card by using the openUrl action with the appropriate deeplink (need the format for that deeplink).
1. I can add "pin as tab" to the ... overflow menu of my adaptive card by including the tab url data in the top-level msteams object in my adaptive card body (not part of initial release)
1. If I've done both 1+2, then "pin as tab" will be available from the stageview.
1. If I've done 1 but not 2, then stageview will still work, but no pin as tab option. (Is this correct? I seem to remember something about all the necessary information being encoded in the url)
1. If I've done 2 but not 1, northstar is "pin as tab" will be there, but that won't be part of the initial release

### Data required

name | type | required | max chars | description
--|--|--|--|--|
entityId| String |yes| 64 | A unique identifier for the tab (chosen by bot developer)
name| String | yes|128 | Display name for the tab
contentUrl| String | yes | 2048 | The https:// URL that points to the entity UI to be displayed in the Teams canvas
websiteUrl | String | No | 2048 | The "open in website" URL
removeUrl | String | No | 2048 | The page to be displayed when a user removes a tab

### Deeplink format

Example link: https://teams.microsoft.com/l/stage/11111111-4333-433d-8888-9e06cbe037c5?url=https://someplace.com/b/publish?EQBCT=asdf1234bfd34c82asdfd16ab683asdf&amp;ss_src=mst

### Example Adaptive Card

```json
{
  "type": "AdaptiveCard",
  "body": [
        {
            "type": "Image",
            "altText": "",
            "url": "https://www.publicdomainpictures.net/pictures/20000/velka/mother-kissing-baby-87129433012057t.jpg"
        },
        {
            "type": "ActionSet",
            "actions": [
                {
                "url": "https://teams.microsoft.com/l/fileDownload/stuff",
                "title": "Download",
                "iconUrl": "https://statics.teams.cdn.office.net/evergreen-assets/adaptiveemail/DownloadIcon2x.png",
                "msTeams": {
                    "overflow": true
                },
                "type": "Action.OpenUrl"
                }
            ]
        }
        
    ],
    "version": "1.0",
    "msTeams": {
        "tab": {
            "entityId": "iamsomeguid",
            "name": "I am the display name",
            "contentUrl": "https://theurl.com/for/teams",
            "websiteUrl": "https://theopeninwebsite.com/url",
            "removeUrl": "https://optionurl/forwhen/tabisremoved"
        }
    }
}
```

### Creating the deeplink

We should provide a helper method for creating the tab unfurling deeplink URL. This should be written so that it can be expanded to support creation of other types of deep-links.

### Add the tab data to the Adaptive Card

We should create a strongly typed object for the tab URL information so that it can easily be added to the `msteams` object in the Adaptive Card payload.

## Customer Impact 
Teams needs this to release their feature. For bot developers not using this feature there should be no impact (other than seeing the additional options available to them).

## Tracking Status
**Dotnet SDK** [Issue](https://github.com/microsoft/botbuilder-dotnet/issues/3965)
- [ ] PR
- [ ] Merged

**Javascript SDK** [Issue](https://github.com/microsoft/botbuilder-js/issues/2267)
- [ ] PR
- [ ] Merged

**Python SDK** [Issue](https://github.com/microsoft/botbuilder-python/issues/1088)
- [ ] PR
- [ ] Merged

**Java SDK** [Issue](https://github.com/microsoft/botbuilder-java/issues/559)
- [ ] PR
- [ ] Merged

**Samples**  [TODO Create samples issue once we scope this feature a bit more]()
- [ ] PR
- [ ] Merged

**Docs**  [TODO Create docs issue once we scope this feature a bit more]()
- [ ] PR
- [ ] Merged

[dcr]

**Comment by cleemullins** [comment]
@clearab Believes this will be R11 work. Outstanding issues is to review spec and staff.
