### ISSUE TITLE
Change onTeamsMemberAdded for Teams to use getMember()

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5810]
The onTeamsMemberAdded event calls getMembers() to create a fully hydrated TeamsChannelAccount object. Now that Teams has released the get single member endpoint, we should update the SDK to use that instead.

As an example, here's the method in the C# repo that needs to be changed: https://github.com/microsoft/botbuilder-dotnet/blob/92242ea0826ea94e671d1b1a98c62fcd5042059a/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L251

## Tracking Status

**Dotnet SDK** (Tracked in [Issue](https://github.com/microsoft/botbuilder-dotnet/issues/3774))
- [x] PR
- [x] Merged

**Javascript SDK** (Tracked in [Issue](https://github.com/microsoft/botbuilder-js/issues/2068))
- [x] PR
- [x] Merged

**Python SDK** (Tracked in [Issue](https://github.com/microsoft/botbuilder-python/issues/974))
- [x] PR
- [x] Merged

**Java SDK** (Tracked in []()
- [x] PR
- [ ] Merged

**Comment by tracyboehrer** [comment]
We should add Java to this since the next preview will have Teams support.

**Comment by Zerryth** [comment]
It needs to be said publicly: @EricDahlvang  - a true Avatar
![image](https://user-images.githubusercontent.com/35248895/80779155-9d729280-8b1f-11ea-9a83-02851f8d333e.png)

**Comment by cleemullins** [comment]
My grandmother used to tell me stories about the old days, a time of peace when the Avatar kept balance between the Java Tribes, Python Kingdom, Lisp Nation, and COBOL Nomads. But that all changed when the Javascripters attacked.



________________________________
