### ISSUE TITLE
Extracting QnA from a AAD protected Url

### ISSUE THREAD

**Issue by neetgupta7** [microsoft/botframework-sdk#5815]
We have an FAQ page in an AD protected application. It means user has to login into that url with their organization account to access the content. And we want to use that url to call QnA maker api to extract the content from that url. Today when we try to directly extract the content it says no content found. Please let me know how can this achieved.

**Comment by tonyanziano** [comment]
@neetgupta7 , thank you for opening this issue.  For product behavior, how-to, or general understanding questions, please use Stackoverflow.  

https://stackoverflow.com/search?q=bot+framework
