### ISSUE TITLE
Add Support For TeamsTaskModule Type activities

### ISSUE THREAD

**Issue by sidmore** [microsoft/botframework-sdk#5816]
## Using TeamsTaskModule acitivity

Teams taskmodule Invoke are of 2 types
* "task/fetch" 
* "task/submit" 

which is used to identify what kind of TaskModule activity it is and could be used to implement specific OnFetch/OnSubmit handlers.

## For example I have these helper methods to figure out the type of TaskModule activity:

`public static class ActivityEx
    {
        private const string FetchType = "task/fetch";
        private const string SubmitType = "task/submit";

        public static bool IsTeamsInvokeActivity(this Activity activity)
        {
            return activity.IsTeamsActivity()
                && activity.IsTaskModuleActivity();
        }

        public static bool IsTaskModuleFetchActivity(this Activity activity)
        {
            return StringComparer.OrdinalIgnoreCase.Equals(activity.Type, ActivityTypes.Invoke)
                && StringComparer.OrdinalIgnoreCase.Equals(activity.Name, FetchType);
        }

        public static bool IsTaskModuleSubmitActivity(this Activity activity)
        {
            return StringComparer.OrdinalIgnoreCase.Equals(activity.Type, ActivityTypes.Invoke)
                && StringComparer.OrdinalIgnoreCase.Equals(activity.Name, SubmitType);
        }

        public static bool IsTaskModuleActivity(this Activity activity)
        {
            return StringComparer.OrdinalIgnoreCase.Equals(activity.Type, ActivityTypes.Invoke)
                && (StringComparer.OrdinalIgnoreCase.Equals(activity.Name, FetchType)
                || StringComparer.OrdinalIgnoreCase.Equals(activity.Name, SubmitType));
        }

`
It will be great if SDK supports this out of the box instead of needing custom code.

**Comment by clearab** [comment]
This has been implemented.
