### ISSUE TITLE
Cleanup 'TenantIdWorkaroundForTeamsMiddleware'

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5822]
There's a lot of "temporary fix" verbiage around this. We should investigate what was temporary and clean this up.

See: 'TenantIdWorkaroundForTeamsMiddleware'

NOTE: This can probably be safely removed - it looks like the workaround is no longer required. We should verify that Teams is sending the tenantId correctly in all cases (almost certain it is), and if so this middleware could be deprecated/removed.

**Comment by cleemullins** [comment]
Assigning to @clearab for prioritization in (maybe) R11.
