### ISSUE TITLE
Add webhooks to escalate to Teams Support team

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5825]
The Teams Support team would like us to add a webhook to our repositories so that we can more easily escalate issues their way. Essentially after we set this up we'll be able to tag an issue with "MSTeams-Developer-Support" and it will be added to their tracking system and they should respond (we can talk SLAs with them as well).

Help needed to setup:
We need help with following steps to setup it.
1.	Create new Label MSTeams-Developer-Support in BotFramework-Services  repo.
2.	Create new webhook and set following:
    1.	Payload Url- {ask Andrew or cmullins}
    2.	Content Type: application/json
    3. Which events would you like to trigger this webhook?  Let me select individual events.
3.	Click on Add Webhook.

**Comment by cleemullins** [comment]
Please link to the spec / functional requirements of the webhook.
