### ISSUE TITLE
Errors in documentation for Adaptive Dialogs

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botframework-sdk#5844]
The first line on the [Adaptive Dialogs documentation page](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-adaptive-dialog-introduction?view=azure-bot-service-4.0) reads:

"Adaptive dialogs offer ```` new A new```` event based addition to the Dialogs library that enables you to ````start simple and quickly layer```` in sophisticated conversation management techniques like interruption handling, dispatching and more.".

In addition to the errors highlighted, the whole paragraph seems to need a revision.

Also below, under the title: Adaptive dialogs defined, sub title "Why adaptive dialog" should say "Why adaptive dialogs".
Each bullet point refer to adaptive dialogs, so they should read "provide", instead of "provides", and so on.

**Comment by cleemullins** [comment]
@kaiqb, looks like there are a number of grammer & structural errors in the Adaptive docs. When you get a minute, can you have a copy-editor review for the basics and then we can all chip-in to help with the more structural.

**Comment by mdrichardson** [comment]
Agreed. I fixed the issues pointed out by @mrivera-ms as a quick-fix, but the doc, as a whole, could use a revamp.

**Comment by Kaiqb** [comment]
Fixed.
