### ISSUE TITLE
Rewrite / Redesign the QnA Maker Dialog(s)

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#5851]
Consider revisting the overall design and implementation of the QnAMaker dialog(s). 

See list of referenced issues (closed but still relevant for additional requirements)

**Comment by johnataylor** [comment]
We can start an analysis of this towards the end of the R10 milestone. With initial work in samples or experimental samples.

**Comment by johnataylor** [comment]
We are taking changes on the current QnA Dailog in this milestone. Moving to next milestone as it doesn't make sense to do this internal refactoring concurrently.

**Comment by HesselWellema** [comment]
Hi Team,

I need to be able to start new dialogs based on result of QnAMaker. Since #2289 I am unable to do so.in QnAMaker Dialog,  Is this request still on your board or do I need to create a new one.

thank you
Hessel
