### ISSUE TITLE
Set EndOfConversationCodes when send EoC

### ISSUE THREAD

**Issue by xieofxie** [microsoft/botframework-sdk#5852]
### Use this [query](https://github.com/Microsoft/botbuilder-dotnet/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3Aenhancement) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
Currently when sending EoC here https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs#L91, Code is not set to any of the EndOfConversationCodes https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Schema/EndOfConversationCodes.cs

**Describe the solution you'd like**
Set to CompletedSuccessfully 

**Describe alternatives you've considered**

**Additional context**

[enhancement]

**Comment by mrivera-ms** [comment]
Probably a protocol change. Likely channel specific. It is unclear how to handle it.

**Comment by EricDahlvang** [comment]
Couldn't we just convert the dialog Status into the corresponding EndOfConversationCode?

```
DialogTurnStatus.Complete == EndOfConversationCodes.CompletedSuccessfully 
DialogTurnStatus.Cancelled == EndOfConversationCodes.UserCancelled 
```

**Comment by cleemullins** [comment]
@EricDahlvang IS this something we should take in R10, or push to R11?

**Comment by EricDahlvang** [comment]
@cleemullins  Seems like a small change.  I should be able to get it into R10.
