### ISSUE TITLE
AppInsights Integration should send up Teams channel info, and AAD app id. and make user_id more clear

### ISSUE THREAD

**Issue by msftjayongg** [microsoft/botframework-sdk#5855]
**Is your feature request related to a problem? Please describe.**
For users to make the most use out of the telemetry, there are important metrics that should be transmitted into the customEvents in ApplicationInsights. Without making the developer do more work. Right now the lack of clarity with the user_id metric lets ISVs overcount. (I've double checked application insights telemetry)

**Describe the solution you'd like**
We should add two fields and fix up the user_id field
1. TenantID.  A lot of ISVs track not just user counts, but also tenant counts.  We should put this information into the custom event.  This information is available in the turnContext.
2. Teams Channel information - in short, "is this a channel" or "is this a a user?".  
3. User_id - in AppInsights, I see two types of users.  Some begin with "msteams29:", and some begin with "a:". I suspect this relates to microsoft/botbuilder-dotnet#2, as some are channel thread ids, and some are user ids.  Not quite sure TBH.  The user_id to actually count real users. (I can log a separate issue on this if needed)

**Describe alternatives you've considered**
Developer can work around this by logging the data herself. However this belongs in the framework - else we're just making more calls to Application Insights unnecessarily.

**Dotnet SDK** [4255](https://github.com/microsoft/botbuilder-dotnet/issues/4255)
- [x] PR
- [x] Merged

**Javascript SDK** [2523](https://github.com/microsoft/botbuilder-js/issues/2523)
- [x] PR
- [x] Merged

**Python SDK** [1246](https://github.com/microsoft/botbuilder-python/issues/1246)
- [x] PR
- [x] Merged

**Java SDK** [691](https://github.com/microsoft/botbuilder-java/issues/691)
- [x] PR
- [x] Merged

**Comment by cleemullins** [comment]
This is a great feature ask. We're planning to take this in our R10 release (which is our next milestone).

**Comment by garypretty** [comment]
Hi @msftjayongg - I have been looking into how we can address this feature request.

Firstly, I serialized the channel data I received in different circumstances to understand what we might log to assist.

*1:1 Chat with the bot*

{"tenant":{"id":"XXXXXX-XXXX-XXXX-XXXX-XXXXXXX"}}

*Group Chat*

{"tenant":{"id":"XXXXXX-XXXX-XXXX-XXXX-XXXXXXX"}}

*Message via a Channel*

{"teamsChannelId":"19:e05xxxxxxxxxxxxxxxxxxxxx4f800e@thread.tacv2","teamsTeamId":"19:e05xxxxxxxxxxxxxxxxxxxxx4f800e@thread.tacv2","channel":{"id":"19:e05d7a1fa66646a9bee7ed47c34f800e@thread.tacv2"},"team":{"id":"19:e05xxxxxxxxxxxxxxxxxxxxx4f800e@thread.tacv2"},"tenant":{"id":"XXXXXX-XXXX-XXXX-XXXX-XXXXXXX"}}

--------------------------------------------

So, to respond to your points.

1. Tenant ID - we get this every time, so we can add this to the custom event properties

2. Channel vs User - if you're in a chat (1:1 or group - but both under the chat tab) - the channel info object is null.  If the bot is receiving a message from a channel, then the channel data is populated.  In this case, we should be able to log the team / channel ID.  Thus, the presence of this within the event data will tell you if this is user chat vs channel.  

3. The User ID, during my testing was always in the format "29:..............................", so I do not know where the "a:" user came from (I have asked internally to try and find out) - can you reliably repro?.  However, in the case of some channels, the user ID alone may not be enough to determine the unique user count and you will need to use a mixture of information at times to understand the unique user count better, which you should be able to get once we log the additional information.

Do the additional data points I have suggested we log make sense to you?  If so I can work up a PR to capture the additional data.

**Comment by garypretty** [comment]
Agreed with Tatiana in Teams that, as per the above, we will add the following items to our telemetry is the user is using the Teams channel.

* Tenant Id
* AAD Id (need to confirm, but I believe this may already be captured as part of user information.)
* TeamInfo, if available

**Comment by msftjayongg** [comment]
Hi Gary,

Sorry I didn't see your message from 13 days ago.  I think your comments make sense.  I don't know where the "a:" come from, did Tatiana have a response to that, seems like she would know.

**Comment by tacri** [comment]
For the point 3 above, a: prefix is usually for 1:1 conversations between the user and the bot. If there is a repro we can confirm what is happening from our logs
