### ISSUE TITLE
Bot framework integration with Cisco Webex teams bot

### ISSUE THREAD

**Issue by Bradrajkumar** [microsoft/botframework-sdk#5864]
Hi all, 
The description provided for webex as a channel is not sufficient to fully integrate the bot framework with Webex bot. Where I can get fully described information for bot framework integration with Cisco Webex teams bot.

**Comment by a-b-r-o-w-n** [comment]
@Bradrajkumar Was your issue resolved? If so, we can close this ticket.

**Comment by dmvtech** [comment]
I am able to reproduce this. Thank you @Bradrajkumar 

@garypretty Can I get your input please? This seems to be just some documentation change, but I wanted to check with you on your thoughts and eyes on this.

**Comment by garypretty** [comment]
Yes, I agree it's a docs change. Looks like they slightly altered that portal / process, but should be a simple change.

**Comment by dmvtech** [comment]
Closing as docs issue is now opened. Linked above.
