### ISSUE TITLE
Extension methods for Teams IP notifications

### ISSUE THREAD

**Issue by Jeffders** [microsoft/botframework-sdk#5868]
Microsoft Teams is going to support a PII/IP scrubbing messages using messageDelete and messageUpdate activities. These will signal to the bot that it should remove or alter the message contents that it has stored for that activity. This request is to add helper methods to the Teams SDK portion of the Bot Builder SDK that can identify these operations. Specifically, it needs to be something like:

IsRetentionDeleteMessage 
type == messageDelete
channelData contains: {"ComplianceEventType”, “RetentionDelete”}.

IsDlpBlockMessage
type == messageUpdate
channelData contains {"ComplianceEventType”, “DlpBlock”}.

TODO: Create repo issues for this one once it gets unblocked.

**Comment by gabog** [comment]
@Jeffders, @clearab: do we have what we need to unblock this issue? Otherwise I will remove it from R10 and move it to the backlog.

**Comment by clearab** [comment]
I don't think they are sending these yet - won't be until July

**Comment by gabog** [comment]
If this gets unblocked by 7/13 then it may make it into R10, if not, we will move this one to the backlog.

**Comment by gabog** [comment]
Moving this to the backlog, we should target this for R11

**Comment by cleemullins** [comment]
@tacri Code is there, but only enabled in a feature-flag. @clearab to follow up regarding scale concerns and deployment.

**Comment by clearab** [comment]
@tacri to let us know when to unblock and start implementation

**Comment by cleemullins** [comment]
Checked with @clearab and confirmed this remains blocked. Removing from the R11 iteration.
