### ISSUE TITLE
Add ToAttachment() method to OAuthCard

### ISSUE THREAD

**Issue by navzam** [microsoft/botframework-sdk#5871]
## Version
4.8.0

## Describe the bug
`OAuthCard` does not have a `ToAttachment()` extension method, making it more difficult to use `OAuthCard`s with `MessageFactory.Attachment()`. Other cards have this extension method:
https://github.com/microsoft/botbuilder-dotnet/blob/0908005f49368d04afe6f15a8dea851e7ccd2493/libraries/Microsoft.Bot.Schema/CardEx.cs#L16-L19

# Implementation note
ToAttachment should be added to the OAuthCard type itself since we are not generating these types from swagger anymore. 

## Tracking Status
**Dotnet SDK** (Tracked in [4040](https://github.com/microsoft/botbuilder-dotnet/issues/4040))
- [x] PR
- [x] Merged

**Javascript SDK** (Tracked in [2326](https://github.com/microsoft/botbuilder-js/issues/2326))
- NA, JS uses CardFactory. (@stevengum: "See https://github.com/microsoft/botbuilder-dotnet/issues/638")

**Python SDK** (Tracked in [1121](https://github.com/microsoft/botbuilder-python/issues/1121))
- NA, Python uses CardFactory

**Java SDK** (Tracked in [591](https://github.com/microsoft/botbuilder-java/issues/591))
- [x] PR
- [x] Merged

**Samples** (Tracked in [2517](https://github.com/microsoft/BotBuilder-Samples/issues/2517))
- [x] PR
- [x] Merged

**Comment by gabog** [comment]
We should do this for all the supported languages (JS, dotnet, python and Java)

**Comment by gabog** [comment]
All related tasks have been completed, Closing.
