### ISSUE TITLE
visual studio not deploying code

### ISSUE THREAD

**Issue by doucheface1** [microsoft/botframework-sdk#5873]
When I publish the visual studio sample bot code it runs through then eventually times out.

Once the timeout has occurred it no longer lets me publish again unless I delete everything in azure and start again 

The error I receive when I try to republish after timeout is:

> Your role instances have recycled a number of times during an update or upgrade operation. This indicates that the new version of your service or the configuration settings you provided when configuring the service prevent the role instances from running. Verify your code does not throw unhandled exceptions and that your configuration settings are correct and then start another update or upgrade operation.

**Comment by dmvtech** [comment]
I would suggest opening a ticket in the Azure portal. This does not appear to be related to bot framework sdk/service and is likely something within the Azure infrastructure.

**Comment by doucheface1** [comment]
its not azure its DNS the instructions are not clear on what to use for DNS name  and Cname 
if you use default bot@cloudapp.net for both the above error occurs. i have rerun with bot@cloudapp.net for DNS name and Bot@ourdomain.com for cname and i have created an external cname record that points bot.ourdomain to bot.cloudapp.net

issue i have now is i think certificate.

what needs to be in the cert the dns domain cloudapp.net or the cname domain ourdomain

i cant create a cert thats trusted externally with cloudapp,net in it as this is not our domain

**Comment by dmvtech** [comment]
I'm not sure what you mean by 'use default bot@cloudapp.net for both'. Use it how?

**Comment by dmvtech** [comment]
Are you using this sample?:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/PolicyRecordingBot

If so, this is not a botframework sample and unrelated to the bot framework. This is not he appropriate repository. You could open an issue there.
