### ISSUE TITLE
Update CardAction to support alt text for images on buttons

### ISSUE THREAD

**Issue by corinagum** [microsoft/botframework-sdk#5874]
## Issue
*Describe the issue you are addressing*
Original issue: https://github.com/microsoft/BotFramework-WebChat/issues/2675
Pull request updating schema: https://github.com/microsoft/botframework-obi/pull/71

As an accessibility concern, PromptOptions has been updated in the schema to support alt text on images and buttons. The SDK will need to be updated to reflect this change.

## Proposed change
Update the SDKs to support the `imageAltText` prop. 

## Component Impact 
Web Chat - This fix is slated for R10 in the Web Chat repo.

## Customer Impact 
*Describe the impact on customers*
We have customers using prompt options with in-accessible buttons by screenreaders

## Tracking Status
**Dotnet SDK** (Tracked in [4041](https://github.com/microsoft/botbuilder-dotnet/issues/4041))
- [x] PR
- [x] Merged

**Javascript SDK** (Tracked in [2327](https://github.com/microsoft/botbuilder-js/issues/2327))
- [x] PR
- [x] Merged

**Python SDK** (Tracked in [1122](https://github.com/microsoft/botbuilder-python/issues/1122))
- [x] PR
- [x] Merged

**Java SDK** (Tracked in [592](https://github.com/microsoft/botbuilder-java/issues/592))
- [x] PR
- [x] Merged

**Samples** (Tracked in [2557](https://github.com/microsoft/BotBuilder-Samples/issues/2557))
- [x] PR
- [x] Merged

[dcr]

**Comment by corinagum** [comment]
@gabog would it be possible to get this issue in for R10? The plan is to have the fix in Web Chat for R10 as well.

**Comment by gabog** [comment]
I tagged it so we can prioritize it for R10 (not sure the priority yet)

**Comment by gabog** [comment]
Hi @corinagum, is there any particular sample you suggest we update once we implement this?

**Comment by corinagum** [comment]
@gabog I just realized I was saying PromptOptions but the actual delta is for CardActions. Sorry for the confusion. It looks like using-cards would be the best sample.

**Comment by EricDahlvang** [comment]
I've updated the title from "...for images **and** buttons" to "...for images **on** buttons"
