### ISSUE TITLE
azureBlobTranscriptStore has performance issues and does not reverse order results

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botframework-sdk#5880]
> The problem with this implementation is that, conversation history is pulled from the beginning i.e. if a conversation history is of 100 lines, and I want to load the latest 20 lines, it give me lines 1 to 20 (oldest ones), instead of 81 to 100. Another issue with this implementation is each message is sent via websocket, which is resulting in a long time to load the conversation history.

**Describe the solution you'd like**
A solution that allows for reverse ordering results and has good performance.

**Additional context**
We need a complete story that works well with connector.conversations.sendConversationHistory

[enhancement]

**Comment by gabog** [comment]
Moved to SDK and assigned Gary, we should probably take this, change the title and come up with a good all solution and guidance for handling transcripts.

**Comment by garypretty** [comment]
@cleemullins @mrivera-ms assigning to you for re-assignment. Thanks.

**Comment by EricDahlvang** [comment]
AzureBlobTranscriptStore is now deprecated in place of https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.azure.blobs.blobstranscriptstore Hopefully, this helps with some of the performance issues.. I have not tested to verify any difference.

Nonetheless, the current story around our transcript interfaces and Blob Transcript implementations is that they are not useful for 1) any normal conversation length, nor 2) a conversation history scenario, i.e. the sendConversationHistory api.

We can just close this, with the understanding that our recommendation for bots using sendConversationHistory should just use custom transcript storage implementations.

**Comment by EricDahlvang** [comment]
Also, we are no longer awaiting this Task : https://github.com/microsoft/botbuilder-dotnet/pull/4681  which will certainly address the performance issues! (in an awkward way)
