### ISSUE TITLE
Automation of 72hr reply window notification 

### ISSUE THREAD

**Issue by munozemilio** [microsoft/botframework-sdk#5882]
## Issue
Currently is DRI responsibility to track and remind assignees to reply within the 72 hrs window.
This is a huge time investment which can be beneficial if invested in other areas.

## Proposed change
Automate the notification either through a teams bot or other means.
Notification should be sent periodically until the bug is being addressed and labeled as customer-replied-to or if customer has replied back.
Notification should cover GitHub and ICM issues

## Component Impact 
None

## Customer Impact 
None

[dcr]

**Comment by mdrichardson** [comment]
I'll update this as I go. I'm going to refer to issues with no response and past the 72h-window as "expired issues".

# MVP Features/Deliverables

## Design Goals

- Easy to Expand
- Easy to Maintain

## Bot

- [X] Use OAuth card to grab user GitHub username and user info
- [ ] Use persistent storage to store user data (it's all public on GH, so no need for encryption)
- [ ] When Azure Function gives data, notify auth-ed users via Teams of their expired and expiring issues
- [ ] Allow users to manually remove themselves from notifications
- [ ] Auto-remove users when bot uninstalled
- [ ] Re-alert the user every 3(?) work hours if ticket is still expired

## Azure Functions

- [ ] Periodically scan all GH repos for all issues
  - [ ] Filter issues that are expiring within 72 hours or have already expired
    - [ ] Send these issues to bot

## Features Post-MVP

- [ ] Notify team channel of expiring issues
- [ ] Add ICMs
  - use Teams email
- [ ] Custom notification frequency and topics
  - Maybe some kind of "disable" message that gets sent with each notification
- [ ] Create DevOps board, Power BI, or web page for expiring items

**Comment by munozemilio** [comment]
I will split this into two bugs since the MVP is done.
