### ISSUE TITLE
Remove AutoRest/AutoGen comment from Schema files

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#5887]
Several classes in dotnet and the JS repos were previously autogenerated from [](). We moved away from autogenerating these classes from the swagger file and we are now maintaining them by hand. 

The AutoGen comment at the top of the classes is erroneous and confusing for the the new developer. 

This PR involves:

- Removing the autogen comment from the top of the files (and add the standard copyright to them).
- Update classes to make them easier to maintain. 

In dotnet: 
- Remove the partial declaration for the classes and merge in any *Ex classes.
- Merge any other helper methods into the class (like ToAttachment for example).

In JS: 
- Remove autogen comment
- All these classes are in index.ts, do we break them in separate files to make them easier to maintain parity across repos?

In Python
- Remove autogen comment
- All these classes are in _models.py, do we break them in separate files to make them easier to maintain parity across repos?

## Tracking Status
**Dotnet SDK** (Tracked in [TBD]())
- [x] PR
- [ ] Merged

**Javascript SDK** (Tracked in [TBD]())
- [x] PR
- [x] Merged

**Python SDK** (Tracked in [TBD]())
- [x] PR
- [x] Merged

**Comment by Zerryth** [comment]
Moving to R11 in favor of picking up help of other higher priority issues for R10

**Comment by Zerryth** [comment]
* [bb-dotnet pull#5002](https://github.com/microsoft/botbuilder-dotnet/pull/5002) will partially address this issue, specifically with removing the auto-generated comments
* Will make a separate PR for the second portion for dotnet edits requested to consolidate partial classes into one class each
