### ISSUE TITLE
Id:System.Exception at Microsoft.Bot.ChannelConnector.BotAPI.ThrowOnFailedStatusCode

### ISSUE THREAD

**Issue by kksantosh** [microsoft/botframework-sdk#5888]
Stack : .NET
.NET Framework version : v4.7
Active Channels: Direct Line
Deployment Environment: Azure Bot Service
language : node js
SDK: v4

issue Discription
...................................
when i am testing my bot on directline channel ,it is working fine most of the time, but some bot showing "couldn't send retry" . and i check in directline then it is showing "There was an error sending this message to your bot: HTTP status code InternalServerError"

and when i checked application insight then i can see exception "Id:System.Exception at Microsoft.Bot.ChannelConnector.BotAPI.ThrowOnFailedStatusCode"

please help me solve this issue.
![application insight](https://user-images.githubusercontent.com/45484443/84244448-48b03780-ab21-11ea-821a-f4e7b9f145b8.png)

**Comment by kksantosh** [comment]
@mdrichardson 
> 2. SNAT port exhaustion. Please see [this post](https://github.com/microsoft/botbuilder-js/issues/2054#issuecomment-622194749) for fixing this issue. I believe this may be the real cause of your problem.

Hi please can you give more information about how to solve this issue " SNAT port exhaustion" for my bot ,am using luis and qnamaker.

**Comment by mdrichardson** [comment]
@kksantosh I saw the SNAT port exhaustion in roughly the same time period that  I saw the 500 errors. To fix it, you need to adjust the max sockets and timeout policy as indicated in [the issue I linked](https://github.com/microsoft/botbuilder-js/issues/2054#issuecomment-622194749). You may want to read through the whole thread to get a good understanding of it.

**Comment by kksantosh** [comment]
@mdrichardson  thanks
Hi can you please check this code and tell me where and how can i use this code in my bot solve SNAT port exhaustion issue. I am little bit new in bot development , I don't have much knowledge about this NPM package. how it is work ,and how it will effect bot working functinality. 

const Agent = require('agentkeepalive');
 
const keepaliveAgent = new Agent({
  maxSockets: 160,
  maxFreeSockets: 10,
  timeout: 60000,
  freeSocketTimeout: 30000 // free socket keepalive for 30 seconds
});

let wasAddUserAgent = builder.ChatConnector.prototype.addUserAgent; 
builder.ChatConnector.prototype.addUserAgent = function (options) {
   wasAddUserAgent(options);
   options.agent = keepaliveAgent;
};

**Comment by mdrichardson** [comment]
@kksantosh Don't use the code from the blog post. Use it directly from [the GitHub comment that I linked to](https://github.com/microsoft/botbuilder-js/issues/2054#issuecomment-622194749)

**Comment by mdrichardson** [comment]
To better illustrate, [here's a sample I made that fixes SNAT issues](https://github.com/mdrichardson/snatPortFix) of the [EchoBot sample](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/02.echo-bot). 

And [here's the diff](https://github.com/mdrichardson/snatPortFix/commit/d9aed79fbf3f9aadf041e1f545ac8daa8f4f953f) so you can see what I added/changed.

**Comment by mdrichardson** [comment]
@kksantosh Were you able to get this working? This issue needs to remain active to stay open.
