### ISSUE TITLE
Read receipt conversationUpdate event

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5891]
We need to create a new conversationUpdate event named "messageRead", and the ActivityHandlers to support it.

## Tracking Status
**Dotnet SDK** (Tracked in [4070](https://github.com/microsoft/botbuilder-dotnet/issues/4070))
- [ ] PR
- [ ] Merged

**Javascript SDK** (Tracked in [2355](https://github.com/microsoft/botbuilder-js/issues/2355))
- [ ] PR
- [ ] Merged

**Python SDK** (Tracked in [1135](https://github.com/microsoft/botbuilder-python/issues/1135))
- [ ] PR
- [ ] Merged

**Java SDK** (Tracked in [606](https://github.com/microsoft/botbuilder-java/issues/606))
- [ ] PR
- [ ] Merged

**Adaptive** [TODO]()
- [ ]  Add triggers to the Teams assembly to support this.

**Samples** Update sample 57 on all platforms to showcase read receipt (Tracked in [2533](https://github.com/microsoft/BotBuilder-Samples/issues/2533))
- [ ] PR
- [ ] Merged

**Comment by gabog** [comment]
This feature is currently blocked, review go/no go on 7/13 based on Teams status

**Comment by gabog** [comment]
Teams is not ready for it now, moving this one back to the backlog.

**Comment by clearab** [comment]
@tacri to let us know when to start work on this

**Comment by clearab** [comment]
Closing for now, will re-open if Teams decides to invest in this area.

**Comment by fesaab** [comment]
Hey @clearab and @tacri, it's been some time now but is there any chance of reopening this issue? 

Or maybe is this already implemented? 😄
