### ISSUE TITLE
Additional channel/chat lifecycle events

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5892]
Microsoft Teams is going to begin sending additional chat & channel lifecycle events. We'll need support for:

## This issue involves implementing the following events for Teams:

- channelRestored
- teamArchived 
- teamUnarchived
- teamRestored
- teamDeleted 
- teamHardDeleted

## Payload of the Channel Restore event 

The schema of the payload of the channel restore event will be exactly same as that of the payload of the channel soft delete event. The channel soft delete event sends the following payload to a bot.  

```
{ 
  "type": "conversationUpdate", 
  "timestamp": "2020-05-15T03:53:03.5410579Z", 
  "id": "f:649db706-e94a-b431-0765-730b0d3a2aac", 
  "channelId": "msteams", 
  "serviceUrl": "https://smba.trafficmanager.net/amer/", 
  "from": { 
    "id": "29:1Lx6hT4lmtBkLHf__zwNPIQJOnx5-PGABdzjy9KOqv0Ak1PkeXBNGVTQCdF585TRbp5rC5I5wk7L7sbh3O2DO6A", 
    "aadObjectId": "89c5fbde-8bee-440b-ba8b-898364637a6a" 
  }, 
  "conversation": { 
    "isGroup": true, 
    "conversationType": "channel", 
    "tenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47", 
    "id": "19:ac500d805189491c8b0043c1d3a28f7c@thread.tacv2" 
  }, 
  "recipient": { 
    "id": "28:f53941bb-57fd-402e-8a7b-eb1bd0a708c7", 
    "name": "YunnyTestEchoBot" 
  }, 
  "channelData": { 
    "channel": { 
      "name": "Test1", 
      "id": "19:c73bc51c0d0a42368a0b58033e8a931d@thread.tacv2" 
    }, 
    "team": { 
      "id": "19:ac500d805189491c8b0043c1d3a28f7c@thread.tacv2" 
    }, 
    "eventType": "channelDeleted", 
    "tenant": { 
      "id": "72f988bf-86f1-41af-91ab-2d7cd011db47" 
    } 
  } 
} 
```
 
The only difference between the channel restore event and the channel soft delete event will be the eventType field in ChannelData (the highlighted section). The eventType will be “channelRestored”. 

### Testing channel restored event

You'll need to be a team owner to test this.

1. Install the bot as part of an app in a team in Teams.
2. Delete the channel.
3. `...` > Manage Team > Channels
4. Restore the channel

![image](https://user-images.githubusercontent.com/1139814/84829980-814a8800-afdd-11ea-8717-8d913f25032d.png)

## Other events
These events should be ready to support and test by July 21st.

- teamArchived 
- teamUnarchived
- teamRestored
- teamDeleted 
- teamHardDeleted

The incoming payload to a bot for each event would be the same as that of teamRenamed event, except the value of EventType of TeamsChannelData object. (You can see the payload in my dev spec)
## Tracking Status
**Dotnet SDK** [Issue](https://github.com/microsoft/botbuilder-dotnet/issues/4079)
- [x] PR
- [x] Merged

**Javascript SDK** [Issue](https://github.com/microsoft/botbuilder-js/issues/2367)
- [x] PR
- [x] Merged

**Python SDK** [Issue](https://github.com/microsoft/botbuilder-python/issues/1143)
- [x] PR
- [x] Merged

**Java SDK** [Issue](https://github.com/microsoft/botbuilder-java/issues/611)
- [x] PR
- [x] Merged

**Adaptive** [Issue](https://github.com/microsoft/botbuilder-dotnet/issues/4380)
- [x]  Create new trigger conditions in the teams assembly.

**Docs
- [x] PR
- [ ] Merged

**Comment by gabog** [comment]
Note, we can code this one against the spec.

**Comment by cleemullins** [comment]
We believe this is done in the SDK's, and @clearab will confirm and close this issue out.

**Comment by gabog** [comment]
@cleemullins, we are missing the declarative part, I created and linked an issue to the main description to track that one.
