### ISSUE TITLE
Teams proactive messaging documentation

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5895]
This article needs to be re-written, and to also reference the helper methods for creating a new thread in a channel.

https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/send-proactive-messages?tabs=dotnet

Tracking issues for Teams Docs review - https://github.com/microsoft/botframework-sdk/issues/5896

**Comment by cleemullins** [comment]
@clearab will write this "this week" :)

**Comment by clearab** [comment]
PR is here: https://github.com/MicrosoftDocs/msteams-docs/pull/1972 (it was almost this week ...)
