### ISSUE TITLE
[BF DOCS] Samples Documentation - Review current samples readmes for consistency and accuracy

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-sdk#5897]
Tracking issue for review of Samples readmes for consistency and accuracy.  Consistency review to be carried out across all SDK samples. A shorter list of high priority / more complex samples should be reviewed for accuracy / level of detail provided in the readme, to ensure developers can get from zero to working bot sample (including details on how to use the sample if necessary).

Granular issues should be raised in the Sample repository. 
Please label all issues as R10, BF Docs and add them to the Docs Pillar project too.

Please also tag any new issues with this tracking issue.

**UPDATE: Steps below updated following initial review**

Tracking Status
- [x] Readme consistency review completed and resulting GitHub issue(s) raised
- [x] Standardize / update dotnet README's based on initial review (includes steps to run / further reading)
- [ ] Issue raised for any dotnet sample that likely requires more detail about how to use the sample.
- [ ] Standardize copy from dotnet to JS
- [ ] Standardize copy from dotnet to Python
- [ ] Standardize copy from dotnet to Java

**Comment by tracyboehrer** [comment]
README review:

1) Standardization of layout.  Capitalization, content, etc...
2) Steps to run are slightly wrong on C# (but not in a breaking way)
3) Further reading should be simplified for all of them (each in a unique way).  There is too much there in most cases.
4) Actions (input) user can perform against the bot (see the Teams README's)
 
Steps to rectify:
1) Standardize dotnet README's 
2) Copy to other repo samples, and
    a) Replace steps to run
    b) Adjust any dotnet specific "Further Reading" links

**Comment by garypretty** [comment]
@tracyboehrer this is done now right?

**Comment by tracyboehrer** [comment]
Yes
