### ISSUE TITLE
[BF DOCS] Identify net new documentation and work with docs team to schedule

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-sdk#5899]
Using existing issues and feedback from support team, 1P customers and other sources (Azure support). Understand the top asks in terms of net new docs and work with the docs team to prioritize and schedule.

**Top BF support team topics**

- Guidance on timing out a conversation
- 15s Timeouts and Long Running Operations Guidance (https://github.com/microsoft/botframework-sdk/issues/5500)
- Bot Channels Adapters – what are they? When to use them over ABS?

**Existing issues**

- Expect replies docs / samples https://github.com/microsoft/BotBuilder-Samples/issues/2313
- Timex https://github.com/microsoft/BotBuilder-Samples/issues/1471
- Operators in pre-built functions https://github.com/microsoft/BotBuilder-Samples/issues/2301

**Comment by garypretty** [comment]
Currently awaiting some further feedback from @darrenj and team. Plus meeting with Azure Support this week.

**Comment by darrenj** [comment]
Top of mind:

- Skill Architecture, walk through the callback mechanism which confuses people
- Skill Debugging. Lots of developers struggle will skillhostendpoint, need to use ngrok when debugging local Bot and remote skill. Guidance will go a long way to help this.
- Version Change event (introduced most recently)
- Enabling SSO with WebChat
- Documentation covering CosmosDB changes (create your own container, etc.)
- CosmosDB TTL for conversation state
- More detail/examples on how to pass data to a skill and receive data from a Skill

**Comment by garypretty** [comment]
Feedback received and reviewed. Issues raised and met with pillar and docs team to prioritize and assign.
