### ISSUE TITLE
[BF DOCS] End to end review for top 3 scenarios

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-sdk#5900]
The top 3 developer scenarios / tasks should be identified and for each an end to end review of using the documentation to work through the scenario should be undertaken.  The review will look at content accuracy, discoverability and flow / links between documentation.

New issues resulting from this review should be raised into the BF Docs repository and labelled with ***BF Docs***. They should also be tagged with this root tracking issue, so that we understand their source.

- [ ] Identify top 3 scenarios to be reviewed
    - [x] 1. Create a bot using Adaptive Dialog
    - [ ] 2. Create a bot that uses both type of dialog system
    - [ ] 3. Create a bot using declarative assets
- [ ] Scenario 1 Reviewed and Issues Created
- [ ] Scenario 2 Reviewed and Issues Created
- [ ] Scenario 3 Reviewed and Issues Created

**Comment by garypretty** [comment]
@Kaiqb is this still a separate thing you are planning to do? i.e. working to identify the top scenarios to test against the docs?

**Comment by Kaiqb** [comment]
@garypretty  - Yes, it is a separate task. I've added the three scenarios in the issue above.
