### ISSUE TITLE
[BF DOCS] Docs for process of enabling SSO with webchat

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-sdk#5903]
Feedback from @darrenj as part of R10 docs pillar.

Would be good to provide docs regarding the enabling of SSO with webchat.  

Need to scope to understand if this is a net new doc or an update to existing.

**Comment by mmiele** [comment]
The related PR is: https://github.com/MicrosoftDocs/bot-docs-pr/pull/2279.
