### ISSUE TITLE
Skill Architecture documentation

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-sdk#5904]
Feedback from @darrenj as part of R10 docs pillar.

> When you invoke a Skill from a Bot, the Skill responds back to the caller through a callback (the /api/skills route) on the caller. This mechanism does cause confusion whereby if the developer is debugging a bot locally and invoking a Skill remotely they need to ensure ngrok tunnelling is setup to ensure responses come back.

e.g. walk through the callback mechanism which confuses people

Need to scope to understand if this is a net new doc or an update to existing.

See bot-docs Work for botframework-sdk issue 5904 [PR #2286](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2286):
- [x] Update Concept/Skills/**About skills** > **Conceptual architecture** and **Bot-to-bot authentication**.
- [x] Update Concept/Skills/**About skill consumers** > **Managing skills**.
- [x] Add call-out in How to/Develop/Skills/**Implement a skill consumer** > **Application configuration**.
- [x] Add call-out in How to/Develop/Skills/**Use a dialog to consume a skill** > **Application configuration**.

**Comment by JonathanFingold** [comment]
@gabog to provide base material for this topic by end of next week.

**Comment by JonathanFingold** [comment]
I'll reach out to Darren to see what the request is.

**Comment by JonathanFingold** [comment]
Initial writing for the PR is finished. Now waiting for review.

**Comment by JonathanFingold** [comment]
PR merged.
