### ISSUE TITLE
Document new Version Changed event in adaptive

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-sdk#5905]
Feedback from @darrenj as part of R10 docs pillar.

Currently no documentation exists regarding the new Version Changed event in adaptive.

This is likely to be an update to the existing adaptive docs.

**Comment by garypretty** [comment]
Pending assignment to Steve on the docs team once he is back in the office and has accepted invitation to join this repo. cc @Kaiqb

**Comment by garypretty** [comment]
Un-assigning from @JonathanFingold - as per notes above this is to be assigned to Steve once he accepts invitation to the repo.

**Comment by cleemullins** [comment]
Assigning to @garypretty  as a placeholder to track this. :) Once Steve accepts, we can re-assign.

**Comment by garypretty** [comment]
Closing as docs have been updated with appropriate references and are awaiting push to live.
