### ISSUE TITLE
[BF DOCS] Update .NET Getting Started Docs to include instructions / ref to .NET Core templates

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-sdk#5910]
We don't currently reference the availability of the .NET Core templates in this getting started doc for .NET https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-sdk-quickstart?view=azure-bot-service-4.0

We have good instructions over in the readme https://github.com/microsoft/BotBuilder-Samples/tree/master/generators/dotnet-templates. 

We should consider updating the doc to show both options for folks who are looking to get started - or alternatively find somewhere else in the official docs to reference and hold instructions for these templates.

**Comment by mmiele** [comment]
Work in progress see PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/2264

**Comment by mmiele** [comment]
Completed.

**Comment by garypretty** [comment]
Excellent update. Thanks for your work on this.
