### ISSUE TITLE
Document changes to Teams schema objects

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#5912]
In particular look at:
- TeamDetails
- TeamsChannelAccount

And ensure the current documentation aligns with the schema.

**Comment by cleemullins** [comment]
Confirmed with @clearab that these objects have changes, and the docs need to reflect that. Trying to land in R10.

**Comment by cleemullins** [comment]
Confirmed with @clearab that this is on-track for landing in R11.

**Comment by clearab** [comment]
This is not a release blocker (no code changes) documentation will be updated next week (first week Nov)
