### ISSUE TITLE
TypeScript versions of all Teams samples. (As from community + Teams group)

### ISSUE THREAD

**Issue by garypretty** [microsoft/botframework-sdk#5913]
@clearab to add priority order for samples.
@EricDahlvang to re-assign as appropriate to support team.

(checked indicates PR submitted)

- [x] 57.teams-conversation-bot 
- [x] 58.teams-start-new-thread-in-channel
- [x] 50.teams-messaging-extensions-search
- [x] 51.teams-messaging-extensions-action

no priority order samples:
- [ ] 46.teams-auth
- [ ] 52.teams-messaging-extensions-search-auth-config
- [ ] 53.teams-messaging-extensions-action-preview
- [ ] 54.teams-task-module (this needs to have iframed based Task Modules as well, sync with Tracy)
- [ ] 55.teams-link-unfurling
- [ ] 56.teams-file-upload

**Comment by EricDahlvang** [comment]
Spoke with @stevkan ... he said he will start with 57.teams-conversation-bot

**Comment by clearab** [comment]
Priority order would be 57, 58, 50, 51, then the rest in any order
