### ISSUE TITLE
Change the main branch to `main` and remove the `master` branch on all repos

### ISSUE THREAD

**Issue by benbrown** [microsoft/botframework-sdk#5918]
We should change the name of our main branch to `main` on all of the Bot Framework SDK repos.

We will need to update CI/CD pipelines and things triggered off of that specific branch name.

Here are the instructions:
https://help.github.com/en/github/administering-a-repository/setting-the-default-branch

- [x] [SDK](https://github.com/microsoft/botframework-sdk)
- [x] [DotNet](https://github.com/Microsoft/botbuilder-dotnet)
- [ ] [JS](https://github.com/Microsoft/botbuilder-js)
- [x] [Python](https://github.com/Microsoft/botbuilder-python)
- [x] [Java](https://github.com/microsoft/botbuilder-java)
- [x] [CLI](https://github.com/Microsoft/botframework-cli)
- [x] [Samples](https://github.com/microsoft/botbuilder-samples)
- [ ] [Docs](https://github.com/MicrosoftDocs/bot-docs-pr/) Note: I don't think we own this repo, not sure who needs to change it
- [ ] [Tools](https://github.com/Microsoft/botbuilder-tools)
- [ ] [Emulator](https://github.com/microsoft/BotFramework-Emulator)
- [ ] [WebChat](https://github.com/microsoft/BotFramework-WebChat)
- [x] [Composer](https://github.com/microsoft/botframework-composer)
- [x] [Functional Tests](https://github.com/microsoft/BotFramework-FunctionalTests)
- [x] [OBI](https://github.com/microsoft/botframework-obi)
- [ ] [VA](https://github.com/microsoft/botframework-solutions)

**Comment by gabog** [comment]
Hi @benbrown, I think this has been done in several repos, can we close this issue or update it with tracking checkboxes to track which repos have been renamed and which ones are left?

**Comment by benbrown** [comment]
Sure thing, @gabog! Thanks for doing the laborious work to get this done!

**Comment by gabog** [comment]
I didn't do it @benbrown, the different repo owners did it :-). 

In any case, I updated the issue description with a list of the repos I know and checked the ones that are done, would you be able to help reaching out to the repo owners of the ones that are not done and see if they can do it? 

Thanks 

PS: feel free to add any repos if I missed any of them.

**Comment by benbrown** [comment]
LOL I misread. I just assume you are out there busting chops on this. :)

Yes, I can do some reachouts! On it.
