### ISSUE TITLE
[BF DOCS] : Handoff” event is not supported on Microsoft Teams Channel (or probably events in general) 

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/botframework-sdk#5920]
From CSS:
“Handoff” event is not supported on Microsoft Teams Channel (or probably events in general) , users are experiencing (400) Bad request whenever used. 

https://icm.ad.msft.net/imp/v3/incidents/details/191012167/home this document here indicates that it is working on all channels :

https://docs.microsoft.com/en-us/azure/bot-service/bot-service-design-pattern-handoff-human?view=azure-bot-service-4.0 

handoff sample code indicates the same :
https://github.com/microsoft/BotBuilder-Samples/tree/master/experimental/handoff-library
this doc states that “HandOff” activity is not enabled on any channel , but it is enabled on webchat at least , so this indicates a conflict as well https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0#summary-table-all-activities-to-all-channels

**Comment by mmiele** [comment]
Gary, I created a preliminary FAQ entry [here](https://review.docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-faq-general?view=azure-bot-service-3.0&branch=pr-en-us-2267#how-to-deal-with-an-outbound-handoff-activity)

**Comment by mmiele** [comment]
Pressed wrong button.

**Comment by mmiele** [comment]
@garypretty Please, assign this issue to me. I am working on it.

**Comment by mmiele** [comment]
Completed. 
Related PR https://github.com/MicrosoftDocs/bot-docs-pr/pull/2277 has been merged.

**Comment by garypretty** [comment]
Looks good. Thank you.
