### ISSUE TITLE
[BF DOCS] Single sign-on with existing auth

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/botframework-sdk#5922]
From CSS: Single sign-on with existing auth (like webchat on a share point site). A tutorial view to https://blog.botframework.com/2018/08/28/sign-in-experiences/

**Comment by mmiele** [comment]
This issue has been addressed in R9. Please, see [Single sign on](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-sso?view=azure-bot-service-4.0) and [Add single sign on to a bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication-sso?view=azure-bot-service-4.0&tabs=csharp%2Ceml) articles.
