### ISSUE TITLE
[BF DOCS] Config steps for Azure Gov 

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/botframework-sdk#5923]
From CSS: Webchat and Directline config steps for Azure Gov (I would prioritize this low)

**Comment by garypretty** [comment]
@Kaiqb @JonathanFingold I don't think we decided who this would be assigned to in our call. Assigned to @Kaiqb temporarily, but can you re-assign to someone on the team please?

**Comment by zxyanliu** [comment]
@garypretty Who can I reach out for resources working on this article?

**Comment by garypretty** [comment]
@Kaiqb do you have someone in mind for this one?

**Comment by Kaiqb** [comment]
@garypretty  - this is assigned to @zxyanliu but she needs help getting access to Azure Gov.

**Comment by garypretty** [comment]
@NickEricson can you help with access to gov? Or point to someone who can?

**Comment by NickEricson** [comment]
+ @willportnoy and @swagatmishra2007 

Are you looking for instructions on how to configure WebChat in Gov or how to create your own account there?

**Comment by zxyanliu** [comment]
I might need a Fairfax DevOps NonRestricted account for non-FTE to try out "gov" things. @Kaiqb 
https://aka.ms/fairfaxonboard -> https://msazure.visualstudio.com/One/_wiki/wikis/One.wiki/8650/Sovereign-Cloud-Onboarding?anchor=get-a-devops-test-account-%26-subscription -> get a DevOps NonRestricted account
