### ISSUE TITLE
[BF DOCS] Security Best Practices for Bots hosted in Azure 

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/botframework-sdk#5924]
From CSS: Security Best Practices for Bots hosted in Azure (We have here and there documentation on IP whitelisting, restricting to a specific region etc but it would be great to have a collated list)

**Comment by mmiele** [comment]
See PR: https://github.com/MicrosoftDocs/bot-docs-pr/pull/2271.

**Comment by mmiele** [comment]
The related PR: [MicrosoftDocs/bot-docs-pr#2271](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2271) has been merged

**Comment by mmiele** [comment]
@Kaiqb This info should suffice. We can make updates as needed.
