### ISSUE TITLE
[BF DOCS] Guidance on using Async/Proactive

### ISSUE THREAD

**Issue by Kaiqb** [microsoft/botframework-sdk#5925]
From CSS: Language specific guidance on using Async, Proactive messages etc to workaround the 15 seconds timeout problem

**Comment by EricDahlvang** [comment]
this might be a dup of https://github.com/microsoft/botframework-sdk/issues/5500

**Comment by garypretty** [comment]
As @EricDahlvang says, this is a dup of #5500 . Closing.
