### ISSUE TITLE
SDK architecture diagram

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botframework-sdk#5934]
- **Purpose**: a logical way to organize and present documentation about the different features.
- **Audience**: developers and architects who want to understand how parts of the SDK relate to each other. (There are at least 3 ways to control conversation flow within the SDK proper: adaptive dialogs, dialogs, activity handler, custom logic.)

We have different levels of abstraction: bot-builder > dialogs > adaptive dialogs; and we also have other types of compartmentalization: app insights vs AI vs adaptive expressions, etc. If we define logical buckets for these, it will be easier to frame associated articles within the doc set.

@JonathanFingold  or @mmiele can be the doc team contact for this.

**Comment by JonathanFingold** [comment]
We're kicking around a diagram that has two layers/levels: _protocol_ and _behavioral_. Behavioral has dialogs and language generation components; protocol has everything else. Protocol is additionally broken into Bot Framework and stand-alone components.

**Comment by JonathanFingold** [comment]
Here are the initial rough drafts:
![ecosystem](https://user-images.githubusercontent.com/35047199/86816992-5631e200-c039-11ea-9eb0-638dc6149c08.png)
![bot-apps](https://user-images.githubusercontent.com/35047199/86817150-7bbeeb80-c039-11ea-9aef-b8e33f274334.png)
![bot-framework-sdk](https://user-images.githubusercontent.com/35047199/86817157-7cf01880-c039-11ea-93fb-631e3b72f556.png)
![tools-and-services](https://user-images.githubusercontent.com/35047199/86817159-7e214580-c039-11ea-9e61-8e746b5f86f7.png)

**Comment by johnataylor** [comment]
We made some progress on this. This work will conclude in the R11 timeframe. Removing the R10 label.

**Comment by JonathanFingold** [comment]
Working with simplified architecture diagrams to start with, without adding a specific architecture article. An updated version of the first concept article, **How bots work**, is the closest we will have in the near term.

![what-is-a-bot](https://user-images.githubusercontent.com/35047199/94298076-5cd64400-ff1a-11ea-8e05-98ba029b1181.png)
![how-bots-work](https://user-images.githubusercontent.com/35047199/94298099-65c71580-ff1a-11ea-9cd2-95388a112ec7.png)

**Comment by JonathanFingold** [comment]
A version of the two simplified diagrams have been added in master and should go live with the new live-sync (bot-docs-pr PR [2404](https://github.com/MicrosoftDocs/bot-docs-pr/pull/2404)).
