### ISSUE TITLE
how can i download whole Knowledgebase by hitting qnamaker api in both environment prod and test

### ISSUE THREAD

**Issue by kksantosh** [microsoft/botframework-sdk#5944]
i am trying to download whole Knowledgebase by hitting APIs but i am getting error 404. i am refering this https://westus.dev.cognitive.microsoft.com/docs/services/5a93fcf85b4ccd136866eb37/operations/knowledgebases_download.

i am using url:
https://(resource name).azurewebsites.net/qnamaker/v4.0/knowledgebases/(kb id)/Prod/qna
Authorization : EndpointKey (key)
Content-Type : application/json

**Comment by scheyal** [comment]
@pchoudhari, can you please respond to the inquiry?

**Comment by pchoudhari** [comment]
@kksantosh , 404 response means that the knowledge base wasn't found. Can you check in the qnamaker.ai portal if the KB still exists?

**Comment by kksantosh** [comment]
@pchoudhari yes I am 100% sure KB present, actually i am using in bot for questioning and answering and it is working.

**Comment by pchoudhari** [comment]
@kksantosh , please check the parameters of the request. If it still doesn't work, please drop a mail with details of the request to qnamakersupport@microsoft.com

**Comment by sunilsoniudaipur** [comment]
Getting issue while downloading the data form QNA

https://botname.azurewebsites.net/qnamaker/v4.0/knowledgebases/kbid/prod/qna

but it is returning 404, QNA data is present, able to get questions and answers using bot. but when trying to get all data download API returns 404. however generate answer API endpoint is working fine.
