### ISSUE TITLE
Session Time Out

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botframework-sdk#5947]
As a request from HR we need a bot to be closed after 15 mins of inactivity. Basically the session should be destroyed, or even better a timeout trigger to be called, where we can define our own logic to deal with session data, re-authentication, saying sorry to the user  etc..

Is there any mechanism in place for this yet? If not any work arounds? I did raise a question about using a trigger that allows you to check authorization on each type of activity, that I could use for this, but that's also not answered yet: microsoft/BotFramework-Composer#3379

**Comment by EricDahlvang** [comment]
Hi @cxbuilders 

We have an issue tracking work to provide documentation of options for this here: https://github.com/microsoft/botframework-sdk/issues/5908

Please review the options provided on that issue, and add any suggestions or feedback there.


Closing this as a duplicate.
