### ISSUE TITLE
OAuthPrompt should provide the ability to cancel itself

### ISSUE THREAD

**Issue by EricDahlvang** [microsoft/botframework-sdk#5964]
## Issue
Example Scenario-
User says : “login”
Bot says : OAuthCard
User says : “I want to enter a number”

Expected behavior – OauthPrompt completes and “I want to enter a number” Activity is handled by the next Prompt/Dialog in the Dialog stack.

## Tracking Status
**Dotnet SDK**
https://github.com/microsoft/botbuilder-dotnet/issues/4395
- [x] PR
- [x] Merged

**Javascript SDK**
https://github.com/microsoft/botbuilder-js/issues/2651
- [x] PR
- [x] Merged

**Python SDK**
https://github.com/microsoft/botbuilder-python/issues/1320 
- [x] PR
- [x] Merged

[dcr]

**Comment by stevengum** [comment]
@swagatmishra2007 and @carlosscastro can you provide more context on this ask? Interruptions and cancellations are already possible at the DialogContainer level, which is likely where you'd want to handle the interruption.

The enhanced OAuthPrompt wouldn't know about the other Prompts or Dialogs being used in the DialogContainer, nor does it have the necessary logic built-in to disambiguate which Dialog it should call.

The current model is:

1. User initiates OAuth flow
    a. Activity likely goes through DialogContainer (e.g. DialogManager, ComponentDialog)
    b. DialogManager begins OAuthPrompt, sends card to user

2. User interrupts/cancels OAuth flow `"I want to enter a number"`
    a. Activity routes to DialogManager
    b. DM determines next dialog to call
    c. DM replaces current OAuthPrompt with appropriate Dialog via DialogContext.ReplaceDialogAsync ([.NET](https://docs.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.dialogs.dialogcontext.replacedialogasync?view=botbuilder-dotnet-stable#Microsoft_Bot_Builder_Dialogs_DialogContext_ReplaceDialogAsync_System_String_System_Object_System_Threading_CancellationToken_), [JS](https://docs.microsoft.com/en-us/javascript/api/botbuilder-dialogs/dialogcontext?view=botbuilder-ts-latest#replacedialog-string--object-), [Py](https://docs.microsoft.com/en-us/python/api/botbuilder-dialogs/botbuilder.dialogs.dialog_context.dialogcontext?view=botbuilder-py-latest#replace-dialog-dialog-id--str--options--object---none-----botbuilder-dialogs-dialog-turn-result-dialogturnresult))

**Comment by cleemullins** [comment]
Discussion with @clearab, @tacri , Sid, and Eric - Andrew will write a spec for this before any next steps.

**Comment by clearab** [comment]
Best we can come up with is to add a flag to OAuth prompt and document needing to set it.

**Comment by clearab** [comment]
JS is in PR

**Comment by EricDahlvang** [comment]
@clearab js is merged (special thanks to @munozemilio !!!)
