### ISSUE TITLE
DCR: proposal for a tweek to the skills protocol

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#5970]
The current PostBack based skills protocol works well for activities but it's extremely brittle when it comes to conveying that a skill has ended.  The first issue is that in order to even make it work the Skill Dialog has to ensure that it's saved off all of its conversation state prior to calling the skill because the `EoC` activity will be posted back and may not even be the calling bot that processes the EoC activity.  That sets up the next issue is that the calling bot has to be super careful not to touch its bot state after its called the skill otherwise it risks clobbering the state changes that resulted from the EoC being processed. And the third issue is that interruptions can result in multiple skills being invoked simultaneously within a conversation so there's race conditions being setup and its possible for an EoC to wind up ending the wrong skill invocation.

Using `expectReplies` mode works around these control flow issues but comes with its own issues because things like activity id's aren't returned for SendActivity calls.  I would propose we consider a hybrid approach for the PostBack mode which has most channel calls work as they do today but only ever conveys EoC as an expect replies response.  That would mean we a) no longer need to pre-save the conversation state because the EoC would **always** be detected by the calling thread. And b)  there would be no unusual race conditions because each skill invocation could only ever clean up itself.  

[dcr]

**Comment by gabog** [comment]
referenced this issue in #5930 (this feature request should be considered as part of resolving that).
closing it.
