### ISSUE TITLE
Delay Activity type not referenced in the Bot Framework Activity spec 

### ISSUE THREAD

**Issue by joe-tossell-mando** [microsoft/botframework-sdk#5971]
## Issue
The delay Activity type referenced in documentation is not referenced in the Bot Framework Activity spec see documentation:
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-send-messages?view=azure-bot-service-4.0&tabs=csharp

Not sure whose issue this is see:
https://github.com/MicrosoftDocs/bot-docs/issues/1849 

## Proposed change
Include delay activity in spec

## Component Impact 
https://github.com/microsoft/botframework-sdk/blob/master/specs/botframework-activity/botframework-activity.md

## Customer Impact 
Allows bots to pace activity responses in a more natural way.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Java SDK**
- [ ] PR
- [ ] Merged

**Python SDK**
- [ ] PR
- [ ] Merged

**Emulator**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Tools**
- [ ] PR
- [ ] Merged

[dcr]

**Comment by daveta** [comment]
Hi @joe-tossell-mando :
The answer by Jonathon [here](https://github.com/MicrosoftDocs/bot-docs/issues/1849#issuecomment-669295816) is correct.  The spec you reference is more about the wire protocol..
Thanks, -Dave
