### ISSUE TITLE
Node BotFramework SDK 4.9.3: rawLocalTimestamp time zone is not updated on time zone change.

### ISSUE THREAD

**Issue by SiarheiKuchukBelitsoft** [microsoft/botframework-sdk#5973]
Hello

I have an issue with extracting time zone from rawLocalTimestamp for Node BotFramework SDK 4.9.3
For example I'm in Minsk.
That code
(<any>context.activity).rawLocalTimestamp
shows
...19:00+03:00

If i change the time zone in Windows Clock to UTC+01
and then send message to Bot, it will get from TurnContext
...19:01+03:00

But if i restart Teams Desktop app, it works fine, i.e. it will show
...19:01+01:00

Can you please adjust time zone on each message in Teams Desktop app.

**Comment by SiarheiKuchukBelitsoft** [comment]
Another big issue with rawLocalTimestamp - that after update Bot to SDK with that feature, users have to relogin to Teams so bot will start getting on backend that field. Please fix it,because noone from customers is going to relogin on bot update!

**Comment by clearab** [comment]
Hi - This is unfortunately an issue with the Teams client itself, not the Bot Framework SDK. I've created a new Issue at the link below so that their product team can reply directly:

https://github.com/MicrosoftDocs/msteams-docs/issues/1950
