### ISSUE TITLE
Text Format In Adaptive Card Broken

### ISSUE THREAD

**Issue by wbinterns** [microsoft/botframework-sdk#5974]
I raised this issue elsewhere, as I thought it was a problem with the qnamaker, so here is the link to that previous [issue](https://github.com/MicrosoftDocs/azure-docs/issues/58810). However, after some discussion it seems that the only difference is in my bots code, and thus more of a SDK issue.

After doing some testing with my current bot, and an example which can be seen [here](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/49.qnamaker-all-features), I have found that the result of the query to the QnaMaker depends on the way used to contact the bot.

For example, in my current bot, I am using the following code to send the response to the user

```c#
await dialogContext.Context.SendActivityAsync(activity).ConfigureAwait(false);
```

Where the activity is a custom class that takes the answer and prompts of the query and makes it into a hero card, as shown:

```c#
public static Activity GetHeroCard(string cardTitle, QnaMakerPrompt[] prompts)
{
    var chatActivity = Activity.CreateMessageActivity();
    var buttons = new List<CardAction>();

    var sortedPrompts = prompts.OrderBy(r => r.DisplayOrder);

    foreach (var prompt in sortedPrompts)
    {
        buttons.Add(
            new CardAction()
            {
                Value = prompt.DisplayText,
                Type =  ActionTypes.ImBack,
                Title = prompt.DisplayText,
            });
    }

    var plCard = new HeroCard()
    {
        Title = cardTitle,
        Buttons = buttons
    };

    var attachment = plCard.ToAttachment();

    chatActivity.Attachments.Add(attachment);

    return (Activity)chatActivity;
}
```

Which yields the following result:
![menulist](https://user-images.githubusercontent.com/51494903/89557211-172db280-d7d8-11ea-810e-08ada0a16945.png)

But then if I use the function from the example, which sends responses to the user by using:

```c#
protected async override Task<IQnAMakerClient> GetQnAMakerClientAsync(DialogContext dc)
{
    Microsoft.Bot.Builder.AI.QnA.QnAMaker response = this._services?.QnAMakerService;
    return response;
}
```

I get the correct, following response:
![menucorrectformat](https://user-images.githubusercontent.com/51494903/89558710-2dd50900-d7da-11ea-9755-19bf1cbc4624.PNG)

Previously, the format within the herocard had worked as intended-it is my assumption that some update to the sdk is causing this issue.

Any help or insights would be appreciated.

NOTE: I am aware the two pictures show different items (A, B) compared to (C, D). The QnAPrompts are exactly the same aside from that simple different.

**Comment by v-kydela** [comment]
Thank you for the report, @wbinterns 

It looks to me like the text in the first screenshot is contained inside the card, and the text in the second screenshot is outside the card. It is indeed possible that there has been a change in whatever channel connector service you're using that affects how cards are interpreted.

About this code:

> ```c#
> protected async override Task<IQnAMakerClient> GetQnAMakerClientAsync(DialogContext dc)
> {
>     Microsoft.Bot.Builder.AI.QnA.QnAMaker response = this._services?.QnAMakerService;
>     return response;
> }
> ```

That doesn't create a card, that just returns a QnA Maker client. If you can find the code that creates the card, you can try logging the card somehow so you can examine the object and see how it differs from yours. It seems possible that it creates an activity with both text and a card attachment.

So I need a few things from you to investigate further.

1. What channel are you using?
1. What is the activity that gets created in the second screenshot?
1. Why isn't using the code that generates the second screenshot an acceptable solution for you?

**Comment by wbinterns** [comment]
Sure thing,

1.	I am using the “Web Chat” channel

2.	Below I have printed out much of the information contained in the Activity, where dc is a DialogContext

dc.Context.Activity.Action: 
dc.Context.Activity.AttachmentLayout: 
dc.Context.Actiivty.Attachments: 
dc.Context.Activity.CallerId: urn:botframework:azure
dc.Context.Activity.ChannelData: {
  "clientActivityId": "1596812792491.01754727424765079.0"
}
dc.Context.Activity.ChannelId: webchat
dc.Context.Activity.Code: 
dc.Context.Activity.DeliveryMode: 
dc.Context.Actiivty.Entities: 
--->ent.Type: ClientCapabilities
dc.Context.Activity.From: 
--->dc.Context.Activity.From.AadObjectId: 
--->dc.Context.Activity.From.Id: 15968127740510.ccqiwopjfrw
--->dc.Context.Activity.From.Name: <my-name>
--->dc.Context.Activity.From.Role: 
dc.Context.Activity.HistoryDisclosed: 
dc.Context.Activity.Id: ImlvFQifAqc2mxT8UwWu8S-6|0000003
dc.Context.Activity.Importance: 
dc.Context.Activity.InputHint: 
dc.Context.Activity.Label: 
dc.Context.Activity.Locale: en-US
dc.Context.Activity.MembersAdded: 
dc.Context.Activity.Name: 
dc.Context.Activity.ReplyToId: 
dc.Context.Activity.ServiceUrl: https://directline.botframework.com/
dc.Context.Activity.Speak: 
dc.Context.Activity.Summary: safety-general (not important for now, but this is how I determine which QnaMakers to call)
dc.Context.Activity.Text: menu
dc.Context.Activity.TextFormat: plain
dc.Context.Activity.TopicName: 
dc.Context.Activity.Type: message
dc.Context.Activity.Value: 
dc.Context.Activity.Value:

3.	There are a few reasons:
a.	For one, sometimes I wish to respond with my own custom cards given certain responses. In my current bot, I check for certain responses from the bot, say “TEST-CARD”, and then return the Activity generated by the GetHeroCard method. For this, I need to be able to edit the response after the call to the KnowledgeBase, but before it is returned to the user.
b.	I have a special case where I am querying multiple QnaMaker Kb’s for the same question. In the new version that works, I am unable to do this. For it to work, I would need to be able to edit how the query to the KnowledgeBase is sent.
c.	Even if I find a way to resolve these issues, I would have to remake the bot using this new code. If at all possible, I would hope this is a small error that I can correct on my current bot, without having to remake it.
In both of these cases I am unable to access the data I need, because as you state, it only returns a QnAMaker Client. I have not yet been able to find a function or method that allows me to edit or view the response or request in anyway, and thus edit it to my liking. From my point of view, after the code snippet above, I am not sure when the call to the KB takes place. The QnAClient is returned, and then I assume it queries the Knowledge Base? I just don’t see where that logic happens.

**Comment by v-kydela** [comment]
@wbinterns - Thank you for the information. It looks like you've shown me a user-to-bot activity instead of the bot-to-user activity that actually contains the card attachment, but it's okay because I've tracked that down for you. While running sample 49 in Emulator, you can see the activity in the JSON panel:

![image](https://user-images.githubusercontent.com/41968495/89678037-5543d880-d8a3-11ea-808d-b797c74daa83.png)

As I suspected, the hero card only contains buttons. The rest of the text is in the activity's text property. You can see how this is implemented in the [Bot Builder source code](https://github.com/microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.AI.QnA/Utils/QnACardBuilder.cs#L85-L124):

```c#
public static IMessageActivity GetQnAPromptsCard(QueryResult result, string cardNoMatchText)
{
    if (result == null)
    {
        throw new ArgumentNullException(nameof(result));
    }

    if (cardNoMatchText == null)
    {
        throw new ArgumentNullException(nameof(cardNoMatchText));
    }

    var chatActivity = Activity.CreateMessageActivity();
    chatActivity.Text = result.Answer;
    var buttonList = new List<CardAction>();

    // Add all prompt
    foreach (var prompt in result.Context.Prompts)
    {
        buttonList.Add(
            new CardAction()
            {
                Value = prompt.DisplayText,
                Type = "imBack",
                Title = prompt.DisplayText,
            });
    }

    var plCard = new HeroCard()
    {
        Buttons = buttonList
    };

    // Create the attachment.
    var attachment = plCard.ToAttachment();

    chatActivity.Attachments.Add(attachment);

    return chatActivity;
}
```

You can use the source code as an example of how to implement this yourself. Does this resolve your issue?

**Comment by wbinterns** [comment]
I will look into this now and get back to you. Apologies for the confusion about the activity.

**Comment by wbinterns** [comment]
After making some minor type changes and resolving some other mine issues, using the Bot Builder Source Code listed above worked like a charm. Thank you kindly!
