### ISSUE TITLE
Add methods for dealing with mentions of Teams, Channels or Tags (Teams)

### ISSUE THREAD

**Issue by matthiasdilger** [microsoft/botframework-sdk#5975]
**Is your feature request related to a problem? Please describe.**
Teams users can mention Team names, channel names or tags when sending a message to the bot like this:

`@bot send a message to all members of @test
`

The bot receives this mention like so (@test is a tag in Teams):

```
[
  {
    mentioned: {
      id: '29:162Hx5WtM8cgUFFPBbUiJ2svduwb2P3RmuXzcqNgN-ZE',
      name: 'test'
    },
    text: '<at>test</at>',
    type: 'mention'
  }
]
```

But the bot can't do anything with this mention. It can't resolve the list of users using the mention id. It can't even figure out whether it's a team, channel or tag. All it can do is get an error when calling a method like TeamsInfo.getMember so that it knows that the mention is not a user. The mention is seems to be different than the usual "Teams id" (19:xxx).

The bot can reply using the mention above (the server accepts the message with the mention) but the Teams client does not properly recognize/highlight the mention and does not notify the users (not sure if because of spamming concerns).

**Describe the solution you'd like**
Implement methods to:

- Translate the mention to a mention type (user, team, channel, tag)
- Get the "Teams id" (19:xxx) for that mention id (29:xxx) and then
- Get the list of users for that team/channel/tag (this already partially works for channels with getPagedMembers)

Allow the bot to mention teams, channels or tags and notify all users. Just like when a normal users mentions a tag, those users get a notification.

[enhancement]

**Comment by clearab** [comment]
Hi - I've spoken to the Teams team about this and it is something they are interested in but would be a longer feature request that they'd need to prioritized against other things in their backlog. So this doesn't get lost I'm going to move this over to their repo so they can track it.

Good idea, and thanks for the feedback!

**Comment by matthiasdilger** [comment]
Hi @clearab, it seems the issue you opened was closed without comment and is now locked, so I can't comment. It seems none of the functionality I suggested was implemented, is that correct?

**Comment by clearab** [comment]
I don't think they've done any work on this yet, no. The aren't open source, so they do not normally track long-running feature requests through GitHub (they use UserVoice for that). If you'd like to inquire further with them, you can do so using one of the methods outlined here: https://aka.ms/teamsdevfeedback.
