### ISSUE TITLE
Token exchange endpoint not called with refresh_token

### ISSUE THREAD

**Issue by GDreyV** [microsoft/botframework-sdk#5990]
Might be related to the https://github.com/microsoft/botframework-sdk/issues/3705
Related question: https://stackoverflow.com/questions/63442894/microsoft-teams-bot-debug-refresh-token-flow

While development of a Microsoft Teams Bot I faced a problem that refresh token endpoint is never called. I believe it's my mistake in configurations but I can't find any details what exactly is going wrong. What I did:

- Set Token Exchange URL in bot settings on Azure side

- Set scopes to `email offline_access`
- Checked that `refresh_token` was issued: I see in logs that `code` was issued:
```
{
  "code": "[removed for security reasons]",
  "grant_type": "authorization_code",
  "redirect_uri": "https://token.botframework.com/.auth/web/redirect",
  "client_id": "microsoft-teams-bot",
  "client_secret": "[removed for security reasons]"
}
```
and after that `refresh_token` was obtained by the `code`:
```
{
  "scope": "email offline_access",
  "token_type": "Bearer",
  "access_token": "[removed for security reasons]",
  "expires_in": 3600,
  "refresh_token": "[removed for security reasons]"
}
```
but `refresh_token` is never used after that - `Token Exchange URL` never get called.

So finally when I handle request from the bot I can't obtain token:
```
await (turnContext.Adapter as IUserTokenProvider).GetUserTokenAsync(turnContext, this.connectionName, string.Empty, cancellationToken: cancellationToken)
```
returns `null`.

Any ideas what might be wrong?

**Comment by lauren-mills** [comment]
@stevkan - can you provide a status here?

**Comment by GDreyV** [comment]
Please let me know if you need additional details like bot id or anything else.
I managed to reproduce the issue locally but also see the issue on production environment - there is no calls on token exchange url in nginx access log (so it's not application level).

**Comment by GDreyV** [comment]
@stevkan, I'm tasting using two bots: f1d676ab-0d2c-4afe-a9be-0af4528949ce is more production and for local testing fc6bb881-643e-4990-8e22-c188f9138e17.

For both bots token exchange url is set on "OAuth Connection Settings" page. I added new oauth provider and filled in all fields. To issue token I'm using https://github.com/openiddict/openiddict-core library. I'm not sure what you mean retrieved? As I understand Bot's backend calls token endpoint with `code` provided with login redirect.

Yes, I debugged in and it works like that: let's say I'm issuing access token which works for 5 minutes. In that 5 minutes I'm getting valid token. As soon as 5 mins pasts `await` code I shared above returns `null`.

**Comment by stevkan** [comment]
Which service provider from the list did you choose and can you provide me with the values you populated it with (don't post any actual secret/key values)?

As for the `openiddict` library, could there be a default token expiry value being passed in? Given that the token disappears at 5 mins seems suggestive of that. Or, perhaps the token is getting refreshed resulting in a `null` value on the original (probably unlikely, but worth checking)?

**Comment by GDreyV** [comment]
I selected `Generic Oauth 2` and values are:
Name: oauth-provider
Client id: microsoft-teams-bot
Client secret: ***
Authorization URL: https://domain.io/connect/authorize
Token URL: https://domain.io/connect/token
Refresh URL: https://domain.io/connect/refresh
Token Exchange URL: https://domain.io/connect/token
Scopes: email offline_access

The problem was that I was looking at exchange endpoint but the bot is using refresh endpoint to obtain access token with refresh token.

Thank you for your help! As I said it was my silly mistake :)
