### ISSUE TITLE
TaskModuleResponseBase.type is missing an enum

### ISSUE THREAD

**Issue by armiantos** [microsoft/botframework-sdk#5996]
## Version
What package version of the SDK are you using.

botbuilder@4.8.0

## Describe the bug
Give a clear and concise description of what the bug is.

MessagingExtensionActionResponse has an example where the task type is of type `'continue'` in one of the example but this string is not listed under the declaration file and triggers a compile error in our TypeScript project. 

```ts
    // Called when messaging extension is clicked - returns the input task module
    protected async handleTeamsMessagingExtensionFetchTask(
        context: TurnContext
    ): Promise<MessagingExtensionActionResponse> {
        return ({
            task: {
                type: 'continue',
                value: {
                    card: getConfirmCard(context.activity.value.context.theme),
                    height: 400,
                    width: 380,
                    title: 'Create game',
                },
            },
        });
    }
```

botframework-schema/src/teams/extension
```
/**
 * Defines values for BotMessagePreviewActionType.
 * Possible values include: 'edit', 'send'
 * @readonly
 * @enum {string}
 */
export type BotMessagePreviewActionType = 'edit' | 'send';
```

Because the string isn't listed as one of the valid strings, we get a compile error.

A workaround we used was to cast the object to type unknown and cast it to MessagingExtensionActionResponse again.

## Expected behavior
Give a clear and concise description of what you expected to happen.

'continue' should be listed as one of the `BotMessagePreviewActionType`

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by clearab** [comment]
this may have already been fixed

**Comment by clearab** [comment]
Need to validate other languages, probably only in TypeScript

**Comment by joshgummersall** [comment]
@clearab missing in dotnet (see [here](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Schema/Teams/Generated/MessagingExtensionAction.cs#L43) and [here](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder/Teams/TeamsActivityHandler.cs#L264)).

**Comment by clearab** [comment]
Digging into this one a bit - edit and send are the correction options for `botMessagePreviewResponse`. I'm going to close this, please re-open if you have additional information.
