### ISSUE TITLE
Missing replyToId in payload from invoke

### ISSUE THREAD

**Issue by suchitagarwal** [microsoft/botframework-sdk#6001]
## Version
AdaptiveCard 1.3

## Describe the bug
I have a bot in Microsoft Teams, that I am using the REST APIs for managing. I send a card with an invoke action as follows:

```js
{
  type: "Action.Submit",
  title: "Run task",
  data: {
    msteams: {
      type: "invoke",
      title: "Run task",
      value: JSON.stringify({"key1": "value", "key1": "value"})
    }
  }
}
```

The button renders correctly, and sends the following body over HTTP POST when clicked:

```js
{ 
  name: 'task/fetch',
  type: 'invoke',
  timestamp: '2020-08-14T05:01:40.651Z',
  localTimestamp: '2020-08-14T01:01:40.651-04:00',
  id: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
  channelId: 'msteams',
  serviceUrl: 'https://smba.trafficmanager.net/amer/',
  from:
   { id: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
     name: 'Suchit Agarwal',
     aadObjectId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx' 
  },
  conversation: { 
    conversationType: 'personal',
    tenantId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
    id: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx' 
  },
  recipient: { 
    id: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
    name: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx' 
  },
  entities: [{ 
    locale: 'en-US',
    country: 'US',
    platform: 'Mac',
    type: 'clientInfo' 
  }],
  channelData: { 
    tenant: { id: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx' },
    source: { name: 'compose' } 
  },
  value: { 
    data: { 
      requestId: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
      taskUUID: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
      type: 'task/fetch',
      viewType: 'run_task' 
    },
    context: { theme: 'default' } 
  },
  locale: 'en-US' 
}
```

Notice, however, that the message received is missing the replyToId. How can I get that back to the server so I can update the message that the card action came from, as described here: https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions#example-incoming-invoke-message

Surprisingly enough, if I set "type" inside "data.msteams" to "messageBack" when constructing the button, I do get the replyToId back in the HTTP POST body

Thanks for your help.

## To Reproduce
See above

## Expected behavior
Should send replyToId in the payload

**Comment by suchitagarwal** [comment]
Thanks for triaging @clearab. @tacri Please let me know if I can provide any extra information. Thanks a lot for your help/.

**Comment by clearab** [comment]
Just got an update from the product team on this one, the fix has been checked in and is rolling through our deployment rings. It should be available in production in the next couple of weeks.

**Comment by suchitagarwal** [comment]
That's awesome! Thanks a lot for the update @clearab. I'll keep testing and leave a note here once I confirm.

**Comment by suchitagarwal** [comment]
Hi @clearab I just tested this on the web app, and it's still happening. does the web app get updated using the same rolling deploy process as well?

**Comment by tsuwandy** [comment]
@clearab, when could the fix be tested on prod?

**Comment by clearab** [comment]
Hi - it takes at least two weeks to roll through the deployment rings, so I wouldn't test until 9/21 at the earliest.

**Comment by clearab** [comment]
This should now be rolled out globally, please reopen if you're still experiencing the issue.
