### ISSUE TITLE
Slack Channel Interactive message buttons wordwrap

### ISSUE THREAD

**Issue by godwin3737** [microsoft/botframework-sdk#6009]
## Version
4.9.2

## Describe the bug
In Slack Channel Buttons with longer text are cut short instead of wordwrap.

## To Reproduce
1. Follow the steps mentioned here to connect a bot to Slack https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs
2.  Ensure to perform the optional step regarding configuring Interactive message with URL https://slack.botframework.com/api/Actions 
3. Have your bot respond with buttons having 8 -10 words
4. The button text are not shown

## Expected behavior
The button text should wrap into next line (like msteams channel)

## Screenshots
![buttons-auto-cut](https://user-images.githubusercontent.com/12369322/91709424-603b1180-eba0-11ea-8837-cdf732d20366.PNG)

**Comment by stevkan** [comment]
@godwin3737, this is a channel-specific feature and is, generally, not in the control of BotFramework. In some cases, 3rd party channels (like Slack) provide the ability to pass in specific commands in the activities `ChannelData` property. I am not aware if Slack offers the ability to word wrap buttons. You will need to reference their developer API [docs](https://api.slack.com/) or reach out to their support team to understand if and how this is possible.
