### ISSUE TITLE
MS teams List card is not displaying the Mongolian letter 'м' (unicode number - 1084) on Mobile app.

### ISSUE THREAD

**Issue by kbatsuren** [microsoft/botframework-sdk#6014]
I am using the bot framework sdk v4 on Micrsofot Teams. The main language of this app is Mongolian, and we experienced this issue of not displaying the cyrillic letter 'м' (unicode number - 1084) in MS Teams List card. 

It is working fine on other platforms like Web Application or Desktop Application, but only the mobile version (here I am using IPhone 8 with the 13.3.1 ios version). Also the letter is fine with other elements such as adaptive cards, button, and text messages.

Here is the screenshots. 

1. Mobile version (with error)
![118634336_789074375228995_138868336142603837_n](https://user-images.githubusercontent.com/50955407/91744197-abc6dd00-ebeb-11ea-9513-4387f800c8fe.jpg) 

2. Desktop version (without error)

![image](https://user-images.githubusercontent.com/50955407/91744630-59d28700-ebec-11ea-816c-217ca116fc7f.png)

**Comment by kbatsuren** [comment]
I have just updated the latest version of MS Teams on IOS mobile version (2.0.20), but still facing the same issue.

**Comment by kbatsuren** [comment]
json list card - 
{
            "contentType": "application/vnd.microsoft.teams.card.list",
            "content": {
                "title": "Нийт 1 ажилтан оллоо.",
                "items": [{
                "type": "person",
                "id": amarsanaag@num.edu.mn,
                "title": "Амарсанаа Ганболд",
                "subtitle": "муис хшуис",
                "tap": {
                    "type": "imBack",
                    "value": "amarsanaag@num.edu.mn гэж хэн бэ?"
                }
            }]
            }
}

**Comment by Wajeed-msft** [comment]
@kbatsuren  Tracking this in Microsoft Teams issues repo: https://github.com/MicrosoftDocs/msteams-docs/issues/2049
@clearab - Could you please close this from Bot Framework repo?

**Comment by clearab** [comment]
Thanks @Wajeed-msft!
