### ISSUE TITLE
Meeting notification alert bubble

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#6026]
Teams is adding support for a bot to mark a message sent to a meeting chat that will cause the Teams client to render it in a notification popup as well as in the chat thread. The method for adding this alert is similar to the existing notification method.

To enable this functionality the bot developer would send an Activity to the meeting chat in the normal method, and add a `notification` object to the `channelData` object. The `externalResourceUrl` in the payload below is optional.

```
POST /v3/conversations/{conversationId}/activities 
```

```
“channelData”:  { 
 “notifcation”:  { 
    “alertInMeeting”: true, 
    “externalResourceUrl”: “https://external.resource.url” 
  } 
} 
```

SDK support for this should introduce a helper method to add this object to the Activity, taking in the `externalResourceUrl` as an optional parameter. This should be modeled after the existing functionality documented here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/conversation-basics?tabs=dotnet#adding-notifications-to-your-message

**Comment by EricDahlvang** [comment]
The existing `notification` object is defined as:

```json
"channelData": {
    "notification": {
      "alert": true
    }
  }
```

With the new fields:
```json
"channelData": {
    "notification": {
      "alert": true,
      "alertInMeeting": true,
      "externalResourceUrl”: “https://external.resource.url”
    }
  }
```

What is the relationship between `alert` and `alertInMeeting`?  Should alert always be true, when alertInMeeting is true? or are these completely separate concepts?

What is `externalResourceUrl` used for?  How do I test this in Teams?

**Comment by tracyboehrer** [comment]
@clearab Do you know about the answers to Erics questions?  Or at least... what we should do so we're the same.

**Comment by clearab** [comment]
There's no direct relationship between alert and alertInMeeting. I'll share the link for the internal dev spec for details on the resourceUrl bit.

**Comment by Kaiqb** [comment]
@clearab - are these done for R11? If not, move them out of the milestone.

**Comment by clearab** [comment]
The code is done, docs have not been done yet. I'll go ahead and close this, and deal with the docs separately.
