### ISSUE TITLE
Provide a way to query the SDK for what features a channel supports

### ISSUE THREAD

**Issue by JonathanFingold** [microsoft/botframework-sdk#6027]
## Issue

Currently, the doc team supports a partial list of the features each channel supports, the [channel reference](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference?view=azure-bot-service-4.0).
1. The doc team has no good way to test this information.
1. The doc team needs to be told when to update information (for new channels or changes within existing channels).

## Proposed change

Add this to the SDK in a way that a dev can query for these features directly.
- Does Kik support Hero cards? If so, up to how many buttons per card are supported?
- What about suggested actions in GroupMe? In Email?
- Which channels will send (or can receive) a `messageReaction` activity?
- And so on.

Bonus points for making this visible through the adapter, so that custom [channel] adapters advertise which features they support. 

## Component Impact 

I'd expect an addition to the Bot.Builder, Bot.Connector, or Bot.Schema package.

## Customer Impact 

1. This would simplify the process of supporting (or choosing to support) features in a bot.
1. This would also provide a "source of truth" that is more likely to be up to date and accurate.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by EricDahlvang** [comment]
Maybe this could be added to the HealthCheck api, or something similar.  A specific bot might only support certain channels, or channel features.

**Comment by JonathanFingold** [comment]
@mdrichardson I don't have the resources to test this on every channel, alas. Is this something the support team could do once a quarter to keep the card support table up to date? (I'd like to include all official channel-specific adapters in the table, too.) We can take this part of the discussion off line.
