### ISSUE TITLE
feature: add a new ExpectReplies property to BeginSkill action

### ISSUE THREAD

**Issue by Stevenic** [microsoft/botframework-sdk#6036]
## Is your feature request related to a problem? Please describe.

BeginSkill currently invokes skills in a way that requires the skill POST all replies back to the bot via a separate HTTPS request. This is not only in-efficient it also makes testing a skill cumbersome.  The underlying SkillDialog supports a more efficient mode of skill communication where the invoked skill will buffer all of its outgoing messages and return it to the skill dialog as an array of activities for it to re-post.

To enable this feature you currently have to manually set the `deliveryMode` on the bots initial activity using something like below:

```
[Activity
	type = message
    text = ${turn.activity.text}
    deliveryMode = expectReplies
]
```

We could simplify this for developers by instead adding a `ExpectedReplies` property to the `BeginSkill` action. Setting this to `true` would enable the more efficient delivery mode. In fact I would argue that it should default to true given that its rare you need the features you get from the heavier more cumbersome delivery mode and testing your skills is so much more difficult in that mode.

**Comment by gabog** [comment]
Hi @garypretty, assigning this one to you, @EricDahlvang will setup a call so we can discuss how this feature should be surfaced in composer and how to drive this forward.

Thanks

**Comment by garypretty** [comment]
@gabog Dropped some time in for us to discuss tomorrow.

**Comment by garypretty** [comment]
@gabog @EricDahlvang I believe we agreed we would surface this setting, leaving the default as 'Normal'. The decision to make this the default is to ensure we do not break folks who are already using the action. Am I remembering that correctly?  I am going to mark this one as a P1 for R12 given I believe the effort to implement is relatively low.

**Comment by EricDahlvang** [comment]
@garypretty  here is the PR for this:
 
https://github.com/microsoft/botbuilder-dotnet/pull/4830

**Comment by mrivera-ms** [comment]
This is being addressed here: [PR5143 ](https://github.com/microsoft/botbuilder-dotnet/issues/5143). Closing as duplicate.
