### ISSUE TITLE
onTeamsMembersAddedEvent not working in botbuilder js sdk

### ISSUE THREAD

**Issue by Way911** [microsoft/botframework-sdk#6045]
## Version
"botbuilder": "~4.9.0" and "botbuilder": "~4.10.0"

## Describe the bug
The official CoreBot project template has a welcome message [implemented](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/typescript_nodejs/03.welcome-users) . But we tested both **onMembersAdded** and **onTeamsMembersAddedEvent** is not triggerred when new teams member first open a conversation with bot. 

When user send a message to the bot both onMessage and onTeamsMembersAdded are triggerd at the same time.

## To Reproduce
1. New teams member open a link to chat with bot for the first time. He has never opened chat bot before.
2. There is no welcome message sent to user.

## Expected behavior
Bot send a welcome message to teams member.

## Tracking Status

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by bao1018** [comment]
Met the same issue, both `onTeamsMembersAddedEvent` and `onMemberAdded` event can not work, can anyone take a look ?

**Comment by clearab** [comment]
Thank you for reporting - could one of you supply us a botId and an approximate timestamp for when the message was missed so we can investigate in our logs further?

**Comment by Way911** [comment]
Yes, the bot id is : af941359-c07e-42c8-9de2-52af0b06e6a1 , the approximate timestamp is one hour before we left the comment, around Sep 17, 2020, 5:00 PM GMT+8.

**Comment by tacri** [comment]
@Way911 , could you please clarify how is the app installed in Teams? Are you uploading the manifest for the tenant or for the user? Trying to understand what does exactly this mean:
_New teams member open a link to chat with bot for the first time. He has never opened chat bot before._

**Comment by Way911** [comment]
We didn't install the app in Teams. We connected Team channel by following instructions.
https://docs.microsoft.com/en-us/azure/bot-service/channel-connect-teams?view=azure-bot-service-4.0
User open bot by this link :  https://teams.microsoft.com/l/chat/0/0?users=28:af941359-c07e-42c8-9de2-52af0b06e6a1

**Comment by clearab** [comment]
Ah, ok. this is the expected behavior then. As is outlined at the top of the doc page you linked to, this isn't really recommended for use in production systems. The recommended path is to install your bot as part of an app - that will cause the event to fire at install time. When deep-linking directly to the chat with your bot the event will not fire until the user interacts with the bot.
