### ISSUE TITLE
TranscriptLoggerMiddleware is logging ContinueConversation events to transcript log

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-sdk#6059]
## Version

4.10.3

## Describe the bug

When a skill calls back to the skill host the skill host creates a "ContinueConversation" event activity to get back into the context of the conversation.  This is essentially a temporary internal activity, but the TranscriptLogger is writing it to the transcript.  I don't think we want it logged to the transcript.

## To Reproduce

Look at logs when using skills

## Expected behavior

I think we shouldn't log it. We need to add logic to exclude internal skill messages from TranscriptLoggerMiddleware like we do in the [TanscriptLogger sample](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/81.skills-skilldialog/DialogRootBot/Middleware/LoggerMiddleware.cs#L31).

## Tracking Status

**Dotnet SDK** [4733](https://github.com/microsoft/botbuilder-dotnet/issues/4733)
- [x] PR
- [x] Merged

**Javascript SDK** [2805](https://github.com/microsoft/botbuilder-js/issues/2805)
- [x] PR
- [x] Merged

**Python SDK** [1393](https://github.com/microsoft/botbuilder-python/issues/1393)
- [x] PR
- [x] Merged

**Java SDK** [807](https://github.com/microsoft/botbuilder-java/issues/807)
- [ ] PR
- [ ] Merged

**Comment by gabog** [comment]
dotnet, JS and Python are done, Java will be done in a future release
