### ISSUE TITLE
 Microsoft bot framework message edit doesn't fired the event

### ISSUE THREAD

**Issue by RahulSalunke64** [microsoft/botframework-sdk#6060]
In Microsoft bot framework, using C# , I am trying the catch up with Edit Message event. But unfortunately it is not hitting the any event to bot endpoint. users can edit their previously sent messages in MS Teams, so is there a way to listen to that edit message event from the bots side?

Noted Point : when I react on any message from bot then i can get the 'OnMessageReactionActivityAsync' event at bot side, but when I tried this with messages which sent to the bot then it was not fired anything at bot end.

**Comment by ninggao** [comment]
@EricDahlvang Could you please take a look at this?

**Comment by EricDahlvang** [comment]
Hi @RahulSalunke64 

Unfortunately, MS Teams does not forward the bot edit or delete activities.  If you feel this feature would be useful, please make a request here: https://microsoftteams.uservoice.com/

**Comment by EricDahlvang** [comment]
Also, this page describes some other ways to contact the Teams team: https://aka.ms/teamsdevfeedback
