### ISSUE TITLE
Slack button throwing error

### ISSUE THREAD

**Issue by rudibr78** [microsoft/botframework-sdk#6065]
## Version
node js botbuilder 3.10

## Describe the bug
Slack bot is receiving and answering messages just fine, but whenever a button is clicked it throws an error : {error: "b3dd75b6-1601558193.811 chat.attachmentAction not ok: dispatch_failed"}

## To Reproduce
1. Try to activate a bot framework bot button on slack

## Expected behavior
Button responds

Console information : 
Oct-1 10:22:31.630 [API-Q] (T01BQNDE04T) b3dd75b6-1601558551.628 chat.attachmentAction called with reason: user_attachment_action_dispatch

gantry-shared.80631cd.min.js?cacheKey=gantry-1601486067:1 Oct-1 10:22:31.630 [API-Q] (T01BQNDE04T) b3dd75b6-1601558551.628 chat.attachmentAction is ENQUEUED

gantry-shared.80631cd.min.js?cacheKey=gantry-1601486067:1 Oct-1 10:22:31.632 [API-Q] (T01BQNDE04T) b3dd75b6-1601558551.628 chat.attachmentAction is ACTIVE

gantry-shared.80631cd.min.js?cacheKey=gantry-1601486067:1 Oct-1 10:22:31.960 [API-Q] (T01BQNDE04T) b3dd75b6-1601558551.628 chat.attachmentAction is REJECTED: API not ok dispatch_failed

VM1931:37 Oct-1 10:22:31.962 (T01BQNDE04T) {error: "b3dd75b6-1601558551.628 chat.attachmentAction not ok: dispatch_failed"}

**Comment by llcranmer** [comment]
I'm facing a similar issue, not using the bot framework, have set up a Netlify lambda that listens for the POST. But the POST is never making it outside of the slack chat page. When I inspect the console I see almost the exact same as Ruby.

```cli
Oct-1 09:36:37.996 [CHECK-UNREADS] (T01BBCZ3760) Not marking C01AQF15CNT because last_read >= latest && channel is read gantry-shared.728e381.min.js:1:274340
Oct-1 09:36:38.013 [API-Q] (T01BBCZ3760) 7a5127c6-1601562998.012 chat.attachmentAction called with reason: user_attachment_action_dispatch gantry-shared.728e381.min.js:1:274340
Oct-1 09:36:38.013 [API-Q] (T01BBCZ3760) 7a5127c6-1601562998.012 chat.attachmentAction is ENQUEUED gantry-shared.728e381.min.js:1:274340
Oct-1 09:36:38.015 [API-Q] (T01BBCZ3760) 7a5127c6-1601562998.012 chat.attachmentAction is ACTIVE gantry-shared.728e381.min.js:1:274340
Oct-1 09:36:38.914 [API-Q] (T01BBCZ3760) 7a5127c6-1601562998.012 chat.attachmentAction is REJECTED: API not ok dispatch_failed gantry-shared.728e381.min.js:1:274340
```

Previously, I saw an error that stated Origin is not the same 'https://slack.com' vs 'https://app.slack.com' but that message has seem to have gone away. I have tried this on Firefox, Safari, and Desktop application. Previously, my interactive chat buttons were working. So not sure what has changed...

**Comment by stevkan** [comment]
@rudibr78, I'm not able to repro the issue in either the browser or desktop app. I'm sending a hero card with a simple yes/no option that sends a postback with the associated values. No errors are detected, the bot responds normally, and the response displays as expected in Slack.

![image](https://user-images.githubusercontent.com/18403946/94865688-e55d5480-03f2-11eb-96dc-632f1798ad6d.png)

I did visit my Slack app for my bot and discovered that I had some outdated scopes which then required a restart of the app. It might be worth visiting your Slack app to review its settings and possibly restart it in case it generally needs a refresh.

All that being said, given you and another experienced this issue using different products (BotFramework & Netlify), my strong suspicion is this is a Slack-specific issue. If the issue persists, I would suggest you reach out to Slack for additional help.

**Comment by stevkan** [comment]
Closing this issue as it appears to be Slack-specific.
