### ISSUE TITLE
Authorization has been denied for this request

### ISSUE THREAD

**Issue by AnatolyArt** [microsoft/botframework-sdk#6071]
I'm trying to send a message to the user (myself) via Skype from the bot, but I get the error {"message":"Authorization has been denied for this request."}

I get jwt token by url: https://login.microsoftonline.com/common/oauth2/v2.0/token
then i try to send message 
`POST /apis/v3/conversations/8:live:ds-1990/activities HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6IlRvanJGRHVVY3pCbXhUQlg3VXhTblg5bWI3Y1BmUnJtcVR5c21MTFpfMU0iLCJhbGciOiJSUzI1NiIsIng1dCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNjAyMDgxNzE0LCJuYmYiOjE2MDIwODE3MTQsImV4cCI6MTYwMjE2ODQxNCwiYWlvIjoiRTJSZ1lHaXBEODVsc2ZDK245Vi84RWJaNUhQaUFBPT0iLCJhcHBfZGlzcGxheW5hbWUiOiJLd29yayBUZXN0IEJvdCIsImFwcGlkIjoiZDIzNmMzM2YtNGE2MC00MzgxLWE5NTItNTZjNTk4Y2ViMGI1IiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3LyIsImlkdHlwIjoiYXBwIiwicmgiOiIwLkFSb0F2NGo1Y3ZHR3IwR1JxeTE4MEJIYlJ6X0ROdEpnU29GRHFWSld4WmpPc0xVYUFBQS4iLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiV1ciLCJ0aWQiOiI3MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDciLCJ1dGkiOiJxSHVyNUxmckFFeTR0Q1c3VUkwX0FRIiwidmVyIjoiMS4wIiwieG1zX3RjZHQiOjEyODkyNDE1NDd9.Ex2H9JIOUvCHIJyWik2Y_2ceDhjOnD-Sv3l_2h3brUIEjpgRU0ekNmpr1z33W_MLPl2HHuXf0UEu-f0wziIAvTTyLz-Z6RcJ_qD6Eqxdt_r31kc-pFVGfmYPK13rmAheLwjHKnUB-4sNf2vR1dafAcaH41vWdFWhD2hu-pf9NMLBwL7-HRIvbOAAhk1mEHAG240G5_xubh6_naVon1HS_i4Ixvafowgm2EcenNuxkITgcJGDFARjuCW1rovQlVarJpEM9mfgHZYnqaCX8ZMw248X4P7xCFJihBdS81HxEoGT5sFYK2FL0yxQaCd_MBvFDVbzaLMDm2Gle2MXRHW6kw
Host: smba.trafficmanager.net
Accept: application/json
Content-Type: application/json
Content-Length: 230

{
    "type": "message",
    "from": {
        "id": "d236c33f-4a60-4381-a952-56c598ceb0b5",
        "name": "KworkTestBot"
    },
   "recipient": {
        "id": "8:live:ds-1990",
        "name": "Anatoly"
    },
    "text": "Hi";
}`

But have a error
`HTTP/1.1 401 Unauthorized
Content-Length: 61
Content-Type: application/json; charset=utf-8
Server: Microsoft-HTTPAPI/2.0
Date: Wed, 07 Oct 2020 14:59:28 GMT

{"message":"Authorization has been denied for this request."}`

why, what i doing wrong?

**Comment by dmvtech** [comment]
Hi @AnatolyArt Can you explain more of what you are attempting to accomplish? Is there a reason that you are trying to construct and send the activity in this manual way instead of using the SDK? Do you (already) have the Skype channel set up in your bot's channels? (FYI, as of this time last year, [bots are not longer able to be registered for the Skype channel](https://support.skype.com/en/faq/FA34646/what-are-skype-bots-and-how-do-i-add-them-as-contacts)).

**Comment by AnatolyArt** [comment]
@dmvtech 
My main task is to send a personal message to the user (company employee) on a specific event.
1)i registred bot at page https://dev.botframework.com/bots
2) add skype channel - https://i.ibb.co/yqT5B6c/bot-channels.png
3) i use php to work with bot, that's why I didn't use the SDK

**Comment by AnatolyArt** [comment]
@dmvtech  any ideas ?

**Comment by AnatolyArt** [comment]
someone can help ?

**Comment by AnatolyArt** [comment]
i steel here, and wait some support... Microsoft where are you?

**Comment by dmvtech** [comment]
hi @AnatolyArt Sorry for the delay.

> I get jwt token by url: https://login.microsoftonline.com/common/oauth2/v2.0/token

Can you try using `https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token` instead? 

Please see [here ](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-quickstart?view=azure-bot-service-4.0#request)for more info.

**Comment by dmvtech** [comment]
I am closing this issue as it doesn't seem to be a blocking issue. Feel free to reopen if you have need to get this resolved.
