### ISSUE TITLE
QnA Maker error 500

### ISSUE THREAD

**Issue by tamerin-tech** [microsoft/botframework-sdk#6081]
Calling the QnA Maker API returns this error:
status code: 500
body:
{"error":{"code":"Unspecified","message":"Something happened. Please retry after some time."}}

the same happens when I try to test it directly on the qnamaker.ai platform

![image](https://user-images.githubusercontent.com/24475275/96494237-5ea7d480-1246-11eb-97f5-c19019e83c47.png)

note - I'm using Hebrew as the language for this KB language

**Comment by cahuertav** [comment]
I have the same problem. 
I'm using Spanish as the language for my KB language

**Comment by anusharavindrar** [comment]
@tamerin-tech, what specific operation are you trying to perform using the QnAMaker API? Do you get any additional error on the Dev Console(Ctrl + Shift + I) in the portal? Also, are you getting this error for a specific KB or it happens for the other KBs as well?

**Comment by tamerin-tech** [comment]
I mainly get this error when trying to use the qnamaker platform (qnamaker.ai)

**Comment by skamranhaq** [comment]
I am facing the same issue " Something happened. Please retry after some time." when using Azure QnA service and 
Chinese-Simplifies as language. For English everything is running fine. Still, no resolution found.
After republish the app-service it starts working for a few requests but then the same error starts to occur.

**Comment by anusharavindrar** [comment]
@tamerin-tech, can you answer my questions above to help understand the issue better? @cahuertav & @skamranhaq, are you guys experiencing this for a specific KB(with Spanish & Chinese language) or this happens for every KB(with a language other than English) on the portal?

**Comment by skamranhaq** [comment]
@anusharavindrar  It was only happening with Chinese KB, with English everything was fine. We resolved this by shifting our App Service to Plan S1. If the issue was related to quota, Azure should message properly instead of 500 errors.

**Comment by tamerin-tech** [comment]
@anusharavindrar  - now it's working - but haven't changed anything on my side...
my request (REST):
POST https://....-qna-maker.azurewebsites.net/qnamaker/knowledgebases/....../generateAnswer
payload: {question: "..."}

now I'm getting full response:
{"answers":[{"questions":["..."],"answer":"**....","score":90.0,"id":30,"source":"....docx","metadata":[],"context":{"isContextOnly":false,"prompts":[]}}],"activeLearningEnabled":false}

is the QnAMaker a stable product or still under development?

**Comment by anusharavindrar** [comment]
@tamerin-tech, glad to hear that it's working now. QnAMaker is a stable product, the issue you encountered might be due to some outage. Closing the issue. Please feel free to re-open if needed.
