### ISSUE TITLE
Adaptive declarative dialogs don't support circular references

### ISSUE THREAD

**Issue by Robulane** [microsoft/botframework-sdk#6094]
[TestLoop.zip](https://github.com/microsoft/botframework-sdk/files/5464592/TestLoop.zip)
## Version
4.10

## Describe the bug
Adaptive declarative dialogs don't fully support the circular references. E.g. the following won't work:
Dialog1 sends a response and calls Dialog2
Dialog2 asks something and calls Dialog1

The bot will be able to ask the question only 2 times and then it will return "Value cannot be null. (Parameter ‘dialogId’)" error.

Also, Dialog1 and Dialog2 will be deserialized multiple times and BF will have multiple instances of each dialog.

## To Reproduce
See Composer bot attached.

## Expected behavior
In the example above, the user should be able to give as many answers as he wants, the bot should continue sending "hello" and asking "what is your number" question. No errors should be returned.

## Screenshots
![image](https://user-images.githubusercontent.com/55888168/97696387-c9a6a600-1aa5-11eb-9d5c-b705dab91ccc.png)

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by CezaryMarcjan** [comment]
This will be addressed in the upcoming release.

**Comment by pedro-ramirez-suarez** [comment]
Has this been resolved? I have a similar issue, the bot asks for some data and it performs some calculation, and then asks the user if the result is correct, if the users said "no" the dialog is repeated, this works two times but the third time that the user said "no" the bot returns the "value cannot be null error"
