### ISSUE TITLE
Need API to know whether conversation exists or not

### ISSUE THREAD

**Issue by amitkumariiit** [microsoft/botframework-sdk#6097]
**Is your feature request related to a problem? Please describe.**

We have a usecase in which we use to reply/update/delete to the existing conversation and sometime while performing this operation we get an error with code `ConversationNotFound`. We have observed sometime that we are able to reply to the conversation even if for the particular conversation we had received `ConversationNotFound` earlier. (This we have verified in the logs that we write. We don't have the repro case for it)

We want to perform some action if conversation doesn't exists like deleting the subscriptions for the channel
(Subscriptions are something which we maintain based on which we attempt to reply/update/delete)
But as the `ConversationNotFound` sometimes are raised even if the conversation exists, we can't just go and delete the subscription.
As per our understanding `ConversationNotFound` is raised in below scenarios.
1. Conversation is deleted
2. Channel is deleted which had this conversation
3. Team got deleted which had this conversation

**Describe the solution you'd like**
We need an **API** to which can tell us if a conversation exists or not for a given conversation id.

**Describe alternatives you've considered**
We considered relying on error conversationNotFound but as mentioned above this is not full proof and sometimes raised if conversation exists also, we are not considering this.

**Additional context**

**Comment by lauren-mills** [comment]
Close due to inactivity. Feel free to reopen as needed.
