### ISSUE TITLE
Why deprecated azure function as an option for hosting bot?

### ISSUE THREAD

**Issue by IvanJobs** [microsoft/botframework-sdk#6099]
Hi There,
Excuse me, but I really can't find any other places to ask the question.

As I can try on Azure, there's no official option to host bot by azure function, only app service wrapped by web app bot.
I'm wondering the reason behind this fact. 
Can anyone help me with this? Thanks in advance.

**Comment by tracyboehrer** [comment]
This is a very old issue, but the current status is that Functions can be used to host a bot.  Unfortunately, our only implementation of that is in the Adaptive Runtime.  To date we do not have samples around this, though there are others that have done it.
