### ISSUE TITLE
Automate creation of Change Logs for Builds

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#6128]
For each build we do (certainly RC builds, and possibly nightly builds) we should have a changelog included with that build. 

To do this, we need:
1. Define the changelog format. The markdown format the script currently emits seems fine. 

2. Decide on the ranges for the changelog. Does the changelog for a nightly show everything since the last major release? 

3. Decide on mechanism for sharing the changelog. The two solutions seem to be: 1) Including the "changelog.md" file in the build or 2) Use the Github release mechanism. 

Note: This is a 1P partner ask, to make signoff of RC builds easier. Extending this to be more general seems like a feature everyone would benefit from. The specific ask is "give us a changelog", and I believe the automation is the best way to do that on an ongoing basis.

**Comment by mrivera-ms** [comment]
@munozemilio, is this still to be included in R13? If not, please update the milestone. Thank you.

**Comment by munozemilio** [comment]
This will be done after code complete date. I will add R14 as milestone since we dont have post-R13
