### ISSUE TITLE
Send welcome message to users on Teams when they open chat window

### ISSUE THREAD

**Issue by shiv479** [microsoft/botframework-sdk#6132]
We have developed a chatbot using Microsoft Bot Framework sdk v4.0. The bot is exposed over Teams channel only using an app created in Teams app studio(Personal Scope Bot). The bot sends a welcome message to users when they installs the bot in their Teams app. But we also want to send a welcome message to users when they open/reopen the chat window. Can we achieve this in Teams Channel? Or is there a way to know when a user become active/inactive when interacting with our bot on Teams channel?

**Comment by clearab** [comment]
No, there is no event that is sent to the bot when a user opens the chat window.
