### ISSUE TITLE
ServiceError when "return to application without granting consent" in the consent screen is selected

### ISSUE THREAD

**Issue by kahopkin** [microsoft/botframework-sdk#6136]
## Version
azure bot service 4.0

## Describe the bug
We are getting the below error message on the prompt screen in MS Teams whenever we select "return to application without granting consent" in the consent screen.
  
![blackberryBug](https://user-images.githubusercontent.com/62229442/101412024-e0fc5e80-38af-11eb-9f84-e29a205771dc.png)

## To Reproduce
Select "Return to application" without giving consent on the consent screen

## Expected behavior
It is supposed to go back to the previous application page

## Screenshots

![blackberryBug](https://user-images.githubusercontent.com/62229442/101412024-e0fc5e80-38af-11eb-9f84-e29a205771dc.png)

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by jwiley84** [comment]
hi @kahopkin 

Thank you for bringing this to our attention. for tracking purposes, i'm going to close this issue and post all work/conversation on [this issue](https://github.com/microsoft/botframework-sdk/issues/6137)
