### ISSUE TITLE
Updates to Adaptive Schemas

### ISSUE THREAD

**Issue by cleemullins** [microsoft/botframework-sdk#6140]
1. Single Source of Truth
Schema files are currently each in language repo ([C#](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Schemas/Microsoft.AdaptiveDialog.schema), JS, etc). We need a single-source of truth for these. 

2.  Localization
We need a localization story for the Labels and Descriptoins. 

3. Tooling Need tooling to extract the schema from the code. 

We'll need to work with @cwhitten  and @tomlm  and @chrimc62  to do some requirements analysis here first.

**Comment by mrivera-ms** [comment]
@cleemullins, @cwhitten, @tomlm, @chrimc62, requirement analysis is still pending for this item. Moving out of R13.
