### ISSUE TITLE
REST API - empty 202 response when sending activity containing attachments

### ISSUE THREAD

**Issue by Spoonrad** [microsoft/botframework-sdk#6155]
## Version
[Bot framework REST API v3
](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0) for a Teams channel
## Describe the bug
[Sending an activity to an existing conversation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#send-to-conversation) using the v3 REST API leads to an empty 202 response, instead of the expected 201 response containing the activity ID ([ResourceResponse](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#resourceresponse-object)) when the Activity contains attachments. Therefore, it is not possible to update the Activity in the future because we cannot retrieve its identifier.

## To Reproduce
1. Install a bot on MS Teams
2. [Create a conversation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#create-conversation) with the user 
1. Send a POST request to [/v3/conversations/<conversation_id>/activities](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#send-to-conversation) with the following body:
```
{
    "type": "message",
    "text": "hello",
    "attachments": [
        {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
            "type": "AdaptiveCard",
            "version": "1.0",
            "body": [],
            "actions": [{
                "type": "Action.Submit",
                "title": "SUBMIT",
                "data": {
                    "payload": "derp"
                }
                }]
      }}
    ],
    "textFormat": "xml"
}
```
Headers must include the bot framework authentication token

## Expected behavior
1. The activity is received as a message by the user
2. A 201 response containing the newly created Activity's
(1) is OK, but (2) is not, a 202 response with no body is received instead

## Additional context
I have also opened a [StackOverflow question](https://stackoverflow.com/questions/65633214/microsoft-bot-framework-rest-api-cannot-retrieve-activity-id-after-sending-mes) on this.
Note that if the body does not contain attachments, a 201 response with the activity ID is received as expected.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by EricDahlvang** [comment]
Hi @Spoonrad 

Please try sending one message with the text alone, and a second with the attachment and no text.  Do you receive a ResourceResponse.Id then?

**Comment by Spoonrad** [comment]
Yes, that works!
In that case though, I'm not sure where to put the text. I understand that I can add it in an Adaptive Card Container, but I'm afrais the display is going to change. I would still consider it a bug that it does not send a 201 response with attachments + text, but thanks for the workaround, which I will try soon and I'll make an update.

**Comment by clearab** [comment]
Unfortunately, this is the expected behavior in Teams. They are considering altering the behavior in the future, but currently this is as designed. What is the desired design for your message? Is there a reason you're not putting the text in the body of the Adaptive Card?

**Comment by Spoonrad** [comment]
Hi @clearab Thanks for your reply

I've tried putting into the card via TextBlock:
```
{
    "type": "message",
    "attachments": [
        {
        "contentType": "application/vnd.microsoft.card.adaptive",
        "content": {
            "type": "AdaptiveCard",
            "version": "1.0",
            "body": [
                {
            "type": "TextBlock",
            "text": "👋<br/><br/><strong>Click below to access your dashboard where you can:</strong><br/><blockquote>🙋\u200d♀️ Add or remove team members<br/>📆  Change the timing and frequency of your rituals<br/>🔎 View your latest reports & data</blockquote>",
            "wrap": false
        }
            ],
            "actions": [{
                "type": "Action.Submit",
                "title": "SUBMIT",
                "data": {
                    "payload": "derp"
                }
                }]
      }}
    ],
    "textFormat": "xml"
}
```

However, there are some problems:
- Text format syntax in a card is different than text rendering outside of it. We use the "xml" format on Teams. I've taken a look at the markdown options for AdaptiveCard, which would have been great (because right now we have to map all of our markdown to an XML format) but the support for MD is too limited (for instance there are no quotation marks)
- Additionally, the text gets wrapped within the card container (see attached screenshot). This isn't great at all for long texts, which we have a lot of.

**Are there workarounds that you may be able to think of?**

Also I don't understand that it is a design choice, or at least I would suggest that the Microsoft documentation be updated to reflect it, because one would expect a response containing a ResourceResponse object in all cases.

**Comment by clearab** [comment]
Typically when you're creating an Adaptive Card you'd attempt to minimize the necessary in-line formatting, and instead use the formatting support in the layout of the card itself. Have you seen the card designer? It is available here (there's also one inside App Studio in the Teams client): https://adaptivecards.io/designer/

The reason for the different response is Teams actually splits your message into two if you send it with both text and an attachment, so instead of sending a response that is valid for only one of the resulting messages they just don't send any (this is why the workaround is to send two yourself). I've created an [Issue](https://github.com/MicrosoftDocs/msteams-docs/issues/2594) in their docs repository to get this behavior documented.

So the options are essentially:

- send two messages, one with the text and one with the buttons in a card
- design and send a single more complex card, working within the layout options and constraints of Adaptive Cards.

**Comment by Spoonrad** [comment]
Thanks for your assistance, I will send two messages. I'm looking forward to the full width adaptive cards that were announced.

I also have a significant issue with how messages are formatted in MS-Teams and the bot framework that I'd like to raise. It's not a bug per se, more like a design problem that makes life difficult for developers. Do you know where I could voice this?

**Comment by clearab** [comment]
You can reach out to the Teams group directly using one of the methods outlined at https://aka.ms/teamsdevfeedback.

**Comment by bandtank** [comment]
This is a terrible behavior for an API to exhibit. There should always be a return value. One of many use cases for sending text along with a card is to provide a readable notification to Apple Watch users. Sending a card by itself provides a generic and useless notification to a watch. Sending two messages is not a viable alternative. I know no one here will be able to fix it, but I wanted to add this comment to the conversation.
