### ISSUE TITLE
Return to application without granting consent displays Error Message

### ISSUE THREAD

**Issue by ManuNswamy** [microsoft/botframework-sdk#6166]
Post the sign in [non-admin user], a page which prompts consent for the permissions needed for the application is displayed. On selecting "return to the application without granting consent" option an error message is displayed[screenshot attached].

![Approve](https://user-images.githubusercontent.com/29920276/105061066-13989a00-5a9f-11eb-8fc4-c21f11426450.png)

![Error Message](https://user-images.githubusercontent.com/29920276/105061109-2317e300-5a9f-11eb-98fc-9399bcc6f6b6.png)

I have followed the page by microsoft that is https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp and did the configuration in our bot with redirect URI as https://token.botframework.com/.auth/web/redirect. We are using the OauthPrompt to sign in the user in our .NET based MS Teams bot application.

The scope used in azure connection settings AADv2 is **openid profile email User.Read Group.Read.All ChannelMessage.Send**

If anybody has any resolution for the issue, then please let me know. Thanks in Advance

**Comment by anusharavindrar** [comment]
Closing this and re-opening the original issue #6137  for further investigation.
