### ISSUE TITLE
Add delete/remove method in DialogSet class

### ISSUE THREAD

**Issue by orsharab-zz** [microsoft/botframework-sdk#6167]
**Is your feature request related to a problem? Please describe.**
We would like to be able to delete a dialog from a bot's DialogSet (by ID)

**Describe the solution you'd like**
Add DialogSet.delete(dialogId) function to DialogSet class

**Describe alternatives you've considered**
Disable typescript to be able to manipulate dialogs property in DialogSet

**Additional context**
We're handling DialogSet state between nodes at runtime

**Comment by joshgummersall** [comment]
@orsharab I transferred this issue to the SDK repo as it touches all implementations of the SDK, not just Javascript.

**Comment by garypretty** [comment]
@joshgummersall can you take a look and comment on the above please?  Specifically it would be good to provide a workaround as to how the above can be achieved without requiring SDK changes.

**Comment by joshgummersall** [comment]
@garypretty, without the ability to mutate `DialogSet` in any way (aside from adding dialogs), the only option is to recreate a `DialogSet` completely. This does seem wasteful to me, but it is technically possible. Given that `Set` is in the name of this datatype, it seems like adding a `remove` or `delete` method doesn't seem out of the question. @orsharab-zz, have you considered this approach?

**Comment by orsharab** [comment]
Hi @joshgummersall, this is what we're doing now and exactly what we want to avoid.

**Comment by joshgummersall** [comment]
@garypretty see above.

**Comment by garypretty** [comment]
Thanks @orsharab.  I am adding this as a P2 to our current milestone. If we can get this done within that release then I think it would be a good one to take.  

Assigning this one to @mrivera-ms for assignment to engineering.

**Comment by mrivera-ms** [comment]
Moving to the next milestone.

**Comment by fabricioloupias** [comment]
Any solution to this? It would be a good functionality for those of us who use the generation of dialogs at runtime, allowing us to edit/delete them
