### ISSUE TITLE
Calling option not showing in bot conversation window in teams

### ISSUE THREAD

**Issue by kiranbudati** [microsoft/botframework-sdk#6181]
I'm trying to build a calling bot with botframework, have enabled calling option in web bot and also, enabled supportsCalling, supportsVideo in the manifest file, but I could not find calling option in bot conversation window.

**Comment by jwiley84** [comment]
Closing as a duplicate of https://stackoverflow.com/questions/65994209/mbf-calling-option-not-showing-in-teams

**Comment by kiranbudati** [comment]
@jwiley84  i'm the one who posted that question
