### ISSUE TITLE
BotFrameworkAdapter should configure OAuthClientConfig according to the used AppCredentials

### ISSUE THREAD

**Issue by stevengum** [microsoft/botframework-sdk#6183]
## Describe the bug
Customers in US Gov clouds need to manually configure the OAuthEndpoint used for User OAuth flows. 

https://github.com/MicrosoftDocs/bot-docs/issues/1954 describes the "fix" for having getting User OAuth working in US Gov clouds, but the BotFrameworkAdapter should be "smart" enough to use the correct values derived from the AppCredentials it is currently using when it creates an OAuthClient.

This shouldn't apply when using the CloudAdapter and new BotFrameworkAuthentication classes, but we should cover this scenario in a unit test.

@swagatmishra2007 & @johnataylor FYI

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by tracyboehrer** [comment]
Replaced with CloudAdapter.
