### ISSUE TITLE
DialogManager does not return EoC code when a dialog ends

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#6186]
## Version
4.11.1.

## Describe the bug
In waterfall dialog, the RunAsync extension method evaluates the result from the dialog and sets the Code property in the Eoc activity being sent back [see DialogExtensions.RunAsunc](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogExtensions.cs#L84).

Dialog manager doesn't set the code (see [DialogManager](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs/DialogManager.cs#L357)).

## Expected behavior
DialogManager should set the code like RunAsync does. 

# Tracking

**Dotnet SDK** [5163](https://github.com/microsoft/botbuilder-dotnet/issues/5163)
- [x] PR
- [x] Merged

**Javascript SDK** [3269](https://github.com/microsoft/botbuilder-js/issues/3269)
- [x] PR
- [x] Merged

**Python SDK** [1502](https://github.com/microsoft/botbuilder-python/issues/1502)
- [x] PR
- [x] Merged

**Java SDK** [954](https://github.com/microsoft/botbuilder-java/issues/954)
- [x] PR
- [x] Merged

**Comment by LeeParrishMSFT** [comment]
Closing this as the final SDK (Java) closed this item today.
