### ISSUE TITLE
Bot Channels Registration Resource Acting Up

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botframework-sdk#6203]
As of yesterday (I believe) the Bot Channels Registration is acting up in several ways;

1. Some Registrations have lost their AD Connections which were present before, causing bots to fail authentication
![image](https://user-images.githubusercontent.com/49873947/107754274-86ed9e80-6d21-11eb-9ced-c283fe88b425.png)
2. Deploying an ARM template though the pipeline suddenly does not work anymore, it just keeps on working on it (not sure how long, could be forever)
![image](https://user-images.githubusercontent.com/49873947/107754007-25c5cb00-6d21-11eb-8030-f717b3121427.png)

I noticed that the UI is changed (like configuration now, previously settings) and that makes me believe there has been an update done, causing this fails.

This has a big impact as multiple bots are not functioning anymore and we cannot redeploy as the pipeline hangs on the Bot Channels Registration ARM template deployment.

**Comment by munozemilio** [comment]
@swagatmishra2007 are you aware of any change that might caused this?

**Comment by Virtual-Josh** [comment]
@swagatmishra2007 can you take a look at this?

**Comment by swagatmishra2007** [comment]
Can i get a botid and oauth connection name?

**Comment by cxbuilders** [comment]
@swagatmishra2007 It misteriously fixed itself and this morning the Arm template finished within 17 sec without any issues. My hunch is that our pipeline ran around the same time the updates or your side were done (or something like that ;))

**Comment by swagatmishra2007** [comment]
sounds good...closing the issue for now. Feel free to reactivate and share bot details if it occurs again
