### ISSUE TITLE
CloudAdapter works with skills 

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#6224]
CloudAdapter adds support for authenticating against any cloud provider through the introduction of a new set of auth classes (the key class is `BotFrameworkAuthentication`). 

The skill classes (SkillHandler, ChannelServiceHandler) are still tied to the BotFrameworkHttpAdapter authentication elements and they should be refactored to use the new BotFrameworkAuthentication class. 

## Implementation approach
We should first take sample 81 (SkillDialog), refactor it to use CloudAdapter and identify the gaps we have when trying to make it work. 
We should also test OAuthPrompt and SSO with the CloudAdapter and ensure they work.

Based on the findings we should address this in the dotnet SDK and the port it to the other platforms. 

## Tracking Status

**Dotnet SDK** [5281](https://github.com/microsoft/botbuilder-dotnet/issues/5281)
- [ ] PR
- [ ] Merged

**Javascript SDK** [3371](https://github.com/microsoft/botbuilder-js/issues/3371)
- [ ] PR
- [ ] Merged

**Python SDK** [1564](https://github.com/microsoft/botbuilder-python/issues/1564)
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by tracyboehrer** [comment]
@gabo Removed Java.  This will be handled when we port CloudAdapter when it's done.
