### ISSUE TITLE
Deprecate HealthCheck activity

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#6225]
ActivityHandler can handle a special InvokeActivity where the name is [healthCheck](https://github.com/gabogorg/botbuilder-dotnet/blob/8a24358d3c9ef29aeccc6fc938cdbf2728bde6da/libraries/Microsoft.Bot.Builder/ActivityHandler.cs#L459).

This feature needs to be removed from the SDKs, we should also check that is not being used anywhere else and validate that we are not referencing it in the OBI documents.

## Tracking Status

**Dotnet SDK** [5284](https://github.com/microsoft/botbuilder-dotnet/issues/5284)
- [X] PR https://github.com/microsoft/botbuilder-dotnet/pull/5352
- [X] Merged

**Javascript SDK** [3374](https://github.com/microsoft/botbuilder-js/issues/3374)
- [x] PR https://github.com/microsoft/botbuilder-js/pull/3482
- [x] Merged

**Python SDK** [1567](https://github.com/microsoft/botbuilder-python/issues/1567)
- [x] PR
- [x] Merged

**Java SDK** [1040](https://github.com/microsoft/botbuilder-java/issues/1040)
- [x] PR
- [x] Merged

**Samples** [TODO if applies]()
- [ ] PR
- [ ] Merged

**Docs** [TODO if applies]()
- [ ] PR
- [ ] Merged

**Comment by hkrutzer** [comment]
Why was this done and what replaces it?

**Comment by esfomeado** [comment]
@gabog Why was this removed and what you recommend to use instead to make the health check?

Thanks
