### ISSUE TITLE
Pull schemas out from SDKs

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#6226]
Pull schemas out part or all the packages out of the SDK and service them from schemas.botframework.com (Monica)
* Move schema tests to functional tests
* Can we move UISchema out of the SDK?

Eric has a PR that is related to this topic [here](https://github.com/microsoft/botbuilder-dotnet/issues/4492)

As part of this issue we should create child issues in the language repos to track the work to be done in each one of them. 

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by mrivera-ms** [comment]
Per discussion with @cleemullins, the SDK will not push this forward. Closing as "Won't Fix".
