### ISSUE TITLE
Please include the current channel name in the Conversation for Microsoft Teams

### ISSUE THREAD

**Issue by haacked** [microsoft/botframework-sdk#6250]
## Issue

When using Bot Framework to create a bot for Microsoft Teams, the `turnContext.Activtity.Conversation` property always has null for the `Name`.

Here's an example of a conversation I'm getting.

```
Conversation:
    Id: 19:some-guid@thread.tacv2;messageid=1617657461612
    Name: 
    IsGroup: True
    Role: 
    TenantId: my-tenant-guid
    ConversationType: channel
    Properties: {}
```

I understand I can get a list of ALL channels via `TeamsInfo.GetTeamChannelsAsync(turnContext)` and then find the one that matches the current conversation, but that seems like a lot of effort just to return the name of the current channel and leaves a lot of room for implementors to get it wrong.

## Proposed change

Set the `Name` property of `turnContext.Conversation` to be the name of the current channel in Teams in cases where it makes sense (ConversationType: "channel" or "teams")

## Component Impact 

???

## Customer Impact 

Any customer currently trying to get the room name for the current conversation has to implement an API call to get every channel. This leaves a lot of room for user error.

**Comment by haacked** [comment]
Hmm, looks like in my case, `TeamsInfo.GetTeamChannelsAsync(turnContext)` returns null for the current channel name. How do I get the channel name?

**Comment by stevkan** [comment]
@haacked, thank you for your patience. I will attempt a repro of this and see what is returned. I hope to have an update for you by EOD, possibly tomorrow.

**Comment by stevkan** [comment]
@EricDahlvang @clearab, can you respond to this feature request and what expected behavior is/should be?

**Comment by clearab** [comment]
That's an interesting idea - my understanding the logic of why it has the current behavior is that name is associated with the conversationId, which in a channel context is actually the Id for the conversation thread, and not actually the channel. The recommendation is typically that you make the call to get the channel names once when your bot is installed in a context, then store/cache the names in your own storage for later lookup.

@Wajeed-msft would you like to track this as a feature request, or would you prefer the user voice route?

**Comment by haacked** [comment]
Ah, thanks for that context.

To provide more context for why I think this is a worthwhile change, I chose to use Azure Bot Service so that we could support multiple chat platforms.

This is one case where the behavior differs from Slack. When we receive messages from Slack, we get the channel name.

It'd be nice not to have to special case Teams in this case and add code to store and cache channel names.

At the very least, if this is not the right place to store the name, maybe put it in channel data.

Thanks for considering it.

**Comment by clearab** [comment]
Seems to make sense to me, I'm not sure why Teams isn't populating those fields - I'll defer to @Wajeed-msft from here.

**Comment by clearab** [comment]
Your bot should receive an event when a channel is created in a team it is already installed in: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/subscribe-to-conversation-events?tabs=dotnet#channel-created
