### ISSUE TITLE
OAuth redirect after slack bot install does not pass temporary auth code

### ISSUE THREAD

**Issue by haacked** [microsoft/botframework-sdk#6256]
## Version

4.12.2

## Describe the bug

Installing a Slack Bot does not pass the temporary auth code to the landing page.

I'm working on a Slack Bot using Azure Bot Service and the .NET Bot Framework. In Slack I have the redirect URL set to https://slack.botframework.com per [the docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0&tabs=abs).

In Azure Bot Service, I have a Landing Page URL set up to my site. When I install my bot into Slack, Slack redirects to https://slack.botframework.com which redirects to my landing page url and passes two parameters in the query string, `teamid` and `signature`. So far so good.

The problem is that in the first redirect, Slack is passing a `code` parameter. This is a temporary authorization code per the [Slack docs](https://api.slack.com/authentication/oauth-v2). I expected https://slack.botframework.com to pass this code along to the landing page URL. Instead it passes a `teamid` and a `signature`. I understand what the `teamid` is, but cannot find any documentation of `signature` and what it's used for.

## To Reproduce

1. Install a Slack Bot built with Azure Bot Service into Slack

## Expected behavior

The final redirect to the landing page URL would contain the Slack temporary auth code.

**Comment by stevkan** [comment]
@haacked, thank you for your patience. I've been able to set up the environment and am working on repro'ing the issue. I hope to have an update for you by EOD, possibly tomorrow.

**Comment by stevkan** [comment]
@haacked, can you share with me the steps you took to setting up your landing page and button? In my testing, when I add my bot as an app from the app directory, I am immediately brought to my landing page which has the embedded Slack button. Which, of course, when pressed brings me to the permissions page for the app allowing me to add the app to the workspace and channel. When pressed, it adds the bot.

However, looking at the various URLs that are passed thru, I don't see a `teamid`, `signature`, or `code`, tho I do see scopes.

**Comment by haacked** [comment]
Sure. Here's the "Add to Slack" button we use in our website.

https://slack.com/oauth/v2/authorize?client_id=1103008406706.1108577904386&scope=app_mentions:read,channels:read,chat:write,groups:read,im:history,im:read,im:write,mpim:history,team:read,users.profile:read,users:read&redirect_uri=https%3a%2f%2fslack.botframework.com%2fHome%2fauth%2fv2&state=abbot-bot

In Slack, we have `https://slack.botframework.com` as a Redirect URL.

In Azure Portal, for the Slack channel in our Bot Registration, we have the Landing Page URL set to https://ab.bot/login.

https://ab.bot/ is an asp.net core application. After installing Abbot via the Add to Slack button, the user is redirected to `https://ab.bot/login?signature=....&teamid=....`. I checked with Slack Support and they said they do not redirect with those parameters. They redirect with a `code` parameter used for the temporary authorization code.

So I suspect the following sequence of events occurs:

1. User installs Bot in Slack.
2. Slack redirects to `slack.botframework.com` passing the temporary authorization code.
3. Azure Bot Service stores that code because it needs it.
4. Azure Bot Service redirects to the specified Landing Page URL (in our case `ab.bot/login`) passing us `signature` and `teamid`.

I don't know where it gets the `signature` from nor what I'm supposed to do with it. What I'm not getting is the temporary access code.

Thanks!

**Comment by stevkan** [comment]
@haacked, thank you for your patience. I've reached out to some colleagues and am waiting for a response. I'll provide an update as soon as I have something more to share.

**Comment by stevkan** [comment]
I was able to get answers to your questions. Regarding the `signature` that is passed when redirected, when a user goes through the OAuth flow to add a bot their Slack channel the request is signed with the customer's signing secret. This is added to the request so it can be verified as a legitimate. The `signature` is the response of that signing.

If of interest, you can use code similar to the below snippet to validate the authenticated request.

```c#
private static string GetSignedUrl(Uri uri, string secret)
{
        var uriBuilder = new UriBuilder(uri);
        var query = HttpUtility.ParseQueryString(uriBuilder.Query);

        // sign with client secret
        #pragma warning disable CA5350 // Do Not Use Weak Cryptographic Algorithms
        using (var crypto = new System.Security.Cryptography.HMACSHA1(System.Text.Encoding.UTF8.GetBytes(secret)))
        #pragma warning restore CA5350 // Do Not Use Weak Cryptographic Algorithms
        {
                var sha1 = crypto.ComputeHash(System.Text.Encoding.UTF8.GetBytes(query.ToString()));

                var computedHash = new System.Text.StringBuilder();
                foreach (var b in sha1)
                    computedHash.Append(b.ToString("x2"));

                query["signature"] = computedHash.ToString();
        }

        uriBuilder.Query = query.ToString();

        return uriBuilder.ToString();
}
```

As for the `code`, there is currently no way to send it as part of the redirect.

**Comment by stevkan** [comment]
Closing this as resolved.
