### ISSUE TITLE
Support for Facebook Personas API

### ISSUE THREAD

**Issue by patrickianco** [microsoft/botframework-sdk#6258]
Hello,

I'm wondering if the botframework sdk supports the use of Facebook's Personas API? I tried adding it to the channelData property but I don't see it reflecting in my chatbot.

**Comment by patrickianco** [comment]
Hello is there an update for this? Is this possible in the current build?

**Comment by tracyboehrer** [comment]
This would be a function of the Facebook Adapter.  Continued development of this has moved to Bot Framework Community.
