### ISSUE TITLE
Triggers need to be able to assign properties

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#6272]
One of the biggest things we've lost in moving from ActivityHandler to triggers is the ability to serialize the incoming Activity/invoke payload into object that are easier for the developer to work with. This means that anyone using Composer that needs to get access to a particular piece of information needs to understand the Activity schema well enough (or find the right documentation). This is prohibitive.

I propose we add a mechanism for triggers to define properties and populate them with data that can then be used in the resulting dialog flow.

For example, a developer shouldn't need to know where to find the membersAdded array on a conversationUpdate Activity- we should assign it to a property and make it easily discoverable and visible for them to use.

This is particularly important for Teams bots, where there are lots of complex payloads that can be very difficult to discover and traverse if you don't have very detailed knowledge of how everything works (messaging extension invokes, for example).

**Comment by tomlm** [comment]
I agree, there 2 are  mechanisms

1.  Condition can add promote properties to turn, so **turn.activity.value.data.action.verb** can be accessed as **turn.action.verb**
2.  You can register a PathResolver which maps **action.xxxx => turn.activity.value.data.action** so **action.verb** works
