### ISSUE TITLE
Unable to open .docx  file downloaded from SharePoint site / Azure Blob Storage in desktop app(Word) in Teams.

### ISSUE THREAD

**Issue by RajdeepRay0411** [microsoft/botframework-sdk#6276]
## Version
Bot Framework SDK 4.8.1

## Describe the bug
When I'm trying to read files from SharePoint/ Azure Blob Storage, The file from SharePoint site / Azure Blob Storage is properly downloaded in teams and uploaded in one drive as well. on clicking the three buttons and choosing different actions gives different results:- 
1. Edit in teams: Doc.aspx is requesting access to open it and on clicking the 'Request access' button it is opening the file in the browser instead of teams.
2. Open in Desktop App: The file is not opening in the desktop app and the following error is coming.
3. Open in Browser:  The file is properly opening in the browser.

## To Reproduce
1. Download any file from SharePoint/Azure Blob Storage using a bot in Teams.
2. Select three dots
3. Click on 'Open in Desktop App'.

## Expected behavior
The document should be opened in the word of the desktop.

## Screenshots
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/51920866/115959269-04efd200-a529-11eb-955f-954a995c7ac3.png)

**Comment by v-kydela** [comment]
Thanks for the report, @RajdeepRay0411 

This looks Teams is sending the wrong command to Office, which would make this a Teams problem rather than a bot problem. The best way to provide Teams feedback is usually through Teams itself, but I'll see if I can find someone who can help.

**Comment by Wajeed-msft** [comment]
@v-kydela - I have raised this on Teams side here: https://github.com/MicrosoftDocs/msteams-docs/issues/3180

Could you please help to close this?
