### ISSUE TITLE
Typo in product documentation - "activites"

### ISSUE THREAD

**Issue by plan-do-break-fix** [microsoft/botframework-sdk#6277]
## Describe the bug

`/docs/umlDiagrams/Authentication/ChannelToBot/README.md` contains the text "activites."

## Expected behavior
Give a clear and concise description of what you expected to happen.

`activites` => `activities`

**Comment by Zerryth** [comment]
Thanks for reporting @plan-do-break-fix. Quick fix is up, and will be in shortly after review
