### ISSUE TITLE
Facebook message_echoes SendActivitiesAsync Forbidden

### ISSUE THREAD

**Issue by EdoardoCinelliSistemEvo** [microsoft/botframework-sdk#6282]
I need to reprompt the quick replies when the owner of the facebook page sand message in the chat. The only way to catch this event is by using Facebook [message_echoes](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/message-echoes/?locale=it_IT) but if i try to use ITurnContext of the echo message or one stored of previous message throw me this error :

> ```
> Exception caught : System.NullReferenceException: Object reference not set to an instance of an object.
>          at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
>          at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass30_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
>       --- End of stack trace from previous location where exception was thrown ---
>          at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
>          at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(String textReplyToSend, String speak, String inputHint, CancellationToken cancellationToken)
>          at eeve.ai.BotFramework.Bot.OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken) in C:\Work\eeve.ai.BotFramework\eeve.ai.BotFramework\Bot.cs:line 193
>          at Microsoft.Bot.Builder.BotFrameworkAdapter.TenantIdWorkaroundForTeamsMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
>          at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
>          at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
> ```

and this one

> ```
> Connection id "0HM8E1HUBD86G", Request id "0HM8E1HUBD86G:00000001": An unhandled exception was thrown by the application.
> Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
>    at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
>    at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
>    at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass30_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(IActivity activity, CancellationToken cancellationToken)
>    at Microsoft.Bot.Builder.TurnContext.SendActivityAsync(String textReplyToSend, String speak, String inputHint, CancellationToken cancellationToken)
>    at eeve.ai.BotFramework.Startup.<>c__DisplayClass6_1.<<ConfigureServices>b__7>d.MoveNext() in C:\Work\eeve.ai.BotFramework\eeve.ai.BotFramework\Startup.cs:line 83
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
>    at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(ClaimsIdentity claimsIdentity, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
>    at Microsoft.Bot.Builder.BotFrameworkAdapter.ProcessActivityAsync(String authHeader, Activity activity, BotCallbackHandler callback, CancellationToken cancellationToken)
>    at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandler.ProcessMessageRequestAsync(HttpRequest request, IAdapterIntegration adapter, BotCallbackHandler botCallbackHandler, CancellationToken cancellationToken)
>    at Microsoft.Bot.Builder.Integration.AspNet.Core.Handlers.BotMessageHandlerBase.HandleAsync(HttpContext httpContext)
>    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
>    at AspNetCoreRateLimit.RateLimitMiddleware`1.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
> ```

This is the body request

```json
{
  "type": "message",
  "serviceUrl": "https://facebook.botframework.com/",
  "channelId": "facebook",
  "from": {
    "id": "xxxxxxxxxxxxxxx"
  },
  "conversation": {
    "id": "xxxxxxxxxxxxxxx-xxxxxxxxxxxxxxx"
  },
  "recipient": {
    "id": "xxxxxxxxxxxxxxx"
  },
  "text": "Sorry, it looks like something went wrong.",
  "inputHint": "acceptingInput",
  "replyToId": "xxxxxxxxxxxx"
}
```

I noticed that even though I used the ITurnContext saved previously the conversation id in the request. Is it possible to fix this bug?

**Comment by v-kydela** [comment]
Thank you for the report, @EdoardoCinelliSistemEvo 

Can you please provide some minimal example code and repro steps?

**Comment by EdoardoCinelliSistemEvo** [comment]
This is a code example of what I am trying to do. The first 2 SendActivityAsync are for debugging only.
```
public async Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default(CancellationToken))
{
    if (turnContext.Activity.Name == "echo" && turnContext.Activity.ChannelId == "facebook" && turnContext.Activity.Type == ActivityTypes.Event)
    {
        JObject echoValue = JObject.Parse(turnContext.Activity.Text);
        if (echoValue["message"] != null)
        {
            if (!(echoValue["message"]["app_id"] != null))
            {
                await turnContext.SendActivityAsync("foo");
                string echoConvId = turnContext.Activity.Conversation.Id.Split("-")[1] + "-" + turnContext.Activity.Conversation.Id.Split("-")[0];
                ITurnContext echoTurnContext = _accessors.ITurnContextSet.Where(x => x.Key == echoConvId).FirstOrDefault().Value;
                await echoTurnContext.SendActivityAsync("foo");
                DialogContext dcEcho = await _accessors.conversationDialogSet.Where(x => x.Key == echoConvId).FirstOrDefault().Value.CreateContextAsync(echoTurnContext);
                await dcEcho.RepromptDialogAsync();
            }
        }
    }
}
```
To recreate this bug you need to activate the message_echoes feature on facebook. As a user, send a message that activates an output with Quick Replies via the botFramework. Supposing that the user doesn't choose any Quick Replies, enter the page inbox as the owner of the page, and send a text message to the user.
After the user has received the message, the Quick Replies disappear and it's no longer possible to make them appear again.

If you need additional information, I remain available for clarification.

**Comment by v-kydela** [comment]
Thanks, @EdoardoCinelliSistemEvo 

I want to see if I can make this example a bit more minimal so that we can narrow down what might be causing the issue. It looks like you're doing a few different things in response to a Facebook echo. Which of those lines are causing the errors that you posted about originally? Can you reproduce the problem using only those lines?

You mention quick replies as part of your repro. Can you reproduce the problem without quick replies?

My understanding is that the echo webhook will be triggered any time your page sends a message to the user, regardless of whether the message came from a page admin or a bot. Can you reproduce the problem when the echo is in response to a bot-to-user message?

Also, given that bot-to-user messages can trigger echoes, it seems risky to be sending more bot-to-user messages in response to those echoes. Could you perhaps be triggering an endless loop, and could that be related to the errors you're getting?

**Comment by EdoardoCinelliSistemEvo** [comment]
> Thanks, @EdoardoCinelliSistemEvo
> 
> I want to see if I can make this example a bit more minimal so that we can narrow down what might be causing the issue. It looks like you're doing a few different things in response to a Facebook echo. Which of those lines are causing the errors that you posted about originally? 

All 3 lead to the error and the third which is the one that should fix my problem has no effect on the chat. All 3 calls are made with the same from id, conversation id and recipient id but they should be reversed since in the second and third call I don't use the same ITurnContext.

>
> Can you reproduce the problem using only those lines?
>

No, to be able to reproduce it you have to save ITurnContext in a list and then access it, I used the BotAccessors for doing that.

>
> You mention quick replies as part of your repro. Can you reproduce the problem without quick replies?
> 

Yes, the error occurs even without the quick replies

>
> My understanding is that the echo webhook will be triggered any time your page sends a message to the user, regardless of whether the message came from a page admin or a bot. Can you reproduce the problem when the echo is in response to a bot-to-user message?
>

Yes, the error also occurs with the echo messages sent by the bot.

> 
> Also, given that bot-to-user messages can trigger echoes, it seems risky to be sending more bot-to-user messages in response to those echoes. Could you perhaps be triggering an endless loop, and could that be related to the errors you're getting?
>

Right observation, but I discriminate the messages sent by the bot with those sent by the Admin with
`if (echoValue["message"] != null)
        {
            if (!(echoValue["message"]["app_id"] != null))`.
In this way an infinite loop cannot take place.

I hope I have clearly answered your questions. If you need additional information, I remain available for clarification.

**Comment by EdoardoCinelliSistemEvo** [comment]
> > All 3 lead to the error and the third which is the one that should fix my problem has no effect on the chat. All 3 calls are made with the same from id, conversation id and recipient id but they should be reversed since in the second and third call I don't use the same ITurnContext.
> 
> All 3 what? I didn't mention 3 of anything, and you have more than 3 lines of code. Can you be more specific about what you're talking about?

1) await turnContext.SendActivityAsync("foo");
2) await echoTurnContext.SendActivityAsync("foo");
3) await dcEcho.RepromptDialogAsync();

**Comment by v-kydela** [comment]
Thank you, @EdoardoCinelliSistemEvo. I've figured out what's going on now.

The Bot Framework Facebook connector service doesn't always have a good idea of how to handle the various Messenger webhooks, and in the case of message_echoes it gets things a little backwards. This makes sense when you think about what an echo is and how it reverses the direction of messages. The connector service looks at Facebook payloads and expects the sender to be the user and the recipient to be the bot and it constructs its conversation ID accordingly, so in this case it constructs its conversation ID backwards. You seem to have intuited this because you wrote code to reverse the conversation ID, but that's not enough. The incoming activity still has the wrong values for its `from` and `recipient` properties, so those need to be reversed as well. Finally, any time you modify the turn context it's good practice to put it back the way it was afterwards, just to make sure you don't screw up the rest of the pipeline.

One way to reverse the `from` and `recipient` properties is to use `ApplyConversationReference`, so you could do something like this:

```c#
private static async Task SendFromEchoAsync(ITurnContext turnContext, Activity activity, CancellationToken cancellationToken = default)
{
    var cr = turnContext.Activity.GetConversationReference();

    turnContext.Activity.ApplyConversationReference(cr);
    ReverseConversationId(turnContext.Activity);

    await turnContext.SendActivityAsync(activity, cancellationToken);

    turnContext.Activity.ApplyConversationReference(cr, true);
    ReverseConversationId(turnContext.Activity);
}

private static void ReverseConversationId(IActivity activity)
{
    var segments = activity.Conversation.Id.Split('-');

    activity.Conversation.Id = $"{segments.Last()}-{segments.First()}";
}
```

Does this resolve your issue?

**Comment by v-kydela** [comment]
@EdoardoCinelliSistemEvo - Are you still working on this?

**Comment by v-kydela** [comment]
@EdoardoCinelliSistemEvo - My sample code doesn't currently mention `ApplyConversationReference`, so I presume you're talking about the comment I made before I edited it. You can see `ApplyConversationReference` used in samples 17, 80, and 81 if that's what you're asking. As with all public methods in the SDK, it is documented: https://docs.microsoft.com/dotnet/api/microsoft.bot.schema.activity.applyconversationreference#Microsoft_Bot_Schema_Activity_ApplyConversationReference_Microsoft_Bot_Schema_ConversationReference_System_Boolean_

I'm glad we could get your issue resolved
