### ISSUE TITLE
Proactive Message from Skill not showing up in Skill consumer

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botframework-sdk#6284]
We have developed various handoff skills that allow skill consumers to handoff their users to chat systems like Genesys, Salesforce, Teams etc. These skills rely on Proactive Messages to relay the agent message back to the user. However when I hooked up a PVA bot to this Skill the proactive messages did not arrive at all.

I isolated this into a simple proactive skill that sends messages every 10 seconds and none of these messages arrived. Any user initiated messages do get processed ok.

I assume this behavior will be similar between regular Bot Framework bots, Composer & PVA, although I only tested this with Composer as the skill and PVA as the skill Consumer. Composer version is V1.4.1

All the logic and examples are the same as the issue I raised with the Proactive Delay: https://github.com/microsoft/BotFramework-WebChat/issues/3874
@v-kydela As this issue is so similar to reproduce as the other one, I hope you don't mind me mentioning you here

**Comment by tdurnford** [comment]
@msomanathan Can you take a look at this?

**Comment by msomanathan** [comment]
@cxbuilders - Could you please try the following overload of `ContinueConversationAsync`: https://github.com/microsoft/botbuilder-dotnet/blob/3181dd34ceb68878d9ffea42626ebb839a58482b/libraries/Microsoft.Bot.Builder/BotAdapter.cs#L183?

From a skill, it needs the OAuthScope of the consumer bot to be passed as the `audience` of the proactive message.

**Comment by msomanathan** [comment]
@cxbuilders Could you please share your bot code for me to repro your scenario?

**Comment by msomanathan** [comment]
@cxbuilders Thanks, I will take a look at the sample. Meanwhile, could you please try to get the `audience` parameter from the turn state like the below code? The turn state should have the OAuth scope of the skill consumer regardless of whether the consumer is PVA or not.
https://github.com/microsoft/BotFramework-FunctionalTests/blob/4507be00dd746f9f34dfbb747d7aa178477e42ce/Bots/DotNet/Skills/CodeFirst/WaterfallSkillBot/Dialogs/Proactive/WaitForProactiveDialog.cs#L70

**Comment by cxbuilders** [comment]
@msomanathan Just tried the OAuthScopeKey using the code you provided and that worked perfectly!

**Comment by cleemullins** [comment]
@msomanathan @cxbuilders closing due to customer having code now working.
