### ISSUE TITLE
Not able to access turnContext.TurnState from Composer

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/botframework-sdk#6292]
## Describe the bug

I'm converting one of the Bot Builder Community's middleware to the Bot Framework Component. This part works well. There's no issue with that. 

However, this middleware (and many others of the similar nature), keep a value in a state just like below [7]; 

![image](https://user-images.githubusercontent.com/16351038/118381341-545b8680-b62d-11eb-9534-b3089016bccc.png)

I am able to debug, it gets hit and it sets the value against `Sentiment` properly. 

**_The challenge is, I can't extract the value of `Sentiment` property in Composer._** 

Is there anything I am missing? I also tried to echo the whole turn object from Composer. 

![image](https://user-images.githubusercontent.com/16351038/118381552-4f97d200-b62f-11eb-9867-4ed6ad065e8d.png)

And it gave me this;

```
{

“lgType”: “Activity”,

“text”: {

"locale": "en-US",

"activity": {

  "type": "message",

  "id": "29bd88f0-b5d9-11eb-9366-a13f515b7b6c",

  "timestamp": "2021-05-16T09:56:27.775+10:00",

  "localTimestamp": "2021-05-16T09:56:27+10:00",

  "serviceUrl": "http://localhost:51287",

  "channelId": "emulator",

  "from": {

    "id": "abd1a24e-8d7b-4f34-9c0a-ddfbc06f1e2b",

    "name": "User",

    "role": "user"

  },

  "conversation": {

    "id": "13813e60-b5d9-11eb-a4f0-bd67a2b3bcc3|livechat"

  },

  "recipient": {

    "id": "aa9ecf70-b5d8-11eb-a4f0-bd67a2b3bcc3",

    "name": "Bot",

    "role": "bot"

  },

  "textFormat": "plain",

  "locale": "en-US",

  "text": "i love this movie",

  "channelData": {

    "clientActivityID": "1621122987753kq5lsipj2in",

    "clientTimestamp": "2021-05-15T23:56:27.753Z"

  }

},

"dialogEvent": {

  "Bubble": false,

  "Name": "recognizeUtterance",

  "Value": {

    "type": "message",

    "id": "29bd88f0-b5d9-11eb-9366-a13f515b7b6c",

    "timestamp": "2021-05-16T09:56:27.775+10:00",

    "localTimestamp": "2021-05-16T09:56:27+10:00",

    "localTimezone": null,

    "serviceUrl": "http://localhost:51287",

    "channelId": "emulator",

    "from": {

      "id": "abd1a24e-8d7b-4f34-9c0a-ddfbc06f1e2b",

      "name": "User",

      "aadObjectId": null,

      "role": "user"

    },

    "conversation": {

      "isGroup": null,

      "conversationType": null,

      "id": "13813e60-b5d9-11eb-a4f0-bd67a2b3bcc3|livechat",

      "name": null,

      "aadObjectId": null,

      "role": null,

      "tenantId": null

    },

    "recipient": {

      "id": "aa9ecf70-b5d8-11eb-a4f0-bd67a2b3bcc3",

      "name": "Bot",

      "aadObjectId": null,

      "role": "bot"

    },

    "textFormat": "plain",

    "attachmentLayout": null,

    "membersAdded": null,

    "membersRemoved": null,

    "reactionsAdded": null,

    "reactionsRemoved": null,

    "topicName": null,

    "historyDisclosed": null,

    "locale": "en-US",

    "text": "i love this movie",

    "speak": null,

    "inputHint": null,

    "summary": null,

    "suggestedActions": null,

    "attachments": null,

    "entities": null,

    "channelData": {

      "clientActivityID": "1621122987753kq5lsipj2in",

      "clientTimestamp": "2021-05-15T23:56:27.753Z"

    },

    "action": null,

    "replyToId": null,

    "label": null,

    "valueType": null,

    "value": null,

    "name": null,

    "relatesTo": null,

    "code": null,

    "expiration": null,

    "importance": null,

    "deliveryMode": null,

    "listenFor": null,

    "textHighlights": null,

    "semanticAction": null,

    "callerId": null

  }

},

"recognized": {

  "text": "i love this movie",

  "alteredText": null,

  "intents": {

    "movie": {

      "score": 1.0,

      "pattern": "movie"

    }

  },

  "entities": {

    "$instance": {}

  },

  "intent": "movie",

  "score": 1.0

},

"result": "i love this movie",

"activityProcessed": true,

"lastresult": "i love this movie"
}

}
```

## Version

Version:  2.0.0-nightly.245700.30d28dc
Electron: 8.2.4
Chrome: 80.0.3987.165
NodeJS: 12.13.0
V8: 8.0.426.27-electron.0

## Browser

- [x] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [x] Windows
- [ ] Ubuntu

## To Reproduce

1. In your middleware, set the turnContext.TurnState.Add<string>['YourProperty', 'YourValue']
2. Try to fetch it from Composer?

## Expected behavior

I should be able to extract the value of `Sentiment` Property from the Composer

**Comment by ninggao** [comment]
@anusharavindrar Could you please take a look at this one?

**Comment by ninggao** [comment]
@dmvtech Could you please take a look at this one?

**Comment by anusharavindrar** [comment]
@boydc2014, any pointers on how to go about solving the user's ask of extracting the value of Sentiment property in Composer.

**Comment by boydc2014** [comment]
@Danieladu can you help check what's the correct way to refer this "Sentiment" object

**Comment by arafattehsin** [comment]
@boydc2014 - I totally agree on TurnState not being equal to "turn" scope. However, the suggested approached `(TurnState.Add("turn.Sentiment",value)` did not work. Although I have managed to make it work by storing it to the `conversation` memory scope and since it is accessible from the Composer; it works. 

However, I am still not sure if it should be considered as a good practice to store these things in `conversation` rather than a `turn` memory scope.

**Comment by boydc2014** [comment]
> @boydc2014 - I totally agree on TurnState not being equal to "turn" scope. However, the suggested approached `(TurnState.Add("turn.Sentiment",value)` did not work. Although I have managed to make it work by storing it to the `conversation` memory scope and since it is accessible from the Composer; it works.
> 
> However, I am still not sure if it should be considered as a good practice to store these things in `conversation` rather than a `turn` memory scope.

Sorry for the inaccruate suggestion, i didn't try turn.Sentiment, there seems to be a little different here, @Danieladu can you help point to how to update turn scope correctly. 

In terms of which scope to pick, turn, conversion, user have different persistence policy, depends on your scenario , here is a more detailed description https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-dialog-memory-states?view=azure-bot-service-4.0#managing-state.

**Comment by Danieladu** [comment]
hi @arafattehsin 
You may could not set "turn.xxx" directly in Middleware, please ref this code to find a right way if you want to set some data into "turn" scope in middleware: https://github.com/microsoft/botbuilder-dotnet/blob/587bde7cc0b1c0f67ec3c4a568d7409c4ec1f706/libraries/Microsoft.Bot.Builder/TurnContext.cs#L114

Or if your code could access "ObjectPath" class, you could apply such code below:
```
ObjectPath.SetPathValue(turnContext.TurnState, "turn.xxx", value);
```

Thanks.

**Comment by arafattehsin** [comment]
> hi @arafattehsin 
> You may could not set "turn.xxx" directly in Middleware, please ref this code to find a right way if you want to set some data into "turn" scope in middleware: https://github.com/microsoft/botbuilder-dotnet/blob/587bde7cc0b1c0f67ec3c4a568d7409c4ec1f706/libraries/Microsoft.Bot.Builder/TurnContext.cs#L114
> 
> Or if your code could access "ObjectPath" class, you could apply such code below:
> ```
> ObjectPath.SetPathValue(turnContext.TurnState, "turn.xxx", value);
> ```
> 
> Thanks.

My problem is to access it in Composer. I am able to set turn.TurnState in the middleware.

**Comment by boydc2014** [comment]
> > hi @arafattehsin
> > You may could not set "turn.xxx" directly in Middleware, please ref this code to find a right way if you want to set some data into "turn" scope in middleware: https://github.com/microsoft/botbuilder-dotnet/blob/587bde7cc0b1c0f67ec3c4a568d7409c4ec1f706/libraries/Microsoft.Bot.Builder/TurnContext.cs#L114
> > Or if your code could access "ObjectPath" class, you could apply such code below:
> > ```
> > ObjectPath.SetPathValue(turnContext.TurnState, "turn.xxx", value);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks.
> 
> My problem is to access it in Composer. I am able to set turn.TurnState in the middleware.

The reason you wasn't able to access it is you didn't set it correctly. This line is wrong, you aren't suppose to set things directly into TurnState object. 
![image](https://user-images.githubusercontent.com/3829387/118745894-c6c8a280-b889-11eb-8eda-3628e91085e8.png)

A correct indicator is this, if you succesfully put your information in here, then later you would be able to refer it. 
![image](https://user-images.githubusercontent.com/3829387/118745957-e2cc4400-b889-11eb-9685-2ad0f22a4bfa.png)

**Comment by Danieladu** [comment]
What you set is a value with a string key, the key name is "turn.xxx". But in Composer, if user input : "turn.xxx", it means turn is a outer property, and xxx is an inner property.
For example:
Turn state:   -> you set "turn.xxx" -> yyy,  the real data is 
```
{
  "turn.xxx": "yyy"
}
```

But if you apply the solution I given: you could get:
```
{
  "turn": {
     "xxx": "yyy"   -> you could use "turn.xxx" in Composer to achieve "yyy" now
   }
}
```

The composer could only access the "turn" scope, but not "turn.xxx" scope.

**Comment by arafattehsin** [comment]
@boydc2014 and @Danieladu - now it makes sense to me. Thanks folks. I will try this way and surely get back to you. Once done, I will then close this issue.

**Comment by arafattehsin** [comment]
Thanks @boydc2014 & @Danieladu - works like a charm!

![image](https://user-images.githubusercontent.com/16351038/118768963-f516a400-b8c2-11eb-82f3-cb576ec6c058.png)
