### ISSUE TITLE
[Analysis] Support for MSIs & single tenant apps

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#6313]
## Summary

We need to add support for using MSI as the authentication mechanism. This will effect essentially the breadth of our set of products.

- [ ] Analysis - examine the breadth of our products and create issues for each impacted product/area
  - [ ] Cloud adapter
  - [ ] Bot Framework adapter
  - [ ] Channel adapters
  - [ ] Skills 
  - [ ] Emulator
  - [ ] Web Chat
  - [ ] Composer creation
  - [ ] Composer provisioning
  - [ ] Composer deployments
  - [ ] Runtime & generators
  - [ ] BF CLI
  - [ ] PVA interop
  - [ ] LUIS integration
  - [ ] QnA Maker integration
  - [ ] Storage providers
  - [ ] Community adapters
  - [ ] Existing packages (human handoff & service now in particular)
- [ ] Implementation
- [ ] Testing
- [ ] Documentation
- [ ] Samples

Child Issues:

- [ ] MSI for CogServices: https://github.com/microsoft/botframework-cli/issues/1136
- [ ] 

## Internal whitepapers

- https://microsoft-my.sharepoint-df.com/:w:/p/kirkul/ESXE9C29r2VAn6X03NRVaNYB2_oR4K25ZfdNFSDBqXApGw?e=PrcAem
- https://microsoft.sharepoint.com/:w:/t/ConversationalAI785/Ecn_jou4toJPi7FdI8hFQr4Bq0EkcTwIOixm00Nd3SgQGg?e=2Sjl0e

**Comment by elliottperry** [comment]
Andrew to speak to Muthu and schedule after the Channel <> Bot auth work is complete. ID 6335

**Comment by tracyboehrer** [comment]
This is mostly resolved, though there are MSI + Skills issues that are being tracked separately.
