### ISSUE TITLE
[Rollup] DirectLine client-side auth with AAD

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#6314]
## Summary

Direct Line relies on a shared secret to allow a client to initiate communication. However, ABS will begin to support AAD/MSAL for all the authorization needs. This allows the customers to control all their auth tokens from a single place and take advantage of all the enhancements that AAD will bring over time – token revocation for example.

- [ ] Analysis of impacted areas (breakdown into further issues)
  - [ ] Webchat (update token refresh logic)
  - [ ] Samples/docs
  - [ ] Composer DirectLine configuration UI
- [ ] Implementation phase 1
  - [ ] Sample
  - [ ] Doc
- [ ] Implementation phase 2
  - [ ] WebChat
  - [ ] Composer

## Internal whitepaper

- https://microsoft.sharepoint.com/:w:/t/ConversationalAI785/Eb3aqC7C8b9AktK3Z878bMMBszfTN8uZkrIf4L13v_y37Q?e=G10ozd

**Comment by elliottperry** [comment]
This is closed due to no work required on SDK. 

Mai and Edwin will test and verify end-to-end.
