### ISSUE TITLE
File downloading is getting failed in MS Teams Bot (Desktop and Web) using File consent card.

### ISSUE THREAD

**Issue by RajdeepRay0411** [microsoft/botframework-sdk#6316]
## Version

Bot Framework SDK 4.8.1
Microsoft.Bot. Schema version 4.8.0
## Describe the bug

1.	File downloading is failing in MS Teams Bot (Desktop and Web) whereas files are properly getting uploaded in Users OneDrive.

2.	We are using a File Consent Card to upload the file in the User’s OneDrive. And once, the file is uploaded in OneDrive, Bot brings back the option to download the document locally in the MS Teams BOT. After clicking on 3 Dots > Download > it is showing “The File Didn’t Download”

Code Snippet for file consent card :
string filename = fileName + "." + fileExtension;

                        long filesize = Convert.ToInt64(result);
                        var consentContext = new Dictionary<string, string>
                            {
                              { "filename", filename }
                            };

                        var fileCard = new FileConsentCard
                        {
                            Description = "This is the file I want to send you",
                            SizeInBytes = filesize,
                            AcceptContext = consentContext,
                            DeclineContext = consentContext
                        };

                        var asAttachment = new Microsoft.Bot.Schema.Attachment
                        {
                            Content = fileCard,
                            ContentType = FileConsentCard.ContentType,
                            Name = filename,
                        };
                        attachment.ContentData = fileCard;
                        attachment.ContentType = FileConsentCard.ContentType;
                        attachment.Text = filename;

## Screenshots
Please find the screenshots,

![Picture1](https://user-images.githubusercontent.com/51920866/121801413-cc30c700-cc54-11eb-90cd-0fed846ee07e.png)

![Picture2](https://user-images.githubusercontent.com/51920866/121801443-e10d5a80-cc54-11eb-9ff5-3d59da57ecde.jpg)

![Picture3](https://user-images.githubusercontent.com/51920866/121801456-f5e9ee00-cc54-11eb-9ff2-601f899fe58b.jpg)

**Comment by clearab** [comment]
Hi - Its hard to tell what is going wrong from the code snippet above. Have you taken a look at our complete file upload sample here - https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/56.teams-file-upload/Bots/TeamsFileUploadBot.cs ? That shows the entire flow, including creating the download card in the `FileUploadCompletedAsync` method.

**Comment by Chetana-MSFT** [comment]
@RajdeepRay0411  Have you gone through [TeamsFilsUploadBot ](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/56.teams-file-upload/Bots/TeamsFileUploadBot.cs) sample, are you still facing the issue.

**Comment by RajdeepRay0411** [comment]
Hi @clearab and @Chetana-MSFT: I had gone through the documents you have shared. I am using the same thing but still, the same issue is coming. Can you please let us know if there have been some changes from the MS side for file uploading and downloading in the latest app updates.

**Comment by Chetana-MSFT** [comment]
Hi @RajdeepRay0411 I am able repro the issue, we have raised a bug for this, concerned engineering team is working on it.
