### ISSUE TITLE
Update Skill manifests to support URI-References

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#6320]
[v 2.1 of the skill manifest schema](https://github.com/microsoft/botframework-sdk/blob/main/schemas/skills/v2.1/skill-manifest.json) only supports absolute URI format for the following fields:

- [privacyUrl](https://github.com/microsoft/botframework-sdk/blob/main/schemas/skills/v2.1/skill-manifest.json#L42)
- [iconUrl](https://github.com/microsoft/botframework-sdk/blob/main/schemas/skills/v2.1/skill-manifest.json#L55)
- [languageModel/url](https://github.com/microsoft/botframework-sdk/blob/main/schemas/skills/v2.1/skill-manifest.json#L358)

We have a scenario where we would like to be able to package a manifest and related assets in a single compressed file so it can be downloaded/uploaded for local processing. 

To support offline processing, we will be changing the format for the properties above to accept `uri-reference`

For example, the current definition for [languageModel/url](https://github.com/microsoft/botframework-sdk/blob/main/schemas/skills/v2.1/skill-manifest.json#L358) would change from:

```json
"url": {
  "type": "string",
  "format": "uri",
  "description": "A URL for the location of the language model file"
},
```

to 

```json
"url": {
  "type": "string",
  "format": "uri-reference",
  "description": "A URI for the location of the language model file"
},
```

## Manifest processing
Based on the [RF3986](https://datatracker.ietf.org/doc/html/rfc3986#section-4.1) definition for `uri-reference`, the applications processing the manifest instance should interpret the fields above as follows:
1. If the URI-reference's prefix does not match the syntax of a scheme (e.g. `file`:, `https:`, etc.) followed by its colon separator, then the URI-reference is a relative reference.
2. Absolute URIs should be resolved as specified in the field
3. Relative URIs should be resolved by combining the URI for the manifest with the relative URI specified in the field

![image](https://user-images.githubusercontent.com/12264946/122236788-d0dfc000-ce8c-11eb-89ec-604c049fe507.png)

## Manifest versioning implications
This change is backward compatible so manifests created against the 2.1 version of the skill manifest schema should still be valid against this updated version (the target new version will be 2.2)

## Question for reviewers
Do we want to support URI references for [endpointUrl](https://github.com/microsoft/botframework-sdk/blob/main/schemas/skills/v2.1/skill-manifest.json#L180)? I can't think of a use case where we would have the bot endpoint relative to the manifest location but just asking since we are going to create a 2.2 manifest and there's an opportunity to expand this.

**Comment by luhan2017** [comment]
I think the endpointUrl is tricky. The endpointUrl does not refer to a file and doesn't follow the file folder structure. In most of the cases manifest are shared as http://endpoint/manifests/manifest.json. The privacy, icon and dispatch model urls are all files and can follow the same folder structure with manifest file. But it will be confused if we apply this rule to endpointUrl. And especially for PVA scenario, what should the endpoint url look like if we load the manifest file from local.
