### ISSUE TITLE
Echobot working fine in emulator. But when deployed and testing on azure (Test in web chat) getting 500 response

### ISSUE THREAD

**Issue by dittukumar** [microsoft/botframework-sdk#6328]
I created an echobot and connected to QNAMaker. It is working fine in local when tested with emulator. Later I deployed the echobot on azure using [this steps](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp). This deployment basically created 3 things 1. Bot channel registration, 2. App Service, 3. App Service Plan
I then opened the azure portal opened the bot (Bot channel registration) which got created. And clicked 'Test in web chat'.
When I type anything in the web chat I don't get any response. So when I inspected the page and saw in network, I could see a call named 'activities'. And in the response I see this message 
{
  "error": {
    "code": "BotError",
    "message": "Failed to send activity: bot returned an error"
  },
  "httpStatusCode": 500
}

What could be the reason? 
Also I verified the app service and its running fine. I have provided the correct MicrosoftAppId and Password also. Please someone help me here.

**Comment by dittukumar** [comment]
@EricDahlvang @pankajdmishra  Need your help here.

**Comment by dmvtech** [comment]
@dittukumar 

> Also I verified the app service and its running fine. I have provided the correct MicrosoftAppId and Password also. Please someone help me here.

Were you testing the same appid/password when testing locally with Emulator?

I would also be interested to see if the bot will work if you run locally with appid/password but [set the endpoint to use ngrok, then test with Test in Web Chat](https://blog.botframework.com/2017/10/19/debug-channel-locally-using-ngrok/).

**Comment by tinuCoder** [comment]
@dittukumar

Did you tried to test the bot in Web chat channel? 

Please check the appid and password auto created in your App on Azure if in case it's the same one please try to regenerate the password and use the new one. This should solve your problem.

If you still face the issue check the Auth file and also please share the exception error log.
