### ISSUE TITLE
OAuth 2 Generic Provider w/ AAD B2C - 404 Bad Request after login

### ISSUE THREAD

**Issue by hypertrends** [microsoft/botframework-sdk#6342]
## Version
What package version of the SDK are you using? v4

C# SDK

## Describe the bug

We are trying to use the OAuth2.0 Generic Provider to connect with our Azure Active Directory B2C so that the Bot framework can get back an OAuth access token to make API calls to our platform from the Teams app.

The standard Teams auth with AAD v2 works just fine and returns a token as expected. The generic provider does not. The "Test Connection" option fails. We are able to see the login screen for our B2C policy, we are successfully able to login, after the login we are redirected back to the redirect url with the "state" and the "code" parameters correctly as shown here (code truncated for brevity)

https://token.botframework.com/.auth/web/redirect?state=e062dcdea3304e6db4518751f4add69a&code=eyJraWQiOiJWNHQyLU5pdzc0ZG1LNHlSVkloSzhaeFdaWWV2dksyUzh0QzdhWHpnYTA4IiwidmVyIjoiMS4wIiwiemlwIjoiRGVmbGF0ZSIsInNlciI6IjEuMCJ9.lNclGosHEWjLqAg5xyC-rYSLcRay80...

However, upon hitting this page, we get the error as shown:

`{
"message": "Login failed",
"statusCode": 404,
"responseBody": "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."
}`

We have followed all the steps provided here: https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-concept-identity-providers?view=azure-bot-service-4.0&tabs=adv1%2Ca2gp

Here is our setup:

- clientId: setup from the B2C registration
- secret: setup from the B2C registration
- RedirectURI in app: https://token.botframework.com/.auth/web/redirect 
- Access Tokens, ID Tokens, implicit grant flows are turned on for the B2C App registration
- Scope List Delimiter - which is a , (comma) as requested in the documentation
- Authorization URL Template: https://revworkdev.b2clogin.com/revworkdev.onmicrosoft.com/oauth2/v2.0/authorize
- Authorization URL Query String Template - ?p=b2c_1a_smart_sign_in&client_id={ClientId}&response_type=code&redirect_uri={RedirectUrl}&scope={Scopes}&state={State}
- Token URL Template - https://revworkdev.b2clogin.com/revworkdev.onmicrosoft.com/oauth2/v2.0/token
- Token URL Query String Template - ?
- Token Body Template - p=b2c_1a_smart_sign_in&refresh_token={RefreshToken}&redirect_uri={RedirectUrl}&grant_type=refresh_token&client_id={ClientId}&client_secret={ClientSecret}
- scopes - openid profile

## Expected behavior
We should've received a token after being redirected to the https://token.botframework.com/.auth/web/redirect URL

## Screenshots
https://www.loom.com/share/5414a130c98445c68639016657cd569f - here is a full loom recording explaining this issue

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by axelsrz** [comment]
Hello @hypertrends thanks for logging this. We're currently contacting the botframework service team to check if this issue is a bug or the feature (AAD B2C) isn't supported yet.

Thanks.

**Comment by axelsrz** [comment]
Hey @Jeffders could you or someone in the service team provide an insight on this issue.

Thanks.

**Comment by Jeffders** [comment]
Hi @hypertrends...thank you for the long note and the amazing video overview of what you are seeing (that includes suggestions on the docs and a form input bug in the Azure portal!).

I had a couple thoughts here:

1. Could you send me the .har file? If you want to work offline as this may take some back and forth...it's my github name with "at microsoft" dot com :p I can then try to loop in some folks from the AAD team to see if they notice something.

2. When I try to go to any site associated with your B2C endpoint, I get a 404...including just going to the login page:
https://revworkdev.b2clogin.com/login or https://revworkdev.b2clogin.com/  ... is it possible this B2C endpoint isn't active?

**Comment by Jeffders** [comment]
One thing I've noticed is that the token endpoint query parameter doesn't look right...currently you have it set to just '?'. Can you set it to '?p=b2c_1a_smart_sign_in' and see if this helps?

For example, when I just go to your token endpoint https://revworkdev.b2clogin.com/revworkdev.onmicrosoft.com/oauth2/v2.0/token, I get the 404.

But when I go to the one with the query parameter, I get a real page: https://revworkdev.b2clogin.com/revworkdev.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1a_smart_sign_in

**Comment by Jeffders** [comment]
One other finding is that for B2C, instead of using a URL query parameter for the policy, you can add it in the path, like this:

 https://revworkdev.b2clogin.com/revworkdev.onmicrosoft.com/b2c_1a_smart_sign_in/oauth2/v2.0/token

Then the query string template can stay "?"

Probably either of these are fine (putting the policy in the query string OR the path), but I just wanted to include this note as well.

**Comment by hypertrends** [comment]
Hello Jeff,
This works. It’s odd because I already had this in the Token Body Template field. I guess I needed to move this into the Token Body Template. I will also try the non-query string parameter approach now to confirm if that also works.

[A close up of a logo  Description automatically generated]
ANUP MARWADI
CEO – HYPERTRENDS GLOBAL INCTM
[A picture containing wall, person, person, posing  Description automatically generated]  [signature_1698191717]
BUILDING PRODUCTS THAT MAKE A DENT IN THE UNIVERSE

800.626.3503  |  Toll Free
858.999.1117  |  Mobile
3687 4th Ave, Suite 103, San Diego, CA 92103
Twitter: @anupmarwadi, @hypertrends
https://www.hypertrends.com/
EMAIL HOURS: 8:30AM-9AM PST | 11:30AM-12:30PM PST | 3-4:00PM PST | FRIDAYS – BAT SIGNAL ONLY 😊

From: Jeff Derstadt ***@***.***>
Date: Thursday, July 15, 2021 at 6:34 AM
To: microsoft/botframework-sdk ***@***.***>
Cc: Anup Marwadi ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/botframework-sdk] OAuth 2 Generic Provider w/ AAD B2C - 404 Bad Request after login (#6342)

One thing I've noticed is that the token endpoint query parameter doesn't look right...currently you have it set to just '?'. Can you set it to '?p=b2c_1a_smart_sign_in' and see if this helps?

For example, when I just go to your token endpoint https://revworkdev.b2clogin.com/revworkdev.onmicrosoft.com/oauth2/v2.0/token, I get the 404.

But when I go to the one with the query parameter, I get a real page: https://revworkdev.b2clogin.com/revworkdev.onmicrosoft.com/oauth2/v2.0/token?p=b2c_1a_smart_sign_in

**Comment by Jeffders** [comment]
Glad things are working for you!!
