### ISSUE TITLE
I am getting the following error when passing 3 or 4 length characters to RecognizeAsync method

### ISSUE THREAD

**Issue by sreejithrkknd** [microsoft/botframework-sdk#6347]
## Version
What package version of the SDK are you using.

## Describe the bug
Latest
## To Reproduce
When passing 3 to 4 length characters to RecognizeAsync() method I am getting the following error
value:"Unable to cast object of type 'System.Collections.ObjectModel.ReadOnlyCollection`1[Microsoft.BotFramework.Orchestrator.Result]' to type 'System.Collections.Generic.List`1[Microsoft.BotFramework.Orchestrator.Result]'.

example- if turn context value contain only 3 or 4 length characters it is throwing the above error ex- passing hi or run or yes or no
                var dc = new DialogContext(new DialogSet(), turnContext, new DialogState());
                var allScores = await _dispatch.RecognizeAsync(dc, (Activity)turnContext.Activity, cancellationToken);

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by tonyanziano** [comment]
@hcyang can you please take a look at this?

**Comment by hcyang** [comment]
Hi @sreejithrkknd, there is a PR (https://github.com/microsoft/botbuilder-dotnet/pull/5763) that fixed the read-only Result issue using OrchestratorRecognizer. That PR has been checked into 4.14 release branch. Please install the latest 4.14 branch release or the daily build and try again.

**Comment by sreejithrkknd** [comment]
Hi @hcyang  it resolved after using the latest package. thank you for helping me out.
