### ISSUE TITLE
Suggestion: flag to enable LUIS spell check

### ISSUE THREAD

**Issue by scheyal** [microsoft/botframework-sdk#6349]
Filed for tracking based on group conversation:

Carlos:
Spell check can be added by adding the `mkt-bing-spell-check-key` header to the http requests to LUIS and then LUIS will return the corrected version into AlteredText. The gap is that the SDK does not expose a way to control headers declaratively or a higher level property specific to spell check.

@darrenj , @carlosscastro FYI :)

**Comment by scheyal** [comment]
Dup of #5794

**Comment by carlosscastro** [comment]
The dupe above is not the right one. Tracking issue is in botbuilder-dotnet, under this issue: https://github.com/microsoft/botbuilder-dotnet/issues/5794
