### ISSUE TITLE
Adding WhatsApp Adapter (MessageBird) to readme file under Channels and Adapters section

### ISSUE THREAD

**Issue by ahmetkocadogan** [microsoft/botframework-sdk#6352]
Hello. Can we add WhatsApp adapter via MessageBird in the table at the section Channels and Adapters (https://github.com/microsoft/botframework-sdk#channels-and-adapters) ?

https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/develop/libraries/Bot.Builder.Community.Adapters.MessageBird

**Comment by tracyboehrer** [comment]
Very old issue, but 3rd part Adapter support moved to Bot Framework Community.
