### ISSUE TITLE
XPATH function doesn't work on Node.JS bots...

### ISSUE THREAD

**Issue by victorlamana** [microsoft/botframework-sdk#6353]
## Describe the bug

There is no "xpath" function available for node.js bots...when I search on the object manipulation submenu it only shows a C# restricted version of the function:

![image](https://user-images.githubusercontent.com/52974336/127170292-4b16b88b-ed1f-4126-8ca1-74650341d4e9.png)

However if I type "=x" on the value field it shows another xpath function which implies that works with Node.JS

![image](https://user-images.githubusercontent.com/52974336/127170410-8c07d75b-5fae-4911-b61b-6de21f7b32fc.png)

But if I select this function the application prompts an error:

![image](https://user-images.githubusercontent.com/52974336/127170716-8b484c55-bd23-449d-a14a-cf54fd2d96ce.png)

If I try to run the bot this is the following message on Trace Error:

![image](https://user-images.githubusercontent.com/52974336/127170997-9ef27be3-c596-4bdb-8f03-e314b5e415fa.png)

Am I doing something wrong?

## Version
2.0 available build 

## Browser

- [X ] Electron distribution
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Edge

## OS

- [ ] macOS
- [ X] Windows
- [ ] Ubuntu

## To Reproduce

1. Create a Node.JS bot
2. Do an API call with XML response
3. Try to access the XML content using xpath function

## Expected behavior

Bot uses XPATH to access XML content

## Screenshots
Already on the description

## Additional context
Any help is appreciated, I found this post earlier today about this function on stackoverflow, which is the one I've been trying to replicate:

https://stackoverflow.com/questions/65708302/how-can-i-compose-a-bot-to-iterate-trough-a-xml-json-object

**Comment by victorlamana** [comment]
Hello Tony, thanks a lot for the reply! Meanwhile, is there any option for me? Is there a way for me to access this XML response from a GET Request on Composer with a node.js bot?

Please

**Comment by tonyanziano** [comment]
Hello @victorlamana ,

According to the docs, you _should_ be able [to use the `json()` prebuild function](https://docs.microsoft.com/en-us/azure/bot-service/adaptive-expressions/adaptive-expressions-prebuilt-functions?view=azure-bot-service-4.0#json) to parse the XML into JSON and then be able to read the response from the JSON.

![image](https://user-images.githubusercontent.com/3452012/127229186-ba9e895b-02f3-4e0b-af31-ad71a64121de.png)

That might be worth a shot

**Comment by victorlamana** [comment]
I can't find a way to make this work, even trying to use the exact  same example from the documentation doesn't work....

I just copy-pasted the exact example from the documentation:

![image](https://user-images.githubusercontent.com/52974336/127325600-6af5585d-8e0a-4135-afc6-a677ba8dba02.png)

And it gives an error

![image](https://user-images.githubusercontent.com/52974336/127326793-a5ee7ab4-2cb6-43c2-92f3-8db5e4e95eea.png)

![image](https://user-images.githubusercontent.com/52974336/127325616-fcf8cfd6-10a1-43ab-9b24-e9aca10a4c3e.png)

If I remove the equal sign before the function, it reads the entire text as a string on the bot:

![image](https://user-images.githubusercontent.com/52974336/127327258-03616e09-e731-474b-91be-48a11d84051f.png)

![image](https://user-images.githubusercontent.com/52974336/127327266-8a9fe988-9248-4830-9f6d-f2dca7103307.png)


I would be truly glad if you show me an example of these functions working with XML just for me to understand what am I doing wrong on Composer

Thanks a lot in advance

**Comment by tonyanziano** [comment]
Hi @victorlamana ,

I looked into the [sourcecode for the `json()` function in the NodeJS sdk](https://github.com/microsoft/botbuilder-js/blob/main/libraries/adaptive-expressions/src/builtinFunctions/json.ts#L30) and it looks like it just calls `JSON.parse()`, which does not work on XML.

The docs should be updated to reflect this, and sorry for the inconvenience.

As for an alternative way to parse the XML, I'm not sure how to accomplish this, but I'll ask around on the team and see if anybody knows.

**Comment by tonyanziano** [comment]
Hi @victorlamana ,

After talking with some teammates, it looks like `xPath` should indeed be available to the Composer JS runtime. Looking at your example, I can see that your expression is: 

`xpath('....` 

try changing the casing to `xPath('...` and see if that works.

**Comment by victorlamana** [comment]
hello @tonyanziano , after some struggling with our Cloud team here we managed to convert the response to JSON with a header on the request. Now it's just the matter of acessing the values on the response but I think it won't be as difficult . 

I'll try your suggestion here just in case someone ends up reading this article on the future

I tested and created a JPATH on this website just to validate what I was inputing on Composer
https://www.freeformatter.com/xpath-tester.html#ad-output
![image](https://user-images.githubusercontent.com/52974336/127386533-03b0cd17-bc28-45a5-ac0e-9f68ce996c4c.png)

The query " /feed/entry/id/text() " works fine:

![image](https://user-images.githubusercontent.com/52974336/127386653-0b426748-3bcc-4bde-bc0a-10513dfe7e7b.png)

But on Composer it is blank:

![image](https://user-images.githubusercontent.com/52974336/127386773-a8235700-00a0-4128-b4d3-9f0322cb6f1e.png)


The Request on Composer is fine too:

![image](https://user-images.githubusercontent.com/52974336/127386817-5294217b-8078-4077-8963-e5651df27217.png)

Thanks a lot for all the help and support @tonyanziano

**Comment by tonyanziano** [comment]
@victorlamana no problem!

I've gone ahead and verified that `xPath` works with a NodeJS bot:

![image](https://user-images.githubusercontent.com/3452012/127390365-a823451a-0c73-43d5-93c4-26ddda0c407d.png)

However, the docs do still use the wrong casing in the examples, so that should be fixed.

![image](https://user-images.githubusercontent.com/3452012/127390680-b7f24001-913b-40b6-842e-5d4bd06290f9.png)
