### ISSUE TITLE
The ConversationUpdate event is sent just once

### ISSUE THREAD

**Issue by nonatocosta** [microsoft/botframework-sdk#6359]
## Version
What package version of the SDK are you using.
4

## Describe the bug
Hello everyone. I installed the Bot Framework Emulator to do some tests locally. I saw in the the official documentation that my bot would receive a notification for ConversationUpdate/UserJoins and another for ConversationUpdate/BotJoins. But, as I could  see in my Bot Framwork Emulator, my bot received only one ConversationUpdate event, with all the members added at the same time.

How to solve this problem.

## To Reproduce
1. Run the bot (I tested with nodejs and python)
2. Open the Bot Framework emulator
3. Inspect the "conversationUpdate" event on the emulator
4. You will see 2 members (user and bot) added at the same time.

## Expected behavior
I would see two "conversationUpdate" events. One for the User-joins and the other for Bot-jois.

## Screenshots
![image](https://user-images.githubusercontent.com/68787711/128616365-93dfad72-675c-4518-8fd7-b34e304cf71d.png)

**Comment by gabog** [comment]
Hi @p-nagpal, can you help us with this one? I think this changed to be only one message but it looks like the docs haven't been updated.

@miguelarcan, can you send us the link in the docs where you saw this docuemented?

Thanks

**Comment by miguelarcan** [comment]
Hey @gabog , sure

that is the link
https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0

> The Bot Framework Service may send a conversation update when a party joins the conversation. **For example, on starting a conversation with the Bot Framework Emulator, you will see two conversation update activities (one for the user joining the conversation and one for the bot joining).** To distinguish these conversation update activities, check who is included in the members added property of the activity.

**Comment by costanonato** [comment]
I did another kind of test to check if this happens just with the bot emulator, but, it seems that the problem happens in the Azure Web Chat as well.

I added a code to show a message in the chat every time the 'onMembersAdded' is called.

```
        this.onMembersAdded(async (context, next) => {/
            const testMessage = '=============onMembersAddedCalled==================='
            await context.sendActivity(MessageFactory.text(testMessage, testMessage))
            await next();
        });
```
.
As you can see in the print below, it is called just once, even in the Azure Chat

![image](https://user-images.githubusercontent.com/26768762/128768686-dec305c1-10c4-4d50-9310-6dbae9884927.png)

**Comment by nonatocosta** [comment]
I did another kind of test to check if this happens just with the bot emulator, but, it seems that the problem happens in the Azure Web Chat as well.

I added a code to show a message in the chat every time the 'onMembersAdded' is called.

        this.onMembersAdded(async (context, next) => {/
            const testMessage = '=============onMembersAddedCalled==================='
            await context.sendActivity(MessageFactory.text(testMessage, testMessage))
            await next();
        });
.
.
As you can see in the print below, it is called just once, even in the Azure Chat
.
![image](https://user-images.githubusercontent.com/68787711/128768966-11009f59-f7af-4716-8637-90748ffe599b.png)

**Comment by p-nagpal** [comment]
Hi @nonatocosta, DirectLine channel always attempts to send a single conversationUpdate if the user identity is available at conversation start. If the user identity is available, the channel includes the bot and the user together as members added into a single conversation update. 

In some scenarios, the conversation may start without a user id and the channel sends a second conversationUpdate when the user identity is made available.

I have open a documentation bug to add this additional information - https://github.com/MicrosoftDocs/bot-docs/issues/2118

Can you share a little bit more about your scenario and usage of two separate ConversationUpdate activities? Does inspecting the MembersAdded work for you?

**Comment by nonatocosta** [comment]
Hi @p-nagpal 

thanks for the answer

yes, inspecting MembersAdded worked for me.

my concern was that I though that my bot was not catching the events correctly.

thank you very much for clarifying it for me

**Comment by gabog** [comment]
Thanks @p-nagpal for taking care of this.
@nonatocosta, I will close this issue, feel free to re-open if you need more help
