### ISSUE TITLE
Botbuilder Dispatch command line issue

### ISSUE THREAD

**Issue by vdimitrova12** [microsoft/botframework-sdk#6363]
## Version
Dispatch 1.7.7

## Describe the bug
I cannot import my dispatch model to LUIS. I found online that similar issue was reported and fixed with dispatch 1.7.1 version but I still got the same issue with 1.7.7 version of dispatch

## To Reproduce
1. Open cmd window and create the dispatch model
2. Add LUIS model and QnA model
3. Run the create command
4. Received the following error: Failed importing TomoniDispatch app - {"error":{"code":"BadArgument","message":"Cannot find the feature with the Id (Turbine Phrases) in the specified application version."}}

## Expected behavior
Expected to be able to create the dispatch model

## Screenshots
![DispatchError](https://user-images.githubusercontent.com/89091597/129763828-f20c380d-b86e-4cdc-a1e0-1fadc7ba0bce.PNG)

## Additional context
I tried to import the dispatch inside LUIS and I received the same error.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by joshgummersall** [comment]
Closing in favor of https://github.com/microsoft/botframework-sdk/issues/6364
