### ISSUE TITLE
Botbuilder Dispatch command line issue

### ISSUE THREAD

**Issue by vdimitrova12** [microsoft/botframework-sdk#6364]
## Version
Dispatch 1.7.7

## Describe the bug
I cannot add QnA model to the dispatch model. I received 401 error.

## To Reproduce
1. Open cmd window and create a dispatch model
2. Try to add QnA model to the dispatch model:
dispatch add -t qna -i "XXX-XXXXX" -n "TomoniDev" -k "XXXXXXXX --intentName q_TomoniDevQnA-qna
4. Received the 401 error. I have tested in Postman with the same values for AppID and key that I used in Dispatch cli tool and I am able to get a response no 401 error.

## Expected behavior
I should be able to add QnA model to the dispatch model.

## Screenshots
![Dispatch_AddError](https://user-images.githubusercontent.com/89091597/129771208-b35b1b5b-7804-4539-9e8e-ff6a5737f678.PNG)

## Additional context
Note in the uploaded print screen that the endpoint URL used in dispatch is not the correct one we use and there is no option to override that URL value.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by joshgummersall** [comment]
Closing in favor of https://github.com/microsoft/botframework-cli/issues/1284
