### ISSUE TITLE
- Labels with dark color are not visible on a dark background (and vice versa on light backgrounds)

### ISSUE THREAD

**Issue by mackizzer** [microsoft/botframework-sdk#6367]
- Labels with dark color are not visible on a dark background (and vice versa on light backgrounds)
- "Raw" `issue view` output should never output colored labels, not even when CLICOLOR_FORCE is set

Fixes #4065, closes https://github.com/cli/cli/pull/4066, closes #4064
Partly reverts #3912 /cc @bchadwic 

__Originally posted by @mislav in https://github.com/cli/cli/pull/4079__

**Comment by joshgummersall** [comment]
Can you provide some more detail as to the issue you're observing? Is this a CLI issue?

**Comment by LeeParrishMSFT** [comment]
Closed due to lack of response.
