### ISSUE TITLE
HttpRequest trace not showing custom headers

### ISSUE THREAD

**Issue by SSanjeevi** [microsoft/botframework-sdk#6368]
## Describe the bug

Send an HTTP request doesn't send the custom headers added

## Version

2.1.0

## Browser

- [ ] Electron distribution

## OS

- [ ] Windows

## To Reproduce

1. Go to 'Send an HTTP request'
2. Click on 'add headers'
3. give values for headers name and value
4. on http request trace in emulator i find headers are not sent in the request headers and the request fails due to this.

## Expected behavior

Added headers should pass in the request headers.

## Screenshots

![image](https://user-images.githubusercontent.com/24915474/130052159-0ffbe96a-a82c-4b70-92ba-7e1ec5b52461.png)

![image](https://user-images.githubusercontent.com/24915474/130052285-c0b3e7b0-9e5b-49a3-85cd-885cd9603b8f.png)

**Comment by tonyanziano** [comment]
SDK team, could there be something wrong with the way the HttpRequest trace is built? It seems like custom headers set within Composer aren't being logged in the trace:

![image](https://user-images.githubusercontent.com/3452012/130109942-82947333-cc2b-4922-bd8c-397a878a43a4.png)

**Comment by joshgummersall** [comment]
It looks like .NET does not always include headers in the trace. The [trace object is created here](https://github.com/microsoft/botbuilder-dotnet/blob/main/libraries/Microsoft.Bot.Builder.Dialogs.Adaptive/Actions/HttpRequest.cs#L268). Reading the code, it seems that headers are never included for `GET` or `DELETE` requests. @mrivera-ms can you confirm if this is by design?

**Comment by SSanjeevi** [comment]
Team one info I even seen the header in the network trace when I was working 2 days back with same request code of adaptive dialogue.

Not sure why it doesn't sends the header now.
Let me check the fiddler once.

**Comment by SSanjeevi** [comment]
@tonyanziano you are right we are not getting headers in log trace only but in request it's sending.
