### ISSUE TITLE
Drag and drop stops working

### ISSUE THREAD

**Issue by WhiteCyClop** [microsoft/botframework-sdk#6374]
## Version
SDK v4

## Describe the bug
I have a personal bot that supports files. At windows desktop app I can attach file by drag'n'drop to the text input field:

![image](https://user-images.githubusercontent.com/47722281/131518833-7b1cf033-7b62-4d1b-9de8-c66dd3c60efc.png)

But when I switch to another "tab" (e.g. Activity, Teams, Calls, Files)

![image](https://user-images.githubusercontent.com/47722281/131520052-f2f02e19-cbb3-4da7-8e5d-c8ce8b1cc9ca.png)

and then return back, then I lose the ability to send a file by drag'n'drop:

![image](https://user-images.githubusercontent.com/47722281/131519422-bbbe7a48-c578-430b-8369-b1bbfda98dcb.png)

To return this ability I have to either send any text message to the bot, or switch to another chat and then return to the chat with my bot

**Comment by dmvtech** [comment]
Hi @WhiteCyClop This issue is related to the Teams client/frontend/UI. Even though it is happening with bots, it is not because of the botframework or SDK. I would suggest opening an issue with the Teams product itself. I'll see if I can find you any info on how you can do that.

**Comment by LeeParrishMSFT** [comment]
When a bot is running within Teams the UI is provides from Teams, so please reach out to the Teams group directly using one of the methods outlined here: https://docs.microsoft.com/en-us/microsoftteams/platform/feedback and they can assist in this. Unfortunately the Bot Framework Team doesn't have the ability to debug or make changes to the Teams product.
