### ISSUE TITLE
response failed chatbot application

### ISSUE THREAD

**Issue by ashok-dot** [microsoft/botframework-sdk#6376]
Hi Team,

i am working on chat bot application . i have facing one issues getting response for odata. my api getting the response  for filter entity set  odata. but  it was return different response on "Repose :Note: Since your browser does notsupport JavaScript, you must press the Continuebutton once to". Can you please help on my issue.

URL:https://###/sap/opu/odata/sap/ZUI5_CHATBOT_TEAMS_SRV/ZSGR_STATUSSet()?$filter=( Ebeln eq' ### ' and Ebelp eq '### ' and UserId eq '###' )?saml2=disabled&$format=json

Repose :Note: Since your browser does notsupport JavaScript, you must press the Continuebutton once to

**Comment by dmvtech** [comment]
This doesn't look to be an issue with the Bot Framework SDK, but is a general programming question on making ODATA REST calls using filters. I'd recommend posting on StackOverflow with the tag ODATA, we don't have the ability on this team to assist on this type of issue.
