### ISSUE TITLE
chatbot return repose two times 

### ISSUE THREAD

**Issue by ashok-dot** [microsoft/botframework-sdk#6377]
Hi Team,

Chatbot application return the same responses two times. i need one response when instance was return at the time. how we can the fix this issue.

like this type:
Example
    Kindly contact MDMG team to maintain QAD ID for supplier
    Kindly contact MDMG team to maintain QAD ID for supplier

**Comment by dmvtech** [comment]
We are not able to reproduce this issue. Please share a reproduction of the issue. Either in a zip or a repository.

**Comment by ashok-dot** [comment]
Hi  Team,

I am not able to zip or repository this code, can you please give me any suggestion for this type of issues. how we can able to fix. Can you please help me.

**Comment by dmvtech** [comment]
@ashok-dot Can you give me steps to reproduce? Is this a Composer bot or a code-first bot? What programming language are you using? Are you using a template? Yeoman/Visual Studio?

**Comment by ashok-dot** [comment]
@dmvtech I am using visual studio and .net programing .below method give to response twice.

private  async Task<DialogTurnResult> FinalStepAsync(waaterfallStepContext, CancellationToken cancellationToken)
{
}
and below steps repeatedly executes
if(scrore<0.55)
{
}

**Comment by ashok-dot** [comment]
Hi Team,


Bot replies twice same message .I am using visual studio and .net programing .Can you help me.how to fix this issue

![ms](https://user-images.githubusercontent.com/71329832/132439309-0d43dad5-2b21-4aad-a700-78dfc5e3e3cf.PNG)

**Comment by dmvtech** [comment]
Hi @ashok-dot There is still not enough information here to go on. Can you share more code? Ideally the entire bot in a repo or zip. But the full class or function might help as well. We can help fastest with a full reproduction of the issue.

**Comment by ashok-dot** [comment]
Sorry,i am unable to share my code as per company policy they want accept this code outside portal. could you please give any other alternative idea.

**Comment by ashok-dot** [comment]
Hi Team,

Bot replies twice same message replay back .Can you please help on this issue.

**Comment by gmikels** [comment]
Hi, I'm seeing this issue as well for both the Teams and Skype channel when I create a third party nodejs messaging endpoint. Here are the steps used for the endpoint created using the 'botbuilder' nodejs client. https://github.com/GoogleCloudPlatform/dialogflow-integrations/tree/master/skype

When I test in Web Chat, everything works as expected:
![image](https://user-images.githubusercontent.com/9043244/133678686-a308e15c-e1f3-47f9-bf23-478ab79ba49f.png)

However, when testing in Teams the response is duplicated:
![image](https://user-images.githubusercontent.com/9043244/133678755-7e99166b-c8b6-4ac8-97af-768bbc1d3854.png)

**Comment by gmikels** [comment]
Some additional information. Dialogflow creates a session that corresponds to id = turnContext.activity.from.id from bot framework. The fact that I'm able to complete a session fully, while still receiving odd duplicate responses makes me think that there are 2 sessions, which means 2 separate turnContext.activity.from.id instances for one Teams chat session.

![image](https://user-images.githubusercontent.com/9043244/133681873-ba92832a-dbaa-4980-9f64-c7344c8d654c.png)

**Comment by dmvtech** [comment]
> Some additional information. Dialogflow creates a session that corresponds to id = turnContext.activity.from.id from bot framework. The fact that I'm able to complete a session fully, while still receiving odd duplicate responses makes me think that there are 2 sessions, which means 2 separate turnContext.activity.from.id instances for one Teams chat session.

Thank you @gmikels. I am investigating further. Thank you for the additional info/data.

**Comment by ashok-dot** [comment]
Hi Team,

Bot replies twice same message replay back .Can you please help on this issue.

**Comment by dmvtech** [comment]
Hi @ashok, I am unable to reproduce this at all. I understand that you cannot share your IP/production code, but if you can create a dummy/repro bot that can reproduce the issue; that would help _tremendously_. Alternatively; if you can point to an [sample](https://github.com/microsoft/BotBuilder-Samples) that reproduces this issue, that would work as well.

@gmikels I do not have the resources available to attempt to reproduce through all the steps you are doing. Same as above; if you have a more simple/straightforward example (BotFramework only, or using one of our samples), that would help.

**Comment by munozemilio** [comment]
Hello @gmikels @ashok-dot could you please provide the requested info if possible?

**Comment by dmvtech** [comment]
Closing due to lack of response. Please comment if you can provide more information that will allow us to easily reproduce the issue.
