### ISSUE TITLE
 Chatbot application return same response display twice in Microsoft teams

### ISSUE THREAD

**Issue by ashok-dot** [microsoft/botframework-sdk#6378]
Hi Team,

Chatbot application return same response display twice in Microsoft teams. How to fix this issue.

Example:
Typing message like :Hi
return response :Hello
                           Hello
this two line of code using last return response.
 await stepContext.Context.SendActivityAsync(reply);
 return await stepContext.EndDialogAsync();

**Comment by dmvtech** [comment]
Closing as duplicate of: https://github.com/microsoft/botframework-sdk/issues/6377
