### ISSUE TITLE
R15 Release List

### ISSUE THREAD

**Issue by mrivera-ms** [microsoft/botframework-sdk#6386]
## Package Location
* C# 
** []()
* JS (Uses the @rc tag on public NPM)
** []()
* Python
**
* BF CLI (Uses the @rc tag on public NPM)
** 
** 
* JAVA
  * *
* Web Chat
  * [ ] CDN 
  * [ ] NPM 
  * [ ] Daily build (for RC)

## GitHub Updates
**Create New Branch** @mrivera-ms 
- [x] C# 
- [ ] JS 
- [ ] Python 
- [ ] Java  
- [ ] BF-Cli 
- [ ] Orchestrator
- [ ] V3 C# & JS - No changes to v3 are needed. 3.30 is already released.

**Setup Branch Protection on New Branch** @mrivera-ms 
- [x] C#
- [ ] JS
- [ ] Python
- [ ] Java 
- [ ] Orchestrator
- [ ] BF-Cli

**Bump Version on Main** @mrivera-ms 
- [x] C#
- [ ] JS
- [ ] Python
- [ ] Java 
- [ ] Orchestrator
- [ ] BF-Cli

**Update Readme.md in main to reflect new branch** @mrivera-ms 
- [x] C#
- [ ] JS
- [ ] Python
- [ ] Java 
- [ ] Orchestrator
- [ ] bf-cli (No updates to make)

**Branch Samples** @mrivera-ms 
- [ ] C#, JS, Python, Java 

**Create DRAFT Release** @EricDahlvang
- [ ] C# 
- [ ] JS
- [ ] Python
- [ ] Java 
- [ ] bf-cli 
- [ ] BotFramework-SDK 
- [ ] BotFramework-Components 

**Consolidate release notes and change logs** @mrivera-ms , @EricDahlvang
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java 
- [ ] bf-cli

**Apply Release Notes to DRAFT Release** @mrivera-ms , @EricDahlvang
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java 
- [ ] bf-cli

**Publish GitHub Release** @EricDahlvang
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java 
- [ ] bf-cli

**Web Chat** @compulim
- [ ] 4.15.0
  - [Release testing page](https://corinagum.github.io/WebChat-release-testing)
  - [Daily build](https://github.com/microsoft/BotFramework-WebChat/releases/daily)
    - [ ] Published to NPM: https://www.npmjs.com/package/botframework-webchat/v/4.15.0
    - [ ] Published to CDN: 

## Functional Skills Tests (Gabo, Monica)
- [ ] Functional Test Pipeline

## Samples E2E Tests (Bruce, Monica)
- [ ] DotNet-CoreBot-Linux-Test
- [ ] DotNet-CoreBot-Win-Test
- [ ] DotNet-EchoBot-Linux-Test
- [ ] DotNet-EchoBot-Win-Test
- [ ] Js-CoreBot-Linux-Test
- [ ] Js-CoreBot-Win-Test
- [ ] Js-EchoBot-Linux-Test
- [ ] Js-EchoBot-Win-Test

## Confirm Preview Packages (Monica)
- [x] C# (Adaptive Testing)
- [x] C# (Microsoft.Bot.Builder.Parsers.LU)
- [x] C# (Microsoft.Bot.Builder.Dialogs.Debugging)
- [x] C# (Microsoft.Bot.Builder.Azure.Queues)

## Required Signoff

**Teams**  Sid Uppal, Andrew Clear
- [ ] C#
- [ ] JS

**PVA** Pawan Taparia, Salem Bacha, Karthik Narayanan
- [ ] C# 

**Cortana** Vivek Goswami (Inactive)
- [ ] C#
- [ ] JS 
- [ ] Python

**Prebuilt Experiences** Lauren/Thomas
- [ ] C# 
- [ ] JS
- [ ] bf-cli

**Emulator** Chris Whitten
- [ ] C# (Chris Whitten) 
- [ ] JS (Chris Whitten)
- [ ] Python (TBD)

## Testing Status 
**Acceptance testing:** @stevkan 

- [ ] C# ActivityHandler samples
- [ ] C# CloudAdapter 
- [ ] Javascript
- [ ] Python

**Orchestrator Package Works**
- [ ] C#
- [ ] JS

**New Azure Blobs package works** @EricDahlvang 
- [ ] C#
- [ ] JS

**Step Into Debugging**
- [ ] C#
- [ ] JS
- [ ] Python

**Console Adapter**
- [ ] C#
- [ ] JS
- [ ] Python

**Simple Dialog Flow**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Simple State Management**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Welcome Messages**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Prompts and Prompt Validations**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Standard Cards**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Adaptive Cards**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Card Actions**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Regex Checking**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**QnA Maker**
- [ ] C#
- [ ] JS
- [ ] Java
- [ ] Python

**LUIS**
- [ ] C#
- [ ] JS
- [ ] Java
- [ ] Python

**Attachments**
- [ ] C#
- [ ] JS
- [ ] Java
- [x] Python

**Proactive Messages**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Middleware**
- [ ] C#
- [ ] JS
- [ ] Java
- [ ] Python

**Translations**
- [ ] C#
- [ ] JS
- [ ] Java
- [ ] Python

**Authentication**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Waterfalls and Dialog Sets**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**State Storage**
- [ ] C#
- [ ] JS
- [ ] Java
- [ ] Python

**Transcript Logging**
- [ ] C#
- [ ] JS
- [ ] Java (?)
- [ ] Python

**Facebook-specific Events**
- [ ] C#
- [ ] JS
- [ ] Java
- [ ] Python

**Application Insights**
- [ ] C#
- [ ] JS
- [ ] Java
- [ ] Python

**Teams**
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Bot Templates**
- [ ] C#
- [ ] JS

**BF-CLI**
- [ ] Global & config
- [ ] Chatdown
- [ ] Luis
- [ ] QnAMaker

** Directline Speech **
- [ ] C#
- [ ] JS
- [ ] Python

** Deploy to Azure using BF CLI **
- [ ] C#
- [ ] JS
- [ ] Python
- [ ] Java

**Comment by JonathanFingold** [comment]
@mrivera-ms Can you add to the check list sending the package lists to Shelly's team? This is a necessary step in updating the reference docs.
