### ISSUE TITLE
Messaging endpoint for Bots

### ISSUE THREAD

**Issue by mithun35h** [microsoft/botframework-sdk#6387]
Hi, 

When i provide the ngrok url in the messaging endpoint for bots it works fine, but when i give custom url with AWS Certificate, it doesn't send any messages back to the endpoint, is their any configuration to enable custom domains?

https://ee90-122-171-203-37.ngrok.io/addons/msteams/1/events - works (receives the messages from ms teams bot app)
https://mithunh.bfcus.tempo.dev/addons/msteams/1/event - doesnt work(doesn't receive any messages from ms teams bot app)

<img width="1552" alt="Screenshot 2021-10-20 at 1 50 44 AM" src="https://user-images.githubusercontent.com/5822879/137984427-92bb3573-6347-4e7b-8408-bd5ab8f8659a.png">

**Comment by dmvtech** [comment]
Hi @mithun35h Does this issue reproduce with other channels? For example; are you able to connect to the custom endpoint using Bot Framework Emulator (and appropriate url & credentials)?

**Comment by dmvtech** [comment]
Closing due to lack of response.
