### ISSUE TITLE
// package.json

### ISSUE THREAD

**Issue by masiha2021crypto** [microsoft/botframework-sdk#6395]
// package.json
{
  "imports": {
    "#dep": {
      "node": "dep-node-native",
      "default": "./dep-polyfill.js"
    }
  },
  "dependencies": {
    "dep-node-native": "^1.0.0"
  }
}

_Originally posted by @masiha2021crypto in https://github.com/yarnpkg/berry/issues/3692#issuecomment-958655991_

**Comment by dmvtech** [comment]
This looks like it might have been submitted my mistake. If you have an actual issue/problem/bug/question; please alter the title and body with specific details, and we can reopen.
