### ISSUE TITLE
turnContext.activity.localTimezone not present in specific android device

### ISSUE THREAD

**Issue by SubbaReddi** [microsoft/botframework-sdk#6433]
## Version
What package version of the SDK are you using.

turnContext.activity.localTimezone was not present, on an Android device with below specification:
•	Android Version: 10
•	Model: galaxy A71
•	Language: English(United Kingdom)

## To Reproduce
1. Deploy any sample bot
2. Login to mobile and set language as English(United kingdom) in Galaxy A71 android device(version 10)
3. In OnMessageActivityAsync method, Try to get turnContext.activity.localTimezone 
4. But LocalTimeZone property is not available. 

## Expected behavior
localTimezone value should be available in format of asia/calcutta, but the specific property is not available 

## Screenshots
Working fine Teams desktop/web:
![image](https://user-images.githubusercontent.com/69682598/143478501-d3913459-e555-41dd-b0ca-b8d7297b2105.png)

Behavior in Android:
![image](https://user-images.githubusercontent.com/69682598/143478415-0ceb1451-2030-40e9-8efe-2474fbcc30a1.png)

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by 53645** [comment]
For me

**Comment by axelsrz** [comment]
Hello @clearab we believe this might be a Teams client issue. We appreciate if you could you chime in, thanks.

**Comment by clearab** [comment]
Yep, I believe the Android client was supposed to start sending this a while back. Sounds like a regression, I'll reach out to them.

**Comment by v-chetsh** [comment]
Hello @clearab - Could you please share the updates or ETA for this regression bug.
