### ISSUE TITLE
Handling multi-turn Dialog or conversation for Alexa skill using Bot framework V4 NodeJS

### ISSUE THREAD

**Issue by mallipriya** [microsoft/botframework-sdk#6435]
The waterfall steps of a dialog are not being visited instead the conversation is getting started from the beginning of the dialog(i.e; from the first waterfall step) for each request made to Alexa Skill. I tried using `return Dialog.EndOfTurn;` and `return {status: DialogTurnStatus.waiting};` so that it waits for user input and forwards to the next waterfall step. I referred to [Bot Community GitHub repo - Alexa adapter Library](https://github.com/BotBuilderCommunity/botbuilder-community-js/tree/master/libraries/botbuilder-adapter-alexa).

Unfortunately, I didn't find a solution but I know `return await step.next();` forwards to the next waterfall step without waiting for the input from the user.

I would like to wait for the user input and then forward it to the next waterfall step. Is there a way or any workaround to achieve this?

Here are the screengrabs of my code-

![image1](https://user-images.githubusercontent.com/51745381/144597632-3248e240-40f7-454f-97ae-074f68d4d53c.png)

![image2](https://user-images.githubusercontent.com/51745381/144597365-028f1600-92e9-4022-a97a-1e57ccb5f03f.png)

**Comment by stevkan** [comment]
@mallipriya, I've run into this "issue" before but passing `return { status: DialogTurnStatus.waiting }` has always resolved the issue. A few questions for you to help clarify:

- What version of the SDK are you running?
- Is this the only dialog called in your bot?
- Can you post the code (not a photo):
    - That calls this dialog?
    - Of both the 'qnaresponseStep()` and `emailPromptStep()` steps? The code in the images is getting cut off.

**Comment by mallipriya** [comment]
@stevkan, Thanks for looking into the issue.
I got it working by configuring the Run() method in the bot.js file. I took reference from BotBuilder-Samples [05.multi-turn-prompt](https://github.com/microsoft/BotBuilder-Samples/blob/99223a51869c859a9e81568facd4580467f92825/samples/javascript_nodejs/05.multi-turn-prompt/bots/dialogBot.js#L37).
