### ISSUE TITLE
Create GitHub action to validate parity label on PRs

### ISSUE THREAD

**Issue by gabog** [microsoft/botframework-sdk#6437]
## Summary

We need to be intentional about parity when creating PRs and we often forget to add a parity label to a PR which generates unnecessary parity issues in the other repos. 

We need to create a GitHub action that checks that a parity label is assigned to a PR when it is created. 

Requirements
* All PRs in the language repos MUST have an Automation: _PartityType_ label set, if that label is not present the validation should fail and the PR can not be merged. 
* Parity labels and behaviors

Label | Usage | Action
---|---|---
Automation: No parity  | single | No parity issues will be created on any repo when the PR is merged
Automation: Parity all| single | Parity issues will be created on all the language repos when the PR is merged
Automation: Parity with dotnet  | multiple | A parity issue will be created in the **dotnet** repo when the PR is merged
Automation: Parity with java | multiple | A parity issue will be created in the **java** repo when the PR is merged
Automation: Parity with js | multiple | A parity issue will be created in the **js** repo when the PR is merged
Automation: Parity with python | multiple | A parity issue will be created in the **pyhton** repo when the PR is merged

* If a single usage label is applied, no other parity labels can be added, in other words, if the `Automation: No parity` is applied to a PR, then it should not be possible to add the `Automation: Parity with dotnet` label.
* Parity labels MUST NOT target the same repo as the PR, e.g.: the `Automation: Parity with js` can not be applied to repos in JS PR. 

Implementation notes
* If possible, we should store the source for this action in a shared location so it can be referenced by several repos and avoid duplicating logic.
* Once we are ready, this check should be added to the dotnet and JS repos

**Comment by BruceHaley** [comment]
The prototype is working. 

We need to create a repo in a shared location to store the source code. Suggested new public repo: https://github.com/microsoft/verify-pr-label-action
I assume someone with Monica's powers or higher is required to create this new repo.

Once the new repo exists, I will merge the source code there, fix pointers to point to the new repo, and create final PRs for review. Blocked until then.
