### ISSUE TITLE
QnAMaker (JS) does not support Custom Question answering

### ISSUE THREAD

**Issue by HesselWellema** [microsoft/botframework-sdk#6438]
Reproducable on 11.qnamaker sample 

```
    "dependencies": {
        "botbuilder": "~4.14.0",
        "botbuilder-ai": "~4.14.0",
        "dotenv": "^8.2.0",
        "restify": "~8.5.1"
    },
```

## To Reproduce
1. Migrate existing QnAMaker knowledge base to Custom question answering. Enable multi language support 
2. Install sample javascript_nodejs\11.qnamaker
3. Make sure the settings in .env are filled
4. Run the sample
5. Enter a random question

The result is an error:  [onTurnError] unhandled error: Error: Failed to generate answers: [object Object]

my .env
```
QnAKnowledgebaseId=<name project>
QnAEndpointKey=<Ocp-Apim-Subscription-Key from prediction url>
QnAEndpointHostName=https://<name language resource>.cognitiveservices.azure.com/
```
The same sample works with the original QnAMaker database.

## Expected behavior
I would expect the sample to return an answer from the database or a message that no answer was found.

## Additional context
I also tries to use the url https://<name language resource>.cognitiveservices.azure.com/language/ 
Same result

## Update
The class GenerateAnswerUtils (called by QnaMaker) is expecting the following:
```
const url = `${endpoint.host}/knowledgebases/${endpoint.knowledgeBaseId}/generateanswer`;
```
This will not work with a QnaMaker KB migrated to Custom Questions which expects an url like this:
```
'https://<languageresourcename>.cognitiveservices.azure.com/language/:query-knowledgebases?projectName=<projectname>&api-version=2021-10-01&deploymentName=production'
```
Not sure if this should be a bugreport or feature request.

**Comment by benbrown** [comment]
@HesselWellema Thank you for highlighting this. We don't yet support this in the SDK. Keep track of the attached feature request for the latest status.
