### ISSUE TITLE
Cannot save changes in botframework portal. It errors out "Please correct the errors and try again"

### ISSUE THREAD

**Issue by Saranya-CTSH** [microsoft/botframework-sdk#6440]
## Version
Bot is created from Teams App Studio

## To Reproduce
Log in to Bot Framework portal
Select Bot
Change something
Try and save
Only get "Please correct the errors and try again." error and nothing saves.

## Expected behavior
User should be able to SAVE the settings

## Screenshots
![image](https://user-images.githubusercontent.com/80040783/145815174-414b8e4d-8e4a-4f62-bedd-d5582ab08f58.png)

**Comment by gabog** [comment]
Hi @Saranya-CTSH does this happen if you try to edit the bot from the Azure Portal?

**Comment by psavine42** [comment]
I am also getting this error as of yesterday. The only thing I need to change is the message endpoint. I do not see how to do this in the azure portal. 
![12-14-2021 10-16-41 AM](https://user-images.githubusercontent.com/13985496/146026515-c1262b57-ccc9-4f0c-8255-86e664cd9f3a.jpg)

In my case the bot was created over a year and a half ago. When I go to my azure portal, I do not see the configuration options shown in the [help pages](docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0&tabs=userassigned) .

I see only the options here: 
![12-14-2021 10-25-28 AM](https://user-images.githubusercontent.com/13985496/146027493-6abb8fc2-3db1-416d-8733-831797239e5b.jpg)

**Comment by Saranya-CTSH** [comment]
> Hi @Saranya-CTSH does this happen if you try to edit the bot from the Azure Portal?

This is fixed after migrating to the Azure Portal. Thanks.

**Comment by Saranya-CTSH** [comment]
> I am also getting this error as of yesterday. The only thing I need to change is the message endpoint. I do not see how to do this in the azure portal. ![12-14-2021 10-16-41 AM](https://user-images.githubusercontent.com/13985496/146026515-c1262b57-ccc9-4f0c-8255-86e664cd9f3a.jpg)
> 
> In my case the bot was created over a year and a half ago. When I go to my azure portal, I do not see the configuration options shown in the [help pages](docs.microsoft.com/en-us/azure/bot-service/bot-service-manage-settings?view=azure-bot-service-4.0&tabs=userassigned) .
> 
> I see only the options here: ![12-14-2021 10-25-28 AM](https://user-images.githubusercontent.com/13985496/146027493-6abb8fc2-3db1-416d-8733-831797239e5b.jpg)
> 
> When I inspect the results in browser console of the request to update the changes, I get the error
> 
> ```
> {"Errors":[{"Field":"MsaAppType","Message":"'MsaAppType' property cannot be changed."}]}
> ```
> 
> This happens when I do not make any changes whatsoever.

Hi, We need to migrate the bot from botframework portal to Azure.
There will be Migrate Button at the top right, along with test -
![image](https://user-images.githubusercontent.com/80040783/146033065-68c21089-0b95-4795-bad7-ad90d8ffa9cb.png)

It will provide a custom template to create the bot resource, and that is where you can change your configs, branding and view analytics and everything.

Azure page you are using should be from dev.teams.microsfot.com, but that page isn't helpful, nor does it update anything to the bot.

**Comment by psavine42** [comment]
> 

That worked. Migrating to azure is the solution.

**Comment by gabog** [comment]
Great to hear that, @Saranya-CTSH, I am closing this one, feel free to re-open if you are still having issues
