### ISSUE TITLE
Bot Service missing Web App?

### ISSUE THREAD

**Issue by thdotnet** [microsoft/botframework-sdk#6446]
It seems that many things changed in the past few months and I do believe the Microsoft Docs is not up to date. In the past (a few months ago), when creating an Azure Bot Service, it was also creating an App Service which would be used to host the bot. Nowadays, you have to create an app service yourself. Is that how it's supposed to be or is it a broken ARM template?

Also, it seems that many people (myself included) are facing 401 errors when trying to test a bot deployed to Azure with Bot Framework Emulator. During the bot configuration, I'm just setting the Microsoft App Id (bot id) + app service URL + /api/messages, and leaving the password as blank (as it has a manged identity assigned). Is there some other setting that I'm missing? 

PS: I've double checked inside the Azure Key Vault, and there's no secrets being created.
PS2: If I remove all settings from appsettings.json, it works fine.

**Comment by anishprasad01** [comment]
Hi @thdotnet,

This is intended behavior. The App Service is no longer created automatically when creating an Azure Bot resource in the portal. By default, when you create a bot with a managed identity, only an `Azure Bot` and a `Managed Identity` resource will be created. There should not be a key vault generated automatically for a managed identity bot.

Are you getting a key vault when you make a new managed identity bot?

**Comment by thdotnet** [comment]
@anishprasad01 I am getting the key vault but seems that no secrets are being created. 

- How do I deploy the bot now? 

Those changes are confusing and I don't think Azure Docs is up to date

**Comment by anishprasad01** [comment]
Here are the [docs](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp%2Cuserassigned) for deploying a code-first bot managed identity bot.

**Comment by anishprasad01** [comment]
Correct. The Azure Portal will create an `Azure Bot` and if using a managed identity, a `Managed Identity` resource. If you create a Multi or Single Tenant bot, an `Azure Key Vault` holding the bot's secrets will be created in place of the managed identity.
