### ISSUE TITLE
Getting channelId instead of teamId from the context

### ISSUE THREAD

**Issue by g138** [microsoft/botframework-sdk#6453]
I am developing an Extension in Microsoft Teams.

I am interested in knowing from **where the extension was invoked meaning from which team?**

Below is the code base and steps I did and found an issue (or bug).

```
async handleTeamsMessagingExtensionFetchTask(context, action) {
	console.log(context._activity.channelData);
}
```

```
{
  channel: { id: '19:123456789@thread.tacv2' },
  team: { id: '19:123456789@thread.tacv2' },
  tenant: { id: '5xxx-xxx-xxxx-xxxx-xxxxx' },
  source: { name: 'compose' }
}
```

So, above you can see the channel data I am getting contains the channel and team id - over here I am entering the random numbers - but the main point is in the team id I get the same value as channel id

**See the image below for more clarity:**

![image](https://user-images.githubusercontent.com/36992519/149763038-23150950-3343-4d0b-b12d-7af2ce8e140e.png)

**My question, is that a bug? or this what it is intended to do?**

**Comment by EricDahlvang** [comment]
Hi @g138 

As stated here: https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/get-teams-context?tabs=dotnet#get-the-list-of-channels-in-a-team

`The channel ID for the General channel always matches the team ID.`

**Comment by ramfattah** [comment]
Closing with @EricDahlvang's answer. If you found a bug, please reopen or comment here and we can continue.
