### ISSUE TITLE
isNotificationOnly not working as expected

### ISSUE THREAD

**Issue by leandroamore** [microsoft/botframework-sdk#6455]
## Version
What package version of the SDK are you using.
"Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.13.2" />
## Describe the bug
I have a proactive messaging bot with the isNotificationOnly property in the manifest.
    "bots": [
        {
            "botId": "<botid>",
            "scopes": [
                "personal",
                "team"
            ],
            "supportsFiles": false,
            "isNotificationOnly": true
        }
For many months the chat was disabled for users and they where allowed to send reactions on received messages. Since last month 2 issues appeard:
1. When the chat window is disabled the user is not able to send reactions on received messages
2. when a new message is received the chat window is enabled and the user can send messages and reactions. if you leave the chat and return the chat is disabled again and ability to send reactions dissapeared.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by clearab** [comment]
As this issue is directly related to the Teams app itself, I've escalated to the appropriate team.

**Comment by v-chetsh** [comment]
@leandroamore - We will check on it from our end and redirect it accordingly.

**Comment by leandroamore** [comment]
Thanks! Let me know if you need any more evidence o help from my side.

**Comment by Nivedipa-MSFT** [comment]
@leandroamore - We are able to repro this issue and we have raised a bug for it. We will let you know once we get any update

**Comment by mrivera-ms** [comment]
Hello @Nivedipa-MSFT are there any updates on this issue?

**Comment by Nivedipa-MSFT** [comment]
@mrivera-ms - We have informed Engineering team about the same and they are currently working on the fix. We will inform you once we have further update. Thanks!

**Comment by axelsrz** [comment]
Hey @clearab and @Nivedipa-MSFT do we have any updates from teams? Thank you.

**Comment by clearab** [comment]
No updates, this is currently "in the backlog"

**Comment by gabog** [comment]
Closing this one as it belongs to Teams and it is being tracked there.

**Comment by Nivedipa-MSFT** [comment]
@leandroamore,@mrivera-ms,@axelsrz - The first issue is fixed.
When the chat window is disabled the user is now able to send reactions on received messages.

On second issue the engineering team is working on it. We will let you know once we have any updates.

**Comment by leandroamore** [comment]
Great, thanks for the update. I can confirm that it's working as expected.

> @leandroamore,@mrivera-ms,@axelsrz - The first issue is fixed. When the chat window is disabled the user is now able to send reactions on received messages.
> 
> On second issue the engineering team is working on it. We will let you know once we have any updates.

**Comment by leandroamore** [comment]
Hi @Nivedipa-MSFT, any update on the second issue?

**Comment by Nivedipa-MSFT** [comment]
@leandroamore - Engineering team is working on it. We will inform you once we have any update.

**Comment by nrodrigu3z** [comment]
Hi @Nivedipa-MSFT how are you? Would you kindly let us know if there is any update on the second issue? Thanks
