### ISSUE TITLE
Teams: Read receipts

### ISSUE THREAD

**Issue by clearab** [microsoft/botframework-sdk#6457]
Add support for read receipts in 1-1 chats in Teams.

**Comment by YunnyChung** [comment]
Also BF team is exposing a helper method in the SDK, which basically compares the message ids to decide whether a specific message sent by a bot was read or not. 

Pseudo code: 
bool IsMessageRead(string idOfMessageBotCares, string userLastReadMessageId) 
- if idOfMessageBotCares < userLastReadMessageId ==> the user read the bot's message.

Please add the following to intellisense: 
- (1) `idOfMessageBotCares` should be the id of a message sent by a bot. 
- (2) `idOfMessageBotCares`  and `userLastReadMessageId` should be in the same thread.

**Comment by YunnyChung** [comment]
The below is the final payload that SMBA wants to send out to bot developers. 
`{
	"name": "application/vnd.microsoft.r[eadReceipt]()",
	"type": "event",
	"timestamp": "2021-12-13T06:42:46.8080275Z",
	"channelId": "msteams",
	"serviceUrl": "https://smba.trafficmanager.net/amer/",
	"from": {
		// user who read the bot’s message
		"id": "29:1SDmXi1RdC-QBzk90U81Hr68ooQac9OduJDydLd_kKb4wi8IS8Tmq6BDAqLQr-3Pv75UxRP6ckrz6fBQp5j4yMg",
		"aadObjectId": "cf41f188-30ee-4698-9a65-8af95b9eb9c3"
	},
	"conversation": {
		"conversationType": "personal",
		"tenantId": "1eabcbf3-c625-466a-88e6-bfd660d41b5b",
		"id": "a:14G1N4QRiy4W3zD4H9h8nB2jSzfihTr7OS-zkNScEAY5FwvL0snFkXlSMsflBCfQLKFdoSiI_bzNxmsN1p3i1vI98brvpZrsistuDm71mLgiJmhQ_zLLtEwH9F-7LPrFm"
	},
	"recipient": {
		// bot information.
		"id": "28:e23cded7-1d12-456c-a93d-15e166a83e10",
		"name": "Echobot1_WorkMachine2"
	},
	"channelData": {
		"tenant": {
			"id": "1eabcbf3-c625-466a-88e6-bfd660d41b5b"
		}
	},
	"value": { 
		// the id of the last read message by the user in 1:bot chat
		“lastReadMessageId” : [1638835053529]()
	}
}`

**Comment by YunnyChung** [comment]
This feature is mainly for LOB company communicator bots. 
This is the pseudocode for the bot. 

Context: the company communicator bot wants to know how many users have or have not read the messages sent by the bot. 
1. The company communicator bot sends an announcement message to everyone in the tenant. 
- The bot needs to save the {threadId: messageId} for each thread. Here the message id is the id of the message that the bot wants to know whether the user read it or not.
2. As time passes, each user starts to read the message. This action will generate the read receipt event. 
3. The bot receives the read receipt event which contains the thread id and the id of the message read by the user in that thread. 
4. The bot queries the id of the message that it wants to know the read status of from its database using the thread id. 
5. Then use SDK helper method `IsMessageRead(string idOfMessageBotCares, string userLastReadMessageId)` to check whether the user read the bot's message. `userLastReadMessageId` is coming from the read receipt event payload.
6. If `IsMessageRead` returns true, count +=1 (assuming the bot has the global counter).

**Comment by YunnyChung** [comment]
This is the sample code for the BF SDK helper method `IsMessageRead`

// Bot SDK helper method.
// idOfMessageBotCares: we expect the bot developers to track the id of message that they want to track per thread. 
// userLastReadMessageId: the id in the event payload. 
```
public bool IsMessageRead(string idOfMessageBotCares, string userLastReadMessageId)
{
    if (String.IsNullOrEmpty(idOfMessageBotCares) || String.IsNullOrEmpty(userLastReadMessageId))
    {
        return false;
    }

    long.TryParse(idOfMessageBotCares, out long idOfMessageBotCaresLong);
    long.TryParse(userLastReadMessageId, out long userLastReadMessageIdLong);

    // if idOfMessageBotCares is smaller than userLastReadMessageId, it means the user read the bot's message. 
    return (idOfMessageBotCares.CompareTo(userLastReadMessageId) <= 0) ? true : false;
}
```

**Comment by YunnyChung** [comment]
This is how I am currently consuming a read receipt event on my testing bot. 
```
protected override async Task OnEventActivityAsync(
    ITurnContext<IEventActivity> turnContext, CancellationToken cancellationToken)
{
    var eventType = turnContext.Activity.Name;
    if (!eventType.Contains("readreceipt", StringComparison.InvariantCultureIgnoreCase))
    {
        return;
    }

    var lastReadMessageIdJObject = turnContext.Activity.Value as JObject; // get a user's read status
    var lastReadMessageId = lastReadMessageIdJObject["lastReadMessageId"].ToString(); // get the user's last read message id
    var threadId = turnContext.Activity.Conversation.Id;

    if (_trackTheMessageBotCaresPerThread.ContainsKey(threadId))
    {
        // readReceiptObject is the object that I created as a bot developer to track necessary information for the message that my bot cares.
        ReadReceiptObject readReceiptObject = _trackTheMessageBotCaresPerThread[threadId];
        bool isMessageRead = IsMessageRead(readReceiptObject.botSentMessageId, lastReadMessageId); // call BF SDK's helper method
        
        // the below line is helpful when a bot developer wants to do something for
        // messages that were read vs messages that were not read.
        // ex: Bot developers can query all the messages that were not read and follow up differently.
        readReceiptObject.isMessageRead = isMessageRead;
    }
}
```

**Comment by dalmonn** [comment]
Hi, we are triying to do the same in our bot, almost the same implementation, we noticed that you added the event but we are not finding the way to receive that event.
I mean, we send a message to a user, but when the user open the conversation the event it's not sending to the bot.
Do we need to add something to receive that message? We allow the permission ChatMessageReadReceipt.Read.Chat when the bot it's installed on teams but it's not working.

**Comment by danielmacedo90** [comment]
I have the same scenario as @dalmonn. 

I added the RSC permission in the manifest, but the event is not being sent to the bot.

```
"webApplicationInfo": {
        "id": "xxxxxxxx-xxxxxxxx-xxxxxxxx",
        "resource": "https://RscBasedStoreApp"
    },
    "authorization": {
        "permissions": {
          "resourceSpecific": [
            {
              "name": "ChatMessageReadReceipt.Read.Chat",
              "type": "Application"
            }
          ]
        }
    }
```

Any other necessary settings missing?
