### ISSUE TITLE
Dead Links Additional Reading

### ISSUE THREAD

**Issue by coldcanuk** [microsoft/botframework-sdk#6459]
## Version
n/a

## Describe the bug
In the Additional Reading section the links for the C# and NodeJS links are dead. 

## To Reproduce
1. Goto https://github.com/microsoft/botframework-sdk/tree/main/Orchestrator
2. Scroll down to Additional Reading section. Click on links for C# samples and NodeJS samples

## Expected behavior
the link should work OR be removed from the Additional Reading section

## Screenshots
n/a

## Additional context
n/a

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by msomanathan** [comment]
@coldcanuk - We have a PR that will fix this issue.
