### ISSUE TITLE
OAuthPrompt does not send an OAuth sign-in card; just returns a null token

### ISSUE THREAD

**Issue by tomezpl** [microsoft/botframework-sdk#6466]
## Version
v4.15.2

## Describe the bug
User authentication appears to be completely broken as OAuthPrompt does not send a sign-in card to the user, instead continues to the next dialog step and returns a null token. Neither OnSignInInvoke nor OnTokenResponse events are raised.

## To Reproduce
1. Clone sample 18 from [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/18.bot-authentication)
2. Run in Bot Framework Emulator (or deploy into Azure & Test in Web Chat)
3. Type 'login'
4. Answer 'Yes' when asked if you want to view the token

## Expected behavior
The OAuthPrompt should send an OAuth card activity to the channel. The auth dialog should only continue after the user clicked the 'sign in' button on the card, and finished the sign in process.

## Screenshots
![image](https://user-images.githubusercontent.com/4386963/154246381-e98765ca-a0ee-4421-b4eb-d3e7a8abd73b.png)

## Additional context
Tested this with an ADFS 2016 (Generic OAuth2) as well as GitHub connection in Azure.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by JordyGit** [comment]
Our production bot also got affected. No code changes happened, same deployment just started having this issue. Happens in Teams, Webchat, bot emulator, (no others tested). We Created a support ticket on azure.

**Comment by scp-mb** [comment]
Also seeing this across all of our environments.

**Comment by claudiucristeagab** [comment]
I can confirm that this is happening also on all our testing/production environments. (.NET bot framework v4.15.2). It is a very serious problem.

**Comment by swagatmishra2007** [comment]
we have found the underlying issue and are working on fixing it. the fix has been deployed to our usa datacenters, so if your bot is hosted in US, it should be working fine now. rest of the data centers is in progress and should be done in the next 30 minutes or so

**Comment by richie5um** [comment]
Same for us too. Eagerly awaiting the fix to roll out to our UK data-centres.

**Comment by claudiucristeagab** [comment]
West Europe looks to be working again.

**Comment by JordyGit** [comment]
Everything is working here too. Guess the issues can be closed.

**Comment by dmvtech** [comment]
Thanks everyone for jumping in and contributing and sharing on this one. Closing, but please comment if any issues continue.
