### ISSUE TITLE
Microsoft.Bot.Schema.BotTimeoutException

### ISSUE THREAD

**Issue by ohiobobcat** [microsoft/botframework-sdk#6469]
## Version
4.14.1 (NodeJS)

## Describe the bug
The error we've been seeing for quite sometime now is:

```
Microsoft.Bot.Schema.BotTimeoutException:
   at Microsoft.Bot.ChannelConnector.BotAPI+<PostActivityToBotAsync>d__35.MoveNext (Microsoft.Bot.Base.ChannelConnector, Version=3.2.3.16, Culture=neutral, PublicKeyToken=null: C:\__w\1\s\ChannelSDK\Microsoft.Bot.Base.ChannelConnector\API\BotAPI.cs:493)
```

It seems as though the 15s timeout is being enforced across a Dialog and not for a single turn in the Dialog lifecycle. We do have some multi-turn Dialogs that can take more than 15s, but not 15s before we respond to the user. 

Example: Authentication Dialog (Waterfall Dialog that consists of numerous child dialogs)

The general flow is:
1. Collect User Info
     - Prompt for FName -> user replies
     - Prompt for LName -> user replies
     - Prompt for Zip Code -> user replies
2. Try Identify User
    - API call
3. Request Additional info
    - Prompt for DoB -> user replies
    - API call to confirm user
4. Verify User
    - Prompt for MFA/OTP destination (text/email) -> user replies
    - API call to send confirmation code
    - Prompt for MFA/OTP code
    - API call to verify OTP code

## Expected behavior
I would expect the timeout to occur only if the user sends a message that the bot doesn't respond to w/in 15 seconds. 

## Screenshots
![image](https://user-images.githubusercontent.com/17410889/154352026-2b2b6c78-e1c6-4dbd-a00b-2971afb084a2.png)

## Additional context
- We currently use the Dispatch model to hand-off to Skills
- Additional info will be provided upon request. 

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by ramfattah** [comment]
Hi @ohiobobcat, 

This behavior is expected. Have you had a chance to look at sending proactive messages doc? [Send proactive notifications to users](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-proactive-message?view=azure-bot-service-4.0&tabs=csharp)
proactive messages sample in [C#](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/16.proactive-messages#readme), [JavaScript](https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/16.proactive-messages#readme), [Java](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/16.proactive-messages#readme), or [Python](https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/python/16.proactive-messages#readme).

**Comment by ohiobobcat** [comment]
While I appreciate the response @ramfattah, I don't quite understand the need to send a proactive message when the bot is in the middle of the conversation. How would I know _when_ to send it? Or, what to send. 

This isn't a long running process, it's a long running _conversation_.

Can you please explain further? It's unclear to me why the timeout is occurring as we process the activity and respond to the user within the 15 seconds allotted through a Directline connection and still receive a `504:GatewayTimeout`.

The documentation below seems to contradict your response but it is completely possible that I'm not understanding this correctly. This appears to be for a single activity, not a long running conversation with multiple turns. 

> Proper handling of long-running operations is an important aspect of a robust bot. When the Azure Bot Service sends an activity to your bot from a channel, the bot is expected to process the activity quickly. If the bot doesn't complete the operation within 10 to 15 seconds, depending on the channel, the Azure Bot Service will time out and report back to the client a 504:GatewayTimeout, as described in [How bots work](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0).

I've also re-reviewed these two sections:

- https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0#http-details
- https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0#the-activity-processing-stack

Thank you, 

AJ

**Comment by ramfattah** [comment]
Thanks for following up. As stated in [Azure Bot Service Doc](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-basics?view=azure-bot-service-4.0#:~:text=The%20bot%20has%2015%20seconds%20to%20acknowledge%20the%20call%20with%20a%20status%20200%20on%20most%20channels.%20If%20the%20bot%20doesn%27t%20respond%20within%2015%20seconds%2C%20an%20HTTP%20GatewayTimeout%20error%20(504)%20occurs.), "The bot has 15 seconds to acknowledge the call with a status 200 on most channels. If the bot doesn't respond within 15 seconds, an HTTP GatewayTimeout error (504) occurs."



the above image shows that the call took 15.3 seconds including the call to skill /account-skill/api/messages in total time.

**Comment by ramfattah** [comment]
Hi @ohiobobcat, any updates? were you able to find more information on the BotTimeoutException error?

**Comment by ohiobobcat** [comment]
@ramfattah sorry for delay here. No new updates at this time. I understand that the screen shot shows that's taking longer than 15 seconds and, at times, it does. 

When it does, I expect to receive the timeout. What we're finding is, intermittently, the timeout happens much sooner than expected but the telemetry doesn't match. I'm going to try and get one of my testers to record their testing session next week. 

In the mean time, we're working to reduce the latency. Thanks!

**Comment by ramfattah** [comment]
@ohiobobcat - sounds good.

**Comment by ramfattah** [comment]
Hi @ohiobobcat -- closing this one for now. Please feel free to re-open if you come across any issues.
