### ISSUE TITLE
replyToId missing when submitted from task modules

### ISSUE THREAD

**Issue by harkiratsaluja** [microsoft/botframework-sdk#6473]
## Version
Adaptive Card v1.5

## Describe the bug
I have an adaptive card with an update button action. On pressing update , the task module opens and shows me a form. After submitting the form, I need to update my original adaptive card by adding a success section to it. Now, the problem I am facing is that inside function `handleTeamsTaskModuleSubmit` the context activity is missing `replyToId` key. As per the documents it should be there. Also, I would like to point that inside fetch i.e `handleTeamsTaskModuleFetch` the context activity does have a `replyToId`.

## To Reproduce
Steps to reproduce the behaviour:
1. Send an adaptive card with update button of invoke type fetch.
2. Return a modal with some input fields and try to submit the form.
3. On form submission `handleTeamsTaskModuleSubmit` is called in which `replyToId` is missing.

## Expected behaviour
Inside `handleTeamsTaskModuleSubmit` the `replyToId` should be present inside context activity.

## Additional context
1. Following the adaptive card which is sent:-

```
{
        "type": "AdaptiveCard",
        "body": [
          {
              "type": "TextBlock",
              "text": "Task Module Invocation from Adaptive Card",
              "weight": "bolder",
              "size": 3
          }
        ],
        "actions": [
        {
              "type": "Action.Submit",
              "title": "Title",
              "data": { "msteams": { "type": "task/fetch" }, "data": {} }
        }
      ]
}
```

2. Following is the task module which is sent

```
CardFactory.adaptiveCard({
 $schema: 'http://adaptivecards.io/schemas/adaptive-card.json',
        version: '1.5',
        type: 'AdaptiveCard',
        body: [
          {
            type: 'Input.Text',
            isRequired: false,
            value: 'Harry',
            label: 'Name',
            id: 'Name',
          }
        ],
        actions: [
          {
            type: 'Action.Submit',
            title: 'Save',
            data: {}
          }
        ]})
```

3. Following is the context of when form is submitted
```
{
    "name": "task/submit",
    "type": "invoke",
    "timestamp": "2022-02-23T11:32:43.928Z",
    "localTimestamp": "2022-02-23T17:02:43.928+05:30",
    "id": "f:a7be97e4-95ed-3ea9-d12d-d5053336995e",
    "channelId": "msteams",
    "serviceUrl": "https://smba.trafficmanager.net/amer/",
    "from": {
        "id": "xxxxxxxxx",
        "name": "Harkirat Saluja",
        "aadObjectId": "xxxxx"
    },
    "conversation": {
        "conversationType": "personal",
        "tenantId": "xxxxxx",
        "id": "xxxxxxxxx"
    },
    "recipient": {
        "id": "xxxx",
        "name": "xxx"
    },
    "entities": [
        {
            "locale": "en-US",
            "country": "US",
            "platform": "Mac",
            "timezone": "Asia/Calcutta",
            "type": "clientInfo"
        }
    ],
    "channelData": {
        "tenant": {
            "id": "ec1ca566-ccd6-4dfe-85b5-b8b6da85b645"
        },
        "source": {
            "name": "compose"
        }
    },
    "value": {
        "data": {
            "privateMeta": "{}",
            "Name": "xxxx",
            "Description": "testing from ms teams"
        },
        "context": {
            "theme": "defaultV2"
        }
    },
    "locale": "en-US",
    "localTimezone": "Asia/Calcutta"
    // replyToId is missing
}
```

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by dmvtech** [comment]
Thanks @harkiratsaluja 

I am able to confirm this current behavior and am currently investigating further.

> As per the documents it should be there.

Can you link the documentation you are referring to please?

**Comment by harkiratsaluja** [comment]
Thank you for the reply. Please find the document link [here](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-actions?tabs=javascript#example-of-incoming-invoke-message)

**Comment by dmvtech** [comment]
@clearab Can you comment on this? Is there something that is missing for the replyToId to be sent? (a certain condition, etc).

**Comment by clearab** [comment]
Hi - this is the expected behavior. The submit doesn't have a replyToId because it isn't associated with any particular message - it is essentially context-less (or rather, that the context is only the task module itself). The fetch on the other hand did have a context, the message that it originated from so it get's a replyToId. You should be able to use the ID from the fetch, or the ID from the original AC send to update the existing message.

**Comment by dmvtech** [comment]
@harkiratsaluja Please see above. Use the replyToId that comes from the `"name": "task/fetch","type": "invoke"` instead of the `"name": "task/submit","type": "invoke"`

**Comment by harkiratsaluja** [comment]
Thank you for the confirmation. I am able to reuse this from `handleTeamsTaskModuleFetch` and it works for my use case.
