### ISSUE TITLE
Get sent message/adaptive card inside handleTeamsTaskModuleSubmit

### ISSUE THREAD

**Issue by harkiratsaluja** [microsoft/botframework-sdk#6474]
## Version
Adaptive card 1.5
Bot builder 4.14.0

## Describe the bug
I have a requirement where I need to update as existing adaptive card on submitting a form from task module in Microsoft teams. I am able to achieve this by sending a new card but I need to achieve this by reusing the adaptive card which was sent as the main message. The documentation shows ways to update by sending entirely a new card. I cannot use that because my card is dynamic and cannot have a fixed structure.

## To Reproduce
1. Adaptive card with an update button is sent using the bot framework.
2. On pressing update, handleTeamsTaskModuleFetch is called inside my bot application. Here I make an api call to my backend to get the adaptive card for my modal. This is an input form.
3. On submitting the form, handleTeamsTaskModuleSubmit is called inside my bot application. Here I make an api to my backend to save the information. Post this I need to update my original adaptive card message, by adding a success/failure text.

## Expected behavior
There should be a way in which the sent message/adaptive card should be available while submitting the form. 

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by dmvtech** [comment]
Hi @harkiratsaluja 

There is no way to get the initial card from the client side. You must keep track of the information/values that are set and submitted back and forth from the bot and then replace the original activity/card. You may have to implement other data stores, etc to accomplish this (depending on the specific requirements). The term _update_ is used, but it really is just a replace with the updated content (as you have found). I'm assuming you have seen this already, but this is what is done in the [Teams conversation bot sample](https://github.com/microsoft/BotBuilder-Samples/blob/248d58abe9c350fe71a21288ae2d794615dbbb09/samples/csharp_dotnetcore/57.teams-conversation-bot/Bots/TeamsConversationBot.cs#L221).

**Comment by harkiratsaluja** [comment]
Thank you for the reply. The documentation is a bit confusing in terms of understanding. I spent almost 3 days trying to figure out how to make update work :). This might be due to the fact I am coming from slack background where this is possible. Thank you once again for the confirmation :).
