### ISSUE TITLE
Adding your own newtonsoft json nuget package in any of your Class libraries throws "The reader's MaxDepth of 64 has been exceeded..."

### ISSUE THREAD

**Issue by Brankec** [microsoft/botframework-sdk#6483]
## Version
Composer version 2.1.2
SDK version 4.15.2

## Describe the bug
When adding a C# Class library with the newtonsoft json nuget package, the bot throws an error that the dialog stack has surpassed 64 depth (specifically the newtonsoft json within the bot framework sdk says that) even though it has not surpassed that depth, not even close.

## To Reproduce
1. Create a new C# Echo bot and just add a few nested dialogs (Have several dialogs that start other dialogs, for me it would die after the 4th or 5th dialog)
2. Simply create a new C# Class library for the bot and add a nuget package Newtonsoft json in that new Class library. The version of newtonsoft json I used during the encounter of this bug was version 13.0.1.
3. It is only required that the bot runtime project has reference to the new C# Class library containing newtonsoft json nuget package, it does not matter if your bot calls or does anything with that new Class library.
4. Start the bot and start nesting the dialogs so the dialogstack increases in size

## Expected behavior
When creating a new C# Class library, that utilizes the Newtonsoft json nuget package, it shouldn't be throwing an error that the bot's dialog stack depth has surpassed the default limit of 64 if it's literally only a few dialogs deep.

## Screenshots
![image](https://user-images.githubusercontent.com/33580274/157958356-c1901008-2a31-4a6d-b111-86577d434c0d.png)

## Additional context
Not Applicable.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by anishprasad01** [comment]
This limitation was [added to version 13](https://github.com/JamesNK/Newtonsoft.Json/releases/tag/13.0.1) of Json.NET. The Bot Framework SDK uses version 12 by default. If you add any other libraries that use a higher version, they will override the SDK's version.

The simple fix here is to simply ensure that nowhere in your project is there a reference to a version greater than 12.
