### ISSUE TITLE
Error when Adding Teams Channel

### ISSUE THREAD

**Issue by ryankmcintyre** [microsoft/botframework-sdk#6485]
## Version
N/A, issue is hit prior to using the SDK

## Describe the bug
Trying to update a bot to allow the Teams Channel results in an error and the Teams Channel isn't added.

## To Reproduce in CLI
1. Create an Azure Bot using a multi-tenant app
2. Run the following command: `az bot msteams create -n {{BotName}} -g {{ResourceGroupName}}`
3. See error 

> Error occurred in sending request. Please file an issue on https://github.com/microsoft/botframework-sdk

## To Reproduce in Portal
1. Create an Azure Bot using a multi-tenant app
2. Open the bot in the portal
3. In the left panel, click **Channels**
4. Click the Microsoft Teams icon, then click **Apply**
5. See error 
![888589a6-e5e2-4f2e-a518-6d72c311e871](https://user-images.githubusercontent.com/1696746/158273883-81936929-234e-41b0-aa07-8fd951c1e39b.jpg)

## Expected behavior
The Teams Channel should be added to the bot.

## Additional context
The above steps worked without error last Friday.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR

- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by ramfattah** [comment]
Hi @ryankmcintyre, I was getting this exact error last night. I tried again after an hour and it was fixed. 
Could you please try to add the Teams channel again and see if this issue is solved now?  

Let me know if this works, thanks!

**Comment by ramfattah** [comment]
I'm closing this one for now. @ryankmcintyre please re-open if you are still having issues. Thanks.

**Comment by ryankmcintyre** [comment]
Currently not an issue, it seems to have been fixed overnight.
