### ISSUE TITLE
The activity id is not generating when channel is direct line speech so message not sending to user

### ISSUE THREAD

**Issue by sreejithrkknd** [microsoft/botframework-sdk#6492]
I am getting the activity id as "" when using direct line speech. working fine on the rest of the channels. I am doing handoff to the third party so no response is showing to the user if the channel is direct line speech
                    
 The user is unable to see the response even though the return message contains in the turn context
 
                            
                       I am sending the response to the user via the above code, except for direct line speech all other channels are showing messages to the user.

**Comment by ramfattah** [comment]
Hey @sreejithrkknd, thank you for raising this. Are you able to provide steps to reproduce this issue? [reference here](https://github.com/microsoft/botframework-sdk/blob/main/.github/ISSUE_TEMPLATE/bot-framework-bug.md#:~:text=To%20Reproduce,See%20error)

**Comment by sreejithrkknd** [comment]
@ramfattah Hai thank you for replying when the third party a controller used to receive/send the text from user to agent/agent to user when running these codes
await ((BotFrameworkHttpAdapter)_adapter).ContinueConversationAsync(
                        _credentials.MsAppId,
                        handoffRecord.ConversationReference,

**Comment by sreejithrkknd** [comment]
Automatically resolved when upgraded package
