### ISSUE TITLE
Azure CLI for bot deployment does not provide a way for selecting platform (x64 or x86)

### ISSUE THREAD

**Issue by hcyang** [microsoft/botframework-sdk#6493]
## Version
What package version of the SDK are you using.

## Describe the bug
The Azure CLI deployment guide (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=multitenant%2Cnewgroup%2Cjavascript#prepare-your-project-files) does not have an option on creating a bot in a X64 environment. The default bot service is hosted in a x86 VM, but (most) users may create a bot using packages with x64 native libraries. Zipping up the bot with these x64 packages cannot run after deployed onto the default x86 environment. One may try to flip the bot service to 64-bit and restart it, however the service VM's PATH setting still execute x86 
'node' even though the underlying VM OS has been restarted in x64.

## To Reproduce
See issue https://github.com/microsoft/botframework-sdk/issues/6462 as an example.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by tracyboehrer** [comment]
Old issue, but this is a better question for Azure.
