### ISSUE TITLE
Adaptive card form just works once after submitted

### ISSUE THREAD

**Issue by fernandofas** [microsoft/botframework-sdk#6501]
## Version
1.2

## Describe the bug
Can't use Adaptive Card Forms twice.
I have a few adaptive cards on my Power Virtual Agent bot for different reasons and all of them are forms sending the data to my email through Power Automate.
So, I after filling up the first form from the first adaptive card and submit, I want to fill up another form which is also an adaptive card.
Before the form appears, the bot is giving me the result of the submitted form already.

## To Reproduce
1. Go to https://powerusers.microsoft.com/t5/General/Adaptive-card-form-just-works-once-after-submitted/m-p/1533953#M3455
2. Watch the error here: https://www.kapwing.com/videos/624ec3eee62d030067e2aa06

## Expected behavior
The forms should appear on both occasions.

## Screenshots
[If applicable, add screenshots to help explain your problem.](https://www.kapwing.com/videos/624ec3eee62d030067e2aa06)

## Additional context
Any idea why this bug is happening?

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by ramfattah** [comment]
possibly the same as https://github.com/microsoft/BotFramework-Composer/issues/9113 issue, closing this one.
