### ISSUE TITLE
How to disable user typing text box with Azure bot

### ISSUE THREAD

**Issue by MeenakshiBalekar** [microsoft/botframework-sdk#6506]
I am looking for recommendation on disabling attachment and text box when adaptive card is displayed in webchat/directline channel. I am looking for complete code on webchat side.

I tried the sample :
https://github.com/microsoft/BotFramework-WebChat/blob/main/samples/05.custom-components/l.disable-adaptive-cards/index.html

However ended up getting javascript error

Can anyone share recommendations on how this can be achieved ?
The code behind is composer C#

**Comment by tracyboehrer** [comment]
Assuming this is no longer an issue given the age.  If it is, open an issue in BotFramework-WebChat.
