### ISSUE TITLE
Language Understanding (LUIS) V3 doesn't support Bing Spell Check API

### ISSUE THREAD

**Issue by mountju** [microsoft/botframework-sdk#6513]
## Version
"botbuilder": "~4.15.0",
"botbuilder-ai": "~4.15.0",

## Describe the bug
I try to improve LUIS intents prediction accuracy. Because there is an issue when missing one letter leads LUIS to a wrong intent. I use the [tutorial](https://docs.microsoft.com/en-us/azure/cognitive-services/luis/luis-tutorial-bing-spellcheck), but still I don't get the expected value "alteredQuery" in the JSON returned form LUIS.
this is how I use it:

```
const luisConfig: LuisApplication = {
    applicationId: [APP_ID_GOES_HERE],
    endpointKey: [KEY_GOES_HERE],
    endpoint: [ENDPOINT_GOES_HERE],
};
```

```
const recognizerOptions: LuisRecognizerOptionsV2 = {
    apiVersion: 'v2',
    bingSpellCheckSubscriptionKey: [KEY_GOES_HERE];
    includeAllIntents: true,
    log: true,
    spellCheck: true,
    log: true,
    includeInstanceData: true
};
```
```
const luisRecognizer = new LuisRecognizer(luisConfig, recognizerOptions, true);
```

## Expected behavior
As per documentation I should get the response as follows:
``` 
"query": "bouk me a fliht to kayro",
  "prediction": {
    "alteredQuery": "book me a flight to cairo",
    "topIntent": "book a flight",
    "intents": {
      "book a flight": {
        "score": 0.9480589
      }
      "None": {
        "score": 0.0332136229
      }
    },
    "entities": {}
  }
}
```

## But the reality is different - there is no "alteredQuery"
``` 
"query": "bouk me a fliht to kayro",
  "prediction": {
    "topIntent": "book a flight",
    "intents": {
      "book a flight": {
        "score": 0.9480589
      }
      "None": {
        "score": 0.0332136229
      }
    },
    "entities": {}
  }
}
```

**Comment by anishprasad01** [comment]
Hi @mountju,

The documentation you have linked specifies that the Bing Spell Check key must be passed to LUIS in the *header* of each call. Is that what you are doing?

**Comment by mountju** [comment]
Hi @anishprasad01 !
My request to the LUIS endpoint outside of the bot with the header works well!
But I still need to use it in SDK (botbuilder-ai).
How can I manage adding header to a request which is done by SDK itself?

**Comment by anishprasad01** [comment]
As a workaround, you could try making the request to LUIS using [HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-6.0) from the .NET standard libraries instead of the Bot SDK LUIS objects. HttpClient will allow you to manually add headers. Once you get back a request, you would then parse the JSON for the `alteredQuery`.

**Comment by mountju** [comment]
@anishprasad01  
got your idea, but we use node.js in our project. so as I understand you it's impossible to use Bing Spell Check API through the SDK, and I need to use REST API as it is

**Comment by anishprasad01** [comment]
Not necessarily. I just defaulted to C#, but C# libraries are by no means the only way to interact with LUIS.  You know how you interacted with it outside the bot? Similarly, you can use whatever the counterpart to HttpClient is available in Node.js.

**Comment by mountju** [comment]
@anishprasad01 thank you for your help!
I will use httpClient for js and LUIS REST API

**Comment by mountju** [comment]
but I very disappointed that LUIS SDK doesn't work well at all

**Comment by anishprasad01** [comment]
> but I very disappointed that LUIS SDK doesn't work well at all

As per your initial question, the LUIS endpoint did return the correctly recognized intent and score. While getting the altered query back might not be specifically supported, the LUIS SDK is working as expected.

**Comment by mountju** [comment]
There are special options for the proper work with Bing Spell Check API in SDK (bingSpellCheckSubscriptionKey, spellCheck) but they couldn't be used at all...

**Comment by anishprasad01** [comment]
Feel free to open a ticket with LUIS to see if perhaps they can improve the SDK. In the meantime, since we have identified a workaround, I am going to go ahead and close this issue. Should you run into further issues, feel free to comment and we can reopen it. If you have new problems in the future, please open a ticket in the appropriate repository.
