### ISSUE TITLE
[Feature Request] WebRTC Support

### ISSUE THREAD

**Issue by AdamSobieski** [microsoft/botframework-sdk#6516]
I would like to request support for [WebRTC](https://en.wikipedia.org/wiki/WebRTC) as a multimodal communication channel for the [Bot Framework](https://github.com/microsoft/botframework-sdk). Thank you.

**Comment by LeeParrishMSFT** [comment]
Thanks for your feedback, we can consider this for work into the future. 

@clearab Tagging you here for consideration into future planned work.
