### ISSUE TITLE
Activities Event and Prompts

### ISSUE THREAD

**Issue by PascalHessler** [microsoft/botframework-sdk#6528]
## Version
4.14.1
Python 3.8.3

## Describe the bug
The botframeworks allows us to send different activities (step_context.context.send_activities([])). Here we can for example use the ActivityTypes type of typing or just a normal message. This works fine, I always combine Typing delay and a Message. When I want to use a Prompt this does not work, it allows only for a message as argument for prompt and retrypompt. However, this does not make any sense. The idea of typing is to create the illusion that someone is actually typing, this should be possible when using a prompt. My solution right now is to send the typing in front of the prompt as well as the message, and have an empty argument in the PromptOptions. Unfortunatley, this seems to lead to a new issue with the handling of user inputs, sometimes it just ignores it.

## Expected behavior
I would suggest, set PromptOptions accepts a list of activites not only Messages.

## Additional context
In my specific case I also need to send a custom event when prompting and when retryprompt triggers. This is of course also not possible right now. (I use a workaround with the speak argument)#

Thank you very much.

**Comment by tracyboehrer** [comment]
Have you tried the ShowTypingMiddleware?

**Comment by tracyboehrer** [comment]
This will be coming in the near future through Message Streaming.  Primarily for streaming OpenAI responses, but could be used for any type streaming source.
