### ISSUE TITLE
Accessing Language Studio Orchestrator in Botframework SDK

### ISSUE THREAD

**Issue by rajeeshmenoth** [microsoft/botframework-sdk#6534]
As of now, I don't see any code for accessing azure language studio **Orchestrator** in C# code ( If anything is available please feel to share here otherwise consider this as a feature request ). Currently, Orchestrator is only supported for old LUIS & QnA maker.

The language studio orchestrator has API access but that would be more complex. If the orchestrator recognizer kind of package is available in the bot framework SDK then that would be great.

**Comment by rajeeshmenoth** [comment]
I have identified a few samples for new custom question answering using Orchestrator : 

[https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples)

**Note:** We are searching the package similar to Luisrecognizer, Dispatcher, and Qnamakerrecognizer.

**Comment by tracyboehrer** [comment]
We have no plans to add this Orchestrator to SDK.
