### ISSUE TITLE
JS Bot returns an HTML that does not get parsed

### ISSUE THREAD

**Issue by mys2kor** [microsoft/botframework-sdk#6538]
## Error
When trying to run a bot built with JS (tried with Node & TS).
As soon as the Bot is opened in emulator, I get an error 
`[onTurnError] unhandled error: Error: <HTML>
                                <HEAD>
                                        <TITLE>Network Error</TITLE>
                                        <style media = "all" >....`

## Version
4

## Describe the bug
When trying to run a bot built with JS (tried with Node & TS).
As soon as the Bot is opened in emulator, I get an error.
Errors as shown in the console window of VS Code & in Emulator are shown below.

**I have created bot with c# and they work just fine on the same machine**
This error is shown with multiple examples from this [repository ](https://github.com/microsoft/BotBuilder-Samples)

![grafik](https://user-images.githubusercontent.com/109787441/188130810-62cec4b8-88b2-4308-93b3-c0c5541656a1.png)
![grafik](https://user-images.githubusercontent.com/109787441/188130828-c46d3783-cc39-4375-8fa9-3007e508dd70.png)

## Expected behavior
No error

## Screenshots
Added above

## Additional context
I work behind my company's firewall.

**Comment by anishprasad01** [comment]
Hi @mys2kor,

Which specific samples did you try to run? Did you make sure to supply all correct info and install dependencies with `npm i` before running the bot?

**Comment by mys2kor** [comment]
I have tried running `19.custom-dialogs` & `48.customQABot-all-features`. I also tried to created a bot from scratch as show in this [article](https://www.agrenpoint.com/azurebot-nodejs-part1/). All of them throw the same error.

**Comment by anishprasad01** [comment]
Could you please try one of the simple samples first? Perhaps the [echo bot](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/02.echo-bot)?

Secondly, here is our documentation page for [creating a bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-create-bot?view=azure-bot-service-4.0&tabs=javascript%2Cvs). If the simple samples also don't work, you can give this a try.

Lastly, which Node version do you have installed and what OS are you running?

**Comment by mys2kor** [comment]
I tried the `echo bot` using the code from the repo & as well and the creating it as suggested in the documentation page. 
Still the exact same error.

I have v16.16.0 of Node & Windows 10 Enterprise (19044.1889 OS build)

**Comment by anishprasad01** [comment]
I tried running some of these samples fresh and could not reproduce this issue, also on Windows Enterprise.

I suppose it is possible that your company firewall could be the culprit. Is it possible for you to test installing the dependencies (`npm install`) and running the echo sample (`npm start`) outside of the company network? It's possible that some dependency is unable to be downloaded, and this could be causing issues.

**Comment by mys2kor** [comment]
I did install dependencies with `npm install` and started the echo bot with `npm start`. There is no problem with the start, it starts fine & gives the port number which I have to connect to.

Also, as you can see the screen shots provided, there seems to be connectivity between the bot and the service (the content in the error message on VS code is same as the content shown in the Emulator). Is is possible that something else may be the issue?

One thing that comes to mind it the deprecation warning when the Bot starts. Something about "http_parser". Is the data that is getting exchanged, not parsed properly? Just thinking out loud.

Another colleague of mine tried this & he gets the same error. Since we have to work behind a firewall, the script working in a personal PC does not help. Any help would be appreciated.

**Comment by anishprasad01** [comment]
> Something about "http_parser". Is the data that is getting exchanged, not parsed properly? Just thinking out loud.

I noticed this warning as well. While it will need to be looked into, it does not appear to prevent bots from running.

I too am behind a company firewall and VPN, but I am unable to reproduce your issue.  One other thing I can suggest is to try a `14.x` Node version, perhaps `14.20.0`. If that also doesn't work and the issue is indeed your company firewall, I'm not sure what I can do to help you beyond suggesting that you speak to your IT department.

**Comment by mys2kor** [comment]
Is it possible to use the v16.16.0 of Node and try to run the code once? I ask because, if it works even with v16.16.0 of Node this would rule out Node version as being the reason. In my machine, I have several other applications built on v16.16.0 of Node, hence I do not want to downgrade them (I do know how to use a particular version of node only with this app). Thanks.

**Comment by anishprasad01** [comment]
I tried with `v16.16.0` and was still unable to reproduce. The sample bots ran correctly. It does seem like your firewall may be the culprit.

**Comment by mys2kor** [comment]
ok. Thank you very much for your help.
