### ISSUE TITLE
Unknown Error when Adding MS Teams Channel to Bot

### ISSUE THREAD

**Issue by AFK-Python** [microsoft/botframework-sdk#6540]
## Version
N/A - hit before sdk

## Describe the bug
Trying to update the bot's channel configuration by adding the MS Teams channel to it.

## To Reproduce
1. Create a bot via powershell's `New-AzBotService` command.
2. Run the following command: `az bot msteams create -n {{BotName}} -g {{ResourceGroupName}}`
3. Following error occurs: 
```
Command group 'bot msteams' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
Unknown error during execution. Please file an issue on https://github.com/microsoft/botframework-sdk
```

## Expected behavior
I would expect the MS Teams channel to be added to the bot's channel configuration.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by stevkan** [comment]
@AFK-Python - Did this used to work and suddenly stopped or is this your first time trying to use this?

To be clear, this is a preview feature. As the link in the error suggests, items marked as 'preview' are subject to change. But I will try dig deeper to see if it is supposed to be or not and will let you know what I find.

**Comment by AFK-Python** [comment]
@stevkan Thank you for looking into it! It has not worked for me before - so first time trying to use this feature. However, I did find a similar issue posted in the past [here](https://github.com/microsoft/botframework-sdk/issues/6485). So it seems that it was working at one point.

**Comment by AFK-Python** [comment]
@stevkan hmmm seems to be working now, I'm thinking it had something to do with how I was logging in, but I'm not entirely sure

**Comment by stevkan** [comment]
@AFK-Python - I'm glad it is working for you now. Because of this, I am going to close the issue. If the problem returns, please feel free to re-open the issue. Just keep in mind the 'preview' comment I posted above, if you do so.
