### ISSUE TITLE
Load Test - Power Virtual Agents, with DirectLine

### ISSUE THREAD

**Issue by karinaSC** [microsoft/botframework-sdk#6544]
Hello guys. Can  help me with a question? I'm run tests on a microsoft bot from power apps, the power virtual agents. I would like to run a performance test with JMeter. Can't I use a directLine API?

Thanks

**Comment by tracyboehrer** [comment]
This is quite old.  Apologies.  But for future searchers:  Yes, but it does require something like this: https://github.com/damadei/BotServiceStressToolkit.  There could be others out there though.
