### ISSUE TITLE
It is compatible with .NET 7?

### ISSUE THREAD

**Issue by MrDave1999** [microsoft/botframework-sdk#6551]
Is there any problem if I use bot framework for a project that targets .NET 7?

**Comment by ramfattah** [comment]
Hi @MrDave1999, 

I used botframework sdk 4.18.1 in .NET 7 project and it works as expected.

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.7" />
    <PackageReference Include="Microsoft.Bot.Builder.Dialogs" Version="4.18.1" />
    <PackageReference Include="Microsoft.Bot.Builder.Integration.AspNet.Core" Version="4.18.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
```
![Screenshot 2022-11-14 145138](https://user-images.githubusercontent.com/38049078/201784858-f6d91209-9498-453e-a165-9746611184c6.png)

**Comment by MrDave1999** [comment]
@ramfattah Thanks for taking the time to test. I just did a test with a project using adaptive cards and it worked as expected.

**Comment by ramfattah** [comment]
@MrDave1999, I created few dotnet bot samples using .NET 7 with minimal APIs [here](https://github.com/ramfattah/botbuilder_minimal_api_samples)
