### ISSUE TITLE
Bug in CustomQuestionAnswering.getAnswers method -Botbuilder-ai version 4.15.0

### ISSUE THREAD

**Issue by PuliNath** [microsoft/botframework-sdk#6556]
- **Botbuilder-ai**: 
- **^4.15.0"**: 

**Describe the bug**
the results answers  from  customQuestionAnswering.getanswers do not contain METADATA, instead the array is empty. whereas direct api call via curl provided from language studio ,does produce the result.
**To Reproduce**
1.  use the getAnswers method from CustomquestionAnswering class from botbuilder-ai 4.15

**Expected behavior**
The metadata parameter returned from  language Studio via CustomQuestionAnswering .getanswers , should have metadata values as trained in the language studio custom question answering.

**Screenshots**

**Additional context**
Could this be due to reason that a dictionary is fetched from the actual/normal curl shared in the language studio portal , the exact same dictionary might have errored out , when converting to an array perhaps?  because the result from getanswers method has empty array.
adding a link to the library : https://learn.microsoft.com/en-us/dotnet/api/microsoft.bot.builder.ai.qna.customquestionanswering.getanswersasync?view=botbuilder-dotnet-stable

**Comment by PuliNath** [comment]
The issue is on the sdk languageutils.ts file ,   private formatQnaResult(kbAnswers: KnowledgeBaseAnswers): QnAMakerResults {
        const qnaResultsAnswers = kbAnswers.answers?.map((kbAnswer: KnowledgeBaseAnswer) => {
            const qnaResult: QnAMakerResult = {
                answer: kbAnswer.answer,
                score: kbAnswer.confidenceScore,
                metadata: kbAnswer.metadata
                    **? Array.from(kbAnswer.metadata)?.map((nv) => {
                          return { name: nv[0], value: nv[1] };**
                      })
                    : null,

The highlighted funtion would return  [] for objects ,m could u please , let us know if this would be fixed or is fixed in a new version of botbuilder-ai????

**Comment by anishprasad01** [comment]
Fixed in 4.17.1. Please update your packages.
