### ISSUE TITLE
Refused to display 'https://webchat.botframework.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by Gil0** [microsoft/botframework-sdk#6561]
## Version
SDK runtime packages 4.12.0

## Describe the bug
Hi Team,
We have a chatbot built in Bot Framework Composer and deployed in a website, everything was working perfectly until yesterday when we realized that our chatbot wouldn't load and so we inspected the webpage and found out the following error message in the console:
Refused to display '[https://webchat.botframework.com/'](https://webchat.botframework.com/%27) in a frame because it set 'X-Frame-Options' to 'sameorigin'.
![image](https://user-images.githubusercontent.com/22921868/209411259-bd1043ac-d19f-4906-a5e1-af8a64b9d2ea.png)

## To Reproduce
1) Create a chatbot using bot framework composer and deploy it to azure
2) Deploy the chatbot in a website using the embedded code and the secret key provided by the Web Chat channel.
3) Try to chat with the bot

## Expected behavior
We hope that our Chat Bot will work again within the company's site within an iframe

## Screenshots
![image](https://user-images.githubusercontent.com/22921868/209411520-2ecfdecb-3f53-4f89-9c0c-f6fad75f0478.png)

## Additional context
We have Bot Framework Composer within our company site (ticket.precitool.com) without making any changes, it stopped working and instead of showing the bot it shows that area in gray with the message.
![image](https://user-images.githubusercontent.com/22921868/209413101-383cd930-5f4f-4d0d-be10-2c117763891b.png)

**Comment by YutongTie-MSFT** [comment]
Thread in Q&A for this issue FYI - https://learn.microsoft.com/en-us/answers/questions/1139498/index.html

**Comment by ramfattah** [comment]
This issue may have been resolved by today.

@Gil0, could you please try again and let us know if you are still having this issue. Thanks

**Comment by Gil0** [comment]
Thank you, the problem was solved.
![image](https://user-images.githubusercontent.com/22921868/209997032-506615c9-ff57-4a37-8cb5-6e6fca82d7f1.png)
