### ISSUE TITLE
What Markdown rules is changing multiple exclamation mark to just !!! (three) and other similar behaviors

### ISSUE THREAD

**Issue by alexinuk** [microsoft/botframework-sdk#6564]
## Version
Latest

## Describe the bug
When a message activity, default options, so textFormat should be MD, has a text value that contains more than three of some "special" characters, ! as well as . have been noticed, either Emulator as well as Webchat will change the representation to just three character (such as !!! or ..., even if the message contains hundreds of those chars).

Given that there shouldn't be standard MD behaviors for what I'm seeing, AFAIK, where I can get a list of those modification that are happening?

## To Reproduce
1. Create a simple sample bot
2. Send a message activity back to the user that contains multiple dots or exclamation marks, more than 3 at least
3. Run the bot and receive the new message, either through emulator or webchat
4. Message will be displayed with only three characters, instead of the hundreds sent

## Expected behavior
We were not expecting this behavior as part of standard MD behavior, so we need to understand what are the rules here.

## Screenshots
<N/A>

## Additional context
<N/A>

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by stevkan** [comment]
@alexinuk - This is expected behavior. Web Chat uses the `markdown-it` package for MD support. Looking at their code, it looks like they replace multiple characters with just three of that kind (ref [markdown-it/replacement.js](https://github.com/markdown-it/markdown-it/blob/2b6cac25823af011ff3bc7628bc9b06e483c5a08/lib/rules_core/replacements.js#L54).

**Comment by alexinuk** [comment]
lovelly thank you. Was that referenced anywhere else? We couldn't find a direct connection. Thanks a ton, Alessio

**Comment by stevkan** [comment]
@alexinuk - No, not that I came across, at least. There is a way to pass in a custom markdown engine (ref this [issue](https://github.com/microsoft/BotFramework-WebChat/issues/3363#issuecomment-664543083) on how to do this). So, in theory, you could pass in different parameters or a different engine that better suits your needs.

**Comment by compulim** [comment]
Thanks @stevkan. This is correct.

Markdown-It is doing a lot of weird things outside of their scope by default. 😢

Sometimes, a library passing a standard test suite doesn't mean they are holding that standard.
