### ISSUE TITLE
In a Slack bot framework's bot, buttons are being replaced or deleted with the text 'null (edited)' when clicked. How can I fix this issue?

### ISSUE THREAD

**Issue by kevaldekivadiya2415** [microsoft/botframework-sdk#6566]
I have created a bot using the Microsoft Bot Framework and integrated it with a Slack channel. When I send buttons, such as "yes" or "no" buttons, through the bot in Slack, the button title and button are deleted and replaced with "null (edited)" after they are clicked.

Button title and button should not be deleted or replaced by "null (edited) text". How can i fix the issues? Can you please provide a solution for this issue? Thank you.
###

**Comment by spzm** [comment]
I start getting the same issue appearing for the Slack channel today on all environments. I didn't find a workaround yet - but for us, it's impacting user experience - so will continue digging for a workaround by myself. For now, it's not clear if it is an Azure Bot service or a Slack change. We didn't have any code updates recently. Any feedback on how it can be fixed is highly appreciated. Thank you!

**Comment by dmvtech** [comment]
Hi @kevaldekivadiya2415 How are you creating and sending the buttons? Are you able to share a sanitized copy of the outgoing activity? A bit of sample code might be helpful.

**Comment by dmvtech** [comment]
> How are you creating and sending the buttons? Are you able to share a sanitized copy of the outgoing activity? A bit of sample code might be helpful.

Ah, sorry. Nevermind. I was able to reproduce it. Investigating further.

**Comment by yoagauthier** [comment]
I do have the same issue on production apps, impacting customers. The same bots are also connected to Teams channel, which do not have the issue, it seems to be only on Slack.

I can also add that I do not use the SDK, we directly use the [REST API](https://learn.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference). 

Good luck investing the issue !

**Comment by yoagauthier** [comment]
Hi @dmvtech, any news on the topic or estimated time of resolution ? 

Or since it's impacting customers in production, maybe could you suggest a workaround that we could implement to re-establish previous button behavior ?

**Comment by tygore587** [comment]
Hi @dmvtech we are also having the same problem in our production environment. 

Do you have any updates on the issue or have a workaround for it?

**Comment by saikumaru** [comment]
@dmvtech - do we have an update please; we too have production apps being impacted with this and clients checking regularly on us. Also would you be kind enough to share the ETA for this?

Replication steps would be as simple as
(a) Running sample- https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/06.using-cards
(b) Exposing the ngrok to bot service
(c) Creating slack channel with the scopes as per the documentation.


@kevaldekivadiya2415 , @tygore587 , @yoagauthier , @spzm - hi guys, has anyone tried contacting Slack with this issue please, if so can you tag me too. Have you tried using the community adapter or botkit ?

**Comment by rbormann** [comment]
We had the same issue and created a support request with MS. They pushed a hotfix to the Bot Framework and the problem seems to be resolved now.. I can no longer replicate the problem..

**Comment by yoagauthier** [comment]
Same for us, we talked with support on Azure Bot Services and everything seems to be resolved, no more issue on Slack.
