### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by PabloLION** [microsoft/botframework-sdk#6573]
## Version
Doesn't matter 

## Describe the bug
The website is down because of some typo writing "https://" as "ttps://" 
- e.g: ` ttps://bot-framework.azureedge.net/static/342739-4ecc0e93cf/intercom-webui/v1.6.2/assets/css/fabric.min.css`

## To Reproduce
1. Go to <https://dev.botframework.com/>

## Expected behavior
The website wont open

## Screenshots
![image](https://user-images.githubusercontent.com/36828324/223746280-533331b0-872a-4ada-877c-ee282a2e1341.png)

## Additional context
Not sure where to report it since the webpage won't open.

**Comment by ramfattah** [comment]
Hi @PabloLION 

The website seems to work as of (March 9, 2023) from my end:
![image](https://user-images.githubusercontent.com/38049078/224110647-258259ae-f597-4a36-9879-15b734dc3e1e.png)
![image](https://user-images.githubusercontent.com/38049078/224110673-9c9514a2-2b98-4b97-9bb3-2dfbed3541f1.png)

Are you still experiencing this issue?

**Comment by PabloLION** [comment]
@ramfattah yea it works for me too after disabling the cache
