### ISSUE TITLE
OOTB Health check API

### ISSUE THREAD

**Issue by thinkcodellc** [microsoft/botframework-sdk#6574]
I understand there was a feature for OOTB healthcheck functionality back in 2020 release (https://github.com/microsoft/botframework-sdk/issues/5660)

However it was deprecated? Is there any means for

1. Doing OOTB healthcheck for a bot?
2. Is there any means through API to check if directline channel is up?

I researched and didnt find any relevant updates/ access in StackOverflow, hence reaching out in this channel. Any feedback or pointer on how to healthcheck for directline chat channel would be appreciated. 

Thanks

**Comment by tracyboehrer** [comment]
There are no built in features to enabled this.  One option would be to add a new Controller with a new endpoint that could then do some internal checks.  Though this isn't exactly the same as testing the bot.  Hitting the bot endpoint via Http directly will just give an unauthorized, but to even get that the bot has to be running.
