### ISSUE TITLE
Adaptive cards tel: url markdown not working in iOS edge and chrome

### ISSUE THREAD

**Issue by MdAbidHussain-91** [microsoft/botframework-sdk#6579]
## Version
What package version of the SDK are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
Give a clear and concise description of what you expected to happen.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by dmvtech** [comment]
Hi @MdAbidHussain-91 

- What channel does this reproduce in? Teams? WebChat? Others?
- Can you please share a sample example adaptive card that reproduces the problem?

**Comment by dmvtech** [comment]
Closing due to lack of response.
