### ISSUE TITLE
Passing The Message Directly To Teams Chatbot On Behalf Of User

### ISSUE THREAD

**Issue by amreshgarg21** [microsoft/botframework-sdk#6582]
Is there a way through which we can pass the messages to the team's chatbot on behalf of the user?

I tried using the ms teams deep link:
https://teams.microsoft.com/l/chat/0/0?<bot-id>&message=Hi

But here the user needs to press enter key or send button in order to send the message. 
I want to directly send it without pressing the send button in MS Teams.

**Comment by anishprasad01** [comment]
Hi @amreshgarg21,

It's not entirely clear to me what you are attempting to do. Could you please explain your goal and what bug or feature request you are submitting?

**Comment by amreshgarg21** [comment]
Like I want to pass the message e.x. "Topics" when the user clicks the button, so he/she gets redirected to his/her Teams Chatbot with that message "Topics" and it should be automatically sent on behalf of the user rather than the user pressing the send button or pressing enter button.

Does there exist a way to do so?

**Comment by anishprasad01** [comment]
I'm afraid I'm still unclear on what you're trying to implement. Perhaps you could explain the overall flow of the application, how a user should interact with it, and what the bot should do.

**Comment by anishprasad01** [comment]
You are going to send a message to the bot, and you want to bot to impersonate the user and post that into the channel?

**Comment by amreshgarg21** [comment]
Yes

**Comment by anishprasad01** [comment]
As far as I am aware, bots impersonating human users is not permitted in Microsoft Teams. You can make use of Microsoft Graph to proactively [install and send messages](https://learn.microsoft.com/en-us/microsoftteams/platform/graph-api/proactive-bots-and-messages/graph-proactive-bots-and-messages?context=graph%2Fcontext&tabs=dotnet) to users without needing them to take explicit action, but these messages will come from the bot, not as another user. The message you send can contain the name of the original sender, but the bot cannot appear as that first sender.
