### ISSUE TITLE
Add command button in message box

### ISSUE THREAD

**Issue by Tuan-TIT** [microsoft/botframework-sdk#6589]
![image](https://user-images.githubusercontent.com/22438257/231942416-6f734054-bda0-4dd6-920a-bd8d58831cdc.png)

Hi,

I tried to add command button like image above but It not work
My config

```
 "composeExtensions": [
        {
            "botId": "{{state.fx-resource-bot.botId}}",
            "canUpdateConfiguration": false,
            "commands": [
                {
                    "id": "createCard",
                    "type": "action",
                    "title": "Add Message",
                    "description": "Add new message",
                    "initialRun": false,
                    "fetchTask": true,
                    "context": [
                      "compose",
                      "commandBox",
                      "message"
                    ]
                }
            ]
        }
    ]
```
What is my error? Or Could you give me document for this. Thanks

**Comment by anishprasad01** [comment]
Hi @Tuan-TIT,

You appear to be using TeamsFx features. The samples and support for these features are found on the [Teams samples repo](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/faba14a3b0a3b3da9ede87ca639b986a2f89de54). You might also want to take a look at the [Teams conversation bot](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation) sample and the [Teams suggested actions](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-suggested-actions) sample.

**Comment by Tuan-TIT** [comment]
Hi @anishprasad01,

Yes, I tried to apply [Teams converation bot](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation) in the past. for my research, the "commandList" config just support to send the back message. But my case, I want to use command to open a popup (message extension)

**Comment by Tuan-TIT** [comment]
hello @anishprasad01 , are you received my message?

**Comment by anishprasad01** [comment]
@Tuan-TIT,

You will be able to get more specific help with Teams features on the aforementioned Teams samples repo, or on StackOverflow. We ask that issues opened on this repo concern SDK bugs or feature requests only.
