### ISSUE TITLE
Duplicate Q&A pairs created when updating documents in custom question answering KB

### ISSUE THREAD

**Issue by Naveen-Reddy237** [microsoft/botframework-sdk#6591]
Hi Team,

I'm using a Custom question answering to generate Q&A pairs based on uploaded documents. However, I'm experiencing an issue where when I update the content in the same document and re-upload it. it is creating duplicate Q&A pairs instead of updating the existing ones.

Can you please investigate and help me resolve this issue?

**Comment by dmvtech** [comment]
Hi @Naveen-Reddy237 

Does this happen with the CQA portal only? Or does this only reproduce when in combination with a bot? If the latter; can you give sample code on how this is implemented?

**Comment by Naveen-Reddy237** [comment]
Hi @dmvtech 

I have created custom question answering project in Language Studio(https://language.cognitive.azure.com)  to generate Q&A pairs based on uploaded documents. and have created a azure bot directly form the portal using create bot option after deploying KB.

**Comment by dmvtech** [comment]
Hi @Naveen-Reddy237 

Where are you seeing the duplicate pairs? Is it in the Language Studio edit screen? Does it show in the Edit\test pane of Language Studio? Or does it **_only_** show duplicates when talking to the bot?

If the latter; are you able to give sample KBs of the before/after that we can test with?

**Comment by dmvtech** [comment]
Hi @Naveen-Reddy237 Did you still need assistance with this issue? If so, can you please help answer the questions posed above?
