### ISSUE TITLE
PVA Error : Your Skill Manifest is not compatible.

### ISSUE THREAD

**Issue by amoyalan20** [microsoft/botframework-sdk#6596]
While adding the skill in PVA got the error below.
![image](https://github.com/microsoft/botframework-sdk/assets/73281779/2140a275-6609-4874-b477-e94d6c11c018)
For reference here is the skill manifest that I'm using,

{
  "$schema": "https://schemas.botframework.com/schemas/skills/skill-manifest-2.1.preview-0.json",
  "$id": "Test",
  "name": "Test",
  "description": "Test description",
  "publisherName": "Your Company",
  "version": "1.1",
  "iconUrl": "https://{YOUR_SKILL_URL}/TestSkillDelete.png",
  "copyright": "Copyright (c) Microsoft Corporation. All rights reserved.",
  "license": "",
  "privacyUrl": "https://{YOUR_SKILL_URL}/privacy.html",
  "tags": [
    "sample",
    "skill"
  ],
  "endpoints": [
    {
      "name": "production",
      "protocol": "BotFrameworkV3",
      "description": "Production endpoint for the skill",
      "endpointUrl": "https://{YOUR_SKILL_URL}/api/messages",
      "msAppId": "{YOUR_SKILL_APPID}"
    }
  ],
  "dispatchModels": {
    "languages": {
      "en-us": [
        {
          "id": "TestSkillLuModel-en",
          "name": "TestSkill LU (English)",
          "contentType": "application/lu",
          "url": "file://TestSkill.lu",
          "description": "English language model for the skill"
        }
      ],
      "de-de": [
        {
          "id": "TestSkillLuModel-de",
          "name": "TestSkill LU (German)",
          "contentType": "application/lu",
          "url": "file://TestSkill.lu",
          "description": "German language model for the skill"
        }
      ],
      "es-es": [
        {
          "id": "TestSkillLuModel-es",
          "name": "TestSkill LU (Spanish)",
          "contentType": "application/lu",
          "url": "file://TestSkill.lu",
          "description": "Spanish language model for the skill"
        }
      ],
      "fr-fr": [
        {
          "id": "TestSkillLuModel-fr",
          "name": "TestSkill LU (French)",
          "contentType": "application/lu",
          "url": "file://TestSkill.lu",
          "description": "French language model for the skill"
        }
      ],
      "it-it": [
        {
          "id": "TestSkillLuModel-it",
          "name": "TestSkill LU (Italian)",
          "contentType": "application/lu",
          "url": "file://TestSkill.lu",
          "description": "Italian language model for the skill"
        }
      ],
      "zh-cn": [
        {
          "id": "TestSkillLuModel-zh",
          "name": "TestSkill LU (Chinese)",
          "contentType": "application/lu",
          "url": "file://TestSkill.lu",
          "description": "Chinese language model for the skill"
        }
      ]
    },
    "intents": {
      "Sample": "#/activities/message",
      "*": "#/activities/message"
    }
  },
  "activities": {
    "sampleAction": {
      "description": "Sample action which accepts an input object and returns an object back.",
      "type": "event",
      "name": "SampleAction",
      "value": {
        "$ref": "#/definitions/inputObject"
      },
      "resultValue": {
        "$ref": "#/definitions/responseObject"
      }
    },
    "message": {
      "type": "message",
      "description": "Receives the users utterance and attempts to resolve it using the skill's LU models"
    }
  },
  "definitions": {
    "inputObject": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The users name."
        }
      }
    },
    "responseObject": {
      "type": "object",
      "properties": {
        "customerId": {
          "type": "integer",
          "description": "A customer identifier."
        }
      }
    }
  }
}

Kindly check and let me know if there anything required from my end.

**Comment by amoyalan20** [comment]
is there any update on this feature?

**Comment by tracyboehrer** [comment]
This is more of a question of what PVA requires.  Start with the simple manifest:  https://github.com/microsoft/botframework-sdk/blob/main/schemas/skills/v2.2/samples/simple-skillmanifest.json

Though I believe PCA requires an activity defined.
