### ISSUE TITLE
"Ajaxextended call failed" error - deploying a Ribbon SBC SWe Edge - Quick Launch from the marketiplace

### ISSUE THREAD

**Issue by rjvicent** [microsoft/botframework-sdk#6599]
Hi all,
I am trying to deploy a Ribbon SBC in a trial tenant and I get the error below.
<img width="635" alt="image" src="https://github.com/microsoft/botframework-sdk/assets/135456512/49347b1d-6574-4808-82a2-0334c4d34aa2">

I get this error only if I use a new subscription. If I use a subscription that I created time ago, it works.

Appreciate help.

Regards,

Rafa

**Comment by anishprasad01** [comment]
Hi @rjvicent,

This issue is unrelated to the Bot Framework SDK. Please contact Azure Support for assistance.
