### ISSUE TITLE
Rendering AdaptiveCards 'FactSet' element

### ISSUE THREAD

**Issue by IAmDenysSamoilenko** [microsoft/botframework-sdk#6603]
## Describe the bug
During posting a message with AdaptiveCard in MicrosoftTeams (using my bot), FactSet element is rendering as a table with visible borders.
If I'll post the same AdaptiveCard using Power Automate - everything will be fine.

## To Reproduce
1. Post an AdaptiveCard to [smba.trafficmanager.net/emea/v3/conversations](url)
Adaptive card JSON:
```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.0",
    "body":
    [
        {
            "type": "FactSet",
            "separator": true,
            "facts":
            [
                {
                    "title": "Site:",
                    "value": "New York (Demo)"
                },
                {
                    "title": "Start Date:",
                    "value": "03/03/2015 ( 8 years, 4 months and 11 days )"
                }
            ]
        }
    ]
}
```

3. Take a look on result: borders are present

## Expected behavior
FactSet element renders without borders

## Screenshots
Actual: 
![image](https://github.com/microsoft/botframework-sdk/assets/97089976/2966ec4e-4440-420c-98d6-d64adab42324)

Expected :
![image](https://github.com/microsoft/botframework-sdk/assets/97089976/120e4c0b-c68a-4094-8924-1bb9c3d661a8)

**Comment by ramfattah** [comment]
Hi @IAmDenysSamoilenko, I'm looking into this.

**Comment by IAmDenysSamoilenko** [comment]
@ramfattah hi, any updates about this?

**Comment by ramfattah** [comment]
Hi @IAmDenysSamoilenko, 

I'm not able to reproduce this issue using sample [07.using-adaptive-cards](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/07.using-adaptive-cards). 
The 'FactSet' Adaptive card displayed the table without borders in Teams Channel.

![image](https://github.com/microsoft/botframework-sdk/assets/38049078/21c4f8e0-68ee-43db-aa80-81a99ae16222)

**Comment by IAmDenysSamoilenko** [comment]
Hi @ramfattah , 
Same for me now. Found that it was not reproducible around 1 week ago.
probably can close a ticket
