### ISSUE TITLE
Redirect the message Directly To Teams Chatbot On Behalf Of User

### ISSUE THREAD

**Issue by lakshmijaykumar** [microsoft/botframework-sdk#6607]
Is there a way through which we can redirect the messages to the team's chatbot on behalf of the user using DeepLink Url?

I tried using the MS Teams deep link:
https://teams.microsoft.com/l/chat/0/0?&message=Hi, this is a predefined message from hyperlink.

But here the user needs to press enter key or send button in order to send the message.
I want to directly send it without pressing the send button in MS Teams.
<img width="683" alt="image" src="https://github.com/microsoft/botframework-sdk/assets/37400488/383ba00a-31b8-4a72-8410-e716c00667b9">

- If a user has previously directed certain messages to the chat placeholder, any subsequent redirections will occur without overwriting the existing text within the placeholder for the same user. User session can be refreshed or closed after the user clicks on that particular URL and chats with Chatbot <so that if they user re-clicks on that link, the deep link works>> 
Can we do any workaround for this as well?

**Comment by dmvtech** [comment]
If these can be done, it would be from the Teams side of things. Nothing in the Bot Framework specifically. Please pursue this with Teams.
