### ISSUE TITLE
UserAssignedMSI + AzureADMyOrg + Teams = Seamless SSO does not work.

### ISSUE THREAD

**Issue by stas-sultanov** [microsoft/botframework-sdk#6611]
## Version
Version="4.21.0"

## Describe the bug
We create a Teams Chat Bot for internal use in our organization.
In EntraID Application Registration we specify "SignInAudience": "AzureADMyOrg".
We use User Assigned Managed Service identity for Azure Bot Service.
In bot application we specify "MicrosoftAppType": "UserAssignedMSI".

In this configuration seamless SSO does not work.
During SingIn Teams shows us a Sign-In card instead of consent. 
We are able to sign-in and bot works.
This happens because in Azure Bot Service Connection AADv2 Token Exchange Url we specify nothing.
And bot application sends OAuthCard with empty TokenExchangeResource.

If only we specify Token Exchange Url  in Azure Bot Service Connection AADv2 we see it in 
OAuthCard.TokenExchangeResource.
With such configuration bot service stop respond.

There are a lot of documents saying that Azure Bot Service Connection AADv2 Token Exchange Url should be blank but this value is need by Teams to Exchange Token.

**Comment by ramfattah** [comment]
Thanks @stas-sultanov, i'm looking into this.

**Comment by ramfattah** [comment]
Hi @stas-sultanov, 

Are you following a specific documentation to implement SSO for user assigned managed identity? if yes, could you please share that documentation link? 



Typically in the past, when I implemented SSO for `MultiTenant` app type, the Token Exchange URL is indeed required. 
https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-conversation-sso-quickstart/BotSSOSetup.md#3-setup-bot-service-connection-tokenstore:~:text=For%20the%20Token%20Exchange%20URL%20use%20the%20Application%20ID%20URL%20obtained%20in%20step%201.3

![image](https://github.com/microsoft/botframework-sdk/assets/38049078/e8439107-a155-451e-999e-df84f09ad973)

**Comment by ramfattah** [comment]
@stas-sultanov, I can try to setup an SSO bot with user assigned managed identity to see if I can reproduce this issue. 

Will report back soon. Thanks.

**Comment by stas-sultanov** [comment]
hi @ramfattah, thank you for your time.

1. we can not move to production because we are facing issue on DEVelopment.
1. we do not follow one documentation, because there is no such documentation that explains how to setup a Teams Bot with following combined
    - Single Tenant App Registration in EntraID 
    - Managed Service Identity for Azure Bot Service
    - SSO

There are documentations about how to use Managed Service Identity for Azure Bot Service, like this [one](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned) but nothing about Teams Single Tenant App with SSO

There are documents like the one you have mentioned, but they about Teams with SSO that uses Multitenant App Registration in EntraID and no Managed Service Identity for Azure Bot Service.

**Comment by ramfattah** [comment]
Hi @stas-sultanov, 

Could you please provide detailed [steps to reproduce](https://github.com/microsoft/botframework-sdk/blob/main/.github/ISSUE_TEMPLATE/bot-framework-bug.md#to-reproduce) the issue? 

Specifically, how you created the app registration, information provided to OAuth identity service provider and when interacting with the bot. 

Thanks.

**Comment by stas-sultanov** [comment]
Hi @ramfattah

**Part 1**
we utilize Azure DevOps pipeline to automatically create EntraID App Registration with help of Powershell MS Graph
here is a sample of app registration manifest (default values are omitted)

```json
{
	"id": "00e2f4d3-2a80-45bb-aa98-050d4ffc0a78",
	"accessTokenAcceptedVersion": 2,
	"appId": "a3a48dab-2a79-4d7b-8fce-c3f3edff48eb",
	"identifierUris":
	[
		"api://botid-a3a48dab-2a79-4d7b-8fce-c3f3edff48eb"
	],
	"logoUrl": "https://aadcdn.msftauthimages.net/dbd5a2dd-h-ro5xuegiat811opxooiwyhcwh0b83pmg8yfaqt9k8/appbranding/cefcikyf71dpps9aywiuwn-4tkl4dcdayfj3wrqxhyu/1033/bannerlogo?ts=638319098827166154",
	"logoutUrl": null,
	"name": "teams-dev",
	"notes": "Please contact owners for any questions.",
	"oauth2AllowIdTokenImplicitFlow": true,
	"oauth2AllowImplicitFlow": true,
	"oauth2Permissions":
	[
		{
			"adminConsentDescription": "Allow application to interact with other systems on behalf of the current user.",
			"adminConsentDisplayName": "Access as user.",
			"id": "a27ced89-6d4a-43bb-8b6e-cc382cf093cb",
			"isEnabled": true,
			"lang": null,
			"origin": "Application",
			"type": "User",
			"userConsentDescription": "Allow application to interact with other systems on behalf of you.",
			"userConsentDisplayName": "Allow application to act on your behalf.",
			"value": "access_as_user"
		}
	],
	"optionalClaims":
	{
		"idToken": [],
		"accessToken":
		[
			{
				"name": "upn",
				"source": null,
				"essential": false,
				"additionalProperties": []
			},
			{
				"name": "idtyp",
				"source": null,
				"essential": false,
				"additionalProperties": []
			}
		],
		"saml2Token": []
	},
	"passwordCredentials":
	[
		{
			"keyId": "d1a1d26a-4d7a-489a-af88-91338d7cc2cc",
			"displayName": "default"
		}
	],
	"preAuthorizedApplications":
	[
		{
			"appId": "5e3ce6c0-2b1f-4285-8d4b-75ee78787346",
			"permissionIds":
			[
				"a27ced89-6d4a-43bb-8b6e-cc382cf093cb"
			]
		},
		{
			"appId": "1fec8e78-bce4-4aaf-ab1b-5451cc387264",
			"permissionIds":
			[
				"a27ced89-6d4a-43bb-8b6e-cc382cf093cb"
			]
		}
	],
	"publisherDomain": "gostas.dev",
	"replyUrlsWithType":
	[
		{
			"url": "https://token.botframework.com/.auth/web/redirect",
			"type": "Web"
		}
	],
	"requiredResourceAccess":
	[
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess":
			[
				{
					"id": "14dad69e-099b-42c9-810b-d002981feec1",
					"type": "Scope"
				},
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				},
				{
					"id": "df021288-bdef-4463-88db-98f22de89214",
					"type": "Role"
				},
				{
					"id": "908de74d-f8b2-4d6b-a9ed-2a17b3b78179",
					"type": "Role"
				}
			]
		}
	],
	"signInAudience": "AzureADMyOrg"
}
```

**Comment by stas-sultanov** [comment]
@ramfattah 

**Part 3**
we utilize Azure Bicep and ARM templates to provision Azure Bot Service Connection
here is a sample of azure bot service connection arm template (default values are omitted)

Please note:
1. We explicitly specify EntraID **tenantId**, because we build Single Tenant solution
2. We specify **tokenExchangeUrl**, because it is needed by Teams to exchange token and make Seamless SSO

```json

{
  "name": "stas-teams-dev-t1/default",
  "type": "Microsoft.BotService/botServices/connections",
  "location": "global",
  "properties":
  {
    "clientId": "a3a48dab-2a79-4d7b-8fce-c3f3edff48eb",
    "clientSecret": null,
    "scopes": "api://botid-a3a48dab-2a79-4d7b-8fce-c3f3edff48eb/access_as_user",
    "serviceProviderId": "30dd229c-58e3-4a48-bdfd-91ec48eb906c",
    "serviceProviderDisplayName": "Azure Active Directory v2",
    "parameters":
    [
      {
        "key": "tokenExchangeUrl",
        "value": "api://botid-a3a48dab-2a79-4d7b-8fce-c3f3edff48eb"
      },
      {
        "key": "tenantId",
        "value": "a2096e5a-09e7-4fe4-bdf2-57fa785b8ede"
      },
      {
        "key": "clientId",
        "value": "a3a48dab-2a79-4d7b-8fce-c3f3edff48eb"
      },
      {
        "key": "clientSecret",
        "value": null
      },
      {
        "key": "scopes",
        "value": "api://botid-a3a48dab-2a79-4d7b-8fce-c3f3edff48eb/access_as_user"
      }
    ]
  }
}

```

**Comment by stas-sultanov** [comment]
@ramfattah

Part 4
we utilize Azure DevOps pipeline to automatically create Microsoft Teams Application Package.
here is a sample of Teams Application manifest. (default values are omitted)

```json
{
	"$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
	"bots":
	[
		{
			"botId": "e92dc380-6e3f-4337-8d05-03941d7012ac",
			"scopes":
			[
				"personal"
			]
		}
	],
	"developer":
	{
		"name": "Stas Sultanov",
	},
	"devicePermissions":
	[
		"openExternal",
		"notifications"
	],
	"id": "73f171ce-ba1d-42fa-9e02-0ea1149be8f4",
	"manifestVersion": "1.16",
	"name":
	{
		"short": "teams-dev-t1",
		"full": "Belle"
	},
	"packageName": "t1.dev.teams.gostas.dev",
	"validDomains":
	[
		"stas-teams-dev-t1.azurewebsites.net",
		"token.botframework.com"
	],
	"version": "1.1.0",
	"webApplicationInfo":
	{
		"id": "a3a48dab-2a79-4d7b-8fce-c3f3edff48eb",
		"resource": "api://botid-a3a48dab-2a79-4d7b-8fce-c3f3edff48eb"
	}
}
```

**Comment by ramfattah** [comment]
Thanks for the detail info @stas-sultanov. I'm attempting to reproduce this issue. 

Will report back soon.

**Comment by ramfattah** [comment]
Hi @stas-sultanov, 

I've been reviewing the following [documentation](https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp#:~:text=Support%20for%20the%20user%2Dassigned%20managed%20identity%20and%20single%2Dtenant%20app%20types%20was%20added%20to%20the%20Bot%20Framework%20SDK%20for%20C%23%20and%20JavaScript%20in%20version%204.15.0.%20These%20app%20types%20aren%27t%20supported%20in%20the%20other%20languages%20or%20in%20Bot%20Framework%20Composer%2C%20Bot%20Framework%20Emulator%2C%20or%20ngrok.) and noticed an important detail regarding ngrok. 
> The Bot Framework SDK introduced support for user-assigned managed identity and single-tenant app types in version 4.15.0 for C# and JavaScript. However, these types aren't supported in other languages or in Bot Framework Composer, Emulator, or tunneling solutions like **ngrok**.

Given this, I wanted to check: during your development and testing phase in the Teams channel, are you using a tunneling solution like ngrok? If so, I wonder if this could be the root cause of the issue?

**Comment by stas-sultanov** [comment]
Hi @ramfattah ,
thank you for information.

We do not use ngrok or any other tunnelling service.

With help of Azure DevOps pipeline, we do the following:
1. Provision App Registration for DEV environments.
2. Provision dedicated DEV environment in Azure, using app Registration from step 1.
3. Create Teams app.zip (manifest + icons), using app Registration from step 1 and Azure resources from step 2.
4. Deploy .net application to DEV environment, using Azure resources from step 2.
5. Install Teams app.zip to Teams application.
6. Test

As I've mentioned earlier everything works, except Seamless SSO in Teams.

**Comment by ramfattah** [comment]
> If only we specify Token Exchange Url in Azure Bot Service Connection AADv2 we see it in
OAuthCard.TokenExchangeResource.
With such configuration bot service stop respond.

Do you get any errors when specifying the token exchange url?

**Comment by dmvtech** [comment]
Closing due to lack of response. Please comment with answers and we can reopen if you need further assistance.

**Comment by stas-sultanov** [comment]
@InfinytRam ,  can not see any error, looks like it is not exposed.

@dmvtech , please reopen as the issue still present.

**Comment by cuixi1222** [comment]
hi @stas-sultanov, were you able to resolve the issue? Our team’s project is also blocked by this, so any update or final fix would be greatly appreciated.

**Comment by stas-sultanov** [comment]
@cuixi1222 , nop :(
the issue is closed, MS does not care.
