### ISSUE TITLE
[Feature Request] Adding support to open-source LLMs and RAG

### ISSUE THREAD

**Issue by mahimairaja** [microsoft/botframework-sdk#6613]
Hi, I believe adding support to connect with `open source LLMs` like LLaMA 2 and performing `Retrieval Augmented Generation` (RAG) and connecting it with bot framework would be essentially helpful in building a better solution...

**Comment by tracyboehrer** [comment]
Though we don't have direct support for LLM's, or samples around it, there is nothing stopping their use from within a bot.  In this case, the bot is just the channel between the user and LLM.  Some things, like Storage, is helpful in this case to preserve chat history.

It may not always be the case we don't have further guidance around this.
