### ISSUE TITLE
Sending intro message before the user starts the conversation on the Team?

### ISSUE THREAD

**Issue by ShaliniRD100** [microsoft/botframework-sdk#6615]
How to Send intro message before the user starts the conversation on the Team? I added a code in OnMembersAddedAsync this is working on Bot framework emulator but when deploy the package and open in Teams channel. This message is not sent to the user

**Comment by dmvtech** [comment]
Is this a brand new bot for Teams? Is this with 1:1 conversation or part of a group/Teams Channel?

For Teams (bot) channel, the welcome message only (ever) get's sent once. In other words; the `OnMembersAddedAsync` method only ever gets called once. If you have another user (not part of a Teams Channel that already contains the bot) that can talk to the bot, they should get the welcome/OnMembersAddedAsync. If not, there is some problem.

**Comment by dmvtech** [comment]
Closing due to lack of response.
