### ISSUE TITLE
Consider updating namespaces from Task* to the concept of a modal dialog at the appropriate time

### ISSUE THREAD

**Issue by sbtron** [microsoft/botframework-sdk#6619]
## Issue

Teamsjs v2 has updated some of the terminology and API namespaces for what used to be called tasks to dialog to better match the concept of modal dialogs in UI - 
https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/dialog?view=msteams-client-js-latest 

Since these libraries could be used together it could lead to developer confusion around these two naming conventions being used to refer to the same concept. This can be explained via documentation in the short-term but longer term please consider updating the namespaces to provide a more coherent experience.  

## Proposed change

Don't have a specific term in mind just identifying that there is a change happening in other libraries and it might be worth considering aligning with the update when appropriate. 

## Component Impact 

Any BotFramework Teams specific namespaces that are using the Task* naming pattern to refer to modal dialog UI

## Customer Impact 

Easier to match and understand the concept when using both teamsjs and bot framework together. 

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by tracyboehrer** [comment]
Thanks for the input.  However, we can't easily or arbitrarily change names of anything without impacting a huge number of projects and customers that take a dependency on Bot Framework SDK.  We also can't control what names they use, if we are even aware of them.
