### ISSUE TITLE
Play Continuous Video Stream on the Bot

### ISSUE THREAD

**Issue by ayushhhCSharp** [microsoft/botframework-sdk#6627]
Hi, 
I am trying to play continuous video stream on the bot from Azure AI Avatar by connecting to the browser, using adaptive cards, but there is no support for the same. 
Can anyone guide me on if the same is on the roadmap, or any alternate ways to do the same?
Any help would be appreciated.
Thank You.

**Comment by tracyboehrer** [comment]
There is nothing on the roadmap for this in SDK.
