### ISSUE TITLE
SendAdaptiveCards does not work with generic objects

### ISSUE THREAD

**Issue by MichaMican** [microsoft/botframework-sdk#6629]
## Version
4.18.1

## Describe the bug
When calling the `SendAdaptiveCard()` function of a `TeamsBotInstallation` with a generic object of type `object` the internal serialization does not wokr properly and a empty adaptive card is send (see Screenshots)

## To Reproduce
1. Create a Notification bot (with toolkit).
2. Replace the notification PostAsync controller code with the following: 
```cs
[HttpPost]
public async Task<ActionResult> PostAsync([FromBody] object body, CancellationToken cancellationToken = default)
{
    var pageSize = 100;
    string continuationToken = null;
    do
    {
        var pagedInstallations = await _conversation.Notification.GetPagedInstallationsAsync(pageSize, continuationToken, cancellationToken);
        continuationToken = pagedInstallations.ContinuationToken;
        var installations = pagedInstallations.Data;
        var usersInstallation = pagedInstallations.Data.Where((i) => (i.ConversationReference.Conversation.TenantId == incidentHandlerRequest.TenantId && i.ConversationReference.User.AadObjectId == incidentHandlerRequest.AadUserId));

        foreach (var installation in usersInstallation)
        {
            var response = await installation.SendAdaptiveCard(body, cancellationToken);
        }
    } while (!string.IsNullOrEmpty(continuationToken));

    return Ok();
}
```
3. Send a valid adaptive card to that endpoint (e.g. via Postman)
4. See empty adaptive card in the chat

## Expected behavior
The adaptivecard that was send to the endpoint should be send properly

## Screenshots
![image](https://github.com/microsoft/botframework-sdk/assets/45571948/3de2eb20-af3e-4f25-95ee-16df21753158)

## Additional context
I worked arround the issue in a very weird way.
I basically converted the object to something that Newtonsoft.Json can deserialize properly
```cs
var jsonSerializerOptions = new System.Text.Json.JsonSerializerOptions(System.Text.Json.JsonSerializerDefaults.Web);
serializedAdaptiveCard = System.Text.Json.JsonSerializer.Serialize(body, jsonSerializerOptions); // System text json can serialize generic objects properly
```
then i Deserialize the serializedAdaptiveCard with Newtonsoft JSON
```cs
var response = await installation.SendAdaptiveCard(JsonConvert.DeserializeObject(serializedAdaptiveCard), cancellationToken);
```
This is an unbelievably dirty workarround. I am not sure if Newtonsoft.Json can be configured to serialize object properly but swapping to System.Text.Json should fix te issue

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by rampaged** [comment]
[SendAdaptiveCard()](https://github.com/OfficeDev/TeamsFx/blob/cfa4f4721d68569ef1bdf6df643ace794336f9ad/packages/dotnet-sdk/src/TeamsFx/Conversation/Channel.cs#L72-L105) isn't part of the Bot Framework SDK. It's tied to the Teams Toolkit and [TeamsFx](https://github.com/OfficeDev/TeamsFx/) repo. 

You might want to drop an issue over there. The TeamsFx folks should sort you out.

Let me know if you have any question. 
Thanks.

**Comment by MichaMican** [comment]
Thanks for the clarification!

**Comment by MichaMican** [comment]
I have created a [issue on TeamsFx side](https://github.com/OfficeDev/TeamsFx/issues/10689) - Therefor i close this for now :)
