### ISSUE TITLE
Token Service doesn't refresh the user token

### ISSUE THREAD

**Issue by atmoraes1** [microsoft/botframework-sdk#6634]
The documentation states the Token Service handles user tokens, but it is not refreshing the token even though Azure Portal requires you to enter the refresh URL details.

**Comment by tracyboehrer** [comment]
@atmoraes1 What documentation are you referring to?

**Comment by atmoraes1** [comment]
One of them is this: [](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-authentication?view=azure-bot-service-4.0). It states you don't need to manage tokens as the Token Service does that for you. But when the token expires, it is not refreshed.

**Comment by stevkan** [comment]
@atmoraes1 - Can you provide a link to the doc(s) you are referring to?
