### ISSUE TITLE
Neither `tid` nor `tenantId` claim is present in the token

### ISSUE THREAD

**Issue by pm7y** [microsoft/botframework-sdk#6644]
## Version
4.22.2

## Describe the bug
Whenever the C# bot app service receives a message (via /api/messages), the following exception is logged in app insights:
_IDX40003: Neither `tid` nor `tenantId` claim is present in the token obtained from Microsoft identity platform._

## To Reproduce
We have a multitenant Azure bot with a teams channel. When a message is sent to the bot C# app service via the Teams channel the bot successfully receives and processes the message and replies to the sender as expected. However, there is an error message (above) logged in app insights, indicating there is a problem.

## Expected behavior
The tenant id shouldn't matter for a multitenant bot, right? How can I resolve this exception?

## Screenshots
![image](https://github.com/microsoft/botframework-sdk/assets/3075792/458ae900-0f43-4fde-8dda-5143f555496d)

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by tracyboehrer** [comment]
The token from Azure Bot Service does not contain either of these claims.  It never has.  But more recently this gets flagged.  There is nothing the bot side can do about this though.  I am curious about where this is happening from though.  Is this from App Insights on the bot itself?  Because the SDK perform token validation on its own, and doesn't rely on AspNet.Core validation.

**Comment by dmvtech** [comment]
Closing due to lack of response. If assistance is still needed, please comment with pertinent information and we will continue.

**Comment by tracyboehrer** [comment]
As a final comment... this will likely change in the not too distant future.

**Comment by cloudsere** [comment]
@tracyboehrer  Hi, kindly check whether things have been changed :)

**Comment by tracyboehrer** [comment]
@cloudsere Things have not changed in this regard yet.  This is something on the radar, but I don't have insight to the timeline yet.
