### ISSUE TITLE
Ngrok Executable Flagged as Potentially Unwanted Software by Microsoft Defender

### ISSUE THREAD

**Issue by deena211** [microsoft/botframework-sdk#6654]
We encountered an issue where the Ngrok executable, which is used for connecting the parent bot to the child bot, was flagged and quarantined as potentially unwanted software by Microsoft Defender. This software is mentioned as tunneling software to connect the bot locally in the [Microsoft Bot Framework documentation](https://learn.microsoft.com/en-us/azure/bot-service/bot-service-debug-channel-ngrok?view=azure-bot-service-4.0).

Ngrok was used by us for a very long time and was working fine. And it suddenly started getting blocked by Windows Defender.

The error message in Windows Defender is "Defender detected and quarantined active 'PUA
/Ngrok!MTB' in file 'ngrok.exe' during a scheduled scan."

We request the Bot Framework SDK team to review the documentation and potentially update the guidance regarding the use of Ngrok or suggest any other alternate software, ensuring it is not flagged by security systems like Microsoft Defender. Any additional steps to whitelist or properly configure the use of Ngrok in the development environment would be highly appreciated.

**Comment by Maurizioxx** [comment]
i have this issue, windows defender: PUA:Win32/Packunwan

**Comment by ZarmDev** [comment]
I have the exact same problem as Maurizioxx! I'm glad I found someone else with this issue

**Comment by rmill2016** [comment]
Also running into this issue as well starting a new RN Ignite Boilerplate `npx ignite-cli@latest new xyz`

**Comment by tracyboehrer** [comment]
NGrok is being removed from Emulator.  We will also remove instructions for it's use from Samples and docs.  Use devtunnels instead.  https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows
