### ISSUE TITLE
BotFramework-Services/issues/363 duplicate Slack Ephemeral result in error

### ISSUE THREAD

**Issue by geo-msft** [microsoft/botframework-sdk#6657]
## Version
What package version of the SDK are you using.
See here BotFramework-Services/issues/363 

## Describe the bug
This issue needs attention
https://github.com/microsoft/BotFramework-Services/issues/363 

## To Reproduce
See here https://github.com/microsoft/BotFramework-Services/issues/363 

## Expected behavior
See here https://github.com/microsoft/BotFramework-Services/issues/363 

## Screenshots
See here https://github.com/microsoft/BotFramework-Services/issues/363 

## Additional context
The customer raised an internal support ticket. 
See here https://github.com/microsoft/BotFramework-Services/issues/363 

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by stevkan** [comment]
@geo-msft - Thank you for bringing this to our attention. We will work on getting the Services issue you linked in front of someone on that team so you can get a proper response. Closing this dupe, in the mean time.
