### ISSUE TITLE
Teams high CPU usage

### ISSUE THREAD

**Issue by tiffanyp8** [microsoft/botframework-sdk#6662]
## Version
What package version of the SDK are you using.
8.0

## Describe the bug
Give a clear and concise description of what the bug is.
Bot is crashing on initial message when users try to start teams. Only some users face this issue.

## Expected behavior
Give a clear and concise description of what you expected to happen.
The bot should send an initial welcome message, but instead it crashes teams on high CPU usage.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by dmvtech** [comment]
Is it just Teams crashing, the bot, or both?

**Comment by tiffanyp8** [comment]
Teams crashes when a user tries to open the bot and chat with it. So the entirety of teams but azure doesn't show specific logs related to the crash. Teams crashes with high CPU usage.

**Comment by jorgeajimenezl** [comment]
@tiffanyp8 Were you able to solve this problem or do you still have it? In case you were able to solve it, can you explain me how to do it?

**Comment by dmvtech** [comment]
This is a Teams issue. If the bot is somehow doing something incorrectly, it shouldn't be crashing Teams. Please seek assistance with the Teams product.
