### ISSUE TITLE
Keyboard controls don't work properly with a screen reader

### ISSUE THREAD

**Issue by rjayapra** [microsoft/botframework-sdk#6665]
## Version
What package version of the SDK are you using.
4.13.0

## Describe the bug
Give a clear and concise description of what the bug is.

Keyboard controls don't work properly with a screen reader as instructed by the chatbot widget help page. This widget help page is part of the Microsoft Webchat library.

## Expected behavior
Expected to work as per the help widget, but does not.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by tracyboehrer** [comment]
This wouldn't be an SDK issue.  WebChat perhaps?
