### ISSUE TITLE
Slack Channel Interactivity button not working

### ISSUE THREAD

**Issue by tyler3497** [microsoft/botframework-sdk#6668]
## Version
Node.js SDK v4

## Describe the bug
When sending an interactive button to the user from the bot in Slack, the button is rendered and shown to the user correctly.  When the user clicks the button, an error occurs, and nothing is ever received on the app side.  The error "chat.attachmentAction not ok: dispatch_failed" shows up in the console when using the web client.  

## To Reproduce
Send button to user in a hero card or slack's Block format
User clicks button
Error occurs

## Expected behavior
The button click event should be sent to the app to be handled.

## Additional context
Followed guide from here to setup: https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channel-connect-slack?view=azure-bot-service-4.0

Looks similar to this issue, but following their fix doesn't work: https://github.com/microsoft/BotFramework-Services/issues/327

Working with Slack support, they have said that everything looks good from their end, and it has to be an issue with the framework or the channel in Azure.  They believe it to be a problem with the request URL not working properly.  This is different to what is being said about the error here: https://github.com/microsoft/botframework-sdk/issues/6065 

When setting the Request Url in the Interactivity & Shortcuts section for the slack app to another address where I can see the requests, instead of the "https://slack.botframework.com/api/Actions" URL, I can see the button payload being sent properly. 

Other notes:
Bot otherwise works correctly in slack, with normal message replies.  Bot is also working fully in Teams and the Web Chat.

**Comment by stevkan** [comment]
Related to https://github.com/microsoft/BotBuilder-Samples/issues/3971
