### ISSUE TITLE
VXIS issue

### ISSUE THREAD

**Issue by gordingin** [microsoft/botframework-sdk#6677]
I downloaded the VXIS from the marketplace and I have VS 2022 installed but it says that it failed to find any valid product. So I can't install it.

11/23/2024 3:26:30 PM - Microsoft VSIX Installer
11/23/2024 3:26:30 PM - -------------------------------------------
11/23/2024 3:26:30 PM - vsixinstaller.exe version:
11/23/2024 3:26:30 PM - 17.12.2069+1ec5133e4b
11/23/2024 3:26:30 PM - -------------------------------------------
11/23/2024 3:26:30 PM - Command line parameters:
11/23/2024 3:26:30 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Mac\Home\Downloads\BotBuilderVSIXV4.vsix
11/23/2024 3:26:30 PM - -------------------------------------------
11/23/2024 3:26:30 PM - Microsoft VSIX Installer
11/23/2024 3:26:30 PM - -------------------------------------------
11/23/2024 3:26:31 PM - Initializing Install...
11/23/2024 3:26:31 PM - Searching for applicable products...
11/23/2024 3:26:32 PM - Found installed product - Visual Studio Community 2022
11/23/2024 3:26:32 PM - Found installed product - Global Location
11/23/2024 3:26:32 PM - Extension Details...
11/23/2024 3:26:32 PM - 	Identifier         : BotBuilderV4.fbe0fc50-a6f1-4500-82a2-189314b7bea2
11/23/2024 3:26:32 PM - 	Name               : Bot Framework v4 SDK Templates for Visual Studio
11/23/2024 3:26:32 PM - 	Author             : Microsoft
11/23/2024 3:26:32 PM - 	Version            : 4.22.0
11/23/2024 3:26:32 PM - 	Description        : Templates for Microsoft Bot Framework v4. Will let you quickly create a bot that uses core AI capabilities.
11/23/2024 3:26:32 PM - 	Locale             : en-US
11/23/2024 3:26:32 PM - 	MoreInfoURL        : https://aka.ms/BotBuilderOverview
11/23/2024 3:26:32 PM - 	InstalledByMSI     : False
11/23/2024 3:26:32 PM - 	SupportedFrameworkVersionRange : [4.5,)
11/23/2024 3:26:32 PM - 	SignatureState     : ValidSignature
11/23/2024 3:26:32 PM - 	SignedBy           : Microsoft Corporation
11/23/2024 3:26:32 PM - 	Certificate Info   : 
11/23/2024 3:26:32 PM - 		-------------------------------------------------------
11/23/2024 3:26:32 PM - 		[Subject]       : CN=Microsoft Corporation, OU=OPC, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
11/23/2024 3:26:32 PM - 		[Issuer]        : CN=Microsoft Code Signing PCA 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
11/23/2024 3:26:32 PM - 		[Serial Number] : 3300000523BAE6749DE1A95064000000000523
11/23/2024 3:26:32 PM - 		[Not Before]    : 4/6/2023 1:28:17 PM
11/23/2024 3:26:32 PM - 		[Not After]     : 4/2/2024 1:28:17 PM
11/23/2024 3:26:32 PM - 		[Thumbprint]    : 9D46CB329871C30878E1C52FA73164474DBD5D29
11/23/2024 3:26:32 PM - 	Supported Products : 
11/23/2024 3:26:32 PM - 		Microsoft.VisualStudio.Community
11/23/2024 3:26:32 PM - 			Version : [15.0,17.0)
11/23/2024 3:26:32 PM - 			ProductArchitecture : x86
11/23/2024 3:26:32 PM - 		Microsoft.VisualStudio.Community
11/23/2024 3:26:32 PM - 			Version : [17.0,18.0)
11/23/2024 3:26:32 PM - 			ProductArchitecture : amd64
11/23/2024 3:26:32 PM - 	References         : 
11/23/2024 3:26:32 PM - 	Prerequisites      : 
11/23/2024 3:26:32 PM - 		-------------------------------------------------------
11/23/2024 3:26:32 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
11/23/2024 3:26:32 PM - 		Name         : Visual Studio core editor
11/23/2024 3:26:32 PM - 		Version      : [15.0,18.0)
11/23/2024 3:26:32 PM - Signature Details...
11/23/2024 3:26:32 PM - 	Extension is signed with a valid signature.
11/23/2024 3:26:32 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by dmvtech** [comment]
@gordingin Are you still experiencing this issue, or did you find a solution?

**Comment by dmvtech** [comment]
Closing due to lack of response.
